// Read-only audit of one exact AIR move/count-origin stop. One fresh M114 only.
(function(){
var C=Java.type('org.openpnp.model.Configuration'),F=Java.type('java.io.File'),Fs=Java.type('java.nio.file.Files'),UTF=Java.type('java.nio.charset.StandardCharsets').UTF_8,MD=Java.type('java.security.MessageDigest'),CT=Java.type('org.openpnp.machine.reference.driver.GcodeDriver$CommandType');
var root='/home/lumen/lumenpnp/',id='20e7157b-9893-4f23-97fc-1478bb8f17f4',faultPath=root+'automation/evidence/paste-contiguous-batch-'+id+'/report.json',faultHash='8d6b15909e59f1e34c652c3ae822051e1d6a1eedb8d46ccea410e35884796e2c',barrierPath=root+'automation/evidence/paste-position-barrier-d3eaf2f7-662a-4663-8560-a306ba6bf7d7/report.json',barrierHash='06e7553b3c6cad5c1cab9e145e89e8ecde33fa520ff1582950f333a8eb1b757a',modelPath=root+'.local-machine-backups/paste-live-model-state-1790899810676/report.json',modelHash='cbdb03a57c3044e95cac5b17e0deb7ade9d39e2d65b8bfee9229603f3ecea1c2',outPath=root+'automation/evidence/paste-air-count-audit-'+id+'-attempt2';
function bytes(s){return new java.lang.String(s).getBytes(UTF);}function hash(b){var a=MD.getInstance('SHA-256').digest(b),s='';for(var i=0;i<a.length;i++)s+=('0'+((a[i]&255).toString(16))).slice(-2);return s;}function read(p){return String(new java.lang.String(Fs.readAllBytes(new F(p).toPath()),UTF));}function field(c,n,o){var f=Java.type(c).class.getDeclaredField(n);f.setAccessible(true);return f.get(o);}function same(a,b,t,label){['X','Y','Z','A','B'].forEach(function(k){if(typeof a[k]!=='number'||typeof b[k]!=='number'||Math.abs(a[k]-b[k])>t)throw Error(label+' '+k+' mismatch');});}
var ff=new F(faultPath),bf=new F(barrierPath),mf=new F(modelPath);if(hash(Fs.readAllBytes(ff.toPath()))!==faultHash||hash(Fs.readAllBytes(bf.toPath()))!==barrierHash||hash(Fs.readAllBytes(mf.toPath()))!==modelHash)throw Error('Exact reviewed AIR fault/barrier/model evidence changed');
var fault=JSON.parse(read(faultPath)),barrier=JSON.parse(read(barrierPath)),model=JSON.parse(read(modelPath)),q=fault.request,failed=fault.stage0,expected=failed&&failed.saved&&failed.saved.raw,expectedCounts=failed&&failed.counts,initial=barrier.position&&barrier.position.responses&&barrier.position.responses[0];
if(fault.id!==id||fault.status!=='failed-no-retry-no-recovery-motion'||fault.uncertainCompletion!==true||fault.motionSubmitted!==true||fault.auditIncomplete!==true||fault.queuedTasksCancelled!==0||fault.executorQuarantined!==true||!q||q.mode!=='air'||q.scope!=='contiguous-native-scrap-batch'||q.jvmStartMs!==model.jvmStartMs||q.liveConfigurationSha256!==model.liveConfigurationSha256||fault.stages.length!==1||fault.stages[0].index!==0||fault.stages[0].axis!=='X'||fault.stages[0].startRaw.X!==309.49||fault.stages[0].targetRaw.X!==317.62||fault.stages[0].verified!==false||!expected||expected.X!==317.62||!expectedCounts)throw Error('Not exact failed AIR first-stage count-origin event');
var init=String(initial).match(/^X:(-?\d+\.\d+) Y:(-?\d+\.\d+) Z:(-?\d+\.\d+) A:(-?\d+\.\d+) B:(-?\d+\.\d+) Count X:(-?\d+) Y:(-?\d+) Z:(-?\d+) A:(-?\d+) B:(-?\d+)$/);if(!init||init[6]!=='99066'||init[7]!=='59062'||init[8]!=='1290'||init[9]!=='888'||init[10]!=='-15655')throw Error('Historical barrier does not bind exact pre-stage raw counts');
var m=C.get().getMachine(),planner=m.getMotionPlanner(),jvm=Number(Java.type('java.lang.management.ManagementFactory').getRuntimeMXBean().getStartTime()),ds=m.getDrivers();if(jvm!==q.jvmStartMs||jvm!==model.jvmStartMs||ds.size()!==1||!m.isBusy()||!m.isEnabled()||!m.isHomed()||Date.parse(model.time)>Number(java.lang.System.currentTimeMillis())||Number(java.lang.System.currentTimeMillis())-Date.parse(model.time)>300000)throw Error('Current JVM/homed latched machine identity changed');
var d=ds.get(0),ex=field('org.openpnp.spi.base.AbstractMachine','executor',m),owner=field('org.openpnp.spi.base.AbstractMachine','taskThread',m),GT='org.openpnp.machine.reference.driver.GcodeDriver',connected=field(GT,'connected',d),reader=field(GT,'readerThread',d),err=field(GT,'errorResponse',d),motions=field('org.openpnp.machine.reference.driver.AbstractMotionPlanner','motionCommands',planner);
if(String(d.getClass().getName())!==GT||String(d.getId())!=='DRV16982438146c1dd4'||!connected||reader==null||!reader.isAlive()||err!=null||d.isMotionPending()||ex==null||!ex.isShutdown()||!ex.isTerminated()||ex.getActiveCount()!==0||ex.getQueue().size()!==0||owner==null||owner.isAlive()||motions.size()!==0||String(planner.getClass().getName())!=='org.openpnp.machine.reference.driver.NullMotionPlanner')throw Error('Expected connected healthy reader and proven dead empty executor');
var panel=Java.type('org.openpnp.gui.MainFrame').get().getJobTab(),state=panel.getClass().getDeclaredField('state');state.setAccessible(true);if(String(state.get(panel))!=='Stopped')throw Error('Job must remain stopped');
var liveHash=(function(){var w=new java.io.StringWriter();C.createSerializer().write(m,w);return hash(bytes(String(w)));})();if(liveHash!==q.liveConfigurationSha256)throw Error('Live model configuration changed');
var axisMap={},axes=new (Java.type('org.openpnp.model.AxesLocation'))(m).drivenBy(d).getControllerAxes();for each(var a in axes){var k=String(a.getLetter());if(axisMap[k])throw Error('Duplicate axis');axisMap[k]=a;}var snap={raw:{},driver:{}};Object.keys(axisMap).forEach(function(k){snap.raw[k]=Number(axisMap[k].getCoordinate());snap.driver[k]=Number(axisMap[k].getDriverCoordinate());});if(Object.keys(snap.raw).sort().join(',')!=='A,B,X,Y,Z')throw Error('Incomplete live axes');same(snap.raw,expected,0.0001,'Live raw model');same(snap.driver,expected,0.0001,'Live driver model');
var heads=m.getDefaultHead(),n1=heads.getNozzleByName('N1'),n2=heads.getNozzleByName('N2'),top=heads.getDefaultCamera(),bottom=null;for each(var cam in m.getCameras())if(String(cam.getLooking())==='Up')bottom=cam;if(n1==null||n2==null||top==null||bottom==null||n2.getNozzleTip()!=null||n2.getCompatibleNozzleTips().size()!==0||n2.isChangerEnabled()||n2.getPart()!=null||m.getPnpJobProcessor().isPreRotateAllNozzles())throw Error('N2 quarantine/heads changed');function nativePose(o){var p=o.getLocation().convertToUnits(Java.type('org.openpnp.model.LengthUnit').Millimeters);return {x:Number(p.getX()),y:Number(p.getY()),z:Number(p.getZ()),rotation:Number(p.getRotation())};}snap.nativePoses={N1:nativePose(n1),N2:nativePose(n2),top:nativePose(top),bottom:nativePose(bottom)};
var ledgerEvidence=null;(q.evidence||[]).forEach(function(e){if(e.sha256===q.previousLedgerSha256)ledgerEvidence=e;});if(!ledgerEvidence||hash(Fs.readAllBytes(new F(ledgerEvidence.path).toPath()))!==ledgerEvidence.sha256)throw Error('Existing air ledger evidence missing/changed');
var out=new F(outPath);if(!out.mkdir())throw Error('Exact audit already claimed; inspect existing report');var r={schema:1,scope:'read-only-exact-air-count-origin-stop-audit',status:'audit-started',faultId:id,faultEvidence:{path:faultPath,sha256:faultHash},barrierEvidence:{path:barrierPath,sha256:barrierHash},modelEvidence:{path:modelPath,sha256:modelHash},ledgerEvidence:ledgerEvidence,jvmStartMs:jvm,liveConfigurationSha256:liveHash,startedAt:new Date().toISOString(),preQuerySnapshot:snap,expectedAfterStageRaw:expected,expectedCountOrigin:{before:{X:99066,Y:59062,Z:1290,A:888,B:-15655},after:expectedCounts},controllerQuerySubmitted:false,motionIssued:false,ledgerReserved:false,positionVerified:false};function save(s){r.status=s;Fs.write(new F(out,'report.json').toPath(),bytes(JSON.stringify(r,null,2)+'\n'));}save('audit-started');
try{eval(read(root+'automation/paste/connection-policy.cjs'));eval(read(root+'automation/paste/waste-prime.cjs'));eval(read(root+'automation/paste/native-air.cjs'));var cmd=String(d.getCommand(null,CT.GET_POSITION_COMMAND)).trim(),regex=String(d.getCommand(null,CT.POSITION_REPORT_REGEX)),ack=String(d.getCommand(null,CT.COMMAND_CONFIRM_REGEX)).trim(),complete=d.getCommand(null,CT.MOVE_TO_COMPLETE_REGEX),errorRegex=String(d.getCommand(null,CT.COMMAND_ERROR_REGEX)),expectedRegex='^.*X:(?<X>-?\\d+\\.\\d+)\\s*Y:(?<Y>-?\\d+\\.\\d+)\\s*Z:(?<Z>-?\\d+\\.\\d+)\\s*A:(?<A>-?\\d+\\.\\d+)\\s*B:(?<B>-?\\d+\\.\\d+).*';if(['M114','M114 ; get position'].indexOf(cmd)<0||ack!=='^ok.*'||regex!==expectedRegex||(complete!=null&&String(complete).trim())||errorRegex!==NativePasteAir.nativeErrorRegex)throw Error('Position query templates changed');var badResponse=Java.type('java.util.regex.Pattern').compile(errorRegex);function checked(lines){PasteConnectionPolicy.responses(lines);lines.forEach(function(x){if(badResponse.matcher(x).matches())throw Error('Controller error/reset response: '+x);});}var old=[];for each(var line in d.receiveResponses())old.push(String(line.getLine()));checked(old);r.staleResponses=old;if(old.some(function(x){return /\b[XYZAB]:/.test(x);}))throw Error('Stale position response present before audit');
 var lines=[];function append(rs){for each(var x in rs)lines.push(String(x.getLine()));}function collect(pattern){append(d.receiveResponses(pattern,3000,new (Java.type('org.openpnp.machine.reference.driver.GcodeDriver$TimeoutAction'))({apply:function(rs){append(rs);r.responses=lines;save('audit-query-incomplete-latch-retained');throw new java.lang.Exception('Fresh audit response timed out');}})));checked(lines);}
 r.controllerQuerySubmitted=true;save('fresh-M114-submitted');var loc=d.getReportedLocation(3000),reported={};for each(var ax in loc.getControllerAxes())reported[String(ax.getLetter())]=Number(loc.getCoordinate(ax));collect(regex);if(!lines.some(function(x){return /^ok/.test(x);}))collect('^ok.*');append(d.receiveResponses());checked(lines);var matches=[];lines.forEach(function(x){var a=x.match(/^X:(-?\d+\.\d+) Y:(-?\d+\.\d+) Z:(-?\d+\.\d+) A:(-?\d+\.\d+) B:(-?\d+\.\d+) Count X:(-?\d+) Y:(-?\d+) Z:(-?\d+) A:(-?\d+) B:(-?\d+)$/);if(a)matches.push({raw:{X:+a[1],Y:+a[2],Z:+a[3],A:+a[4],B:+a[5]},counts:{X:+a[6],Y:+a[7],Z:+a[8],A:+a[9],B:+a[10]},index:lines.indexOf(x)});});if(matches.length!==1||!lines.slice(matches[0].index+1).some(function(x){return /^ok/.test(x);}))throw Error('Exactly one fresh full M114 line followed by ACK required');same(reported,expected,0.0001,'Fresh controller pose');same(matches[0].raw,expected,0.0001,'Fresh M114 pose');var counts=matches[0].counts;Object.keys(expectedCounts).forEach(function(k){if(counts[k]!==expectedCounts[k])throw Error('Fresh count-origin mismatch '+k);});if(counts.X!==101667||counts.Y!==59062||counts.Z!==1290||counts.A!==888||counts.B!==-15655)throw Error('Fresh counts do not prove exact one-axis stage target and unchanged held axes');var after={raw:{},driver:{},nativePoses:{}};Object.keys(axisMap).forEach(function(k){after.raw[k]=Number(axisMap[k].getCoordinate());after.driver[k]=Number(axisMap[k].getDriverCoordinate());});same(after.raw,expected,0.0001,'Post-query raw model');same(after.driver,reported,0.0001,'Post-query driver model');after.nativePoses={N1:nativePose(n1),N2:nativePose(n2),top:nativePose(top),bottom:nativePose(bottom)};r.responses=lines;r.reported=reported;r.counts=counts;r.afterQuerySnapshot=after;r.positionVerified=true;r.motionIssued=false;r.ledgerReserved=false;r.uncertainCompletion=false;r.finishedAt=new Date().toISOString();save('audit-complete-awaiting-separate-model-release');}
catch(e){r.error=String(e);r.finishedAt=new Date().toISOString();save('audit-failed-no-release');throw e;}
print(String(out));
})();
