// One-shot dispatcher for reviewed repository scripts. No automatic looping.
var C=Java.type('org.openpnp.model.Configuration'),F=Java.type('java.io.File'),Fs=Java.type('java.nio.file.Files');
var requestFile=new F('/home/lumen/lumenpnp/automation/plans/operator-command.json');
var q=JSON.parse(String(new java.lang.String(Fs.readAllBytes(requestFile.toPath()),'UTF-8')));
var actions={'paste-batch-reconcile':'Reconcile_Paste_Batch_Budget.js','paste-batch-release':'Release_Paste_Batch_Stop.js','paste-batch-audit':'Audit_Paste_Batch_Stop.js','paste-contiguous-batch-preview':'Preview_Paste_Contiguous_Batch.js','paste-contiguous-batch':'Commission_Paste_Contiguous_Batch.js','paste-startup-quarantine':'Restore_Paste_Startup_Quarantine.js','paste-prime-release':'Release_Paste_Prime_Stop.js','paste-prime-audit':'Audit_Paste_Prime_Stop.js','paste-waste-prime':'Prime_Paste_Into_Waste.js','paste-waste-prime-preview':'Preview_Paste_Waste_Prime.js','paste-commissioning-stroke':'Commission_Paste_B_Stroke.js','paste-commissioning-stroke-preview':'Preview_Paste_Commissioning_Stroke.js','paste-dose-cycle':'Commission_Paste_Dose_Cycle.js','paste-dose-cycle-preview':'Preview_Paste_Dose_Cycle.js','paste-fiducial-vision':'Read_Paste_Fiducial_Vision.js','paste-top-exposure':'Capture_Paste_Top_Exposure.js','paste-bottom-exposure':'Capture_Paste_Bottom_Exposure.js','paste-camera-led':'Restore_Paste_Camera_LED.js','paste-b-current':'Set_Paste_B_Current.js','paste-home-finalize':'Finalize_Paste_Home_After_Report.js','paste-reset-home':'Home_Paste_After_Reset.js','paste-reset-clearance':'Observe_Paste_Reset_Clearance.js','paste-reset-connect':'Reconnect_Paste_After_Reset.js','paste-reset-invalidate':'Invalidate_Paste_Reset_State.js','paste-model-state':'Read_Paste_Model_State.js','paste-vacuum-probe':'Probe_Paste_Surface_By_Vacuum.js','paste-b-config':'Configure_Paste_B_Axis.js','paste-z-observe':'Observe_Paste_Z.js','paste-position-barrier':'Read_Paste_Position_Barrier.js','paste-error-latch':'Install_Paste_Error_Latch.js','paste-vacuum-baseline':'Record_Paste_Vacuum_Baseline.js','paste-survey-release':'Release_Paste_Survey_Stop.js','paste-survey-audit':'Audit_Paste_Survey_Stop.js','paste-survey':'Survey_Paste_Coupon.js','paste-measure':'Capture_Paste_Measurement.js','paste-connect-inspect':'Connect_Inspect_Paste_Controller.js','paste-quarantine':'Apply_Paste_Quarantine.js','paste-air':'Run_Paste_Air.js','paste-state':'Inspect_Paste_Controller.js',vacuum:'Set_Reviewed_Vacuum_High.js',adopt:'Adopt_Reviewed_Held_Part.js',discover:'Discover_Current_Feeder.js',home:'Home_After_Restart.js',load:'Load_Prepared_FTP_Job.js',register:'Register_Current_FTP.js',recover:'Recover_Retained_Resistor.js',probe:'Probe_Reviewed_XY.js',reconcile:'Reconcile_Removed_R1_R7.js',state:'Inspect_OpenPnP.js',registration:'Check_Fresh_Registration.js',index:'Index_And_Inspect_Pocket.js',opening:'Inspect_Feed_Opening.js',center:'Apply_Reviewed_Pocket_Center.js',pick:'Verify_Reviewed_Pocket_Pick.js',place:'Place_Selected_Resistor.js',record:'Record_Reviewed_Selected.js',review:'Inspect_Board_Components.js',empty:'Inspect_Empty_Baseline.js',seal:'Inspect_Pick_Seal.js'};
if(!actions[q.action]||q.reviewed!==true||Math.abs(java.lang.System.currentTimeMillis()-q.createdMs)>30000||(C.get().getMachine().isBusy()&&['paste-batch-release','paste-batch-audit','paste-prime-release','paste-prime-audit','paste-home-finalize','paste-reset-invalidate','paste-model-state','paste-survey-audit','paste-survey-release'].indexOf(q.action)<0))throw new Error('Invalid/stale command or busy machine');
// Installation blocks legacy motion without modifying its calibrated scripts.
if(['paste-batch-reconcile','paste-batch-release','paste-batch-audit','paste-contiguous-batch-preview','paste-contiguous-batch','paste-startup-quarantine','paste-prime-release','paste-prime-audit','paste-waste-prime','paste-waste-prime-preview','paste-commissioning-stroke','paste-commissioning-stroke-preview','paste-dose-cycle','paste-dose-cycle-preview','paste-fiducial-vision','paste-top-exposure','paste-bottom-exposure','paste-camera-led','paste-b-current','paste-home-finalize','paste-reset-home','paste-reset-clearance','paste-reset-connect','paste-reset-invalidate','paste-model-state','paste-vacuum-probe','paste-b-config','paste-z-observe','paste-position-barrier','paste-error-latch','paste-vacuum-baseline','paste-survey-release','paste-survey-audit','paste-survey','paste-measure','paste-connect-inspect','paste-state','paste-quarantine','paste-air'].indexOf(q.action)<0){
 var lockFile=new F('/home/lumen/lumenpnp/automation/paste/installation-lock.json'),lock;
 try{lock=JSON.parse(String(new java.lang.String(Fs.readAllBytes(lockFile.toPath()),'UTF-8')));}catch(e){throw new Error('Paste installation lock missing/malformed; legacy reviewed actions blocked');}
 if(!lock||lock.schema!==1||lock.locked!==false)throw new Error('Paste installation locked; legacy reviewed actions blocked until installation and both-head clearance review');
}
Fs.delete(requestFile.toPath());
C.get().getScripting().execute(new F('/home/lumen/lumenpnp/automation/scripts/'+actions[q.action]));
