#!/usr/bin/env node
// Offline only: binds already reviewed evidence into one signed B stroke.
'use strict';
const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto'),P=require('../paste/commissioning-stroke.cjs');
const sha=b=>crypto.createHash('sha256').update(b).digest('hex');
function file(p){const full=path.resolve(p),bytes=fs.readFileSync(full);return {path:full,sha256:sha(bytes),bytes,value:JSON.parse(bytes)};}
function imageFile(p){const full=path.resolve(p),bytes=fs.readFileSync(full);return {path:full,sha256:sha(bytes),bytes};}
function build(input,{now=Date.now(),id=null}={}){
 if(!input||input.schema!==1||input.scope!=='reviewed-commissioning-stroke-input')throw Error('Explicit offline commissioning input required');
 const barrier=file(input.barrierPath),b=barrier.value,profile=file(input.profilePath),image=imageFile(input.reviewedImagePath),preview=file(input.nativePreviewPath),ledger=file(input.primeLedgerPath),prior=file(input.priorLedgerPath),carry=file(input.carryoverPath);id=id||preview.value.id;
 if(b.status!=='completed-read-only-position-barrier'||b.controllerPositionVerified!==true||b.uncertainCompletion!==false||b.noMotionCommandSubmitted!==true)throw Error('Fresh successful no-motion position barrier required');
 if(input.reviewedImageSha256!==image.sha256||input.reviewedPoseImageSha256!==image.sha256||input.poseAndClearanceReviewed!==true)throw Error('Fresh parent-reviewed pose/clearance image required');
 if(!Number.isFinite(input.imageCapturedMs)||!Number.isFinite(input.reviewedMs)||input.imageCapturedMs>input.reviewedMs||input.reviewedMs>now||now-input.reviewedMs>300000)throw Error('Fresh reviewed image timestamp required');
 if(!Number.isFinite(Date.parse(b.finishedAt))||Date.parse(b.finishedAt)<input.imageCapturedMs)throw Error('Position barrier must follow reviewed pose image');
 if(preview.value.status!=='completed-model-only-native-preview'||preview.value.noControllerAccess!==true||preview.value.noMotion!==true||preview.value.id!==id||preview.value.request.deltaDegrees!==input.deltaDegrees||preview.value.jvmStartMs!==b.request.jvmStartMs||preview.value.request.jvmStartMs!==b.request.jvmStartMs||preview.value.liveConfigurationSha256!==b.liveConfigurationSha256||preview.value.request.liveConfigurationSha256!==b.liveConfigurationSha256||JSON.stringify(preview.value.request.expectedRaw)!==JSON.stringify(b.afterQuerySnapshot.raw)||JSON.stringify(preview.value.request.expectedDriver)!==JSON.stringify(b.afterQuerySnapshot.driver)||JSON.stringify(preview.value.before.raw)!==JSON.stringify(b.afterQuerySnapshot.raw)||JSON.stringify(preview.value.before.driver)!==JSON.stringify(b.afterQuerySnapshot.driver)||JSON.stringify(preview.value.after.raw)!==JSON.stringify(b.afterQuerySnapshot.raw)||JSON.stringify(preview.value.after.driver)!==JSON.stringify(b.afterQuerySnapshot.driver))throw Error('Exact disconnected same-pose native preview required');
 if(ledger.value.status!=='verified'||ledger.value.sessionId!==profile.value.sessionId||ledger.value.lastVerifiedB!==-240||ledger.value.reservedDegrees!==960||ledger.value.postResetCarryover.priorGrossDegrees!==10940||ledger.value.postResetCarryover.manualDisplacementUnknown!==true)throw Error('Current verified prime ledger/carryover mismatch');
 const c=carry.value;if(c.primeLedgerSha256!==ledger.sha256||c.priorLedgerSha256!==prior.sha256||c.priorGrossDegrees!==10940||c.manualDisplacementUnknown!==true||c.verifiedPrimeDegrees!==960||c.startB!==-240||c.maximumAbsoluteDegrees!==120)throw Error('Signed commissioning carryover record mismatch');
 if(b.request.jvmStartMs!==profile.value.jvmStartMs||b.liveConfigurationSha256!==profile.value.liveConfigurationSha256)throw Error('Profile/barrier JVM or configuration mismatch');
 const prev=input.previousCommissioningLedgerPath?file(input.previousCommissioningLedgerPath):null;
 if(b.afterQuerySnapshot.raw.B!==(prev?prev.value.lastVerifiedB:-240))throw Error('Fresh barrier B differs from signed commissioning ledger');
 const previousReport=input.previousReportPath?file(input.previousReportPath):null;
 if(!!prev!==!!previousReport)throw Error('Previous terminal report and commissioning ledger must be supplied together');
 if(previousReport)P.validatePreviousReport(previousReport.value,prev.value,prev.sha256,input.imageCapturedMs);
 const q={schema:1,scope:'single-signed-raw-B-commissioning-stroke',enabled:false,id,sessionId:profile.value.sessionId,jvmStartMs:b.request.jvmStartMs,createdMs:preview.value.request.createdMs,reviewedImageMs:input.reviewedMs,imageCapturedMs:input.imageCapturedMs,axis:'B',deltaDegrees:input.deltaDegrees,speedFraction:.05,liveConfigurationSha256:b.liveConfigurationSha256,expectedRaw:b.afterQuerySnapshot.raw,expectedDriver:b.afterQuerySnapshot.driver,expectedNativePoses:b.afterQuerySnapshot.nativePoses,syringeId:profile.value.syringeId,primeLedgerSha256:ledger.sha256,carryoverSha256:carry.sha256,previousLedgerSha256:prev?prev.sha256:null,previousReportEvidence:previousReport?{path:previousReport.path,sha256:previousReport.sha256}:null,clearanceReview:input.clearanceReview===true,reviewedImageEvidence:{path:image.path,sha256:image.sha256},barrierEvidence:{path:barrier.path,sha256:barrier.sha256},profileEvidence:{path:profile.path,sha256:profile.sha256},primeLedgerEvidence:{path:ledger.path,sha256:ledger.sha256},priorLedgerEvidence:{path:prior.path,sha256:prior.sha256},carryoverEvidence:{path:carry.path,sha256:carry.sha256},nativePreviewEvidence:{path:preview.path,sha256:preview.sha256},expectedExpandedCommands:preview.value.formatter.expandedCommands,receivingProfile:{measured:profile.value.measured===true,flowCalibrated:false,sha256:profile.sha256,measuredGapMm:profile.value.measuredGapMm,gapUncertaintyMm:profile.value.gapUncertaintyMm,rawPose:profile.value.rawPose},evidence:[barrier,image,preview,ledger,prior,carry,profile].map(x=>({path:x.path,sha256:x.sha256}))};
 P.validate(q,now,q.jvmStartMs);const prospective=P.reserve(prev?prev.value:null,q,carry.value);return {request:q,prospectiveAbsoluteDegrees:prospective.totalAbsoluteDegrees,ledgerWritten:false,dispatched:false};
}
function main(){const a=process.argv.slice(2);if(a.length!==2)throw Error('Usage: node build_commissioning_stroke_request.cjs input.json request.json');const r=build(JSON.parse(fs.readFileSync(a[0],'utf8')));fs.writeFileSync(a[1],JSON.stringify(r.request,null,2)+'\n',{flag:'wx'});console.log(JSON.stringify({requestPath:path.resolve(a[1]),id:r.request.id,enabled:false,prospectiveAbsoluteDegrees:r.prospectiveAbsoluteDegrees,dispatched:false}));}
if(require.main===module){try{main();}catch(e){console.error(e.message);process.exitCode=1;}}
module.exports={build};
