#!/usr/bin/env node
// Offline only: bind reviewed pose, profile, carryover and 3-stage native preview.
'use strict';
const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto'),P=require('../paste/commissioning-stroke.cjs');
const sha=b=>crypto.createHash('sha256').update(b).digest('hex');
function file(p){const full=path.resolve(p),bytes=fs.readFileSync(full);return {path:full,sha256:sha(bytes),bytes,value:JSON.parse(bytes)};}
function imageFile(p){const full=path.resolve(p),bytes=fs.readFileSync(full);return {path:full,sha256:sha(bytes),bytes};}
function build(input,{now=Date.now(),id=null}={}){
 if(!input||input.schema!==1||input.scope!=='reviewed-paste-dose-cycle-input')throw Error('Explicit offline dose-cycle input required');
 const barrier=file(input.barrierPath),b=barrier.value,profile=file(input.profilePath),image=imageFile(input.reviewedImagePath),preview=file(input.nativePreviewPath),prime=file(input.primeLedgerPath),prior=file(input.priorLedgerPath),carry=file(input.carryoverPath),old=file(input.previousCommissioningLedgerPath),report=file(input.previousReportPath);id=id||preview.value.id;
 if(b.status!=='completed-read-only-position-barrier'||b.controllerPositionVerified!==true||b.uncertainCompletion!==false||b.noMotionCommandSubmitted!==true)throw Error('Fresh successful no-motion barrier required');
 if(input.reviewedImageSha256!==image.sha256||input.reviewedPoseImageSha256!==image.sha256||input.poseAndClearanceReviewed!==true||input.liftClearanceReviewed!==true)throw Error('Fresh parent-reviewed pose and lift-clearance image required');
 if(!Number.isFinite(input.imageCapturedMs)||!Number.isFinite(input.reviewedMs)||input.imageCapturedMs>input.reviewedMs||input.reviewedMs>now||now-input.reviewedMs>300000||now-input.imageCapturedMs>300000||Date.parse(b.finishedAt)<input.imageCapturedMs)throw Error('Fresh reviewed image/barrier timestamps required');
 const v=preview.value,pr=v.request;if(v.status!=='completed-model-only-dose-cycle-preview'||v.noControllerAccess!==true||v.noMotion!==true||v.id!==id||v.jvmStartMs!==b.request.jvmStartMs||pr.jvmStartMs!==b.request.jvmStartMs||pr.sessionId!==profile.value.sessionId||v.liveConfigurationSha256!==b.liveConfigurationSha256||pr.liveConfigurationSha256!==b.liveConfigurationSha256||JSON.stringify(pr.expectedRaw)!==JSON.stringify(b.afterQuerySnapshot.raw)||JSON.stringify(pr.expectedDriver)!==JSON.stringify(b.afterQuerySnapshot.driver)||JSON.stringify(v.before.raw)!==JSON.stringify(b.afterQuerySnapshot.raw)||JSON.stringify(v.before.driver)!==JSON.stringify(b.afterQuerySnapshot.driver)||JSON.stringify(v.after.raw)!==JSON.stringify(b.afterQuerySnapshot.raw)||JSON.stringify(v.after.driver)!==JSON.stringify(b.afterQuerySnapshot.driver)||!Array.isArray(v.stages)||v.stages.length!==3)throw Error('Exact same-pose detached three-stage preview required');
 if(pr.doseDegrees!==input.doseDegrees||pr.retractDegrees!==input.retractDegrees||pr.dwellMilliseconds!==input.dwellMilliseconds)throw Error('Preview parameters differ from reviewed cycle input');
 if(prime.value.status!=='verified'||prime.value.sessionId!==profile.value.sessionId||prime.value.lastVerifiedB!==-240||prime.value.reservedDegrees!==960)throw Error('Current verified prime ledger mismatch');
 const c=carry.value;if(c.primeLedgerSha256!==prime.sha256||c.priorLedgerSha256!==prior.sha256||c.priorGrossDegrees!==10940||c.manualDisplacementUnknown!==true||c.verifiedPrimeDegrees!==960||c.startB!==-240||c.maximumAbsoluteDegrees!==120)throw Error('Hash-bound syringe carryover mismatch');
 if(b.request.jvmStartMs!==profile.value.jvmStartMs||b.liveConfigurationSha256!==profile.value.liveConfigurationSha256||profile.value.sessionId!==old.value.sessionId||profile.value.syringeId!==old.value.syringeId)throw Error('Profile, ledger and barrier identity mismatch');
 const terminal=['completed-commissioning-stroke-awaiting-observation','completed-dose-cycle-awaiting-observation'];const last=old.value.entries[old.value.entries.length-1];if(old.value.status!=='verified'||b.afterQuerySnapshot.raw.B!==old.value.lastVerifiedB||terminal.indexOf(report.value.status)<0||report.value.uncertainCompletion!==false||report.value.completedLedgerSha256!==old.sha256||!last||(last.cycleId?last.cycleId!==report.value.id:last.requestId!==report.value.id)||Date.parse(report.value.finishedAt)>input.imageCapturedMs)throw Error('Fresh observation must follow exact prior verified B ledger/report');
 const stages=v.stages.map((s,i)=>{const names=['dose','retract','lift'];if(s.name!==names[i]||!s.formatterEvidence||!s.formatterEvidence.path||!s.formatterEvidence.sha256)throw Error('Preview stage order/evidence incomplete');const f=file(s.formatterEvidence.path);if(f.sha256!==s.formatterEvidence.sha256||JSON.stringify(f.value.expandedCommands)!==JSON.stringify(s.expandedCommands))throw Error('Native stage formatter evidence changed');return {name:s.name,axis:s.axis,speedFraction:s.speedFraction,startRaw:s.startRaw,targetRaw:s.targetRaw,path:f.path,sha256:f.sha256,expandedCommands:s.expandedCommands};});
 const q={schema:1,scope:'single-native-B-dose-retract-Z-lift-cycle',enabled:false,id,sessionId:profile.value.sessionId,jvmStartMs:b.request.jvmStartMs,createdMs:pr.createdMs,imageCapturedMs:input.imageCapturedMs,reviewedImageMs:input.reviewedMs,axis:'B',doseDegrees:input.doseDegrees,retractDegrees:input.retractDegrees,dwellMilliseconds:input.dwellMilliseconds,liftDeltaMm:-5,liftClearanceReview:true,dispenseSpeedFraction:.05,retractSpeedFraction:.05,liftSpeedFraction:1.0,liveConfigurationSha256:b.liveConfigurationSha256,expectedRaw:b.afterQuerySnapshot.raw,expectedDriver:b.afterQuerySnapshot.driver,expectedNativePoses:b.afterQuerySnapshot.nativePoses,liftTargetRaw:stages[2].targetRaw,syringeId:profile.value.syringeId,primeLedgerSha256:prime.sha256,carryoverSha256:carry.sha256,previousLedgerSha256:old.sha256,previousReportEvidence:{path:report.path,sha256:report.sha256},reviewedImageEvidence:{path:image.path,sha256:image.sha256},barrierEvidence:{path:barrier.path,sha256:barrier.sha256},profileEvidence:{path:profile.path,sha256:profile.sha256},primeLedgerEvidence:{path:prime.path,sha256:prime.sha256},priorLedgerEvidence:{path:prior.path,sha256:prior.sha256},carryoverEvidence:{path:carry.path,sha256:carry.sha256},nativePreviewEvidence:{path:preview.path,sha256:preview.sha256},receivingProfile:{measured:profile.value.measured===true,flowCalibrated:false,sha256:profile.sha256,measuredGapMm:profile.value.measuredGapMm,gapUncertaintyMm:profile.value.gapUncertaintyMm,rawPose:profile.value.rawPose},evidence:[barrier,image,preview,prime,prior,carry,profile].concat(stages.map(s=>({path:s.path,sha256:s.sha256}))).map(x=>({path:x.path,sha256:x.sha256})),previewStages:stages};
 P.validateCycle(q,now,q.jvmStartMs);const prospective=P.reserveCycle(old.value,q,c);return {request:q,prospectiveAbsoluteDegrees:prospective.totalAbsoluteDegrees,ledgerWritten:false,dispatched:false};
}
function main(){const a=process.argv.slice(2);if(a.length!==2)throw Error('Usage: node build_paste_dose_cycle_request.cjs input.json request.json');const r=build(JSON.parse(fs.readFileSync(a[0],'utf8')));fs.writeFileSync(a[1],JSON.stringify(r.request,null,2)+'\n',{flag:'wx'});console.log(JSON.stringify({requestPath:path.resolve(a[1]),id:r.request.id,enabled:false,prospectiveAbsoluteDegrees:r.prospectiveAbsoluteDegrees,dispatched:false}));}
if(require.main===module){try{main();}catch(e){console.error(e.message);process.exitCode=1;}}
module.exports={build};
