// Bounded top-camera-only XY inspection. Existing OpenPnP owner/executor only.
(function(){
 var C=Java.type('org.openpnp.model.Configuration'),F=Java.type('java.io.File'),Fs=Java.type('java.nio.file.Files'),UTF=Java.type('java.nio.charset.StandardCharsets').UTF_8,MD=Java.type('java.security.MessageDigest'),MM=Java.type('org.openpnp.model.LengthUnit').Millimeters,AL=Java.type('org.openpnp.model.AxesLocation'),MO=Java.type('org.openpnp.model.Motion$MotionOption'),CT=Java.type('org.openpnp.machine.reference.driver.GcodeDriver$CommandType'),ImageIO=Java.type('javax.imageio.ImageIO');
 var root='/home/lumen/lumenpnp/',m=C.get().getMachine(),planner=m.getMotionPlanner();
 function read(f){return String(new java.lang.String(Fs.readAllBytes(f.toPath()),UTF));}
 function hash(b){var a=MD.getInstance('SHA-256').digest(b),s='';for(var i=0;i<a.length;i++)s+=('0'+((a[i]&255).toString(16))).slice(-2);return s;}
 function bytes(s){return new java.lang.String(s).getBytes(UTF);}
 function file(path,digest){var f=new F(path);if(!f.isFile()||hash(Fs.readAllBytes(f.toPath()))!==digest)throw Error('Hash-bound evidence changed: '+path);return f;}
 function pv(c,n,o){var f=Java.type(c).class.getDeclaredField(n);f.setAccessible(true);return f.get(o);}
 eval(read(new F(root+'automation/paste/fast-camera-inspection.cjs')));eval(read(new F(root+'automation/paste/connection-policy.cjs')));eval(read(new F(root+'automation/paste/native-air.cjs')));
 var q=JSON.parse(read(new F(root+'automation/plans/fast-camera-inspection-request.json'))),jvm=Number(Java.type('java.lang.management.ManagementFactory').getRuntimeMXBean().getStartTime());
 PasteFastCameraInspection.validate(q,Number(java.lang.System.currentTimeMillis()),jvm);
 var sf=file(q.sourceReport.path,q.sourceReport.sha256),source=JSON.parse(read(sf)),sourceSnap=source.afterQuerySnapshot||{},sourceRequest=source.request||{};
 PasteFastCameraInspection.verifySourceReport(source,q);
 var regFile=file(q.registration.path,q.registration.sha256),reg=JSON.parse(read(regFile));if(reg.scope!=='offline-native-fresh-ftp-two-fiducial-transform-with-third-point-check'||!reg.acceptance||reg.acceptance.passed!==true||reg.machineConfigurationChanged!==false||reg.jobChanged!==false)throw Error('Registration is not accepted offline geometry');
 if(!reg.board||typeof reg.board.sha256!=='string')throw Error('Registration must bind canonical FTP CAD');file(root+'pnp/pcb/ftp/ftp.kicad_pcb',reg.board.sha256);var regTargets={};(reg.resistorPadMachineXYTargets||[]).forEach(function(t){regTargets[t.padId]=t.machineXYMm;});if(q.mode==='registered-references')q.targets.forEach(function(t){var a=regTargets[t.reference+'.1'],b=regTargets[t.reference+'.2'];if(!a||!b||Math.abs(t.pads[0].x-a[0])>.000001||Math.abs(t.pads[0].y-a[1])>.000001||Math.abs(t.pads[1].x-b[0])>.000001||Math.abs(t.pads[1].y-b[1])>.000001||Math.abs(t.x-(a[0]+b[0])/2)>.0001||Math.abs(t.y-(a[1]+b[1])/2)>.0001)throw Error('Reference target does not match hash-bound registration');});
 var jobFile=file(q.inspectionJob.jobPath,q.inspectionJob.jobSha256);file(q.inspectionJob.boardPath,q.inspectionJob.boardSha256);
 var policy=JSON.parse(read(new F(root+'automation/paste/camera-inspection-policy.json'))),lock=JSON.parse(read(new F(root+'automation/paste/installation-lock.json')));PasteFastCameraInspection.installationPolicy(policy,lock,'paste-fast-camera-inspection');
 var panel=Java.type('org.openpnp.gui.MainFrame').get().getJobTab(),state=panel.getClass().getDeclaredField('state');state.setAccessible(true);if(m.getDrivers().size()!==1||m.getHeads().size()!==1)throw Error('Unexpected machine topology');var d=m.getDrivers().get(0),top=m.getDefaultHead().getDefaultCamera(),right=m.getDefaultHead().getNozzleByName('N2'),left=m.getDefaultHead().getNozzleByName('N1');
 if(String(d.getClass().getName())!=='org.openpnp.machine.reference.driver.GcodeDriver'||String(d.getId())!=='DRV16982438146c1dd4'||String(planner.getClass().getName())!=='org.openpnp.machine.reference.driver.NullMotionPlanner'||String(top.getId())!=='CAM1607555396816'||String(top.getLooking())!=='Down')throw Error('Unknown audited machine/driver/planner');
 if(panel.getJob()==null||String(panel.getJob().getFile())!==String(jobFile)||panel.getJob().getBoardLocations().size()!==1)throw Error('Hash-bound disabled inspection job must be loaded');var placements=panel.getJob().getBoardLocations().get(0).getBoard().getPlacements();if(placements.size()===0)throw Error('Disabled inspection board placements missing');for each(var placement in placements)if(placement.isEnabled())throw Error('Inspection placement became enabled');
 if(String(state.get(panel))!=='Stopped'||m.isBusy()||!m.isEnabled()||!m.isHomed())throw Error('Need stopped, idle, enabled, homed machine');
 if(left.getPart()!=null||left.getPartsFeeder()!=null||right.getPart()!=null||right.getPartsFeeder()!=null||right.getNozzleTip()!=null||right.getCompatibleNozzleTips().size()!==0||right.getRotationModeOffset()!=null||right.isChangerEnabled()||right.getManualNozzleTipChangeLocation().isInitialized()||m.getPnpJobProcessor().isPreRotateAllNozzles())throw Error('Nozzle state/quarantine precondition failed');
 var ex=pv('org.openpnp.spi.base.AbstractMachine','executor',m);if(ex==null||ex.isShutdown()||ex.isTerminated()||ex.getCorePoolSize()!==1||ex.getMaximumPoolSize()!==1||ex.getActiveCount()!==0||!ex.getQueue().isEmpty())throw Error('Existing single-worker executor must be idle');
 var axes={},ids={X:'AXS169824381580efcb',Y:'AXS16982438158c4660',Z:'AXS16982438158d0458',A:'AXS16b068df4e35374e',B:'AXS17108288e61da5fb'};for each(var a in new AL(m).drivenBy(d).getControllerAxes()){var k=String(a.getLetter());if(ids[k]!==String(a.getId()))throw Error('Axis identity changed');axes[k]=a;}
 if(Object.keys(axes).sort().join(',')!=='A,B,X,Y,Z')throw Error('Raw axis set changed');
 var mapped=[];for each(var a in top.getMappedAxes(m).getControllerAxes())mapped.push(String(a.getLetter()));if(mapped.sort().join(',')!=='X,Y')throw Error('Top camera must map physical XY only');
 var items={N1:left,N2:right,top:top,bottom:null};for each(var camera in m.getCameras())if(String(camera.getLooking())==='Up'){if(items.bottom!==null)throw Error('Unexpected extra bottom camera');items.bottom=camera;}if(items.bottom===null)throw Error('Required bottom camera missing');
 function poses(){var out={};Object.keys(items).forEach(function(k){var p=items[k].getLocation().convertToUnits(MM);out[k]={x:Number(p.getX()),y:Number(p.getY()),z:Number(p.getZ()),rotation:Number(p.getRotation())};});return out;}
 function comparePoses(a,b){Object.keys(items).forEach(function(k){['x','y','z','rotation'].forEach(function(t){if(Math.abs(a[k][t]-b[k][t])>0.0001)throw Error('Native pose changed '+k+' '+t);});});}
 var snap=function(){var r={},v={};Object.keys(axes).forEach(function(k){r[k]=Number(axes[k].getCoordinate());v[k]=Number(axes[k].getDriverCoordinate());});return {raw:r,driver:v,nativePoses:poses()};};
 var now=snap();Object.keys(q.expectedRaw).forEach(function(k){if(now.raw[k]!==q.expectedRaw[k]||now.driver[k]!==q.expectedDriver[k])throw Error('Exact raw/driver precondition failed at '+k);});comparePoses(now.nativePoses,q.expectedNativePoses);
 if(hash(bytes(String((function(){var w=new java.io.StringWriter();C.createSerializer().write(m,w);return w;})())))!==q.liveConfigurationSha256)throw Error('Live configuration hash changed');
 var reader=pv('org.openpnp.machine.reference.driver.GcodeDriver','readerThread',d),cmds=d.commands;if(reader==null||!reader.isAlive()||pv('org.openpnp.machine.reference.driver.GcodeDriver','readerThread',d)!==reader||pv('org.openpnp.machine.reference.driver.GcodeDriver','errorResponse',d)!=null||String(pv('org.openpnp.machine.reference.driver.GcodeDriver','connected',d))!=='true'||d.isMotionPending())throw Error('Serial reader/driver unhealthy');
 var ackTimeout=Number(pv('org.openpnp.machine.reference.driver.GcodeDriver','infinityTimeoutMilliseconds',d));if(!(ackTimeout>0&&ackTimeout<=60000))throw Error('Position timeout outside reviewed limit');
 var posRegex='^.*X:(?<X>-?\\d+\\.\\d+)\\s*Y:(?<Y>-?\\d+\\.\\d+)\\s*Z:(?<Z>-?\\d+\\.\\d+)\\s*A:(?<A>-?\\d+\\.\\d+)\\s*B:(?<B>-?\\d+\\.\\d+).*',positionPattern=Java.type('java.util.regex.Pattern').compile(posRegex);
 if(String(d.getCommand(null,CT.GET_POSITION_COMMAND)).trim()!=='M114'&&String(d.getCommand(null,CT.GET_POSITION_COMMAND)).trim()!=='M114 ; get position')throw Error('Position query command is not reviewed M114');
 if(String(d.getCommand(null,CT.POSITION_REPORT_REGEX))!==posRegex||String(d.getCommand(null,CT.COMMAND_CONFIRM_REGEX)).trim()!=='^ok.*'||String(d.getCommand(null,CT.COMMAND_ERROR_REGEX))!==NativePasteAir.nativeErrorRegex||JSON.stringify(PasteConnectionPolicy.tokens(d.getCommand(top,CT.MOVE_TO_COMPLETE_COMMAND)))!==JSON.stringify(['M400']))throw Error('M114 delimiter, ACK/error pattern, or native completion changed');
 function append(lines,out){for each(var l in lines)out.push(String(l.getLine()));}
 function checked(lines){PasteConnectionPolicy.responses(lines);lines.forEach(function(l){if(/unknown command|halted|fatal|\bkilled\b/i.test(l))throw Error('Controller fault: '+l);});}
 function query(){if(d.commands!==cmds||pv('org.openpnp.machine.reference.driver.GcodeDriver','readerThread',d)!==reader||!reader.isAlive()||d.isMotionPending())throw Error('Reader/driver changed');var lines=[],stale=d.receiveResponses();append(stale,lines);checked(lines);if(lines.some(function(l){return /^[XYZAB]:/.test(l);}))throw Error('Stale native position response');var reported=d.getReportedLocation(3000),out={};for each(var a in reported.getControllerAxes())out[String(a.getLetter())]=Number(reported.getCoordinate(a));var matched=d.receiveResponses(posRegex,3000,new (Java.type('org.openpnp.machine.reference.driver.GcodeDriver$TimeoutAction'))({apply:function(rs){append(rs,lines);checked(lines);throw new java.lang.Exception('Fresh M114 position delimiter timeout; no retry');}}));append(matched,lines);checked(lines);var at=-1;lines.forEach(function(l,i){if(positionPattern.matcher(l).matches())at=i;});if(at<0)throw Error('Fresh M114 report delimiter missing');if(!lines.slice(at+1).some(function(l){return /^ok/.test(l);}))throw Error('Fresh M114 ACK missing');append(d.receiveResponses(),lines);checked(lines);return out;}
 var report={schema:1,id:q.id,scope:q.scope,status:'claimed',startedAt:new Date().toISOString(),request:q,beforeQuerySnapshot:now,motionSubmitted:false,controllerPositionVerified:false,uncertainCompletion:false,frames:[],transitions:[]};
 var dir=new F(root+'automation/evidence/camera-inspection-'+q.id);if(!dir.mkdir())throw Error('Inspection UUID already claimed; no replay');function save(s){report.status=s;report.transitions.push({status:s,time:new Date().toISOString()});Fs.write(new F(dir,'report.json').toPath(),bytes(JSON.stringify(report,null,2)+'\n'));}
 function capture(ref,index){var open=top.getClass().getDeclaredMethod('isOpen');open.setAccessible(true);if(!open.invoke(top))throw Error('Existing top camera stream is not open');var image=top.captureRaw();if(image==null||!ImageIO.write(image,'png',new F(dir,'frame-'+('0'+index).slice(-2)+'-'+ref+'.png')))throw Error('Top frame capture failed');var current=snap(),info={reference:ref,path:'frame-'+('0'+index).slice(-2)+'-'+ref+'.png',width:image.getWidth(),height:image.getHeight(),rawAxes:current.raw,nativePose:current.nativePoses.top};report.frames.push(info);report.afterImages={top:{path:info.path,width:info.width,height:info.height}};}
 save('preflight-before-native-query');
 var taskSetter=Java.type('org.openpnp.spi.base.AbstractMachine').class.getDeclaredMethod('setTaskThread',Java.type('java.lang.Thread').class);taskSetter.setAccessible(true);
 function taskOwner(thread){taskSetter.invoke(m,Java.to([thread],'java.lang.Object[]'));}
 try{ex.submit(new (Java.type('java.util.concurrent.Callable'))({call:function(){var owned=false;try{if(m.isBusy()||!ex.getQueue().isEmpty())throw Error('Native task ownership changed before inspection');taskOwner(java.lang.Thread.currentThread());owned=true;m.fireMachineBusy(true);
  var beforeReported=query();report.beforeReported=beforeReported;Object.keys(now.raw).forEach(function(k){var tol=(k==='A'||k==='B')?0.3:0.02;if(Math.abs(beforeReported[k]-now.raw[k])>tol||Math.abs(beforeReported[k]-now.driver[k])>tol)throw Error('Initial M114 report disagrees with raw/driver '+k);});save('pre-move-position-queried');
  var routeResults=PasteFastCameraInspection.executeRoute(q,{
   snapshot:function(){return snap();},
   beforeMove:function(step,index,cur){if((m.isBusy()&&!m.isTask(java.lang.Thread.currentThread()))||!ex.getQueue().isEmpty()||d.isMotionPending())throw Error('Competing work before route step');var target=new AL(axes.X,step.x).put(new AL(axes.Y,step.y));if(!planner.isValidLocation(top,target))throw Error('XY route point outside planner bounds');report.controllerPositionVerified=false;report.motionSubmitted=true;report.activeStep=index;save('submitting-bounded-xy-step');},
   move:function(step,index){var target=new AL(axes.X,step.x).put(new AL(axes.Y,step.y));planner.moveTo(top,target,1.0,MO.SpeedOverPrecision);report.nativeMotionCompletionReported=true;},
   query:function(){return query();},
   afterStep:function(step,index,after,afterReported){report.afterQuerySnapshot=after;report.afterReported=afterReported;report.controllerPositionVerified=true;for each(var ref in step.captureReferences){java.lang.Thread.sleep(Math.ceil(Math.max(200,Number(top.getSettleTimeMs()))));capture(String(ref),index);}save('route-step-'+index+'-verified');}
  });
  if(q.routeSteps.length===0){report.motionSubmitted=false;report.afterQuerySnapshot=now;report.afterReported=beforeReported;report.controllerPositionVerified=true;if(q.mode==='reviewed-scrap-camera'){java.lang.Thread.sleep(Math.ceil(Math.max(200,Number(top.getSettleTimeMs()))));capture('scrap',0);save('stationary-scrap-frame-captured');}}
  report.finishedAt=new Date().toISOString();report.uncertainCompletion=false;report.physicalAcceptanceEstablished=false;report.calibrationEstablished=false;save('completed-camera-survey-awaiting-image-review');
 }catch(e){report.error=String(e);report.uncertainCompletion=report.motionSubmitted&&!report.controllerPositionVerified;report.auditIncomplete=true;report.finishedAt=new Date().toISOString();save('failed-no-retry-no-recovery');if(report.motionSubmitted){while(!ex.getQueue().isEmpty())ex.getQueue().poll();ex.shutdown();report.executorQuarantined=true;save('executor-quarantined-after-uncertain-failure');}throw e;}finally{if(owned&&!report.executorQuarantined){taskOwner(null);m.fireMachineBusy(false);}}return null;}}));}catch(e){report.error=String(e);report.finishedAt=new Date().toISOString();save('enqueue-failed-no-motion');throw e;}
})();
