// Exact post-powercycle native disconnection/model invalidation. No query, motion,
// reconnect, enable, home, configuration save, coordinate restore or fault replay.
(function(){
 var C=Java.type('org.openpnp.model.Configuration'),F=Java.type('java.io.File'),Fs=Java.type('java.nio.file.Files'),UTF=Java.type('java.nio.charset.StandardCharsets').UTF_8,MD=Java.type('java.security.MessageDigest'),AL=Java.type('org.openpnp.model.AxesLocation');
 var root='/home/lumen/lumenpnp/',sourcePath=root+'automation/evidence/paste-model-state-1790769877961/report.json',sourceHash='74dd9792754e0b090aa053cc87a75764bb2ef1faf469a7bc9ea7fa2d5874944f';
 function bytes(s){return new java.lang.String(s).getBytes(UTF);}function hash(b){var a=MD.getInstance('SHA-256').digest(b),s='';for(var i=0;i<a.length;i++)s+=('0'+((a[i]&255).toString(16))).slice(-2);return s;}
 function field(c,n){var f=Java.type(c).class.getDeclaredField(n);f.setAccessible(true);return f;}function val(c,n,o){return field(c,n).get(o);}
 var input=Fs.readAllBytes(new F(sourcePath).toPath());if(hash(input)!==sourceHash)throw Error('Reviewed reset diagnostic changed');var source=JSON.parse(String(new java.lang.String(input,UTF)));
 if(source.scope!=='pure-model-state-no-controller-access'||source.controllerPoseTrusted!==false||!source.enabled||!source.homed||!source.busy||source.drivers.length!==1||source.drivers[0].readerAlive!==false||source.drivers[0].connected!==true||source.motionQueue!==0||source.taskOwner.alive!==false)throw Error('Not the reviewed stale reset state');
 if(!Java.type('javax.swing.SwingUtilities').isEventDispatchThread())throw Error('Reviewed synchronous dispatcher required');
 var cfg=C.get(),m=cfg.getMachine(),planner=m.getMotionPlanner(),jvm=Number(Java.type('java.lang.management.ManagementFactory').getRuntimeMXBean().getStartTime());
 if(jvm!==source.jvmStartMs||m.getDrivers().size()!==1||String(planner.getClass().getName())!=='org.openpnp.machine.reference.driver.NullMotionPlanner')throw Error('Session/planner changed');
 var d=m.getDrivers().get(0),GD='org.openpnp.machine.reference.driver.GcodeDriver',SP='org.openpnp.machine.reference.driver.SerialPortCommunications',AM='org.openpnp.spi.base.AbstractMachine',AP='org.openpnp.machine.reference.driver.AbstractMotionPlanner';
 if(String(d.getClass().getName())!==GD||String(d.getId())!=='DRV16982438146c1dd4')throw Error('Driver changed');
 var jar=new F(d.getClass().getProtectionDomain().getCodeSource().getLocation().toURI());if(hash(Fs.readAllBytes(jar.toPath()))!=='bcd34923ae91d61a96b98b4c82c93cdc90093ff94292270fd0a18fc6f96f7752')throw Error('Installed API changed');
 var serial=d.getSerial(),reader=val(GD,'readerThread',d),port=val(SP,'serialPort',serial),exField=field(AM,'executor'),ownerField=field(AM,'taskThread'),ex=exField.get(m),owner=ownerField.get(m),right=m.getDefaultHead().getNozzleByName('N2');
 var panel=Java.type('org.openpnp.gui.MainFrame').get().getJobTab(),state=panel.getClass().getDeclaredField('state');state.setAccessible(true);
 function serialized(){var w=new java.io.StringWriter();C.createSerializer().write(m,w);return String(w);}
 function snapshot(){var r={};for each(var a in new AL(m).drivenBy(d).getControllerAxes())r[String(a.getLetter())]={id:String(a.getId()),model:Number(a.getCoordinate()),driver:Number(a.getDriverCoordinate())};return r;}
 function sameCoordinates(){var r=snapshot();if(Object.keys(r).sort().join(',')!=='A,B,X,Y,Z')throw Error('Axes changed');source.axes.forEach(function(a){var b=r[a.letter];if(!b||b.id!==a.id||!isFinite(b.model)||!isFinite(b.driver)||Math.abs(b.model-a.model)>0.0001||Math.abs(b.driver-a.driver)>0.0001)throw Error('Cached coordinates changed; never restore them');});return r;}
 function inertActuator(a){if(String(a.getClass().getName())!=='org.openpnp.machine.reference.ReferenceActuator'||String(a.getDisabledActuation())!=='LeaveAsIs')throw Error('Disable callback could actuate');}
 function common(){for each(var a in m.getActuators())inertActuator(a);for each(var h in m.getHeads()){if(h.getPumpActuator()!=null)throw Error('Head disable callback could operate pump');for each(var a in h.getActuators())inertActuator(a);}if(String(state.get(panel))!=='Stopped'||d.isMotionPending()||val(AP,'motionCommands',planner).size()!==0)throw Error('Job/motion state changed');var sub=val(AP,'subordinateMotion',planner),sq=val(AP+'$SubordinateMotion','queue',sub);if(sq!=null&&!sq.isEmpty())throw Error('Pending subordinate axes');if(right==null||String(right.getId())!=='NOZ1710829fd33a0170'||right.getNozzleTip()!=null||right.getCompatibleNozzleTips().size()!==0||right.getRotationModeOffset()!=null||right.isChangerEnabled()||right.getManualNozzleTipChangeLocation().isInitialized()||m.getPnpJobProcessor().isPreRotateAllNozzles())throw Error('N2 quarantine changed');for each(var h in m.getHeads())for each(var n in h.getNozzles())if(n.getPart()!=null||n.getPartsFeeder()!=null)throw Error('Held/associated part');if(hash(bytes(serialized()))!==source.liveConfigurationSha256)throw Error('Configuration changed');sameCoordinates();}
 function initialGate(){common();if(!m.isBusy()||!m.isEnabled()||!m.isHomed()||reader==null||reader.isAlive()||val(GD,'readerThread',d)!==reader||String(val(GD,'connected',d))!=='true'||val(GD,'errorResponse',d)!=null)throw Error('Expected exact dead-reader stale state');if(ex==null||!ex.isShutdown()||!ex.isTerminated()||ex.getActiveCount()!==0||!ex.getQueue().isEmpty()||owner==null||owner.isAlive()||exField.get(m)!==ex||ownerField.get(m)!==owner)throw Error('Expected exact terminated empty native executor');}
 initialGate();var out=new F(root+'.local-machine-backups/paste-reset-invalidation-'+String(java.lang.System.currentTimeMillis()));if(!out.mkdir())throw Error('Cannot claim private reset record');
 function write(name,b){Fs.write(new F(out,name).toPath(),b);if(hash(Fs.readAllBytes(new F(out,name).toPath()))!==hash(b))throw Error('Backup/report write verification failed');}
 var disk=new F(cfg.getConfigurationDirectory(),'machine.xml'),diskBytes=Fs.readAllBytes(disk.toPath()),diskHash=hash(diskBytes),before=serialized();write('disk-machine-before.xml',diskBytes);write('live-machine-before.xml',bytes(before));
 var r={schema:1,scope:'native-post-reset-disconnect-and-invalidate-only',sourcePath:sourcePath,sourceSha256:sourceHash,jvmStartMs:jvm,liveConfigurationSha256:source.liveConfigurationSha256,controllerPoseTrusted:false,homingRequired:true,noControllerCommands:true,noMotion:true,noReconnect:true,configurationSaved:false,startedAt:new Date().toISOString(),beforeCachedAxes:sameCoordinates()};
 function save(status){r.status=status;write('report.json',bytes(JSON.stringify(r,null,2)+'\n'));}save('backups-verified-before-native-disconnect');var fresh=null,released=false;
 try{
  initialGate();d.disconnect();
  var remaining=val(SP,'serialPort',serial),remainingReader=val(GD,'readerThread',d);if(String(val(GD,'connected',d))!=='false'||(port!=null&&port.isOpen())||(remaining!=null&&remaining.isOpen())||(reader!=null&&reader.isAlive())||(remainingReader!=null&&remainingReader.isAlive()))throw Error('Native disconnect closure not verified');
  r.nativeDisconnectVerified=true;save('native-disconnected-before-machine-disable');
  // Audited disconnected driver setEnabled(false) sends no DISABLE command.
  m.setEnabled(false);planner.unhome();m.setHomed(false);
  if(m.isEnabled()||m.isHomed()||String(val(GD,'connected',d))!=='false')throw Error('Disable/unhome state invalidation failed');common();
  if(exField.get(m)!==ex||ownerField.get(m)!==owner||!ex.isTerminated()||!ex.getQueue().isEmpty())throw Error('Executor changed during invalidation');
  fresh=new (Java.type('java.util.concurrent.ThreadPoolExecutor'))(1,1,1,Java.type('java.util.concurrent.TimeUnit').SECONDS,new (Java.type('java.util.concurrent.LinkedBlockingQueue'))());
  if(fresh.getPoolSize()!==0||fresh.getActiveCount()!==0||!fresh.getQueue().isEmpty())throw Error('Replacement executor unexpectedly active');
  exField.set(m,fresh);released=true;ownerField.set(m,null);m.fireMachineBusy(false);
  if(m.isBusy()||m.isEnabled()||m.isHomed()||exField.get(m)!==fresh||ownerField.get(m)!==null||fresh.getPoolSize()!==0||!fresh.getQueue().isEmpty())throw Error('Post-reset model release verification failed');common();
  if(hash(Fs.readAllBytes(disk.toPath()))!==diskHash)throw Error('Saved configuration changed');write('live-machine-after.xml',bytes(serialized()));r.diskUnchanged=true;r.afterCachedAxes=sameCoordinates();r.cachedCoordinatesRemainUntrusted=true;r.finishedAt=new Date().toISOString();save('reset-invalidated-disabled-unhomed-disconnected-awaiting-separate-connect');
 }catch(e){r.error=String(e);if(released){ownerField.set(m,owner);exField.set(m,ex);try{m.fireMachineBusy(true);}catch(notifyError){r.notificationError=String(notifyError);}}if(fresh!=null)fresh.shutdown();r.finishedAt=new Date().toISOString();save('reset-invalidation-failed-no-retry-never-restore-homing');throw e;}
 print(String(out));
})();
