// Pure current-model native B formatter preview. No controller query, task,
// planner.moveTo, actuation, serial access, or mutation of live coordinates.
(function(){
 var C=Java.type('org.openpnp.model.Configuration'),F=Java.type('java.io.File'),Fs=Java.type('java.nio.file.Files'),UTF=Java.type('java.nio.charset.StandardCharsets').UTF_8,MD=Java.type('java.security.MessageDigest'),AL=Java.type('org.openpnp.model.AxesLocation'),MM=Java.type('org.openpnp.model.LengthUnit').Millimeters,MO=Java.type('org.openpnp.model.Motion$MotionOption'),CT=Java.type('org.openpnp.machine.reference.driver.GcodeDriver$CommandType');
 var root='/home/lumen/lumenpnp/',m=C.get().getMachine(),planner=m.getMotionPlanner();
 function read(path){return String(new java.lang.String(Fs.readAllBytes(new F(path).toPath()),UTF));}
 function bytes(s){return new java.lang.String(s).getBytes(UTF);}
 function hash(b){var a=MD.getInstance('SHA-256').digest(b),s='';for(var i=0;i<a.length;i++)s+=('0'+((a[i]&255).toString(16))).slice(-2);return s;}
 function field(c,n,o){var f=Java.type(c).class.getDeclaredField(n);f.setAccessible(true);return f.get(o);}
 function configHash(){var w=new java.io.StringWriter();C.createSerializer().write(m,w);return hash(bytes(String(w)));}
 eval(read(root+'automation/paste/waste-prime.cjs'));eval(read(root+'automation/paste/waste-prime-native-preview.js'));
 var q=JSON.parse(read(root+'automation/plans/paste-waste-prime-preview-request.json')),jvm=Number(Java.type('java.lang.management.ManagementFactory').getRuntimeMXBean().getStartTime()),now=Number(java.lang.System.currentTimeMillis());
 if(q.schema!==1||q.scope!=='model-only-B-minus20-native-preview'||q.jvmStartMs!==jvm||typeof q.createdMs!=='number'||!isFinite(q.createdMs)||q.createdMs>now||now-q.createdMs>300000||!/^[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}$/.test(q.id))throw Error('Fresh exact-session model-preview request required');
 if(m.getDrivers().size()!==1||String(planner.getClass().getName())!=='org.openpnp.machine.reference.driver.NullMotionPlanner')throw Error('Audited native model required');
 var d=m.getDrivers().get(0),GD='org.openpnp.machine.reference.driver.GcodeDriver',AP='org.openpnp.machine.reference.driver.AbstractMotionPlanner',AM='org.openpnp.spi.base.AbstractMachine',top=m.getDefaultHead().getDefaultCamera();
 if(String(d.getClass().getName())!==GD||String(d.getId())!=='DRV16982438146c1dd4')throw Error('Driver changed');
 var jar=new F(d.getClass().getProtectionDomain().getCodeSource().getLocation().toURI());if(hash(Fs.readAllBytes(jar.toPath()))!=='bcd34923ae91d61a96b98b4c82c93cdc90093ff94292270fd0a18fc6f96f7752')throw Error('Native formatter binary changed');
 var axes={},ids={X:'AXS169824381580efcb',Y:'AXS16982438158c4660',Z:'AXS16982438158d0458',A:'AXS16b068df4e35374e',B:'AXS17108288e61da5fb'};
 for each(var a in new AL(m).drivenBy(d).getControllerAxes()){var k=String(a.getLetter());if(!ids[k]||axes[k]||String(a.getId())!==ids[k])throw Error('Raw axis identity changed');axes[k]=a;}
 if(Object.keys(axes).sort().join(',')!=='A,B,X,Y,Z')throw Error('Five axes required');
 function snapshot(){var s={raw:{},driver:{}};Object.keys(axes).forEach(function(k){s.raw[k]=Number(axes[k].getCoordinate());s.driver[k]=Number(axes[k].getDriverCoordinate());});return s;}
 var reader=field(GD,'readerThread',d),commands=d.commands,executor=field(AM,'executor',m),panel=Java.type('org.openpnp.gui.MainFrame').get().getJobTab(),stateField=panel.getClass().getDeclaredField('state');stateField.setAccessible(true);
 function gate(){if(m.isBusy()||!m.isEnabled()||!m.isHomed()||!planner.isHomed()||String(stateField.get(panel))!=='Stopped'||d.isInSimulationMode()||d.isMotionPending()||configHash()!==q.liveConfigurationSha256||field(GD,'readerThread',d)!==reader||reader==null||!reader.isAlive()||field(GD,'errorResponse',d)!=null||d.commands!==commands)throw Error('Live model/session/configuration changed');if(executor==null||executor!==field(AM,'executor',m)||executor.isShutdown()||executor.getActiveCount()!==0||!executor.getQueue().isEmpty()||field(AP,'motionCommands',planner).size()!==0)throw Error('Native work queued');var sub=field(AP,'subordinateMotion',planner),queue=field(AP+'$SubordinateMotion','queue',sub);if(queue!=null&&!queue.isEmpty())throw Error('Subordinate work queued');if(axes.B.isLimitRotation()||axes.B.isWrapAroundRotation()||!axes.B.isInvertLinearRotational()||Number(axes.B.getFeedratePerSecond().convertToUnits(MM).getValue())!==100||Number(axes.B.getAccelerationPerSecond2().convertToUnits(MM).getValue())!==500||Number(axes.B.getJerkPerSecond3().convertToUnits(MM).getValue())!==2000||Number(planner.getMinimumSpeed())!==.05)throw Error('Reviewed B configuration required');}
 gate();var before=snapshot();PasteWastePrime.compareExact(before.raw,q.expectedRaw,'preview raw');PasteWastePrime.compareExact(before.driver,q.expectedDriver,'preview driver');
 var start=new AL(),end=new AL(),target={};Object.keys(axes).forEach(function(k){target[k]=before.raw[k]-(k==='B'?20:0);start=start.put(new AL(axes[k],before.raw[k]));end=end.put(new AL(axes[k],target[k]));});
 var motion=new (Java.type('org.openpnp.model.Motion'))(top,start,end,.05,MO.SpeedOverPrecision),projected=motion.interpolatedMoveToCommands(d,false);if(projected.size()!==1)throw Error('Expected one native projection');var command=projected.get(0),moved=command.getMovedAxesLocation();if(moved.getControllerAxes().size()!==1||!moved.contains(axes.B)||Number(moved.getCoordinate(axes.B))!==target.B)throw Error('Projection wraps B or changes other axes');
 var formatter=PasteWastePrimeNativePreview.preview(d,command,String(d.getCommand(top,CT.MOVE_TO_COMMAND)));PasteWastePrime.expanded(formatter.expandedCommands,target.B);
 gate();var after=snapshot();PasteWastePrime.compareExact(after.raw,before.raw,'unchanged preview raw');PasteWastePrime.compareExact(after.driver,before.driver,'unchanged preview driver');
 var r={schema:1,id:q.id,scope:'model-only-waste-prime-native-preview',status:'completed-model-only-native-preview',request:q,jvmStartMs:jvm,liveConfigurationSha256:q.liveConfigurationSha256,before:before,after:after,target:target,formatter:formatter,noControllerAccess:true,noMotion:true,finishedAt:new Date().toISOString()};
 var out=new F(root+'automation/evidence/paste-waste-prime-preview-'+q.id);if(!out.mkdir())throw Error('Preview UUID already claimed');Fs.write(new F(out,'report.json').toPath(),bytes(JSON.stringify(r,null,2)+'\n'));print(String(out));
})();
