// Detached cumulative formatter preview for one bounded contiguous scrap batch.
// No controller query, planner dispatch, task submission, serial access or motion.
(function(){
 var C=Java.type('org.openpnp.model.Configuration'),F=Java.type('java.io.File'),Fs=Java.type('java.nio.file.Files'),UTF=Java.type('java.nio.charset.StandardCharsets').UTF_8,MD=Java.type('java.security.MessageDigest'),AL=Java.type('org.openpnp.model.AxesLocation'),MM=Java.type('org.openpnp.model.LengthUnit').Millimeters,MO=Java.type('org.openpnp.model.Motion$MotionOption'),CT=Java.type('org.openpnp.machine.reference.driver.GcodeDriver$CommandType');
 var root='/home/lumen/lumenpnp/',m=C.get().getMachine(),planner=m.getMotionPlanner();
 function read(p){return String(new java.lang.String(Fs.readAllBytes(new F(p).toPath()),UTF));}
 function bytes(s){return new java.lang.String(s).getBytes(UTF);}
 function hash(b){var a=MD.getInstance('SHA-256').digest(b),s='';for(var i=0;i<a.length;i++)s+=('0'+((a[i]&255).toString(16))).slice(-2);return s;}
 function field(c,n,o){var f=Java.type(c).class.getDeclaredField(n);f.setAccessible(true);return f;}
 function configHash(){var w=new java.io.StringWriter();C.createSerializer().write(m,w);return hash(bytes(String(w)));}
 eval(read(root+'automation/paste/waste-prime.cjs'));
 eval(read(root+'automation/paste/ftp-pad-group.cjs'));
 eval(read(root+'automation/paste/ftp-inline-conditioning.cjs'));
 eval(read(root+'automation/paste/ftp-registration-revalidation.cjs'));
 eval(read(root+'automation/paste/fast-camera-inspection.cjs'));
 eval(read(root+'automation/paste/ftp-one-pad-cleanup.cjs'));
 eval(read(root+'automation/paste/ftp-two-pad.cjs'));
 eval(read(root+'automation/paste/commissioning-stroke.cjs'));
 eval(read(root+'automation/paste/position-barrier.cjs'));
 eval(read(root+'automation/paste/manual-home-ledger-anchor.cjs'));
 var q=JSON.parse(read(root+'automation/plans/paste-contiguous-batch-preview-request.json'));
 var jvm=Number(Java.type('java.lang.management.ManagementFactory').getRuntimeMXBean().getStartTime()),now=Number(java.lang.System.currentTimeMillis());
 if(q.schema!==1||['contiguous-native-scrap-batch-preview','contiguous-native-scrap-sequence-comparison-preview',PasteFtpTwoPad.scope(true,q)].indexOf(q.scope)<0)throw Error('Batch preview scope required');
 CommissioningStroke.validateBatch(q,now,jvm,true);
 function freezeEvidence(value){if(value&&typeof value==='object'){Object.keys(value).forEach(function(k){freezeEvidence(value[k]);});Object.freeze(value);}return value;}
 // Per-preview immutable cache: every read still rehashes the file before reuse.
 var frozenEvidenceJson=Object.create(null);
 function parseFrozenEvidence(data,e){var key=String(new F(e.path).getCanonicalPath())+'#'+e.sha256;if(Object.prototype.hasOwnProperty.call(frozenEvidenceJson,key))return frozenEvidenceJson[key];var parsed=freezeEvidence(JSON.parse(String(new java.lang.String(data,UTF))));frozenEvidenceJson[key]=parsed;return parsed;}
 function boundEvidence(e,json){var b=Fs.readAllBytes(new F(e.path).toPath());if(hash(b)!==e.sha256)throw Error('Manual-home evidence changed');return json?parseFrozenEvidence(b,e):String(new java.lang.String(b,UTF));}
 if(q.manualHomeLedgerAnchorEvidence)PasteManualHomeLedgerAnchor.validate(boundEvidence(q.manualHomeLedgerAnchorEvidence,true),q,boundEvidence,now);
 function ftpEvidence(e,json){var b=Fs.readAllBytes(new F(e.path).toPath());if(hash(b)!==e.sha256)throw Error('FTP source changed');return json?parseFrozenEvidence(b,e):null;}
 if(PasteFtpTwoPad.isFtp(q))PasteFtpTwoPad.verifySources(q,ftpEvidence);
 var mDrivers=m.getDrivers(),GD='org.openpnp.machine.reference.driver.GcodeDriver',AP='org.openpnp.machine.reference.driver.AbstractMotionPlanner',AM='org.openpnp.spi.base.AbstractMachine',top=m.getDefaultHead().getDefaultCamera();
 if(mDrivers.size()!==1||String(planner.getClass().getName())!=='org.openpnp.machine.reference.driver.NullMotionPlanner')throw Error('Audited native model required');
 var d=mDrivers.get(0);if(String(d.getClass().getName())!==GD||String(d.getId())!=='DRV16982438146c1dd4')throw Error('Driver changed');
 var jar=new F(d.getClass().getProtectionDomain().getCodeSource().getLocation().toURI());if(hash(Fs.readAllBytes(jar.toPath()))!=='bcd34923ae91d61a96b98b4c82c93cdc90093ff94292270fd0a18fc6f96f7752')throw Error('Native formatter binary changed');
 var axes={},ids={X:'AXS169824381580efcb',Y:'AXS16982438158c4660',Z:'AXS16982438158d0458',A:'AXS16b068df4e35374e',B:'AXS17108288e61da5fb'};
 for each(var a in new AL(m).drivenBy(d).getControllerAxes()){var k=String(a.getLetter());if(!ids[k]||axes[k]||String(a.getId())!==ids[k])throw Error('Raw axis identity changed');axes[k]=a;}
 if(Object.keys(axes).sort().join(',')!=='A,B,X,Y,Z')throw Error('Five exact raw axes required');
 var head=m.getDefaultHead(),left=head.getNozzleByName('N1'),right=head.getNozzleByName('N2'),bottom=null;
 for each(var cam in m.getCameras())if(String(cam.getLooking())==='Up'){if(bottom!==null)throw Error('Multiple bottom cameras');bottom=cam;}
 if(left==null||right==null||top==null||bottom==null||String(left.getId())!=='N1'||String(top.getId())!=='CAM1607555396816'||String(top.getLooking())!=='Down'||String(right.getId())!=='NOZ1710829fd33a0170')throw Error('Unexpected nozzle/camera topology');
 var items={N1:left,N2:right,top:top,bottom:bottom};
 function poses(){var out={};Object.keys(items).forEach(function(k){var p=items[k].getLocation().convertToUnits(MM);out[k]={x:Number(p.getX()),y:Number(p.getY()),z:Number(p.getZ()),rotation:Number(p.getRotation())};});return out;}
 function snap(){var s={raw:{},driver:{},nativePoses:poses()};Object.keys(axes).forEach(function(k){s.raw[k]=Number(axes[k].getCoordinate());s.driver[k]=Number(axes[k].getDriverCoordinate());});return s;}
 function projectedPoses(raw){var result={};Object.keys(items).forEach(function(k){var n=items[k],location=n.getMappedAxes(m);Object.keys(axes).forEach(function(a){location=location.put(new AL(axes[a],raw[a]));});var p=n.toHeadMountableLocation(n.toTransformed(location)).convertToUnits(MM);result[k]={x:Number(p.getX()),y:Number(p.getY()),z:Number(p.getZ()),rotation:Number(p.getRotation())};});return result;}
 function exactPose(a,b,label){['N1','N2','top','bottom'].forEach(function(k){['x','y','z','rotation'].forEach(function(v){PasteWastePrime.close(a[k][v],b[k][v],.0001,label+' '+k+' '+v);});});}
 var reader=field(GD,'readerThread',d).get(d),commands=d.commands,executor=field(AM,'executor',m).get(m),panel=Java.type('org.openpnp.gui.MainFrame').get().getJobTab(),state=panel.getClass().getDeclaredField('state');state.setAccessible(true);
 function gate(){if(m.isBusy()||!m.isEnabled()||!m.isHomed()||!planner.isHomed()||String(state.get(panel))!=='Stopped'||d.isInSimulationMode()||d.isMotionPending()||configHash()!==q.liveConfigurationSha256||field(GD,'readerThread',d).get(d)!==reader||reader==null||!reader.isAlive()||field(GD,'errorResponse',d).get(d)!=null||d.commands!==commands)throw Error('Live model/session/configuration changed');if(executor==null||executor!==field(AM,'executor',m).get(m)||executor.isShutdown()||executor.getActiveCount()!==0||!executor.getQueue().isEmpty()||field(AP,'motionCommands',planner).get(planner).size()!==0)throw Error('Native work queued');var sub=field(AP,'subordinateMotion',planner).get(planner),sq=field(AP+'$SubordinateMotion','queue',sub).get(sub);if(sq!=null&&!sq.isEmpty())throw Error('Subordinate work queued');if(axes.B.isLimitRotation()||axes.B.isWrapAroundRotation()||!axes.B.isInvertLinearRotational()||Number(axes.B.getFeedratePerSecond().convertToUnits(MM).getValue())!==100||Number(axes.B.getAccelerationPerSecond2().convertToUnits(MM).getValue())!==500||Number(axes.B.getJerkPerSecond3().convertToUnits(MM).getValue())!==2000||Number(planner.getMinimumSpeed())!==.05)throw Error('Reviewed B configuration required');['X','Y'].forEach(function(k){if(['None','OneSidedPositioning'].indexOf(String(axes[k].getBacklashCompensationMethod()))<0)throw Error('Unaudited XY backlash method');});if(String(axes.Z.getBacklashCompensationMethod())!=='DirectionalCompensation'||Number(axes.Z.getBacklashOffset().convertToUnits(MM).getValue())!==0||Number(axes.Z.getSneakUpOffset().convertToUnits(MM).getValue())!==0)throw Error('Unaudited Z backlash');}
 gate();var before=snap();PasteWastePrime.compareExact(before.raw,q.expectedRaw,'preview raw');PasteWastePrime.compareExact(before.driver,q.expectedDriver,'preview driver');exactPose(before.nativePoses,q.expectedNativePoses,'preview native pose');
 function rawTarget(start,axis,value){var r={};Object.keys(start).forEach(function(k){r[k]=start[k];});r[axis]=value;return r;}
 var specs=q.previewStages.map(function(s,i){return {name:'stage'+i,axis:s.axis,start:s.startRaw,target:s.targetRaw,speed:s.speedFraction,dwellMilliseconds:s.dwellMilliseconds===undefined?0:s.dwellMilliseconds};});
 // One detached driver clone carries its send-on-change cache across all bounded
 // formatter calls, matching sequential native formatting without touching d.
 var captures=[],rates={};for(var ri=1;ri<=3;ri++)rates[ri]=d.getMinimumRate(ri);
 function forbidden(){throw new java.lang.IllegalStateException('Detached preview cannot access transport');}
 var Clone=Java.extend(Java.type(GD),{connect:forbidden,getCommunications:forbidden,getSerial:forbidden,sendCommand:forbidden,getMinimumRate:function(order){return rates[Number(order)];},getAxisVariables:function(machine){return java.util.Arrays.asList(Java.to(['X','Y','Z','A','B'],'java.lang.String[]'));},sendGcode:function(g){captures.push(String(g));}});
 var clone=new Clone();clone.setUnits(d.getUnits());clone.setUsingLetterVariables(d.isUsingLetterVariables());clone.setSupportingPreMove(d.isSupportingPreMove());clone.setMotionControlType(d.getMotionControlType());
 if(String(clone.getUnits())!=='Millimeters'||!clone.isUsingLetterVariables()||clone.isSupportingPreMove())throw Error('Audited letter-variable formatter required');
 clone.setCommand(null,CT.MOVE_TO_COMMAND,String(d.getCommand(top,CT.MOVE_TO_COMMAND)));
 ['sendOnChangeFeedRate','sendOnChangeAcceleration','sendOnChangeJerk'].forEach(function(name){var f=field(GD,name),original=f.get(d);if(original===null){f.set(clone,null);return;}var klass=Java.type(GD+'$SendOnChange').class,ctor=klass.getDeclaredConstructor();ctor.setAccessible(true);var cp=ctor.newInstance();['sendOnChange','relativeDeviation','variable','lastValue'].forEach(function(key){var part=field(GD+'$SendOnChange',key);part.set(cp,part.get(original));});f.set(clone,cp);});
 var detachedMachine=new (Java.type('org.openpnp.machine.reference.ReferenceMachine'))(),detachedHead=new (Java.type('org.openpnp.machine.reference.ReferenceHead'))(),mountable=new (Java.type('org.openpnp.machine.reference.ReferenceNozzle'))();detachedMachine.addHead(detachedHead);detachedHead.addNozzle(mountable);
 var copiedAxes={};Object.keys(axes).forEach(function(k){var src=axes[k],cp=new (Java.type('org.openpnp.machine.reference.axis.ReferenceControllerAxis'))();cp.setType(src.getType());cp.setLetter(src.getLetter());cp.setDriver(clone);cp.setInvertLinearRotational(src.isInvertLinearRotational());cp.setDriverCoordinate(src.getDriverCoordinate());detachedMachine.addAxis(cp);copiedAxes[k]=cp;});
 function location(raw){var a=new AL();Object.keys(copiedAxes).forEach(function(k){a=a.put(new AL(copiedAxes[k],raw[k]));});return a;}
 var MC=Java.type('org.openpnp.model.Motion$MoveToCommand'),stages=[];
 specs.forEach(function(s){gate();if(!planner.isValidLocation(top,new AL(axes[s.axis],s.target[s.axis])))throw Error('Preview stage outside native limits');var nativeTargets=projectedPoses(s.target);['N1','N2'].forEach(function(k){var b=q.headClearanceBounds[k];['x','y','z'].forEach(function(a){var u=a.toUpperCase();if(nativeTargets[k][a]<b['min'+u]||nativeTargets[k][a]>b['max'+u])throw Error('Preview head path exceeds reviewed bounds '+k+' '+a);});});var start=new AL(),end=new AL();Object.keys(axes).forEach(function(k){start=start.put(new AL(axes[k],s.start[k]));end=end.put(new AL(axes[k],s.target[k]));});var motion=new (Java.type('org.openpnp.model.Motion'))(top,start,end,s.speed,MO.SpeedOverPrecision),projected=motion.interpolatedMoveToCommands(d,false);if(projected.size()!==1)throw Error('Stage '+s.name+' must project to one native command');var cmd=projected.get(0),moved=cmd.getMovedAxesLocation();if(moved.getControllerAxes().size()!==1||!moved.contains(axes[s.axis])||Number(moved.getCoordinate(axes[s.axis]))!==s.target[s.axis])throw Error('Stage '+s.name+' projection changed axes or target');
  var beforeCount=captures.length,st=location(s.start),en=location(s.target),mv=new AL();mv=mv.put(new AL(copiedAxes[s.axis],s.target[s.axis]));var detached=new MC(null,st,en,mv,cmd.getFeedRatePerSecond(),cmd.getAccelerationPerSecond2(),cmd.getJerkPerSecond3(),cmd.getTimeStart(),cmd.getTimeDuration(),cmd.getV0(),cmd.getV1());clone.moveTo(mountable,detached);if(captures.length!==beforeCount+1)throw Error('Stage '+s.name+' did not produce one intercepted formatter output');
  var text=captures[captures.length-1],expanded=text.split(/\r?\n/).map(function(line){return line.trim().replace(/\s+/g,' ');}).filter(function(line){return line.length;});stages.push({name:s.name,axis:s.axis,speedFraction:s.speed,dwellMilliseconds:s.dwellMilliseconds,startRaw:s.start,targetRaw:s.target,nativeTargets:nativeTargets,expandedCommands:expanded,formatter:{scope:'disconnected-native-GcodeDriver-moveTo-formatter',expandedCommands:expanded,rawExpandedText:text,transportCalls:0,stagewiseSendOnChangeCache:true}});
 });
 gate();var after=snap();PasteWastePrime.compareExact(after.raw,before.raw,'unchanged preview raw');PasteWastePrime.compareExact(after.driver,before.driver,'unchanged preview driver');exactPose(after.nativePoses,before.nativePoses,'unchanged preview native pose');
 var trace=new F(root+'automation/evidence/paste-contiguous-batch-preview-'+q.id);if(!trace.mkdir())throw Error('Preview evidence already claimed');
 stages.forEach(function(s){var fn=s.name+'-formatter.json',o={schema:1,id:q.id,name:s.name,axis:s.axis,speedFraction:s.speedFraction,dwellMilliseconds:s.dwellMilliseconds,startRaw:s.startRaw,targetRaw:s.targetRaw,expandedCommands:s.expandedCommands,formatter:s.formatter};Fs.write(new F(trace,fn).toPath(),bytes(JSON.stringify(o,null,2)+'\n'));s.formatterEvidence={path:String(new F(trace,fn)),sha256:hash(Fs.readAllBytes(new F(trace,fn).toPath()))};s.path=s.formatterEvidence.path;s.sha256=s.formatterEvidence.sha256;});
 var r={schema:1,id:q.id,scope:q.scope,status:'completed-model-only-contiguous-batch-preview',request:q,jvmStartMs:jvm,liveConfigurationSha256:q.liveConfigurationSha256,before:before,after:after,stages:stages,cacheModel:'One detached GcodeDriver clone per report; scalar send-on-change cache copied from live driver once and carried across all reviewed batch stages in order.',noControllerAccess:true,noMotion:true,finishedAt:new Date().toISOString()};
 Fs.write(new F(trace,'report.json').toPath(),bytes(JSON.stringify(r,null,2)+'\n'));print(String(trace));
})();
