// Native OpenPnP fiducial detector at an explicitly reviewed current pose.
// Reads the saved FTP job model offline; never selects/saves it or moves hardware.
(function(){
 var C=Java.type('org.openpnp.model.Configuration'),F=Java.type('java.io.File'),Fs=Java.type('java.nio.file.Files'),UTF=Java.type('java.nio.charset.StandardCharsets').UTF_8,AL=Java.type('org.openpnp.model.AxesLocation'),I=Java.type('javax.imageio.ImageIO'),MD=Java.type('java.security.MessageDigest'),U2=Java.type('org.openpnp.util.Utils2D'),LUnit=Java.type('org.openpnp.model.LengthUnit'),IR=Java.type('org.openpnp.vision.pipeline.stages.ImageRead'),CS=Java.type('org.openpnp.vision.FluentCv$ColorSpace'),KP=Java.type('org.opencv.core.KeyPoint'),VU=Java.type('org.openpnp.util.VisionUtils'),EX=Java.type('java.lang.Exception'),ROOT='/home/lumen/lumenpnp/';
 function field(c,n,o){var f=Java.type(c).class.getDeclaredField(n);f.setAccessible(true);return f.get(o);}
 function bytes(s){return new java.lang.String(s).getBytes(UTF);}
 function hash(data){var a=MD.getInstance('SHA-256').digest(data),s='';for(var i=0;i<a.length;i++)s+=('0'+((a[i]&255).toString(16))).slice(-2);return s;}
 function writeJson(file,value){Fs.write(file.toPath(),bytes(JSON.stringify(value,null,2)+'\n'));}
 function configHash(m){var w=new java.io.StringWriter();C.createSerializer().write(m,w);return hash(bytes(String(w)));}
 function mm(p){var q=p.convertToUnits(LUnit.Millimeters);return {x:Number(q.getX()),y:Number(q.getY()),z:Number(q.getZ()),rotation:Number(q.getRotation())};}
 function snapshot(m,driver){var a={};for each(var axis in new AL(m).drivenBy(driver).getControllerAxes())a[String(axis.getLetter())]={model:Number(axis.getCoordinate()),driver:Number(axis.getDriverCoordinate())};return a;}
 function sameAxes(a,b){return !!a&&!!b&&['X','Y','Z','A','B'].every(function(k){return a[k]&&b[k]&&a[k].model===b[k].model&&a[k].driver===b[k].driver;});}
 function sameRaw(a,b){return !!a&&!!b&&['X','Y','Z','A','B'].every(function(k){return Number(a[k])===Number(b[k]);});}
 function samePose(a,b){return !!a&&!!b&&['x','y','z','rotation'].every(function(k){return Number(a[k])===Number(b[k]);});}
 var out=new F(ROOT+'automation/evidence/native-fiducial-static-'+java.lang.System.currentTimeMillis());if(!out.mkdir())throw Error('Unique evidence directory required');
 var report={schema:1,scope:'native-current-pose-fiducial-vision',status:'started',requestId:String(java.util.UUID.randomUUID()),startedAt:new Date().toISOString(),images:{},noMotion:true,noActuation:true,noVacuum:true,jobSaved:false,configurationSaved:false,physicalRegistrationEstablished:false};
 var exposure=null,originalExposure=null,originalAuto=null,pipe=null,m=null,driver=null,camera=null,before=null,startCamera=null,beforeHash=null;
 try{
  var requestPath=ROOT+'automation/plans/paste-fiducial-vision-request.json',requestBytes=Fs.readAllBytes(new F(requestPath).toPath()),request=JSON.parse(String(new java.lang.String(requestBytes,UTF)));
  if(request.schema!==1||request.scope!=='native-current-pose-fiducial-vision-request'||['FID1','FID2','FID3'].indexOf(String(request.reference))<0)throw Error('Explicit schema-1 fiducial vision request required');
  if(!request.sourceBarrier||typeof request.sourceBarrier.path!=='string'||typeof request.sourceBarrier.sha256!=='string')throw Error('Hash-bound current-position barrier required');
  var barrierBytes=Fs.readAllBytes(new F(request.sourceBarrier.path).toPath());if(hash(barrierBytes)!==request.sourceBarrier.sha256)throw Error('Source barrier hash mismatch');var barrier=JSON.parse(String(new java.lang.String(barrierBytes,UTF)));
  if(barrier.schema!==1||!barrier.request||barrier.request.scope!=='read-only-native-position-barrier'||barrier.status!=='completed-read-only-position-barrier'||barrier.controllerPositionVerified!==true||barrier.uncertainCompletion!==false||barrier.noMotionCommandSubmitted!==true||!barrier.afterQuerySnapshot)throw Error('Completed read-only source barrier required');
  var immutableRequest=new F(out,'request.json');Fs.write(immutableRequest.toPath(),requestBytes);report.requestId=String(request.id||report.requestId);report.requestEvidence={path:String(immutableRequest),sha256:hash(requestBytes)};report.sourceBarrier={path:String(request.sourceBarrier.path),sha256:String(request.sourceBarrier.sha256)};report.sourceBarrierId=String(barrier.request.id);report.sourceBarrierSnapshot=barrier.afterQuerySnapshot;report.reference=String(request.reference);report.expectedCameraLocationMm=request.expectedCameraLocationMm;
  if(!request.expectedCameraLocationMm||typeof request.expectedCameraLocationMm!=='object')throw Error('Explicit expectedCameraLocationMm required');
  var cfg=C.get();m=cfg.getMachine();var planner=m.getMotionPlanner(),panel=Java.type('org.openpnp.gui.MainFrame').get().getJobTab(),state=panel.getClass().getDeclaredField('state');state.setAccessible(true);
  if(!m.isEnabled()||!m.isHomed()||m.isBusy()||String(state.get(panel))!=='Stopped')throw Error('Enabled, homed, idle machine and stopped job required');
  if(m.getDrivers().size()!==1)throw Error('Single existing driver required');driver=m.getDrivers().get(0);
  if(driver.isMotionPending()||field('org.openpnp.machine.reference.driver.AbstractMotionPlanner','motionCommands',planner).size()!==0)throw Error('Motion queue must be empty');
  var executor=field('org.openpnp.spi.base.AbstractMachine','executor',m);if(executor!=null&&(executor.isShutdown()||executor.isTerminated()||executor.getActiveCount()!==0||!executor.getQueue().isEmpty()))throw Error('Native machine executor must be idle');
  var h=m.getDefaultHead(),nozzles=h.getNozzles(),n1=null,n2=null;for each(var n in nozzles){var nn=String(n.getName());if(nn==='N1')n1=n;if(nn==='N2')n2=n;if(n.getPart()!=null)throw Error('No nozzle may hold a part');}
  if(n1==null||n2==null||n2.getNozzleTip()!=null)throw Error('N2 must remain excluded with no installed tip');
  before=snapshot(m,driver);if(!before.Z||!before.B)throw Error('Raw Z/B pose unavailable');if(!sameRaw({X:before.X?before.X.model:undefined,Y:before.Y?before.Y.model:undefined,Z:before.Z.model,A:before.A?before.A.model:undefined,B:before.B.model},barrier.afterQuerySnapshot.raw))throw Error('Live raw model differs from source barrier');
  if(!sameAxes(before,barrier.afterQuerySnapshot.raw?{X:{model:barrier.afterQuerySnapshot.raw.X,driver:barrier.afterQuerySnapshot.driver.X},Y:{model:barrier.afterQuerySnapshot.raw.Y,driver:barrier.afterQuerySnapshot.driver.Y},Z:{model:barrier.afterQuerySnapshot.raw.Z,driver:barrier.afterQuerySnapshot.driver.Z},A:{model:barrier.afterQuerySnapshot.raw.A,driver:barrier.afterQuerySnapshot.driver.A},B:{model:barrier.afterQuerySnapshot.raw.B,driver:barrier.afterQuerySnapshot.driver.B}}:null))throw Error('Live raw/driver model differs from barrier');
  camera=h.getDefaultCamera();if(camera==null||String(camera.getLooking())!=='Down'||String(camera.getId())!=='CAM1607555396816')throw Error('Expected native top camera');
  if(!samePose(mm(camera.getLocation()),request.expectedCameraLocationMm)||!samePose(barrier.afterQuerySnapshot.nativePoses.top,request.expectedCameraLocationMm))throw Error('Current top-camera pose differs from request/source barrier');
  var openMethod=camera.getClass().getDeclaredMethod('isOpen');openMethod.setAccessible(true);if(!openMethod.invoke(camera))throw Error('Top camera stream must already be open; no camera reopen');
  exposure=camera.getExposure();if(exposure==null||!exposure.isSupported()||exposure.isAuto()||Number(exposure.getValue())!==146)throw Error('Expected supported manual top exposure 146');
  originalExposure=Number(exposure.getValue());originalAuto=exposure.isAuto();beforeHash=configHash(m);if(beforeHash!==barrier.liveConfigurationSha256)throw Error('Live configuration differs from source barrier');
  startCamera=mm(camera.getLocation());report.jvmStartMs=Number(Java.type('java.lang.management.ManagementFactory').getRuntimeMXBean().getStartTime());report.liveConfigurationBeforeSha256=beforeHash;report.modelPoseBefore=before;report.camera={id:String(camera.getId()),locationMm:startCamera,exposureOriginal:originalExposure,exposureUsed:36,exposureRestored:false};report.nativePose={cameraLocationMm:startCamera,rawAxes:before};
  if(Number(barrier.request.jvmStartMs)!==report.jvmStartMs||barrier.request.liveConfigurationSha256!==beforeHash)throw Error('Source barrier JVM/configuration session differs');
  var savedJobPath=ROOT+'automation/jobs/ftp-20260924.job.xml',savedJob=cfg.loadJob(new F(savedJobPath));if(savedJob==null||String(savedJob.getFile()).indexOf('ftp-20260924.job.xml')<0)throw Error('Saved FTP job model could not be loaded offline');
  var bls=savedJob.getBoardLocations();if(bls.size()!==1)throw Error('Saved FTP job must contain exactly one board');var bl=bls.get(0),board=bl.getBoard(),placements=board.getPlacements(),fids=[],selectedPlacement=null;
  ['FID1','FID2','FID3'].forEach(function(ref){var p=null;for each(var candidate in placements)if(String(candidate.getId())===ref)p=candidate;if(p==null||p.getPart()==null)throw Error('Saved FTP job missing fiducial '+ref);var local=mm(p.getLocation()),global=U2.calculateBoardPlacementLocation(bl,p.getLocation());fids.push({reference:ref,partId:String(p.getPart().getId()),localXYMm:[local.x,local.y],savedJobExpectedMachineXYMm:[mm(global).x,mm(global).y]});if(ref===String(request.reference))selectedPlacement=p;});
  if(selectedPlacement==null)throw Error('Requested fiducial absent from saved job');var matrix=[0,0,0,0,0,0],ltg=bl.getLocalToGlobalTransform();if(ltg!=null)ltg.getMatrix(matrix);else matrix=[1,0,0,1,0,0];
  report.jobPath=savedJobPath;report.board={boardId:String(bl.getUniqueId()),side:String(bl.getGlobalSide()),localToGlobalMatrix:matrix,fiducials:fids,savedTransformForComparisonOnly:true};report.nativeFiducialDetection={reference:String(request.reference),expectedMachineXYMm:[startCamera.x,startCamera.y],savedJobExpectedMachineXYMm:fids[['FID1','FID2','FID3'].indexOf(String(request.reference))].savedJobExpectedMachineXYMm,keypoints:[]};
  exposure.setValue(36);if(Number(exposure.getValue())!==36||exposure.isAuto())throw Error('Manual exposure 36 setter not verified');java.lang.Thread.sleep(700);
  if(!sameAxes(snapshot(m,driver),before)||!samePose(mm(camera.getLocation()),startCamera))throw Error('Model pose changed before capture');
  var raw=camera.captureRaw(),nativeImage=camera.captureTransformed();if(raw==null||nativeImage==null)throw Error('Current-pose top capture failed');
  var rawFile=new F(out,'top-raw.png'),nativeFile=new F(out,'native-pipeline-input.png');if(!I.write(raw,'png',rawFile)||!I.write(nativeImage,'png',nativeFile))throw Error('Cannot save current-pose images');
  report.images.raw={path:String(rawFile),sha256:hash(Fs.readAllBytes(rawFile.toPath())),width:raw.getWidth(),height:raw.getHeight()};report.images.nativeInput={path:String(nativeFile),sha256:hash(Fs.readAllBytes(nativeFile.toPath())),width:nativeImage.getWidth(),height:nativeImage.getHeight()};
  var locator=m.getFiducialLocator(),target=[startCamera.x,startCamera.y],expected=new (Java.type('org.openpnp.model.Location'))(LUnit.Millimeters,target[0],target[1],startCamera.z,startCamera.rotation),settings=locator.getInheritedVisionSettings(selectedPlacement.getPart());
  if(settings==null||!settings.isEnabled())throw Error('Saved native fiducial vision settings unavailable or disabled');report.nativeFiducialDetection.visionSettingsId=String(settings.getId());report.nativeFiducialDetection.visionSettingsName=String(settings.getName());
  // getFiducialPipeline returns the settings-owned object here. Clone first,
  // then prepare the clone with the native public API.
  pipe=settings.getPipeline().clone();locator.preparePipeline(pipe,settings.getPipelineParameterAssignments(),camera,selectedPlacement.getPart(),expected);
  var imageStage=new IR();imageStage.setName('image');imageStage.setColorSpace(CS.Bgr);imageStage.setFile(nativeFile);pipe.remove('image');pipe.insert(imageStage,0);pipe.setProperty('fiducial.center',expected);pipe.setProperty('MaskCircle.center',expected);var circle=pipe.getStage('cir');if(circle==null||String(circle.getClass().getName())!=='org.openpnp.vision.pipeline.stages.DetectCircularSymmetry')throw Error('Expected saved cir stage');circle.setMinDiameter(80);circle.setMaxDiameter(115);circle.setMaxDistance(70);circle.setSuperSampling(4);report.nativeFiducialDetection.cloneOnlyParameters={minDiameterPixels:80,maxDiameterPixels:115,maxDistancePixels:70,superSampling:4,basis:'Observed 1mm copper disk approximately94pixels; bounded current-pose search excludes FID lettering172pixels from center. Saved settings unchanged.'};pipe.process();
  var found=pipe.getExpectedResult('results').getExpectedListModel(KP.class,new EX('Native fiducial results missing')),best=null,bestDist=Number.POSITIVE_INFINITY;
  for each(var kp in found){var pos=VU.getPixelLocation(camera,Number(kp.pt.x),Number(kp.pt.y)),q=mm(pos),xy=[q.x,q.y],dx=xy[0]-target[0],dy=xy[1]-target[1],dist=Math.sqrt(dx*dx+dy*dy);report.nativeFiducialDetection.keypoints.push({pixel:[Number(kp.pt.x),Number(kp.pt.y)],machineXYMm:xy,cameraCenterResidualMm:dist});if(dist<bestDist){best=xy;bestDist=dist;}}
  report.nativeFiducialDetection.detectedMachineXYMm=best;report.nativeFiducialDetection.cameraCenterResidualMm=isFinite(bestDist)?bestDist:null;
  report.status=best==null?'completed-no-native-fiducial-awaiting-review':'completed-native-fiducial-detection-awaiting-review';
 }catch(error){report.error=String(error);report.status='failed-preflight-or-detection';}
 finally{
  if(pipe!=null)try{pipe.close();}catch(closeError){report.pipelineCloseError=String(closeError);report.status='failed-inspect-pipeline-close';}
  if(exposure!=null&&originalExposure!==null)try{exposure.setValue(originalExposure);exposure.setAuto(originalAuto);report.camera=report.camera||{};report.camera.exposureRestored=Number(exposure.getValue())===originalExposure&&exposure.isAuto()===originalAuto;if(!report.camera.exposureRestored)throw Error('Original camera exposure not restored');}catch(restoreError){report.restoreError=String(restoreError);report.status='failed-inspect-restoration';}
  if(m!=null&&driver!=null)try{report.modelPoseAfter=snapshot(m,driver);report.modelPoseUnchanged=before==null||sameAxes(report.modelPoseAfter,before);report.liveConfigurationAfterSha256=configHash(m);report.configurationRestored=beforeHash==null||report.liveConfigurationAfterSha256===beforeHash;if(camera!=null&&startCamera!=null)report.camera.locationAfterMm=mm(camera.getLocation());if(report.modelPoseUnchanged===false||report.configurationRestored===false||report.camera&&report.camera.exposureRestored===false)report.status='failed-inspect-restoration';}catch(finalError){report.finalError=String(finalError);report.status='failed-inspect-restoration';}
  report.finishedAt=new Date().toISOString();report.noMotion=report.modelPoseUnchanged!==false;report.noActuation=true;report.noVacuum=true;report.jobSaved=false;report.configurationSaved=false;
  try{writeJson(new F(out,'report.json'),report);}catch(writeError){print('Evidence write failed: '+String(writeError));}
  print(String(out));
 }
})();
