// Exact model-only release after an independently completed fresh AIR count audit.
// Resets only the proven empty dead executor and the retained busy marker.
(function(){
var C=Java.type('org.openpnp.model.Configuration'),F=Java.type('java.io.File'),Fs=Java.type('java.nio.file.Files'),UTF=Java.type('java.nio.charset.StandardCharsets').UTF_8,MD=Java.type('java.security.MessageDigest'),MM=Java.type('org.openpnp.model.LengthUnit').Millimeters,AL=Java.type('org.openpnp.model.AxesLocation');
var root='/home/lumen/lumenpnp/',id='20e7157b-9893-4f23-97fc-1478bb8f17f4',faultPath=root+'automation/evidence/paste-contiguous-batch-'+id+'/report.json',faultHash='8d6b15909e59f1e34c652c3ae822051e1d6a1eedb8d46ccea410e35884796e2c',requestPath=root+'automation/plans/paste-air-count-origin-release-request.json';
function bytes(s){return new java.lang.String(s).getBytes(UTF);}function hash(b){var a=MD.getInstance('SHA-256').digest(b),s='';for(var i=0;i<a.length;i++)s+=('0'+((a[i]&255).toString(16))).slice(-2);return s;}function read(p){return String(new java.lang.String(Fs.readAllBytes(new F(p).toPath()),UTF));}function verified(ev,label){if(!ev||typeof ev.path!=='string'||ev.path.charAt(0)!=='/'||!/^[a-f0-9]{64}$/.test(ev.sha256))throw Error('Hash-bound '+label+' required');var b=Fs.readAllBytes(new F(ev.path).toPath());if(hash(b)!==ev.sha256)throw Error(label+' changed');return JSON.parse(String(new java.lang.String(b,UTF)));}function field(c,n){var f=Java.type(c).class.getDeclaredField(n);f.setAccessible(true);return f;}function close(a,b,label){if(typeof a!=='number'||typeof b!=='number'||!isFinite(a)||!isFinite(b)||Math.abs(a-b)>0.0001)throw Error(label+' changed');}
var q=JSON.parse(read(requestPath)),now=Number(java.lang.System.currentTimeMillis());if(!q||!q.auditEvidence)throw Error('Reviewed hash-bound audit evidence required');var fault=verified({path:faultPath,sha256:faultHash},'exact AIR fault'),audit=verified(q.auditEvidence,'fresh independent audit');
if(!q||q.schema!==1||q.scope!=='reviewed-air-count-origin-stop-release'||q.faultId!==id||!q.faultEvidence||q.faultEvidence.path!==faultPath||q.faultEvidence.sha256!==faultHash||q.jvmStartMs!==fault.request.jvmStartMs||q.liveConfigurationSha256!==fault.request.liveConfigurationSha256||typeof q.createdMs!=='number'||q.createdMs>now||now-q.createdMs>300000||typeof q.operator!=='string'||!q.operator.trim()||typeof q.reviewBasis!=='string'||q.reviewBasis.trim().length<30)throw Error('Fresh explicit exact-fault release request required');
if(q.auditEvidence.path!==root+'automation/evidence/paste-air-count-audit-'+id+'-attempt2/report.json'||audit.scope!=='read-only-exact-air-count-origin-stop-audit'||audit.status!=='audit-complete-awaiting-separate-model-release'||audit.faultId!==id||audit.faultEvidence.path!==faultPath||audit.faultEvidence.sha256!==faultHash||audit.jvmStartMs!==q.jvmStartMs||audit.liveConfigurationSha256!==q.liveConfigurationSha256||audit.positionVerified!==true||audit.motionIssued!==false||audit.ledgerReserved!==false||!audit.finishedAt||now-Date.parse(audit.finishedAt)>300000||!audit.expectedAfterStageRaw||!audit.afterQuerySnapshot||!audit.counts||audit.counts.X!==101667||audit.counts.Y!==59062||audit.counts.Z!==1290||audit.counts.A!==888||audit.counts.B!==-15655)throw Error('Fresh successful no-motion AIR audit required');
var sourceQ=fault.request,stage=fault.stage0,expected=stage&&stage.saved&&stage.saved.raw;if(fault.status!=='failed-no-retry-no-recovery-motion'||fault.uncertainCompletion!==true||fault.motionSubmitted!==true||fault.executorQuarantined!==true||fault.auditIncomplete!==true||fault.queuedTasksCancelled!==0||!expected||expected.X!==317.62||audit.expectedAfterStageRaw.X!==317.62)throw Error('Exact failed stage/fault state changed');
var ledger=verified(audit.ledgerEvidence,'unchanged existing ledger');if(audit.ledgerEvidence.sha256!==sourceQ.previousLedgerSha256||hash(Fs.readAllBytes(new F(audit.ledgerEvidence.path).toPath()))!==audit.ledgerEvidence.sha256)throw Error('AIR batch ledger must remain unchanged');
var m=C.get().getMachine(),planner=m.getMotionPlanner(),jvm=Number(Java.type('java.lang.management.ManagementFactory').getRuntimeMXBean().getStartTime()),drivers=m.getDrivers();if(jvm!==q.jvmStartMs||!m.isBusy()||!m.isEnabled()||!m.isHomed()||drivers.size()!==1||String(planner.getClass().getName())!=='org.openpnp.machine.reference.driver.NullMotionPlanner')throw Error('Current latched machine/JVM changed');
var d=drivers.get(0),exField=field('org.openpnp.spi.base.AbstractMachine','executor'),ownerField=field('org.openpnp.spi.base.AbstractMachine','taskThread'),oldEx=exField.get(m),oldOwner=ownerField.get(m),GT='org.openpnp.machine.reference.driver.GcodeDriver';if(String(d.getClass().getName())!==GT||String(d.getId())!=='DRV16982438146c1dd4'||!field(GT,'connected').get(d))throw Error('Native driver owner changed');
var panel=Java.type('org.openpnp.gui.MainFrame').get().getJobTab(),state=panel.getClass().getDeclaredField('state');state.setAccessible(true);
function conf(){var w=new java.io.StringWriter();C.createSerializer().write(m,w);return hash(bytes(String(w)));}
var reader=field(GT,'readerThread').get(d),motions=field('org.openpnp.machine.reference.driver.AbstractMotionPlanner','motionCommands').get(planner);
if(String(state.get(panel))!=='Stopped'||oldEx==null||!oldEx.isShutdown()||!oldEx.isTerminated()||oldEx.getActiveCount()!==0||oldEx.getQueue().size()!==0||oldOwner==null||oldOwner.isAlive()||motions.size()!==0||d.isMotionPending()||reader==null||!reader.isAlive()||field(GT,'errorResponse').get(d)!=null||conf()!==q.liveConfigurationSha256)throw Error('Expected exact stopped busy fault with healthy reader and dead empty executor');
var right=m.getDefaultHead().getNozzleByName('N2'),left=m.getDefaultHead().getNozzleByName('N1');if(right==null||left==null||right.getNozzleTip()!=null||right.getCompatibleNozzleTips().size()!==0||right.isChangerEnabled()||right.getPart()!=null||m.getPnpJobProcessor().isPreRotateAllNozzles())throw Error('N2 quarantine changed');
var axes={};for each(var a in new AL(m).drivenBy(d).getControllerAxes()){var k=String(a.getLetter());if(axes[k])throw Error('Duplicate axis');axes[k]=a;}function snapshot(){var s={raw:{},driver:{},nativePoses:{}};Object.keys(axes).forEach(function(k){s.raw[k]=Number(axes[k].getCoordinate());s.driver[k]=Number(axes[k].getDriverCoordinate());});var top=m.getDefaultHead().getDefaultCamera(),bottom=null;for each(var c in m.getCameras())if(String(c.getLooking())==='Up')bottom=c;var all={N1:left,N2:right,top:top,bottom:bottom};Object.keys(all).forEach(function(k){var p=all[k].getLocation().convertToUnits(MM);s.nativePoses[k]={x:Number(p.getX()),y:Number(p.getY()),z:Number(p.getZ()),rotation:Number(p.getRotation())};});return s;}function same(s){['X','Y','Z','A','B'].forEach(function(k){close(s.raw[k],audit.afterQuerySnapshot.raw[k],'raw '+k);close(s.driver[k],audit.afterQuerySnapshot.driver[k],'driver '+k);});['N1','N2','top','bottom'].forEach(function(k){['x','y','z','rotation'].forEach(function(a){close(s.nativePoses[k][a],audit.afterQuerySnapshot.nativePoses[k][a],k+' '+a);});});}
same(snapshot());
var out=new F(root+'automation/evidence/paste-air-count-release-'+id);if(!out.mkdir())throw Error('Exact release already claimed; inspect existing report');var r={schema:1,scope:'model-only-exact-air-count-origin-stop-release',faultId:id,faultEvidence:q.faultEvidence,auditEvidence:q.auditEvidence,jvmStartMs:jvm,liveConfigurationSha256:q.liveConfigurationSha256,operator:q.operator,reviewBasis:q.reviewBasis,startedAt:new Date().toISOString(),before:snapshot(),busyLatchCleared:false,executorReset:false,controllerQueryIssued:false,motionIssued:false,replayIssued:false,configurationSaved:false,ledgerModified:false};function save(s){r.status=s;Fs.write(new F(out,'report.json').toPath(),bytes(JSON.stringify(r,null,2)+'\n'));}save('validated-before-model-only-release');
var fresh=null,changed=false;try{fresh=new (Java.type('java.util.concurrent.ThreadPoolExecutor'))(1,1,1,Java.type('java.util.concurrent.TimeUnit').SECONDS,new (Java.type('java.util.concurrent.LinkedBlockingQueue'))());if(fresh.getPoolSize()!==0||fresh.getActiveCount()!==0||fresh.getQueue().size()!==0)throw Error('Replacement executor unexpectedly active');if(conf()!==q.liveConfigurationSha256||!m.isBusy()||!oldEx.isShutdown()||!oldEx.isTerminated()||oldEx.getQueue().size()!==0||oldOwner.isAlive())throw Error('Machine changed immediately before release');exField.set(m,fresh);changed=true;ownerField.set(m,null);m.fireMachineBusy(false);if(m.isBusy()||exField.get(m)!==fresh||ownerField.get(m)!==null||fresh.isShutdown()||fresh.getPoolSize()!==0||fresh.getQueue().size()!==0||conf()!==q.liveConfigurationSha256)throw Error('Post-release state mismatch');same(snapshot());if(hash(Fs.readAllBytes(new F(audit.ledgerEvidence.path).toPath()))!==audit.ledgerEvidence.sha256)throw Error('Existing ledger changed');r.after=snapshot();r.busyLatchCleared=true;r.executorReset=true;r.finishedAt=new Date().toISOString();save('model-release-complete-no-motion-no-query-no-replay');}catch(e){r.error=String(e);if(changed){ownerField.set(m,oldOwner);exField.set(m,oldEx);try{m.fireMachineBusy(true);}catch(ne){r.notifyError=String(ne);}}if(fresh!==null)fresh.shutdown();r.finishedAt=new Date().toISOString();save('release-failed-old-model-latch-restored');throw e;}print(String(out));
})();
