// Model-only restoration of the N2 exclusion field initialized by OpenPnP startup.
(function(){
var C=Java.type('org.openpnp.model.Configuration'),F=Java.type('java.io.File'),Fs=Java.type('java.nio.file.Files'),UTF=Java.type('java.nio.charset.StandardCharsets').UTF_8,MD=Java.type('java.security.MessageDigest'),L=Java.type('org.openpnp.model.Location'),MM=Java.type('org.openpnp.model.LengthUnit').Millimeters;
var m=C.get().getMachine(),n=m.getDefaultHead().getNozzleByName('N2');
function bytes(s){return new java.lang.String(s).getBytes(UTF);}function hash(b){var a=MD.getInstance('SHA-256').digest(b),s='';for(var i=0;i<a.length;i++)s+=('0'+((a[i]&255).toString(16))).slice(-2);return s;}
function xml(){var w=new java.io.StringWriter();C.createSerializer().write(m,w);return String(w);}
function field(type,name,obj){var f=Java.type(type).class.getDeclaredField(name);f.setAccessible(true);return f.get(obj);}
var root='/home/lumen/lumenpnp/',q=JSON.parse(String(new java.lang.String(Fs.readAllBytes(new F(root+'automation/plans/paste-startup-quarantine-request.json').toPath()),UTF))),now=Number(java.lang.System.currentTimeMillis()),jvm=Number(Java.type('java.lang.management.ManagementFactory').getRuntimeMXBean().getStartTime()),before=xml(),beforeHash=hash(bytes(before));
if(!q||q.schema!==1||q.scope!=='reviewed-startup-n2-manual-change-exclusion-restore'||!/^[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}$/.test(q.id)||typeof q.createdMs!=='number'||!isFinite(q.createdMs)||q.createdMs>now||now-q.createdMs>300000||q.jvmStartMs!==jvm||!!q.expectedEnabled!==!!m.isEnabled()||q.expectedHomed!==false||q.expectedBusy!==false||q.expectedDriverConnected!==false||q.expectedLiveConfigurationSha256!==beforeHash||q.action!=='unset-manual-nozzle-tip-change-location-only'||typeof q.operator!=='string'||!q.operator.trim()||typeof q.reviewBasis!=='string'||q.reviewBasis.trim().length<30||typeof q.sourceCapturedMs!=='number'||!isFinite(q.sourceCapturedMs)||q.sourceCapturedMs>q.createdMs||q.createdMs-q.sourceCapturedMs>300000)throw Error('Fresh request bound to this JVM and exact live startup state required');
if(!q.sourceEvidence||typeof q.sourceEvidence.path!=='string'||!/^\/[a-zA-Z0-9_./-]+$/.test(q.sourceEvidence.path)||!/^[a-f0-9]{64}$/.test(q.sourceEvidence.sha256))throw Error('Hash-bound current pure-model source report required');
var sourceFile=new F(q.sourceEvidence.path);if(!sourceFile.isFile()||hash(Fs.readAllBytes(sourceFile.toPath()))!==q.sourceEvidence.sha256)throw Error('Startup source report missing or changed');
var source=JSON.parse(String(new java.lang.String(Fs.readAllBytes(sourceFile.toPath()),UTF)));
var sourceTime=Date.parse(source.time);if(source.scope!=='pure-model-state-no-controller-access'||source.jvmStartMs!==jvm||source.enabled!==q.expectedEnabled||source.homed!==false||source.busy!==false||source.liveConfigurationSha256!==beforeHash||sourceTime!==q.sourceCapturedMs||now-sourceTime>300000||source.drivers==null||source.drivers.length!==1||source.drivers[0].connected!==false||source.drivers[0].motionPending!==false||source.nozzles==null||!source.nozzles.some(function(x){return x.name==='N2'&&x.tip==null&&x.compatible===0&&x.changer===false&&x.part==null;}))throw Error('Fresh source report does not prove exact disabled/enabled unhomed startup quarantine');
var driver=m.getDrivers().get(0);if(String(driver.getClass().getName())!=='org.openpnp.machine.reference.driver.GcodeDriver'||String(driver.getId())!=='DRV16982438146c1dd4'||!!field('org.openpnp.machine.reference.driver.GcodeDriver','connected',driver)||m.isBusy()||m.isHomed()||!!m.isEnabled()!==q.expectedEnabled||m.getDrivers().size()!==1||driver.isMotionPending()||n.getNozzleTip()!=null||n.getCompatibleNozzleTips().size()!==0||n.isChangerEnabled()||n.getRotationModeOffset()!=null||m.getPnpJobProcessor().isPreRotateAllNozzles())throw Error('Idle unhomed startup with otherwise quarantined N2 required');
var out=new F('/home/lumen/lumenpnp/.local-machine-backups/paste-startup-quarantine-'+java.lang.System.currentTimeMillis());if(!out.mkdir())throw Error('Unique backup required');var disk=new F(C.get().getConfigurationDirectory(),'machine.xml'),diskBytes=Fs.readAllBytes(disk.toPath());Fs.write(new F(out,'disk-before.xml').toPath(),diskBytes);Fs.write(new F(out,'live-before.xml').toPath(),bytes(before));
n.setManualNozzleTipChangeLocation(new L(MM,0,0,0,0));
if(n.getManualNozzleTipChangeLocation().isInitialized()||hash(Fs.readAllBytes(disk.toPath()))!==hash(diskBytes))throw Error('Quarantine verification failed');
var after=xml();Fs.write(new F(out,'live-after.xml').toPath(),bytes(after));Fs.write(new F(out,'report.json').toPath(),bytes(JSON.stringify({status:'startup-N2-manual-change-exclusion-restored',request:q,sourceEvidence:q.sourceEvidence,sourceConfigurationSha256:beforeHash,noControllerCommands:true,noMotion:true,configurationSaved:false,liveConfigurationSha256:hash(bytes(after))},null,2)+'\n'));print(String(out));
})();
