// STAGED stationary raw B-current change; no motion, flash, EEPROM or machine config edits.
var PASTE_B_CURRENT_ENABLED = true;
(function(){
 if(!PASTE_B_CURRENT_ENABLED)throw Error('B-current action disabled pending independent review');
 var C=Java.type('org.openpnp.model.Configuration'),F=Java.type('java.io.File'),Fs=Java.type('java.nio.file.Files'),UTF=Java.type('java.nio.charset.StandardCharsets').UTF_8,MD=Java.type('java.security.MessageDigest'),MM=Java.type('org.openpnp.model.LengthUnit').Millimeters,AL=Java.type('org.openpnp.model.AxesLocation'),CT=Java.type('org.openpnp.machine.reference.driver.GcodeDriver$CommandType');
 var root='/home/lumen/lumenpnp/',m=C.get().getMachine(),planner=m.getMotionPlanner();
 function read(p){return String(new java.lang.String(Fs.readAllBytes(new F(p).toPath()),UTF));}function bytes(s){return new java.lang.String(s).getBytes(UTF);}function hash(b){var a=MD.getInstance('SHA-256').digest(b),s='';for(var i=0;i<a.length;i++)s+=('0'+((a[i]&255).toString(16))).slice(-2);return s;}
 function privateValue(c,n,o){var f=Java.type(c).class.getDeclaredField(n);f.setAccessible(true);return f.get(o);}function configHash(){var w=new java.io.StringWriter();C.createSerializer().write(m,w);return hash(bytes(String(w)));}
 eval(read(root+'automation/paste/survey-request.cjs'));eval(read(root+'automation/paste/connection-policy.cjs'));eval(read(root+'automation/paste/native-air.cjs'));eval(read(root+'automation/paste/b-current.cjs'));
 var q=JSON.parse(read(root+'automation/plans/paste-b-current-request.json')),jvm=Number(Java.type('java.lang.management.ManagementFactory').getRuntimeMXBean().getStartTime());PasteBCurrent.validate(q,Number(java.lang.System.currentTimeMillis()),jvm);
 function freeze(v){if(v&&typeof v==='object'){Object.keys(v).forEach(function(k){freeze(v[k]);});Object.freeze(v);}return v;}freeze(q);
 var barrierBytes=Fs.readAllBytes(new F(q.sourceBarrierEvidence.path).toPath());if(hash(barrierBytes)!==q.sourceBarrierEvidence.sha256)throw Error('Source barrier evidence changed');var barrier=freeze(JSON.parse(String(new java.lang.String(barrierBytes,UTF))));PasteBCurrent.sourceBarrier(barrier,q);
 var panel=Java.type('org.openpnp.gui.MainFrame').get().getJobTab(),state=panel.getClass().getDeclaredField('state');state.setAccessible(true);if(m.getDrivers().size()!==1)throw Error('Unexpected driver topology');var d=m.getDrivers().get(0);
 if(String(d.getClass().getName())!=='org.openpnp.machine.reference.driver.GcodeDriver'||String(d.getId())!=='DRV16982438146c1dd4'||String(planner.getClass().getName())!=='org.openpnp.machine.reference.driver.NullMotionPlanner')throw Error('Unknown audited native owner/planner');
 var jar=new F(d.getClass().getProtectionDomain().getCodeSource().getLocation().toURI());if(hash(Fs.readAllBytes(jar.toPath()))!=='bcd34923ae91d61a96b98b4c82c93cdc90093ff94292270fd0a18fc6f96f7752')throw Error('Installed native API binary changed');
 var head=m.getDefaultHead(),left=head.getNozzleByName('N1'),right=head.getNozzleByName('N2'),top=head.getDefaultCamera(),bottom=null;for each(var camera in m.getCameras())if(String(camera.getLooking())==='Up'){if(bottom!==null)throw Error('Multiple bottom cameras');bottom=camera;}
 if(left==null||right==null||top==null||bottom==null||String(left.getId())!=='N1'||String(top.getId())!=='CAM1607555396816'||String(right.getId())!=='NOZ1710829fd33a0170')throw Error('Unexpected head/camera topology');var items={N1:left,N2:right,top:top,bottom:bottom};
 function pose(n){var p=n.getLocation().convertToUnits(MM);return {x:Number(p.getX()),y:Number(p.getY()),z:Number(p.getZ()),rotation:Number(p.getRotation())};}function poses(){var o={};Object.keys(items).forEach(function(k){o[k]=pose(items[k]);});return o;}function comparePoses(a,b){Object.keys(items).forEach(function(k){['x','y','z','rotation'].forEach(function(t){PasteSurveyRequest.close(a[k][t],b[k][t],0.0001,k+' '+t);});});}
 var axes={},ids={X:'AXS169824381580efcb',Y:'AXS16982438158c4660',Z:'AXS16982438158d0458',A:'AXS16b068df4e35374e',B:'AXS17108288e61da5fb'};for each(var a in new AL(m).drivenBy(d).getControllerAxes()){var l=String(a.getLetter());if(!ids[l]||String(a.getId())!==ids[l]||axes[l])throw Error('Unexpected controller axis');axes[l]=a;}if(Object.keys(axes).sort().join(',')!=='A,B,X,Y,Z')throw Error('Missing controller axis');
 function snapshot(){var s={raw:{},driver:{},nativePoses:poses()};Object.keys(axes).forEach(function(k){s.raw[k]=Number(axes[k].getCoordinate());s.driver[k]=Number(axes[k].getDriverCoordinate());});return s;}
 var originalReader=privateValue('org.openpnp.machine.reference.driver.GcodeDriver','readerThread',d),originalCommands=d.commands,positionRegex='^.*X:(?<X>-?\\d+\\.\\d+)\\s*Y:(?<Y>-?\\d+\\.\\d+)\\s*Z:(?<Z>-?\\d+\\.\\d+)\\s*A:(?<A>-?\\d+\\.\\d+)\\s*B:(?<B>-?\\d+\\.\\d+).*',positionPattern=java.util.regex.Pattern.compile(positionRegex),nativePositionAckTimeout=Number(privateValue('org.openpnp.machine.reference.driver.GcodeDriver','infinityTimeoutMilliseconds',d));if(!isFinite(nativePositionAckTimeout)||nativePositionAckTimeout<=0||nativePositionAckTimeout>60000)throw Error('Unreviewed native position ACK timeout');
 function stateGate(){PasteBCurrent.validate(q,Number(java.lang.System.currentTimeMillis()),jvm);if(configHash()!==q.liveConfigurationSha256)throw Error('Live configuration changed');if(d.isInSimulationMode()||String(d.getCommunicationsType())!=='serial')throw Error('Physical existing native serial owner required');
  var active=privateValue('org.openpnp.spi.base.AbstractMachine','executor',m),owned=m.isTask(java.lang.Thread.currentThread());if(executor!=null&&(active!==executor||executor.isShutdown()||executor.isTerminated()||executor.getActiveCount()!==(owned?1:0)||!executor.getQueue().isEmpty()))throw Error('Native executor identity/state changed');if(d.commands!==originalCommands||originalReader==null||!originalReader.isAlive()||privateValue('org.openpnp.machine.reference.driver.GcodeDriver','readerThread',d)!==originalReader||privateValue('org.openpnp.machine.reference.driver.GcodeDriver','errorResponse',d)!=null)throw Error('Native reader/commands changed or controller fault latched');if(String(privateValue('org.openpnp.machine.reference.driver.GcodeDriver','connected',d))!=='true'||d.isMotionPending())throw Error('Existing driver disconnected or motion pending');
  if((m.isBusy()&&!m.isTask(java.lang.Thread.currentThread()))||!m.isEnabled()||!m.isHomed()||String(state.get(panel))!=='Stopped')throw Error('Need idle enabled homed machine and stopped job');if(privateValue('org.openpnp.machine.reference.driver.AbstractMotionPlanner','motionCommands',planner).size()!==0)throw Error('Motion already queued');
  for each(var h in m.getHeads())for each(var n in h.getNozzles())if(n.getPart()!=null||n.getPartsFeeder()!=null)throw Error('Held/associated part');if(right.getNozzleTip()!=null||right.getCompatibleNozzleTips().size()!==0||right.getRotationModeOffset()!=null||right.isChangerEnabled()||right.getManualNozzleTipChangeLocation().isInitialized()||m.getPnpJobProcessor().isPreRotateAllNozzles())throw Error('Right-head quarantine changed');
  var mapped=[];for each(var x in top.getMappedAxes(m).getControllerAxes()){mapped.push(String(x.getLetter()));if(String(x.getType())==='Rotation')throw Error('Top camera maps physical rotation');}if(mapped.sort().join(',')!=='X,Y')throw Error('Top camera axis mapping changed');var sub=privateValue('org.openpnp.machine.reference.driver.AbstractMotionPlanner','subordinateMotion',planner),subq=privateValue('org.openpnp.machine.reference.driver.AbstractMotionPlanner$SubordinateMotion','queue',sub);if(subq!=null&&!subq.isEmpty())throw Error('Prior subordinate motion queued');
  if(['M114','M114 ; get position'].indexOf(String(d.getCommand(null,CT.GET_POSITION_COMMAND)).trim())<0)throw Error('Position query command changed');
  if(String(d.getCommand(null,CT.COMMAND_ERROR_REGEX))!==NativePasteAir.nativeErrorRegex||String(d.getCommand(null,CT.POSITION_REPORT_REGEX))!==positionRegex||String(d.getCommand(null,CT.COMMAND_CONFIRM_REGEX)).trim()!=='^ok.*')throw Error('Native fault/position/ACK response contract changed');if(['M114','M114 ; get position'].indexOf(String(d.getCommand(null,CT.GET_POSITION_COMMAND)).trim())<0)throw Error('Native position query command changed');if(JSON.stringify(PasteConnectionPolicy.tokens(d.getCommand(top,CT.MOVE_TO_COMPLETE_COMMAND)))!==JSON.stringify(['M400']))throw Error('Native motion completion command changed');
 }
 var executor=privateValue('org.openpnp.spi.base.AbstractMachine','executor',m);stateGate();if(executor==null||executor.isShutdown()||executor.isTerminated()||executor.getCorePoolSize()!==1||executor.getMaximumPoolSize()!==1||executor.getActiveCount()!==0||!executor.getQueue().isEmpty())throw Error('Existing native single worker must be idle');
 var initial=freeze(snapshot());PasteSurveyRequest.compareExact(initial.raw,q.expectedRaw,'expected raw');PasteSurveyRequest.compareExact(initial.driver,q.expectedDriver,'expected driver');comparePoses(initial.nativePoses,q.expectedNativePoses);
 var out=new F(root+'automation/evidence/paste-b-current-'+q.id);if(!out.mkdir())throw Error('B-current request UUID already claimed; no retry');var r={schema:1,id:q.id,status:'claimed',startedAt:new Date().toISOString(),request:q,beforeQuerySnapshot:initial,transitions:[],motionSubmitted:false,bCurrentCommandSubmitted:false,flashOrEepromCommandSubmitted:false,physicalCurrentVerified:false,calibrationEstablished:false,noReplay:true};function save(s){r.status=s;r.transitions.push({status:s,time:new Date().toISOString()});Fs.write(new F(out,'report.json').toPath(),bytes(JSON.stringify(r,null,2)+'\n'));}save('preflight-no-controller-command');
 function append(lines,to){for each(var l in lines)to.push(String(l.getLine()));}function checked(lines){PasteConnectionPolicy.responses(lines);lines.forEach(function(x){if(/unknown command|halted|fatal|\bkilled\b/i.test(x))throw Error('Controller fault: '+x);});}function collect(regex,e){var list=d.receiveResponses(regex,3000,new (Java.type('org.openpnp.machine.reference.driver.GcodeDriver$TimeoutAction'))({apply:function(lines){append(lines,e.responses);checked(e.responses);save('response-timeout');throw new java.lang.Exception('Native response timeout; no retry');}}));append(list,e.responses);checked(e.responses);}
 function currentQuery(saved,label){stateGate();var s=snapshot();PasteSurveyRequest.compareExact(s.raw,saved.raw,'stationary raw');PasteSurveyRequest.compareExact(s.driver,saved.driver,'stationary driver');comparePoses(s.nativePoses,saved.nativePoses);var e={command:'M503',responses:[]};r[label]=e;append(d.receiveResponses(),e.responses);checked(e.responses);if(e.responses.length)throw Error('Unclaimed responses before M503');r.controllerCommandSubmitted=true;r.transportUncertain=true;save(label+'-M503-started');d.sendCommand('M503',3000);e.sendCommandReturned=true;append(d.receiveResponses(),e.responses);checked(e.responses);e.currents=PasteBCurrent.parseM906(e.responses);var after=snapshot();PasteSurveyRequest.compareExact(after.raw,saved.raw,'M503 unchanged raw');PasteSurveyRequest.compareExact(after.driver,saved.driver,'M503 unchanged driver');comparePoses(after.nativePoses,saved.nativePoses);r.transportUncertain=false;save(label+'-M503-reported');return e.currents;}
 function setCurrent(){stateGate();var s=snapshot();PasteSurveyRequest.compareExact(s.raw,initial.raw,'pre-current raw');PasteSurveyRequest.compareExact(s.driver,initial.driver,'pre-current driver');comparePoses(s.nativePoses,initial.nativePoses);var stale=[];append(d.receiveResponses(),stale);checked(stale);if(stale.length)throw Error('Unsolicited response before current command');var command='M906 B'+q.targetCurrentMa,e={command:command,responses:[],acknowledgedBySendCommand:false};r.commands=[e];r.controllerCommandSubmitted=true;r.bCurrentCommandSubmitted=true;r.transportUncertain=true;save('single-M906-B-current-command-started');d.sendCommand(command,3000);e.sendCommandReturned=true;append(d.receiveResponses(),e.responses);checked(e.responses);e.acknowledgedBySendCommand=true;r.transportUncertain=false;save('single-M906-B-current-command-returned');}
 function queryPosition(saved,label){stateGate();var s=snapshot();PasteSurveyRequest.compareExact(s.raw,saved.raw,'position-query raw');PasteSurveyRequest.compareExact(s.driver,saved.driver,'position-query driver');comparePoses(s.nativePoses,saved.nativePoses);var e={responses:[]};r[label]=e;append(d.receiveResponses(),e.responses);checked(e.responses);if(e.responses.some(function(x){return positionPattern.matcher(x).matches();}))throw Error('Stale M114 response');r.controllerCommandSubmitted=true;r.transportUncertain=true;save(label+'-M114-started');var loc=d.getReportedLocation(3000),reported={};for each(var a in loc.getControllerAxes())reported[String(a.getLetter())]=Number(loc.getCoordinate(a));e.reported=reported;collect(positionRegex,e);var delimiter=-1;e.responses.forEach(function(x,i){if(positionPattern.matcher(x).matches())delimiter=i;});if(delimiter<0)throw Error('Fresh M114 report missing');if(!e.responses.slice(delimiter+1).some(function(x){return /^ok/.test(x);}))collect('^ok.*',e);append(d.receiveResponses(),e.responses);checked(e.responses);PasteSurveyRequest.compareReported(reported,saved.raw,saved.driver);e.after=snapshot();PasteSurveyRequest.compareExact(e.after.raw,saved.raw,'M114 unchanged raw');PasteSurveyRequest.compareExact(e.after.driver,saved.driver,'M114 unchanged driver');comparePoses(e.after.nativePoses,saved.nativePoses);r.transportUncertain=false;save(label+'-stationary-M114-verified');}
 save('queued-on-existing-native-executor');try{executor.submit(new (Java.type('java.util.concurrent.Callable'))({call:function(){var owned=false,keepBusy=false;try{if(m.isBusy()||!executor.getQueue().isEmpty())throw Error('Native task ownership changed');var setter=Java.type('org.openpnp.spi.base.AbstractMachine').class.getDeclaredMethod('setTaskThread',Java.type('java.lang.Thread').class);setter.setAccessible(true);setter.invoke(m,Java.to([java.lang.Thread.currentThread()],'java.lang.Object[]'));owned=true;m.fireMachineBusy(true);
  stateGate();var begin=snapshot();PasteSurveyRequest.compareExact(begin.raw,initial.raw,'queued raw');PasteSurveyRequest.compareExact(begin.driver,initial.driver,'queued driver');comparePoses(begin.nativePoses,initial.nativePoses);queryPosition(initial,'before');var before=currentQuery(initial,'beforeCurrent');if(before.B!==q.expectedCurrentMa)throw Error('Live M503 B current differs from reviewed expected value');setCurrent();var after=currentQuery(initial,'afterCurrent');PasteBCurrent.verifyOnlyBChanged(before,after,q.expectedCurrentMa,q.targetCurrentMa);queryPosition(initial,'after');stateGate();if(configHash()!==q.liveConfigurationSha256)throw Error('Configuration changed during current adjustment');r.afterQuerySnapshot=r.after.after;r.currentsBefore=before;r.currentsAfter=after;r.onlyBCurrentChangedVerified=true;r.controllerPositionVerified=true;r.noMotionCommandSubmitted=true;r.flashOrEepromCommandSubmitted=false;r.uncertainCompletion=false;r.finishedAt=new Date().toISOString();save('completed-stationary-B-current-change-awaiting-review');
 }catch(e){r.error=String(e);r.uncertainCompletion=!!r.transportUncertain;r.auditIncomplete=true;r.finishedAt=new Date().toISOString();if(r.controllerCommandSubmitted||r.transportUncertain){keepBusy=true;r.queuedTasksCancelled=0;var pending;while((pending=executor.getQueue().poll())!=null){if(pending instanceof Java.type('java.util.concurrent.Future'))pending.cancel(false);r.queuedTasksCancelled++;}executor.shutdown();r.executorQuarantined=true;r.faultGateScope='Retained busy marker and stopped native executor; operator recovery required; no retry.';}save('failed-no-retry-no-motion-recovery');
 }finally{if(owned&&!keepBusy){var reset=Java.type('org.openpnp.spi.base.AbstractMachine').class.getDeclaredMethod('setTaskThread',Java.type('java.lang.Thread').class);reset.setAccessible(true);reset.invoke(m,Java.to([null],'java.lang.Object[]'));m.fireMachineBusy(false);}print(String(out));}return null;}}));}catch(queueError){r.error=String(queueError);r.uncertainCompletion=false;save('enqueue-failed-no-command');throw queueError;}
})();
