'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const B=require('./commissioning-stroke.cjs');
const hash='a'.repeat(64),id='12345678-1234-1234-1234-123456789abc',sessionId='abcd1234-1234-1234-1234-123456789abc';
const ev=()=>({path:'/synthetic-only',sha256:hash});
const raw=()=>({X:100,Y:200,Z:50,A:720,B:-240});
function request(mode='wet',preview=false){
 const r=raw(),target={...r,[mode==='wet'?'B':'Z']:mode==='wet'?-246:45};
 return {schema:1,scope:preview?'contiguous-native-scrap-batch-preview':'contiguous-native-scrap-batch',enabled:false,mode,stopPath:'/synthetic-stop',id,sessionId,jvmStartMs:1,createdMs:1000,imageCapturedMs:900,reviewedImageMs:950,liveConfigurationSha256:hash,expectedRaw:r,expectedDriver:{...r},expectedNativePoses:{N1:{x:100,y:200,z:50},N2:{x:100,y:200,z:50},top:{},bottom:{}},rawBounds:{X:{min:95,max:105},Y:{min:195,max:205},Z:{min:45,max:55},B:{min:-260,max:-220}},headClearanceBounds:{N1:{minX:0,maxX:500,minY:0,maxY:500,minZ:0,maxZ:100},N2:{minX:0,maxX:500,minY:0,maxY:500,minZ:0,maxZ:100}},bothHeadsClearanceReview:true,clearanceReviewEvidence:ev(),xyClearanceRawZ:45,receivingProfile:{provenance:'commissioning-provisional',precisionCalibrated:false,flowCalibrated:false,sha256:hash,estimatedGapMm:.65,gapUncertaintyMm:.4,basis:'synthetic observed height interval',rawPose:{...r}},previewStages:[{axis:mode==='wet'?'B':'Z',speedFraction:mode==='wet'?.05:1,startRaw:r,targetRaw:target,...(mode==='wet'?{gapEvidence:ev(),estimatedGapMm:.65,gapUncertaintyMm:.4}:{}),...(preview?{}:{expandedCommands:['synthetic'],...ev()})}],finalTargetRaw:target,evidence:Array.from({length:7},ev),previousReportEvidence:ev(),nativePreviewEvidence:ev(),profileEvidence:ev(),barrierEvidence:ev(),reviewedImageEvidence:ev(),previousLedgerSha256:hash,syringeId:'synthetic',primeLedgerSha256:hash,carryoverSha256:hash,budgetAmendmentEvidence:null};
}
const clone=x=>JSON.parse(JSON.stringify(x));
const ledger=()=>({schema:1,scope:'signed-B-commissioning-strokes',sessionId,syringeId:'synthetic',primeLedgerSha256:hash,carryoverSha256:hash,startB:-240,lastVerifiedB:-240,totalAbsoluteDegrees:0,entries:[],status:'verified'});
const carry=()=>({schema:1,sessionId,syringeId:'synthetic',primeLedgerSha256:hash,priorGrossDegrees:10940,manualDisplacementUnknown:true,verifiedPrimeDegrees:960,startB:-240,maximumAbsoluteDegrees:120});
test('bounded wet batch reserves full gross and verifies each B stage',()=>{const q=request(),l=B.reserveBatch(ledger(),q,carry());assert.equal(l.totalAbsoluteDegrees,6);assert.equal(l.entries[0].batchId,id);assert.throws(()=>B.finishBatch(l,q,true));const done=B.finishBatch(B.markBatchStep(l,q,0,-246),q,true);assert.equal(done.status,'verified');assert.equal(done.lastVerifiedB,-246);assert.equal(done.totalAbsoluteDegrees,6);});
test('fault consumes all reserved B budget and bars replay',()=>{const q=request(),l=B.reserveBatch(ledger(),q,carry()),fault=B.finishBatch(l,q,false);assert.equal(fault.totalAbsoluteDegrees,6);assert.equal(fault.entries[0].status,'faulted');assert.throws(()=>B.reserveBatch(fault,q,carry()));});
test('air batch has zero B stages and cannot reserve budget',()=>{const q=request('air');B.validateBatch(q,1000,1);assert.throws(()=>B.reserveBatch(ledger(),q,carry()));const bad=clone(q);bad.previewStages[0].axis='B';assert.throws(()=>B.validateBatch(bad,1000,1));});
test('contiguous single-axis, length, speed and clearance bounds fail closed',()=>{const q=request();for(const edit of [x=>x.previewStages[0].targetRaw.A++,x=>x.previewStages[0].speedFraction=1,x=>x.previewStages=Array.from({length:41},()=>x.previewStages[0]),x=>x.receivingProfile.gapUncertaintyMm=.6]){const v=clone(q);edit(v);assert.throws(()=>B.validateBatch(v,1000,1));}const a=request('air');a.previewStages[0].axis='X';a.previewStages[0].targetRaw={...a.expectedRaw,X:101};a.finalTargetRaw={...a.previewStages[0].targetRaw};assert.throws(()=>B.validateBatch(a,1000,1));a.previewStages[0].wipeReview=true;a.previewStages[0].wipeReviewEvidence=ev();a.previewStages[0].estimatedGapMm=.5;a.previewStages[0].gapUncertaintyMm=.2;B.validateBatch(a,1000,1);});
test('prior report accepts batch tail only with exact completed ledger hash',()=>{const q=request(),l=B.finishBatch(B.markBatchStep(B.reserveBatch(ledger(),q,carry()),q,0,-246),q,true),r={id,request:{id},status:'completed-contiguous-batch-awaiting-observation',uncertainCompletion:false,completedLedgerSha256:hash,finishedAt:'2026-09-30T00:00:00.000Z'};assert.equal(B.validatePreviousReport(r,l,hash,Date.parse(r.finishedAt)+1),true);r.completedLedgerSha256='b'.repeat(64);assert.throws(()=>B.validatePreviousReport(r,l,hash,Date.parse(r.finishedAt)+1));});
test('negative stage uncertainty and negative gap cannot bypass lower bound',()=>{const q=request();q.previewStages[0].estimatedGapMm=-1;q.previewStages[0].gapUncertaintyMm=-2;assert.throws(()=>B.validateBatch(q,1000,1));const a=request('air');a.previewStages[0].axis='X';a.previewStages[0].targetRaw={...a.expectedRaw,X:101};a.finalTargetRaw={...a.previewStages[0].targetRaw};a.previewStages[0].wipeReview=true;a.previewStages[0].wipeReviewEvidence=ev();a.previewStages[0].estimatedGapMm=-1;a.previewStages[0].gapUncertaintyMm=-2;assert.throws(()=>B.validateBatch(a,1000,1));});
test('batch ID replay rejected even with shifted B index; B verification is ordered',()=>{const q=request(),l=B.reserveBatch(ledger(),q,carry()),done=B.finishBatch(B.markBatchStep(l,q,0,-246),q,true);const q2=clone(q);q2.expectedRaw.B=-246;q2.expectedDriver.B=-246;const r=q2.expectedRaw,xy={...r,X:101};q2.previewStages.unshift({axis:'X',startRaw:r,targetRaw:xy,speedFraction:1,expandedCommands:['synthetic'],...ev()});q2.previewStages[1].startRaw=xy;q2.previewStages[1].targetRaw={...xy,B:-252};q2.finalTargetRaw={...xy,B:-252};q2.xyClearanceRawZ=50;assert.throws(()=>B.reserveBatch(done,q2,carry()),/batch replay/);const q3=request();const second={...q3.previewStages[0],startRaw:q3.finalTargetRaw,targetRaw:{...q3.finalTargetRaw,B:-252}};q3.previewStages.push(second);q3.finalTargetRaw=second.targetRaw;const two=B.reserveBatch(ledger(),q3,carry());assert.throws(()=>B.markBatchStep(two,q3,1,-252));assert.throws(()=>B.finishBatch(two,q3,true));});
test('cooperative stop allows only an already-reviewed clearance lift',()=>{const q=request('air'),at={...q.expectedRaw,Z:50},lift={axis:'Z',speedFraction:1,startRaw:at,targetRaw:{...at,Z:q.xyClearanceRawZ}};assert.equal(B.stopDecision(q,at,lift,false),'continue');assert.equal(B.stopDecision(q,at,lift,true),'reviewed-clearance-lift');assert.equal(B.stopDecision(q,at,{...lift,axis:'B'},true),'stop-hold-position');assert.equal(B.stopDecision(q,{...at,Z:q.xyClearanceRawZ},lift,true),'stop-at-clearance');});
test('optional post-B dwell accepts only integer 0..2000 and never linear stages',()=>{for(const preview of [false,true]){const q=request('wet',preview);B.validateBatch(q,1000,1,preview);for(const ms of [0,1,50,2000]){q.previewStages[0].dwellMilliseconds=ms;B.validateBatch(q,1000,1,preview);}for(const ms of [-1,2001,1.5,'50',null,NaN,Infinity]){q.previewStages[0].dwellMilliseconds=ms;assert.throws(()=>B.validateBatch(q,1000,1,preview));}}const a=request('air');a.previewStages[0].dwellMilliseconds=0;assert.throws(()=>B.validateBatch(a,1000,1));});

const FTP=require('./ftp-two-pad.cjs');
function ftpRequest(){
 const q=request(),start=raw();q.scope=FTP.scope(false);q.rawBounds.Z.max=50;q.previewStages=[];let at={...start};
 function add(axis,value){const target={...at,[axis]:value};q.previewStages.push({axis,startRaw:at,targetRaw:target,speedFraction:axis==='B'?.05:1,expandedCommands:['synthetic'],...ev(),...(axis==='B'?{gapEvidence:{path:'/ftp/surface.json',sha256:hash},estimatedGapMm:.65,gapUncertaintyMm:.4}:{})});at=target;}
 add('B',-246);add('Z',45);add('X',101);add('Z',50);add('B',-252);add('Z',45);q.finalTargetRaw=at;
 const e=name=>({path:'/ftp/'+name,sha256:hash});
 q.ftpTargetEvidence=e('targets.json');q.ftpTargetRecord={schema:1,scope:'ftp-two-pad-commissioning-targets',boardId:'synthetic-cleaned-demo',sessionId,jvmStartMs:1,liveConfigurationSha256:hash,reviewedBy:'synthetic-test',reviewedMs:950,boardCleaned:true,padsAvailable:true,boardUnmovedSinceRegistration:true,provenance:'commissioning-provisional',precisionCalibrated:false,flowCalibrated:false,cadEvidence:e('board.kicad_pcb'),registrationEvidence:e('registration.json'),tipOffsetEvidence:e('offset.json'),surfaceEvidence:e('surface.json'),padAvailabilityImage:e('available.png'),cameraMinusTipXYMm:[5,-3],quantizationMm:0.01,surface:{rawZ:50,estimatedGapMm:.65,gapUncertaintyMm:.4},pads:[{padId:'R1.1',doseStageIndex:0,rawPose:{X:100,Y:200,Z:50,A:720}},{padId:'R1.2',doseStageIndex:4,rawPose:{X:101,Y:200,Z:50,A:720}}],padChecks:['R1','R16','R40'].map(reference=>({reference,padId:reference+'.1',reviewedAligned:true,reportEvidence:e(reference+'/report.json'),imageEvidence:e(reference+'/top.png')}))};return q;
}
function ftpSources(q){
 const t=q.ftpTargetRecord,files={},e=name=>({path:'/ftp/'+name,sha256:hash});
 const cameraReport=xy=>({status:'completed-contiguous-air-batch-awaiting-observation',controllerPositionVerified:true,uncertainCompletion:false,finishedAt:new Date(900).toISOString(),request:{jvmStartMs:1,liveConfigurationSha256:hash},afterImages:{top:{path:'top.png'}},afterQuerySnapshot:{nativePoses:{top:{x:xy[0],y:xy[1]}}}});
 const targets=Array.from({length:40},(_,i)=>[1,2].map(n=>({padId:`R${i+1}.${n}`,machineXYMm:[104+n,197]}))).flat();
 const reg={scope:'offline-fresh-ftp-two-fiducial-transform-with-third-point-check',acceptance:{passed:true},board:t.cadEvidence,session:{jvmStartMs:1,liveConfigurationSha256:hash},independentFID3Check:{residualMm:.01},measurements:{},resistorPadMachineXYTargets:targets};
 for(const fid of ['FID1','FID2','FID3']){reg.measurements[fid]={imageCenterErrorPx:1,report:e(fid+'/report.json'),image:e(fid+'/top.png')};files['/ftp/'+fid+'/report.json']=cameraReport([0,0]);}
 for(const c of t.padChecks)files[c.reportEvidence.path]=cameraReport(targets.find(p=>p.padId===c.padId).machineXYMm);
 const base={boardId:t.boardId,provenance:'commissioning-provisional',precisionCalibrated:false,jvmStartMs:1,liveConfigurationSha256:hash,reviewedBy:'synthetic-test',basisEvidence:e('basis.json')};
 files[t.registrationEvidence.path]=reg;files[t.tipOffsetEvidence.path]={...base,cameraMinusTipXYMm:t.cameraMinusTipXYMm};files[t.surfaceEvidence.path]={...base,surface:t.surface};files[q.ftpTargetEvidence.path]=clone(t);
 return {files,read:(e,json)=>{assert.match(e.sha256,/^[a-f0-9]{64}$/);if(json){assert.ok(files[e.path],e.path);return files[e.path];}return null;}};
}
test('FTP two-pad wet branch preserves whole-budget reservation and ordered verification',()=>{const q=ftpRequest();B.validateBatch(q,1000,1);let l=B.reserveBatch(ledger(),q,carry());assert.equal(l.totalAbsoluteDegrees,12);l=B.markBatchStep(l,q,0,-246);l=B.markBatchStep(l,q,4,-252);assert.equal(B.finishBatch(l,q,true).lastVerifiedB,-252);const f=ftpSources(q);FTP.verifySources(q,f.read);});
test('FTP prevents duplicate/different-resistor targets, wrong dose pose and extra dose stage',()=>{for(const edit of [q=>q.ftpTargetRecord.pads[1].padId='R1.1',q=>q.ftpTargetRecord.pads[1].padId='R2.2',q=>q.ftpTargetRecord.pads[0].rawPose.X++,q=>q.ftpTargetRecord.pads[1].doseStageIndex=0,q=>q.ftpTargetRecord.surface.estimatedGapMm=.9,q=>q.ftpTargetRecord.pads[0].doseStageIndex=2]){const q=ftpRequest();edit(q);assert.throws(()=>B.validateBatch(q,1000,1));}});
test('FTP cannot downgrade to scrap, claim calibration, omit review or exceed board Z',()=>{for(const edit of [q=>q.scope='contiguous-native-scrap-batch',q=>q.ftpTargetRecord.precisionCalibrated=true,q=>q.ftpTargetRecord.boardUnmovedSinceRegistration=false,q=>q.ftpTargetRecord.reviewedMs=NaN,q=>q.ftpTargetRecord.reviewedMs=-400000,q=>q.rawBounds.Z.max=51,q=>delete q.ftpTargetEvidence]){const q=ftpRequest();edit(q);assert.throws(()=>B.validateBatch(q,1000,1));}});
test('FTP rejects low XY even with legacy noncontact wipe evidence',()=>{const q=ftpRequest();q.previewStages[2].wipeReview=true;q.previewStages[2].wipeReviewEvidence=ev();assert.throws(()=>B.validateBatch(q,1000,1));});
test('FTP air record permits no B and cannot map dose indices',()=>{const q=ftpRequest();q.mode='air';q.previewStages=q.previewStages.filter(s=>s.axis!=='B').map(s=>({...s,startRaw:{...s.startRaw,B:-240},targetRaw:{...s.targetRaw,B:-240}}));q.finalTargetRaw.B=-240;q.ftpTargetRecord.pads.forEach(p=>p.doseStageIndex=null);B.validateBatch(q,1000,1);assert.throws(()=>B.reserveBatch(ledger(),q,carry()));q.ftpTargetRecord.pads[0].doseStageIndex=0;assert.throws(()=>B.validateBatch(q,1000,1));});
test('FTP source verification rejects swapped record, offset, surface and camera evidence',()=>{for(const edit of [(q,f)=>f.files[q.ftpTargetEvidence.path].boardId='different',(q,f)=>f.files[q.ftpTargetRecord.tipOffsetEvidence.path].cameraMinusTipXYMm=[6,-3],(q,f)=>f.files[q.ftpTargetRecord.surfaceEvidence.path].surface={...q.ftpTargetRecord.surface,rawZ:51},(q,f)=>f.files['/ftp/R16/report.json'].afterQuerySnapshot.nativePoses.top.x=NaN,(q,f)=>f.files['/ftp/FID1/report.json'].uncertainCompletion=true]){const q=ftpRequest(),f=ftpSources(q);edit(q,f);assert.throws(()=>FTP.verifySources(q,f.read));}});
test('FTP registered coordinates must match selected tip offset; preview equality is order independent',()=>{const q=ftpRequest(),f=ftpSources(q);f.files[q.ftpTargetRecord.registrationEvidence.path].resistorPadMachineXYTargets[0].machineXYMm[0]+=.1;assert.throws(()=>FTP.verifySources(q,f.read));assert.equal(FTP.same({a:1,b:2},{b:2,a:1}),true);assert.equal(FTP.same({a:1},{a:2}),false);});

test('FTP rejects any added positive B stage, including relief at clearance',()=>{for(const placement of ['before','after']){const q=ftpRequest();if(placement==='after'){const at=q.finalTargetRaw,target={...at,B:at.B+2};q.previewStages.push({axis:'B',startRaw:at,targetRaw:target,speedFraction:.05,expandedCommands:['synthetic'],...ev(),gapEvidence:q.ftpTargetRecord.surfaceEvidence,estimatedGapMm:5.65,gapUncertaintyMm:.4});q.finalTargetRaw=target;}else{const at=q.expectedRaw,target={...at,B:at.B+2};q.previewStages.forEach(s=>{s.startRaw={...s.startRaw,B:s.startRaw.B+2};s.targetRaw={...s.targetRaw,B:s.targetRaw.B+2};});q.finalTargetRaw={...q.finalTargetRaw,B:q.finalTargetRaw.B+2};q.ftpTargetRecord.pads.forEach(p=>p.doseStageIndex++);q.previewStages.unshift({axis:'B',startRaw:at,targetRaw:target,speedFraction:.05,expandedCommands:['synthetic'],...ev(),gapEvidence:q.ftpTargetRecord.surfaceEvidence,estimatedGapMm:.65,gapUncertaintyMm:.4});}assert.throws(()=>B.validateBatch(q,1000,1),/only its two negative B/);}});


test('FTP explicitly quantizes registered-minus-offset targets onto M114 0.01 mm grid',()=>{const q=ftpRequest(),f=ftpSources(q);f.files[q.ftpTargetRecord.registrationEvidence.path].resistorPadMachineXYTargets[0].machineXYMm[0]=105.004;FTP.verifySources(q,f.read);q.ftpTargetRecord.pads[0].rawPose.X=100.004;assert.throws(()=>B.validateBatch(q,1000,1),/0.01 mm/);q.ftpTargetRecord.pads[0].rawPose.X=100;delete q.ftpTargetRecord.quantizationMm;assert.throws(()=>B.validateBatch(q,1000,1),/0.01 mm/);});

function stoppedBatchFixture(){
 const l=ledger();function append(d){const at=l.lastVerifiedB;l.entries.push({requestId:'synthetic-'+l.entries.length,startB:at,targetB:at+d,deltaDegrees:d,absoluteDegrees:Math.abs(d),status:'verified'});l.lastVerifiedB+=d;l.totalAbsoluteDegrees+=Math.abs(d);}
 [-20,-20,-20,-20,-2,20,6,6,6].forEach(append);const anchor=clone(l);
 [...Array(61).fill(-20),-6,-4,-4,...Array(19).fill(20),4,4].forEach(append);
 assert.equal(l.totalAbsoluteDegrees,1742);assert.equal(l.lastVerifiedB,-1130);
 const faultId='b67374aa-8c39-413d-abca-a2eee9f92768';[3,8].forEach((stageIndex,i)=>l.entries.push({requestId:faultId+':'+stageIndex,batchId:faultId,stageIndex,startB:-1130-i*20,targetB:-1150-i*20,deltaDegrees:-20,absoluteDegrees:20,status:'faulted'}));l.totalAbsoluteDegrees+=40;l.status='faulted';
 const audit={faultId,faultSha256:'9728056a1a3e8598e03ed75e35c1053d57af5b11d5e7cc377fc74f555361358c',ledgerSha256:'cd47fafbe31512a904fc43420b84033fc8abd36d0fc1eb2131a19e13dd2ce2a8',status:'audit-complete-awaiting-separate-reviewed-latch-clear',confirmedNoBStageSubmitted:true,verifiedNoBCountChange:true,positionVerified:true,motionIssued:false,uncertainCompletion:false,counts:{B:-5017},reported:{B:-1130}};
 return {l,audit,anchor,faultId};
}
test('exact no-B reconciliation preserves every fault entry and all charged gross; rejects replay and contrary evidence',()=>{
 const {l,audit}=stoppedBatchFixture(),next=B.reconcileUnexecutedBatch(l,audit);assert.deepEqual(next.entries.slice(0,-1),l.entries);assert.equal(l.status,'faulted');assert.equal(next.status,'verified');assert.equal(next.totalAbsoluteDegrees,1782);assert.equal(next.lastVerifiedB,-1130);assert.equal(next.entries.at(-1).absoluteDegrees,0);assert.throws(()=>B.reconcileUnexecutedBatch(next,audit));
 for(const edit of [a=>a.confirmedNoBStageSubmitted=false,a=>a.counts.B++,a=>a.reported.B--,a=>a.motionIssued=true]){const a=clone(audit);edit(a);assert.throws(()=>B.reconcileUnexecutedBatch(l,a));}
 const changed=clone(l);changed.entries.at(-1).status='verified';assert.throws(()=>B.reconcileUnexecutedBatch(changed,audit));const refund=clone(l);refund.totalAbsoluteDegrees-=40;assert.throws(()=>B.reconcileUnexecutedBatch(refund,audit));
});
test('8400-degree batch amendment preserves the immutable 120-degree anchor and requires matching review evidence',()=>{
 const anchor=ledger();let b=-240;for(const d of [-20,-20,-20,-20,-2,20,6,6,6]){const start=b;b+=d;anchor.entries.push({requestId:`anchor-${anchor.entries.length}`,startB:start,targetB:b,deltaDegrees:d,absoluteDegrees:Math.abs(d),status:'verified'});anchor.totalAbsoluteDegrees+=Math.abs(d);}anchor.lastVerifiedB=b;
 const anchorHash='b'.repeat(64),travel={path:'/8400-review.json',sha256:'9'.repeat(64)},ar={id:anchor.entries.at(-1).requestId,status:'completed-commissioning-stroke-awaiting-observation',uncertainCompletion:false,completedLedgerSha256:anchorHash,finishedAt:'1970-01-01T00:00:00.000Z',request:{id:anchor.entries.at(-1).requestId,sessionId,jvmStartMs:1,liveConfigurationSha256:hash}};
 const record={schema:1,sessionId,syringeId:'synthetic',originalCarryoverSha256:hash,anchorLedgerSha256:anchorHash,anchorGrossDegrees:120,anchorB:-284,newMaximumAbsoluteDegrees:8400,reviewedAt:new Date(500).toISOString(),reviewedBy:'synthetic',reason:'Fixed travel review for bounded commissioning.',anchorLedgerEvidence:{path:'/anchor-ledger.json',sha256:anchorHash},anchorReportEvidence:ev(),travelReviewEvidence:travel};
 const envelope={...record,...ev(),travelReviewEvidence:{...travel}},context={record,anchorLedger:anchor,anchorReport:ar};
 const q=request();q.expectedRaw.B=-284;q.expectedDriver.B=-284;q.rawBounds.B={min:-350,max:-250};q.previewStages[0].startRaw={...q.expectedRaw};q.previewStages[0].targetRaw={...q.expectedRaw,B:-290};q.finalTargetRaw={...q.previewStages[0].targetRaw};q.previousLedgerSha256=hash;q.budgetAmendmentEvidence=envelope;q.evidence.push(travel);
 const reserved=B.reserveBatch(anchor,q,carry(),context);assert.equal(reserved.totalAbsoluteDegrees,126);assert.deepEqual(reserved.entries.slice(0,anchor.entries.length),anchor.entries);assert.equal(carry().maximumAbsoluteDegrees,120);
 const missing=request();Object.assign(missing,q,{evidence:q.evidence.filter(x=>x.path!==travel.path)});assert.throws(()=>B.reserveBatch(anchor,missing,carry(),context),/travel review/);
});
test('reconciliation terminal binds the preserved ledger and next batch charges forward without fault replay',()=>{
 const {l,audit,anchor,faultId}=stoppedBatchFixture(),next=B.reconcileUnexecutedBatch(l,audit),rid=next.entries.at(-1).requestId;
 const terminal={id:rid,request:{id:rid},status:'completed-pre-dose-batch-reconciliation-no-motion',uncertainCompletion:false,completedLedgerSha256:hash,finishedAt:new Date(600).toISOString(),confirmedNoBStageSubmitted:true,motionIssued:false,lastVerifiedB:-1130,reservedGrossDegrees:1782};B.validatePreviousReport(terminal,next,hash,900);assert.throws(()=>B.validatePreviousReport({...terminal,confirmedNoBStageSubmitted:false},next,hash,900));
 const q=request();q.expectedRaw.B=-1130;q.expectedDriver.B=-1130;q.rawBounds.B={min:-1200,max:-1000};q.previewStages[0].startRaw={...q.expectedRaw};q.previewStages[0].targetRaw={...q.expectedRaw,B:-1136};q.finalTargetRaw={...q.previewStages[0].targetRaw};
 const ar={id:anchor.entries.at(-1).requestId,request:{id:anchor.entries.at(-1).requestId,sessionId,jvmStartMs:1,liveConfigurationSha256:hash},status:'completed-commissioning-stroke-awaiting-observation',uncertainCompletion:false,completedLedgerSha256:hash,finishedAt:new Date(0).toISOString()};
 const record={schema:1,sessionId,syringeId:'synthetic',originalCarryoverSha256:hash,anchorLedgerSha256:hash,anchorGrossDegrees:120,anchorB:-284,newMaximumAbsoluteDegrees:2400,reviewedAt:new Date(500).toISOString(),reviewedBy:'synthetic',reason:'Continue exact independently audited no-B reconciliation',anchorLedgerEvidence:ev(),anchorReportEvidence:ev()};q.budgetAmendmentEvidence={...record,...ev()};const context={record,anchorLedger:anchor,anchorReport:ar};
 const reserved=B.reserveBatch(next,q,carry(),context);assert.equal(reserved.totalAbsoluteDegrees,1788);assert.equal(reserved.lastVerifiedB,-1130);assert.deepEqual(reserved.entries.slice(0,next.entries.length),next.entries);assert.equal(B.finishBatch(B.markBatchStep(reserved,q,0,-1136),q,true).lastVerifiedB,-1136);
 assert.throws(()=>B.reserveBatch(next,{...q,id:faultId},carry(),context),/replay/);const changed=clone(next);changed.entries.at(-1).chargedUnexecutedDegrees=0;assert.throws(()=>B.reserveBatch(changed,q,carry(),context),/reconciliation/);
});

test('batch-only three-degree relief and restoration reserve gross, verify ordered positions, and cannot replay',()=>{
 const q=request();q.rawBounds.B={min:-300,max:-200};q.previewStages=[];let at={...q.expectedRaw};
 for(const delta of [-20,3,-3,-20,3]){const target={...at,B:at.B+delta};q.previewStages.push({axis:'B',speedFraction:.05,startRaw:at,targetRaw:target,gapEvidence:ev(),estimatedGapMm:.65,gapUncertaintyMm:.4,expandedCommands:['synthetic'],...ev()});at=target;}q.finalTargetRaw=at;
 B.validateBatch(q,1000,1);B.validateBatch({...q,scope:'contiguous-native-scrap-batch-preview'},1000,1,true);
 let l=B.reserveBatch(ledger(),q,carry());assert.equal(l.totalAbsoluteDegrees,49);assert.equal(B.finishBatch(l,q,false).totalAbsoluteDegrees,49);
 q.previewStages.forEach((s,i)=>{l=B.markBatchStep(l,q,i,s.targetRaw.B);});l=B.finishBatch(l,q,true);assert.equal(l.lastVerifiedB,-277);
 const next=request();next.id='22345678-1234-1234-1234-123456789abc';next.expectedRaw.B=-277;next.expectedDriver.B=-277;next.rawBounds.B={min:-300,max:-200};next.previewStages[0].startRaw={...next.expectedRaw};next.previewStages[0].targetRaw={...next.expectedRaw,B:-274};next.finalTargetRaw={...next.previewStages[0].targetRaw};assert.equal(B.reserveBatch(l,next,carry()).totalAbsoluteDegrees,52);
 assert.throws(()=>B.reserveBatch(l,{...next,id:q.id},carry()),/replay/);const forged=clone(l);delete forged.entries[1].batchId;assert.throws(()=>B.reserveBatch(forged,next,carry()),/Malformed/);const wrongKey=clone(l);wrongKey.entries[1].requestId='unrelated';assert.throws(()=>B.reserveBatch(wrongKey,next,carry()),/Malformed/);
 for(const delta of [-5,5,3.1]){const bad=clone(next);bad.previewStages[0].targetRaw.B=bad.expectedRaw.B+delta;bad.finalTargetRaw={...bad.previewStages[0].targetRaw};assert.throws(()=>B.validateBatch(bad,1000,1));}const faster=clone(next);faster.previewStages[0].speedFraction=.15;assert.throws(()=>B.validateBatch(faster,1000,1));
 assert.equal(B.allowedSteps.includes(3),false);assert.equal(B.allowedSteps.includes(-3),false);
});

function compensatedFixture(dose=4,retract=2){
 const q=ftpRequest(),t=q.ftpTargetRecord,e=name=>({path:'/ftp/'+name,sha256:hash});
 q.expectedRaw.Z=45;q.expectedDriver.Z=45;q.receivingProfile.rawPose.Z=45;q.rawBounds.B={min:-350,max:-150};q.previewStages=[];let at={...q.expectedRaw};
 function add(axis,value,dwell=0){const target={...at,[axis]:value};q.previewStages.push({axis,startRaw:at,targetRaw:target,speedFraction:axis==='B'?.05:1,expandedCommands:['synthetic'],...ev(),...(axis==='B'?{gapEvidence:t.surfaceEvidence,estimatedGapMm:.65+50-at.Z,gapUncertaintyMm:.4,dwellMilliseconds:dwell}:{})});at=target;return q.previewStages.length-1;}
 t.pads.forEach((p,n)=>{delete p.doseStageIndex;if(n)add('X',101);add('Z',50);p.restoreStageIndex=add('B',at.B-retract);p.doseStageIndices=dose===12?[add('B',at.B-6),add('B',at.B-6,200)]:[add('B',at.B-dose,200)];p.retractStageIndex=add('B',at.B+retract);p.liftStageIndex=add('Z',45);});
 const finalIdleStageIndex=add('B',at.B+20,2000);q.finalTargetRaw=at;
 const c=t.compensatedSequence={schema:1,protocol:'restore-dose-retract-lift-two-pad',doseDegrees:dose,retractDegrees:retract,dwellMilliseconds:200,maximumElapsedMilliseconds:1000,conditioningFinishedMs:800,finalIdleStageIndex,conditioningReportEvidence:e('conditioning.json'),conditioningLedgerEvidence:e('conditioning-ledger-copy.json'),preparationExperimentEvidence:e('preparation.json'),tipObservationEvidence:e('tip-review.json')};q.previousReportEvidence=c.conditioningReportEvidence;
 const f=ftpSources(q),rid='32345678-1234-1234-1234-123456789abc';
 let pos={...q.expectedRaw,Z:50,B:-240-retract+20};const ss=[];
 function prior(axis,target,dwell=0){const next={...pos,[axis]:target};ss.push({axis,startRaw:pos,targetRaw:next,dwellMilliseconds:dwell});pos=next;}
 prior('B',-240-retract,200);prior('B',-240);prior('Z',45);
 const rq={id:rid,scope:'contiguous-native-scrap-batch',mode:'wet',sessionId,syringeId:q.syringeId,jvmStartMs:1,liveConfigurationSha256:hash,clearanceReviewEvidence:e('preparation-review.json'),previewStages:ss,finalTargetRaw:pos};
 f.files[c.conditioningReportEvidence.path]={id:rid,request:rq,status:'completed-contiguous-batch-awaiting-observation',controllerPositionVerified:true,uncertainCompletion:false,finishedAt:new Date(800).toISOString(),completedLedgerSha256:hash,afterQuerySnapshot:{raw:pos},stages:ss.map((s,i)=>({...s,index:i,verified:true,finishedAt:new Date(800).toISOString()}))};
 f.files[c.conditioningLedgerEvidence.path]={status:'verified',sessionId,syringeId:q.syringeId,lastVerifiedB:-240,entries:[{status:'verified',batchId:rid,stageIndex:1,targetB:-240,deltaDegrees:retract}]};
 f.files[c.preparationExperimentEvidence.path]={schema:1,scope:'reviewed-scrap-retraction-coupon',mode:'transfer-preparation',retractDegrees:retract,maximumTransferElapsedMilliseconds:1000,conditioningDoseDegrees:20,workRawZ:50,clearanceRawZ:45,dwellMilliseconds:200};
 f.files[rq.clearanceReviewEvidence.path]={experimentEvidence:c.preparationExperimentEvidence};
 f.files[c.tipObservationEvidence.path]={reviewedBy:'synthetic',reviewedMs:900,capturedMs:850,noLongStrand:true,conditioningReportEvidence:c.conditioningReportEvidence,imageEvidence:e('tip.png')};
 return {q,t,c,f};
}
test('compensated FTP covers every B stage, reserves gross, and verifies ordered low doses',()=>{
 for(const dose of [2,3,4,6,12,20])for(const retract of [2,3,4,6]){const {q,f}=compensatedFixture(dose,retract);B.validateBatch(q,1000,1);FTP.verifySources(q,f.read);let l=B.reserveBatch(ledger(),q,carry());assert.equal(l.totalAbsoluteDegrees,2*dose+4*retract+20);q.previewStages.forEach((s,i)=>{if(s.axis==='B')l=B.markBatchStep(l,q,i,s.targetRaw.B);});assert.equal(B.finishBatch(l,q,true).lastVerifiedB,q.finalTargetRaw.B);}
});
test('compensated FTP rejects unknown protocol, expiry, uncovered B and shifted/mismatched groups',()=>{
 const edits=[x=>x.c.protocol='arbitrary',x=>x.c.doseDegrees=5,x=>x.c.retractDegrees=true,x=>x.c.maximumElapsedMilliseconds=300001,x=>x.c.conditioningFinishedMs=-5000,x=>x.c.conditioningFinishedMs=1001,x=>x.c.dwellMilliseconds=200.5,x=>x.t.pads[0].restoreStageIndex++,x=>x.t.pads[0].doseStageIndices=[0],x=>x.t.pads[1].restoreStageIndex=x.t.pads[0].restoreStageIndex,x=>x.t.pads[0].retractStageIndex++,x=>x.t.pads[0].liftStageIndex++,x=>x.c.finalIdleStageIndex--,x=>x.q.previousReportEvidence=ev(),x=>x.c.conditioningLedgerEvidence.sha256='b'.repeat(64),x=>x.t.pads[0].doseStageIndex=1,x=>x.q.previewStages[x.t.pads[0].restoreStageIndex].gapUncertaintyMm=.3];
 for(const edit of edits){const x=compensatedFixture();edit(x);assert.throws(()=>B.validateBatch(x.q,1000,1));}
 const x=compensatedFixture();assert.throws(()=>FTP.entryTime(x.q,1801),/expired/);
 const y=compensatedFixture();const extra={...y.q.previewStages.at(-1),startRaw:y.q.finalTargetRaw,targetRaw:{...y.q.finalTargetRaw,B:y.q.finalTargetRaw.B+2}};y.q.previewStages.push(extra);y.q.finalTargetRaw=extra.targetRaw;assert.throws(()=>B.validateBatch(y.q,1000,1));
});
test('compensated FTP rejects uncertain preparation, extra idle, stale B, unverified tail and unbound tip evidence',()=>{
 const edits=[x=>x.f.files[x.c.conditioningReportEvidence.path].uncertainCompletion=true,x=>x.f.files[x.c.conditioningReportEvidence.path].controllerPositionVerified=false,x=>x.f.files[x.c.conditioningReportEvidence.path].stages[1].verified=false,x=>x.f.files[x.c.conditioningReportEvidence.path].afterQuerySnapshot.raw.B++,x=>x.f.files[x.c.conditioningReportEvidence.path].finishedAt=new Date(799).toISOString(),x=>x.f.files[x.c.conditioningLedgerEvidence.path].entries[0].deltaDegrees=20,x=>x.f.files[x.c.preparationExperimentEvidence.path].mode='coupon',x=>x.f.files[x.c.preparationExperimentEvidence.path].maximumTransferElapsedMilliseconds=2000,x=>x.f.files['/ftp/preparation-review.json'].experimentEvidence=ev(),x=>x.f.files[x.c.tipObservationEvidence.path].noLongStrand=false,x=>x.f.files[x.c.tipObservationEvidence.path].reviewedMs=799,x=>x.f.files[x.c.tipObservationEvidence.path].capturedMs=799];
 for(const edit of edits){const x=compensatedFixture();edit(x);assert.throws(()=>FTP.verifySources(x.q,x.f.read));}
 const x=compensatedFixture(),r=x.f.files[x.c.conditioningReportEvidence.path],ss=r.request.previewStages,at=ss.at(-1).targetRaw,extra={axis:'B',startRaw:at,targetRaw:{...at,B:at.B+20}};ss.push(extra);r.stages.push({...extra,index:3,verified:true});assert.throws(()=>FTP.verifySources(x.q,x.f.read),/must end/);
});
