'use strict';
// Pure policy for a separately reviewed, single raw-B commissioning stroke.
// Kept ES5 for the installed Nashorn runtime. No controller/filesystem access.
(function(root){
var fail=function(s){throw Error(s);},hashPattern=/^[a-f0-9]{64}$/;
var finite=function(v,k){if(typeof v!=='number'||!isFinite(v))fail(k+' must be finite');return v;};
var steps=[2,4,6,20,-2,-4,-6,-20],batchSteps=steps.concat([3,-3]);
function validate(q,now,jvm){
 if(!q||q.schema!==1||q.scope!=='single-signed-raw-B-commissioning-stroke'||q.enabled!==false)fail('Unknown or enabled commissioning request');
 if(!/^[a-f0-9-]{36}$/.test(q.id)||!/^[a-f0-9-]{36}$/.test(q.sessionId)||q.jvmStartMs!==jvm)fail('Exact request/session/JVM required');
 if(q.axis!=='B'||steps.indexOf(q.deltaDegrees)<0||Math.abs(q.deltaDegrees)>20)fail('Only bounded reviewed signed B steps allowed');
 if(q.speedFraction!==0.05)fail('Native fraction must remain the reviewed 0.05');
 if(!hashPattern.test(q.liveConfigurationSha256)||!q.evidence||!Array.isArray(q.evidence)||q.evidence.length<4)fail('Hash-bound config/profile/image/barrier evidence required');
 q.evidence.forEach(function(e){if(!e||typeof e.path!=='string'||e.path.charAt(0)!=='/'||!hashPattern.test(e.sha256))fail('Hash-bound evidence path/hash invalid');});
 if(!q.expectedRaw||!q.expectedDriver||!q.expectedNativePoses)fail('Exact current pose snapshots required');
 if(!isFinite(q.imageCapturedMs)||!isFinite(q.reviewedImageMs)||q.imageCapturedMs>q.reviewedImageMs||q.reviewedImageMs>q.createdMs||q.createdMs-q.reviewedImageMs>300000)fail('Fresh reviewed image timing required');
 if(q.previousLedgerSha256!==null&&(!q.previousReportEvidence||typeof q.previousReportEvidence.path!=='string'||!hashPattern.test(q.previousReportEvidence.sha256)))fail('Previous terminal stroke report required');
 ['X','Y','Z','A','B'].forEach(function(k){finite(q.expectedRaw[k],'raw '+k);finite(q.expectedDriver[k],'driver '+k);});
 var p=q.receivingProfile;if(!p||p.measured!==true||p.flowCalibrated!==false||!hashPattern.test(p.sha256)||finite(p.measuredGapMm,'measured gap')<=0||finite(p.gapUncertaintyMm,'gap uncertainty')<0||finite(p.measuredGapMm-p.gapUncertaintyMm,'minimum gap')<0.1)fail('Signed stroke requires measured noncontact gap with uncertainty lower bound at least 0.1 mm');
 ['X','Y','Z','A'].forEach(function(k){if(!p.rawPose||typeof p.rawPose[k]!=='number'||Math.abs(p.rawPose[k]-q.expectedRaw[k])>0.0001)fail('Measured receiving profile does not bind current fixed '+k);});
 if(q.deltaDegrees>0&&q.clearanceReview!==true)fail('Positive relief requires reviewed clear travel pose');
 if(typeof now!=='number'||!isFinite(now)||q.createdMs>now||now-q.createdMs>300000||now-q.imageCapturedMs>300000)fail('Stale/future request or image');
 return q;
}
function validateBudgetAmendment(q,record,anchor,anchorReport,current,carry){
 var e=q&&q.budgetAmendmentEvidence,ae=record&&record.anchorLedgerEvidence,re=record&&record.anchorReportEvidence;
 if(!e||!record||record.schema!==1||record.sessionId!==q.sessionId||record.syringeId!==q.syringeId||record.originalCarryoverSha256!==q.carryoverSha256||!hashPattern.test(record.anchorLedgerSha256)||!ae||ae.sha256!==record.anchorLedgerSha256||!re||!hashPattern.test(re.sha256)||record.anchorGrossDegrees!==120||record.anchorB!==-284||[240,2400].indexOf(record.newMaximumAbsoluteDegrees)<0)fail('Explicit fixed-ceiling budget amendment required');
 if(e.path!==q.budgetAmendmentEvidence.path||e.sha256!==q.budgetAmendmentEvidence.sha256||e.sessionId!==record.sessionId||e.syringeId!==record.syringeId||e.originalCarryoverSha256!==record.originalCarryoverSha256||e.anchorLedgerSha256!==record.anchorLedgerSha256||e.anchorGrossDegrees!==record.anchorGrossDegrees||e.anchorB!==record.anchorB||e.newMaximumAbsoluteDegrees!==record.newMaximumAbsoluteDegrees||e.reviewedAt!==record.reviewedAt||e.reviewedBy!==record.reviewedBy||e.reason!==record.reason)fail('Request does not bind the reviewed amendment record');
 if(typeof e.path!=='string'||e.path.charAt(0)!=='/'||!hashPattern.test(e.sha256)||typeof ae.path!=='string'||ae.path.charAt(0)!=='/'||!hashPattern.test(ae.sha256)||typeof re.path!=='string'||re.path.charAt(0)!=='/'||!hashPattern.test(re.sha256)||typeof record.reason!=='string'||record.reason.trim().length<12||typeof record.reviewedBy!=='string'||!record.reviewedBy.trim())fail('Budget amendment review evidence incomplete');
 if(typeof record.reviewedAt!=='string'||!/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}\.\d{3}Z$/.test(record.reviewedAt))fail('Budget amendment review timestamp must use UTC ISO milliseconds (.dddZ)');
 var reviewed=Date.parse(record.reviewedAt),created=q.createdMs;if(!isFinite(reviewed)||!isFinite(created)||reviewed>created||created-reviewed>86400000)fail('Budget amendment review is future-dated or stale');
 if(!carry||carry.maximumAbsoluteDegrees!==120||record.originalCarryoverSha256!==q.carryoverSha256||record.sessionId!==carry.sessionId||record.syringeId!==carry.syringeId)fail('Original 120-degree carryover must remain unchanged');
 if(!anchor||anchor.status!=='verified'||anchor.schema!==1||anchor.scope!=='signed-B-commissioning-strokes'||anchor.sessionId!==q.sessionId||anchor.syringeId!==q.syringeId||anchor.carryoverSha256!==q.carryoverSha256||anchor.totalAbsoluteDegrees!==record.anchorGrossDegrees||anchor.lastVerifiedB!==record.anchorB||!Array.isArray(anchor.entries)||anchor.entries.length===0)fail('Amendment anchor ledger does not match reviewed gross/B');
 var tail=anchor.entries[anchor.entries.length-1];if(!tail||tail.status!=='verified'||(tail.requestId!==anchorReport.id&&tail.cycleId!==anchorReport.id))fail('Anchor ledger tail/report ID mismatch');
 validatePreviousReport(anchorReport,anchor,record.anchorLedgerSha256,reviewed);
 if(!anchorReport.request||anchorReport.request.sessionId!==q.sessionId||anchorReport.request.jvmStartMs!==q.jvmStartMs||anchorReport.request.liveConfigurationSha256!==q.liveConfigurationSha256)fail('Anchor report is not from the current session/configuration');
 if(!current||current.status!=='verified'||current.sessionId!==anchor.sessionId||current.syringeId!==anchor.syringeId||current.carryoverSha256!==anchor.carryoverSha256||current.primeLedgerSha256!==anchor.primeLedgerSha256||current.startB!==anchor.startB||current.entries.length<anchor.entries.length||JSON.stringify(current.entries.slice(0,anchor.entries.length))!==JSON.stringify(anchor.entries))fail('Current ledger does not retain the immutable anchor history prefix');
 if(current.totalAbsoluteDegrees<record.anchorGrossDegrees||current.totalAbsoluteDegrees>record.newMaximumAbsoluteDegrees)fail('Current ledger exceeds reviewed amendment ceiling');
 return record.newMaximumAbsoluteDegrees;
}
function reserve(old,q,carry,amendment){
 validate(q,q.createdMs,q.jvmStartMs);
 if(q.budgetAmendmentEvidence&&!amendment)fail('Reviewed budget amendment evidence was not loaded');
 if(!carry||carry.schema!==1||carry.sessionId!==q.sessionId||carry.syringeId!==q.syringeId||carry.primeLedgerSha256!==q.primeLedgerSha256||carry.priorGrossDegrees!==10940||carry.manualDisplacementUnknown!==true||carry.verifiedPrimeDegrees!==960||carry.startB!==-240||carry.maximumAbsoluteDegrees!==120)fail('Hash-bound prime and prior-syringe carryover required');
 var l=old?JSON.parse(JSON.stringify(old)):{schema:1,scope:'signed-B-commissioning-strokes',sessionId:q.sessionId,syringeId:q.syringeId,primeLedgerSha256:q.primeLedgerSha256,carryoverSha256:q.carryoverSha256,startB:-240,lastVerifiedB:-240,totalAbsoluteDegrees:0,entries:[],status:'verified'};
 if(l.schema!==1||l.scope!=='signed-B-commissioning-strokes'||l.sessionId!==q.sessionId||l.syringeId!==q.syringeId||l.primeLedgerSha256!==q.primeLedgerSha256||l.carryoverSha256!==q.carryoverSha256||l.status!=='verified'||!Array.isArray(l.entries))fail('Commissioning ledger identity/status invalid');
 if(old){if(!hashPattern.test(q.previousLedgerSha256)||old.lastVerifiedB!==q.expectedRaw.B)fail('Previous ledger hash or exact B position mismatch');}
 else if(q.previousLedgerSha256!==null||q.expectedRaw.B!==-240)fail('Initial request must match immutable prime ledger B=-240');
 var maximum=amendment?validateBudgetAmendment(q,amendment.record,amendment.anchorLedger,amendment.anchorReport,l,carry):120;
 if(typeof l.totalAbsoluteDegrees!=='number'||!isFinite(l.totalAbsoluteDegrees)||Math.floor(l.totalAbsoluteDegrees)!==l.totalAbsoluteDegrees||l.totalAbsoluteDegrees<0||l.totalAbsoluteDegrees>maximum||l.startB!==-240||!isFinite(l.lastVerifiedB))fail('Commissioning ledger budget/position malformed');
 var sum=0,at=-240,seen={};l.entries.forEach(function(e){if(!e||typeof e.requestId!=='string'||seen[e.requestId]||e.status!=='verified'||steps.indexOf(e.deltaDegrees)<0||e.startB!==at||e.targetB!==e.startB+e.deltaDegrees||e.absoluteDegrees!==Math.abs(e.deltaDegrees))fail('Commissioning ledger history malformed');seen[e.requestId]=true;sum+=e.absoluteDegrees;at=e.targetB;});
 if(sum!==l.totalAbsoluteDegrees||at!==l.lastVerifiedB||sum>maximum)fail('Commissioning ledger gross/target chain mismatch');
 if(seen[q.id])fail('Commissioning request replay');
 var next=l.totalAbsoluteDegrees+Math.abs(q.deltaDegrees);if(next>maximum)fail('Commissioning absolute stroke budget exhausted');
 l.totalAbsoluteDegrees=next;l.status='reserved';l.entries.push({requestId:q.id,startB:q.expectedRaw.B,targetB:q.expectedRaw.B+q.deltaDegrees,deltaDegrees:q.deltaDegrees,absoluteDegrees:Math.abs(q.deltaDegrees),status:'reserved'});return l;
}
function finish(old,q,success){var l=JSON.parse(JSON.stringify(old)),e=l.entries[l.entries.length-1];if(l.status!=='reserved'||!e||e.requestId!==q.id)fail('Unknown reserved commissioning stroke');e.status=success?'verified':'faulted';l.status=e.status;if(success)l.lastVerifiedB=e.targetB;return l;}
// One explicit no-B reconciliation; original fault entries and gross charge stay intact.
var batchStopId='b67374aa-8c39-413d-abca-a2eee9f92768',batchReconcileId='a6b138b6-2c91-4198-a057-684c3ab39dae',batchStopSha='9728056a1a3e8598e03ed75e35c1053d57af5b11d5e7cc377fc74f555361358c',batchAuditSha='74506ab2f3f7163c35664478b0f394d80bda3e27da1aabef44aec984f96e409f',batchFaultLedgerSha='cd47fafbe31512a904fc43420b84033fc8abd36d0fc1eb2131a19e13dd2ce2a8';
function exactStoppedDose(e,stage,start,target){return e&&e.requestId===batchStopId+':'+stage&&e.batchId===batchStopId&&e.stageIndex===stage&&e.startB===start&&e.targetB===target&&e.deltaDegrees===-20&&e.absoluteDegrees===20&&e.status==='faulted';}
function reconciliationIndices(l){var result={},found=false;(l.entries||[]).forEach(function(e,i){if(e.kind!=='unexecuted-batch-reconciliation')return;if(found||i<2||e.requestId!==batchReconcileId||e.reconcilesBatchId!==batchStopId||e.faultSha256!==batchStopSha||e.auditSha256!==batchAuditSha||e.faultedLedgerSha256!==batchFaultLedgerSha||e.startB!==-1130||e.targetB!==-1130||e.deltaDegrees!==0||e.absoluteDegrees!==0||e.chargedUnexecutedDegrees!==40||e.executedBStages!==0||e.status!=='verified'||!exactStoppedDose(l.entries[i-2],3,-1130,-1150)||!exactStoppedDose(l.entries[i-1],8,-1150,-1170))fail('Invalid exact no-B reconciliation history');found=true;result[i-2]='fault-first';result[i-1]='fault-second';result[i]='reconciliation';});return result;}
function reconcileUnexecutedBatch(old,audit){
 if(!old||old.status!=='faulted'||old.totalAbsoluteDegrees!==1782||old.lastVerifiedB!==-1130||!old.entries||old.entries.length<2||!exactStoppedDose(old.entries[old.entries.length-2],3,-1130,-1150)||!exactStoppedDose(old.entries[old.entries.length-1],8,-1150,-1170))fail('Exact charged pre-dose batch fault required');
 if(!audit||audit.faultId!==batchStopId||audit.faultSha256!==batchStopSha||audit.ledgerSha256!==batchFaultLedgerSha||audit.status!=='audit-complete-awaiting-separate-reviewed-latch-clear'||audit.confirmedNoBStageSubmitted!==true||audit.verifiedNoBCountChange!==true||audit.positionVerified!==true||audit.motionIssued!==false||audit.uncertainCompletion!==false||!audit.counts||audit.counts.B!==-5017||!audit.reported||audit.reported.B!==-1130)fail('Exact fresh no-B audit required');
 var l=JSON.parse(JSON.stringify(old));if(l.entries.some(function(e){return e.requestId===batchReconcileId||e.kind==='unexecuted-batch-reconciliation';}))fail('No reconciliation replay');
 l.entries.push({requestId:batchReconcileId,kind:'unexecuted-batch-reconciliation',reconcilesBatchId:batchStopId,faultSha256:batchStopSha,auditSha256:batchAuditSha,faultedLedgerSha256:batchFaultLedgerSha,startB:-1130,targetB:-1130,deltaDegrees:0,absoluteDegrees:0,chargedUnexecutedDegrees:40,executedBStages:0,status:'verified'});l.status='verified';reconciliationIndices(l);return l;
}
function validatePreviousReport(report,ledger,ledgerSha,imageCapturedMs){var last=ledger&&ledger.entries&&ledger.entries.length?ledger.entries[ledger.entries.length-1]:null,requestId=report&&report.request&&report.request.id,reportId=report&&report.id,finished=report&&Date.parse(report.finishedAt),statuses=['completed-pre-dose-batch-reconciliation-no-motion','completed-commissioning-stroke-awaiting-observation','completed-dose-cycle-awaiting-observation','completed-contiguous-batch-awaiting-observation'];if(!report||statuses.indexOf(report.status)<0||report.uncertainCompletion!==false||!ledger||ledger.status!=='verified'||!hashPattern.test(ledgerSha)||report.completedLedgerSha256!==ledgerSha||!last||last.status!=='verified'||!requestId||requestId!==reportId||(last.requestId!==requestId&&last.cycleId!==requestId&&last.batchId!==requestId)||!isFinite(finished)||!isFinite(imageCapturedMs)||finished>imageCapturedMs)fail('Prior terminal report must hash-bind the exact latest verified stroke/cycle/batch before the fresh image');if(report.status==='completed-pre-dose-batch-reconciliation-no-motion'){reconciliationIndices(ledger);if(last.kind!=='unexecuted-batch-reconciliation'||reportId!==batchReconcileId||report.confirmedNoBStageSubmitted!==true||report.motionIssued!==false||report.lastVerifiedB!==-1130||report.reservedGrossDegrees!==1782)fail('Exact reconciliation terminal required');}return true;}
function validateCycle(q,now,jvm){
 if(!q||q.schema!==1||q.scope!=='single-native-B-dose-retract-Z-lift-cycle'||q.enabled!==false)fail('Unknown/enabled dose-cycle request');
 if(!/^[a-f0-9-]{36}$/.test(q.id)||!/^[a-f0-9-]{36}$/.test(q.sessionId)||q.jvmStartMs!==jvm||q.axis!=='B')fail('Exact cycle/session/JVM required');
 if([2,4,6,20].indexOf(q.doseDegrees)<0||[2,4,6,20].indexOf(q.retractDegrees)<0||Math.floor(q.dwellMilliseconds)!==q.dwellMilliseconds||q.dwellMilliseconds<0||q.dwellMilliseconds>1000||q.liftDeltaMm!==-5)fail('Dose/retract/dwell/lift outside reviewed bounds; installed raw Z lift is exactly -5 mm');
 if(q.dispenseSpeedFraction!==0.05||q.retractSpeedFraction!==0.05||q.liftSpeedFraction!==1.0)fail('Native per-axis speed fractions changed');
 if(!hashPattern.test(q.liveConfigurationSha256)||!Array.isArray(q.evidence)||q.evidence.length<7)fail('Exact config/profile/barrier/image/preview/ledger evidence required');
 q.evidence.forEach(function(e){if(!e||typeof e.path!=='string'||e.path.charAt(0)!=='/'||!hashPattern.test(e.sha256))fail('Cycle evidence path/hash invalid');});
 if(!q.expectedRaw||!q.expectedDriver||!q.expectedNativePoses)fail('Exact cycle start poses required');
 ['X','Y','Z','A','B'].forEach(function(k){finite(q.expectedRaw[k],'raw '+k);finite(q.expectedDriver[k],'driver '+k);});
 if(!q.liftTargetRaw||q.liftTargetRaw.Z!==q.expectedRaw.Z+q.liftDeltaMm||q.liftTargetRaw.B!==q.expectedRaw.B-q.doseDegrees+q.retractDegrees||!q.liftClearanceReview||!Array.isArray(q.previewStages)||q.previewStages.length!==3)fail('Exact reviewed five-millimeter lift and three-stage previews required');
 ['X','Y','Z','A','B'].forEach(function(k){finite(q.liftTargetRaw[k],'lift target '+k);if(k!=='Z'&&q.liftTargetRaw[k]!==q.expectedRaw[k]-(k==='B'?q.doseDegrees:0)+(k==='B'?q.retractDegrees:0))fail('Lift target changes a non-Z axis unexpectedly');});
 var doseB=q.expectedRaw.B-q.doseDegrees,retractB=doseB+q.retractDegrees,targets=[{axis:'B',startB:q.expectedRaw.B,targetB:doseB,speedFraction:.05},{axis:'B',startB:doseB,targetB:retractB,speedFraction:.05},{axis:'Z',startB:retractB,targetB:q.expectedRaw.Z+q.liftDeltaMm,speedFraction:1.0}];
 q.previewStages.forEach(function(s,i){if(!s)fail('Missing preview stage');var x=targets[i],start=s.startRaw,target=s.targetRaw;if(s.axis!==x.axis||s.speedFraction!==x.speedFraction||!start||!target||!hashPattern.test(s.sha256)||typeof s.path!=='string'||s.path.charAt(0)!=='/')fail('Missing/hashless preview stage');['X','Y','Z','A','B'].forEach(function(k){var expectedStart=q.expectedRaw[k],expectedTarget=q.expectedRaw[k];if(i===1){if(k==='B'){expectedStart=doseB;expectedTarget=retractB;}}else if(i===2){if(k==='B'){expectedStart=retractB;expectedTarget=retractB;}if(k==='Z')expectedTarget+=q.liftDeltaMm;}else if(k==='B')expectedTarget=doseB;if(start[k]!==expectedStart||target[k]!==expectedTarget)fail('Preview stage '+i+' target chain changed');});});
 if(!isFinite(q.imageCapturedMs)||!isFinite(q.reviewedImageMs)||q.imageCapturedMs>q.reviewedImageMs||q.reviewedImageMs>q.createdMs||q.createdMs-q.reviewedImageMs>300000)fail('Fresh cycle image review required');
 var p=q.receivingProfile;if(!p||p.measured!==true||p.flowCalibrated!==false||!hashPattern.test(p.sha256)||finite(p.measuredGapMm,'gap')<=0||finite(p.gapUncertaintyMm,'gap uncertainty')<0||finite(p.measuredGapMm-p.gapUncertaintyMm,'minimum gap')<0.1)fail('Measured tip gap with uncertainty lower bound >=0.1 mm required');
 ['X','Y','Z','A'].forEach(function(k){if(!p.rawPose||typeof p.rawPose[k]!=='number'||Math.abs(p.rawPose[k]-q.expectedRaw[k])>0.0001)fail('Profile does not bind current '+k);});
 if(!isFinite(now)||q.createdMs>now||now-q.createdMs>300000||now-q.imageCapturedMs>300000)fail('Stale cycle request/image');
 return q;
}
function reserveCycle(old,q,carry,amendment){
 validateCycle(q,q.createdMs,q.jvmStartMs);
 if(q.budgetAmendmentEvidence&&!amendment)fail('Reviewed budget amendment evidence was not loaded');
 if(!carry||carry.schema!==1||carry.sessionId!==q.sessionId||carry.syringeId!==q.syringeId||carry.primeLedgerSha256!==q.primeLedgerSha256||carry.priorGrossDegrees!==10940||carry.manualDisplacementUnknown!==true||carry.verifiedPrimeDegrees!==960||carry.startB!==-240||carry.maximumAbsoluteDegrees!==120)fail('Hash-bound syringe carryover required');
 var l=old?JSON.parse(JSON.stringify(old)):{schema:1,scope:'signed-B-commissioning-strokes',sessionId:q.sessionId,syringeId:q.syringeId,primeLedgerSha256:q.primeLedgerSha256,carryoverSha256:q.carryoverSha256,startB:-240,lastVerifiedB:-240,totalAbsoluteDegrees:0,entries:[],status:'verified'};
 if(l.schema!==1||l.scope!=='signed-B-commissioning-strokes'||l.sessionId!==q.sessionId||l.syringeId!==q.syringeId||l.primeLedgerSha256!==q.primeLedgerSha256||l.carryoverSha256!==q.carryoverSha256||l.status!=='verified'||!Array.isArray(l.entries))fail('Cycle ledger identity/status invalid');
 if(old){if(!hashPattern.test(q.previousLedgerSha256)||old.lastVerifiedB!==q.expectedRaw.B)fail('Previous ledger hash/current B mismatch');}else if(q.previousLedgerSha256!==null||q.expectedRaw.B!==-240)fail('Initial cycle must start from B=-240 prime ledger');
 var maximum=amendment?validateBudgetAmendment(q,amendment.record,amendment.anchorLedger,amendment.anchorReport,l,carry):120;
 var sum=0,at=-240,seen={};l.entries.forEach(function(e){if(!e||typeof e.requestId!=='string'||seen[e.requestId]||e.status!=='verified'||steps.indexOf(e.deltaDegrees)<0||e.startB!==at||e.targetB!==e.startB+e.deltaDegrees||e.absoluteDegrees!==Math.abs(e.deltaDegrees))fail('Cycle history malformed');seen[e.requestId]=true;sum+=e.absoluteDegrees;at=e.targetB;});
 if(l.startB!==-240||!isFinite(l.totalAbsoluteDegrees)||Math.floor(l.totalAbsoluteDegrees)!==l.totalAbsoluteDegrees||sum!==l.totalAbsoluteDegrees||at!==l.lastVerifiedB||sum>maximum||seen[q.id+':dose']||seen[q.id+':retract'])fail('Cycle ledger sum/chain/replay mismatch');
 var doseStart=q.expectedRaw.B,doseTarget=doseStart-q.doseDegrees,retractTarget=doseTarget+q.retractDegrees,total=sum+q.doseDegrees+q.retractDegrees;if(total>maximum)fail('Cycle would exceed absolute stroke ceiling');
 l.totalAbsoluteDegrees=total;l.status='reserved';l.activeCycleId=q.id;l.entries.push({requestId:q.id+':dose',cycleId:q.id,phase:'dose',startB:doseStart,targetB:doseTarget,deltaDegrees:-q.doseDegrees,absoluteDegrees:q.doseDegrees,status:'reserved'});l.entries.push({requestId:q.id+':retract',cycleId:q.id,phase:'retract',startB:doseTarget,targetB:retractTarget,deltaDegrees:q.retractDegrees,absoluteDegrees:q.retractDegrees,status:'reserved'});return l;
}
function markCycleStep(old,q,index,reportedB){if(index!==0&&index!==1)fail('Unknown cycle substep index');var l=JSON.parse(JSON.stringify(old)),dose=l.entries[l.entries.length-2],retract=l.entries[l.entries.length-1],e=index===0?dose:retract;if(l.status!=='reserved'||l.activeCycleId!==q.id||!dose||!retract||dose.cycleId!==q.id||retract.cycleId!==q.id||e.status!=='reserved')fail('Unknown cycle substep');if(index===1&&dose.status!=='verified')fail('Dose B step must verify before retract');finite(reportedB,'verified B');if(Math.abs(reportedB-e.targetB)>0.3)fail('Controller B differs from cycle substep target');e.status='verified';l.lastVerifiedB=e.targetB;return l;}
function finishCycle(old,q,success){var l=JSON.parse(JSON.stringify(old)),dose=l.entries[l.entries.length-2],retract=l.entries[l.entries.length-1];if(l.status!=='reserved'||l.activeCycleId!==q.id||!dose||!retract||dose.cycleId!==q.id||retract.cycleId!==q.id)fail('Unknown reserved cycle');if(success&&(dose.status!=='verified'||retract.status!=='verified'||l.lastVerifiedB!==retract.targetB))fail('Both B cycle substeps must be verified');if(!success){if(dose.status==='reserved')dose.status='faulted';if(retract.status==='reserved')retract.status='faulted';}else{dose.status='verified';retract.status='verified';}l.status=success?'verified':'faulted';delete l.activeCycleId;return l;}
function validateBatch(q,now,jvm,preview){
 if(!q||q.schema!==1||[preview?'contiguous-native-scrap-batch-preview':'contiguous-native-scrap-batch',preview?'contiguous-native-ftp-two-pad-preview':'contiguous-native-ftp-two-pad'].indexOf(q.scope)<0||q.enabled!==false||['air','wet'].indexOf(q.mode)<0||typeof q.stopPath!=='string'||q.stopPath.charAt(0)!=='/')fail('Unknown, enabled, or unstoppably configured batch request');
 if(!/^[a-f0-9-]{36}$/.test(q.id)||!/^[a-f0-9-]{36}$/.test(q.sessionId)||q.jvmStartMs!==jvm||!hashPattern.test(q.liveConfigurationSha256))fail('Exact batch/session/configuration required');
 if(!q.expectedRaw||!q.expectedDriver||!q.expectedNativePoses||!Array.isArray(q.previewStages)||q.previewStages.length<1||q.previewStages.length>40)fail('One to forty exact stages and initial pose required');
 ['X','Y','Z','A','B'].forEach(function(k){finite(q.expectedRaw[k],'raw '+k);finite(q.expectedDriver[k],'driver '+k);});
 var bounds=q.rawBounds;if(!bounds||!q.headClearanceBounds||q.bothHeadsClearanceReview!==true||!q.clearanceReviewEvidence||typeof q.clearanceReviewEvidence.path!=='string'||q.clearanceReviewEvidence.path.charAt(0)!=='/'||!hashPattern.test(q.clearanceReviewEvidence.sha256))fail('Explicit hash-bound raw and both-head clearance review required');
 ['X','Y','Z','B'].forEach(function(k){if(!bounds[k]||finite(bounds[k].min,k+' min')>finite(bounds[k].max,k+' max')||q.expectedRaw[k]<bounds[k].min||q.expectedRaw[k]>bounds[k].max)fail('Raw bound or initial pose invalid '+k);});
 if(finite(q.xyClearanceRawZ,'XY clearance Z')<bounds.Z.min||q.xyClearanceRawZ>bounds.Z.max)fail('Reviewed XY clearance Z outside raw bounds');
 ['N1','N2'].forEach(function(k){var b=q.headClearanceBounds[k],pose=q.expectedNativePoses[k];if(!b||!pose)fail('Both-head clearance interval/pose required');['X','Y','Z'].forEach(function(a){var low=finite(b['min'+a],k+' min'+a),high=finite(b['max'+a],k+' max'+a),value=finite(pose[a.toLowerCase()],k+' pose '+a);if(low>high||value<low||value>high)fail('Initial both-head pose outside reviewed interval');});});
 var p=q.receivingProfile;if(!p||p.provenance!=='commissioning-provisional'||p.flowCalibrated!==false||p.precisionCalibrated!==false||!hashPattern.test(p.sha256)||finite(p.estimatedGapMm,'estimated gap')<=0||finite(p.gapUncertaintyMm,'gap uncertainty')<0||p.estimatedGapMm-p.gapUncertaintyMm<0.1||typeof p.basis!=='string'||p.basis.length<12)fail('Provisional commissioning gap with reviewed lower bound >=0.1 mm required');
 ['X','Y','Z','A'].forEach(function(k){if(!p.rawPose||Math.abs(finite(p.rawPose[k],'profile '+k)-q.expectedRaw[k])>0.0001)fail('Profile does not bind initial '+k);});
 if(!isFinite(q.createdMs)||q.createdMs>now||now-q.createdMs>300000||!isFinite(q.imageCapturedMs)||!isFinite(q.reviewedImageMs)||q.imageCapturedMs>q.reviewedImageMs||q.reviewedImageMs>q.createdMs||now-q.imageCapturedMs>300000)fail('Fresh image/request required');
 var prior=q.expectedRaw,bCount=0;
 q.previewStages.forEach(function(s,i){if(!s||['X','Y','Z','B'].indexOf(s.axis)<0||!s.startRaw||!s.targetRaw||s.speedFraction!==(s.axis==='B'?.05:1)||(!preview&&(!Array.isArray(s.expandedCommands)||s.expandedCommands.length<1||!hashPattern.test(s.sha256)||typeof s.path!=='string'||s.path.charAt(0)!=='/')))fail('Invalid stage '+i);
  if(s.axis!=='B'&&s.dwellMilliseconds!==undefined)fail('Post-stage dwell is B-only');if(s.axis==='B'&&s.dwellMilliseconds!==undefined){var dwell=finite(s.dwellMilliseconds,'B-stage dwell');if(Math.floor(dwell)!==dwell||dwell<0||dwell>2000)fail('B-stage dwell must be integer 0..2000 ms');}
  var delta=finite(s.targetRaw[s.axis],'stage target')-prior[s.axis];if(delta===0)fail('Zero stage');if(s.axis==='B'){if(q.mode!=='wet'||batchSteps.indexOf(delta)<0||!s.gapEvidence||typeof s.gapEvidence.path!=='string'||s.gapEvidence.path.charAt(0)!=='/'||!hashPattern.test(s.gapEvidence.sha256))fail('B step needs reviewed provisional gap evidence');var bg=finite(s.estimatedGapMm,'B-stage gap'),bu=finite(s.gapUncertaintyMm,'B-stage gap uncertainty');if(bg<=0||bu<0||bg-bu<0.1)fail('B-stage gap lower bound must be >=0.1 mm');bCount++;}else if(Math.abs(delta)>(s.axis==='Z'?5:10))fail('Linear step outside reviewed bound');
  if(s.axis==='X'||s.axis==='Y'){if(s.startRaw.Z!==q.xyClearanceRawZ){if(s.wipeReview!==true||!s.wipeReviewEvidence||typeof s.wipeReviewEvidence.path!=='string'||s.wipeReviewEvidence.path.charAt(0)!=='/'||!hashPattern.test(s.wipeReviewEvidence.sha256))fail('XY at dispense height requires reviewed noncontact wipe evidence');var wg=finite(s.estimatedGapMm,'wipe gap'),wu=finite(s.gapUncertaintyMm,'wipe uncertainty');if(wg<=0||wu<0||wg-wu<0.1)fail('Wipe gap lower bound must be >=0.1 mm');}else if(s.wipeReview===true)fail('Wipe review reserved for dispense-height XY');}
  ['X','Y','Z','A','B'].forEach(function(k){if(s.startRaw[k]!==prior[k]||finite(s.targetRaw[k],'stage '+k)!==(k===s.axis?prior[k]+delta:prior[k]))fail('Discontiguous or multi-axis stage '+i);if(k!=='A'&&bounds[k]&&(s.targetRaw[k]<bounds[k].min||s.targetRaw[k]>bounds[k].max))fail('Stage outside reviewed raw bounds '+i);});prior=s.targetRaw;
 });
 if((q.mode==='wet'&&!bCount)||(q.mode==='air'&&bCount)||!q.finalTargetRaw)fail('Batch mode/B or final target mismatch');['X','Y','Z','A','B'].forEach(function(k){if(q.finalTargetRaw[k]!==prior[k])fail('Final target mismatch '+k);});
 var ftp=typeof module!=='undefined'&&module.exports?require('./ftp-two-pad.cjs'):root.PasteFtpTwoPad;if(q.scope.indexOf('contiguous-native-ftp-two-pad')===0){if(!ftp)fail('FTP target policy not loaded');ftp.validate(q,now);}else if(q.ftpTargetRecord!==undefined||q.ftpTargetEvidence!==undefined)fail('FTP targets cannot use scrap scope');
 if(!preview){if(!Array.isArray(q.evidence)||q.evidence.length<7||!q.previousReportEvidence||!q.nativePreviewEvidence||!q.profileEvidence||!q.barrierEvidence||!q.reviewedImageEvidence)fail('Batch evidence incomplete');q.evidence.forEach(function(e){if(!e||typeof e.path!=='string'||e.path.charAt(0)!=='/'||!hashPattern.test(e.sha256))fail('Hashless batch evidence');});}
 return q;
}
function validBatchStageIndex(v){return typeof v==='number'&&isFinite(v)&&Math.floor(v)===v&&v>=0&&v<40;}
function reserveBatch(old,q,carry,amendment){
 validateBatch(q,q.createdMs,q.jvmStartMs,false);
 if(q.mode!=='wet')fail('Air batch must not reserve B budget');
 if(!old||old.schema!==1||old.scope!=='signed-B-commissioning-strokes'||old.status!=='verified'||old.sessionId!==q.sessionId||old.syringeId!==q.syringeId||old.primeLedgerSha256!==q.primeLedgerSha256||old.carryoverSha256!==q.carryoverSha256||old.lastVerifiedB!==q.expectedRaw.B||!hashPattern.test(q.previousLedgerSha256))fail('Exact verified previous ledger required');
 if(!carry||carry.schema!==1||carry.sessionId!==q.sessionId||carry.syringeId!==q.syringeId||carry.primeLedgerSha256!==q.primeLedgerSha256||carry.priorGrossDegrees!==10940||carry.manualDisplacementUnknown!==true||carry.verifiedPrimeDegrees!==960||carry.startB!==-240||carry.maximumAbsoluteDegrees!==120)fail('Immutable prime/carryover history required');
 if(q.budgetAmendmentEvidence&&!amendment)fail('Reviewed budget amendment missing');var max=amendment?validateBudgetAmendment(q,amendment.record,amendment.anchorLedger,amendment.anchorReport,old,carry):120;
 var l=JSON.parse(JSON.stringify(old)),sum=0,at=-240,seen={};if(!Array.isArray(l.entries)||l.startB!==-240)fail('Malformed ledger');var reconciled=reconciliationIndices(l);l.entries.forEach(function(e,index){if(reconciled[index]){if(seen[e.requestId]||e.batchId===q.id||e.requestId===q.id||at!==-1130)fail('Reconciliation replay or actual B mismatch');seen[e.requestId]=true;sum+=e.absoluteDegrees;return;}if(!e||e.status!=='verified'||typeof e.requestId!=='string'||seen[e.requestId]||e.batchId===q.id||batchSteps.indexOf(e.deltaDegrees)<0||(Math.abs(e.deltaDegrees)===3&&(typeof e.batchId!=='string'||!/^[a-f0-9-]{36}$/.test(e.batchId)||!validBatchStageIndex(e.stageIndex)||e.requestId!==e.batchId+':'+e.stageIndex))||e.startB!==at||e.targetB!==at+e.deltaDegrees||e.absoluteDegrees!==Math.abs(e.deltaDegrees))fail('Malformed prior B chain or batch replay');seen[e.requestId]=true;sum+=e.absoluteDegrees;at=e.targetB;});if(sum!==l.totalAbsoluteDegrees||at!==l.lastVerifiedB||sum>max)fail('Prior gross/B mismatch');
 l.status='reserved';l.activeBatchId=q.id;q.previewStages.forEach(function(s,i){if(s.axis!=='B')return;var key=q.id+':'+i;if(seen[key])fail('Batch replay');var delta=s.targetRaw.B-s.startRaw.B;sum+=Math.abs(delta);l.entries.push({requestId:key,batchId:q.id,stageIndex:i,startB:s.startRaw.B,targetB:s.targetRaw.B,deltaDegrees:delta,absoluteDegrees:Math.abs(delta),status:'reserved'});});if(sum>max)fail('Batch exceeds reviewed gross budget');l.totalAbsoluteDegrees=sum;return l;
}
function markBatchStep(old,q,index,reportedB){var s=q.previewStages[index];if(!s||s.axis!=='B')fail('No B at stage');var l=JSON.parse(JSON.stringify(old)),entries=l.entries.filter(function(x){return x.batchId===q.id;}),e=entries.filter(function(x){return x.stageIndex===index;})[0],first=entries.filter(function(x){return x.status==='reserved';})[0];if(l.status!=='reserved'||l.activeBatchId!==q.id||!e||e!==first||e.startB!==l.lastVerifiedB||Math.abs(finite(reportedB,'verified B')-e.targetB)>0.3)fail('Batch B order/position verification mismatch');e.status='verified';l.lastVerifiedB=e.targetB;return l;}
function finishBatch(old,q,success){var l=JSON.parse(JSON.stringify(old)),entries=l.entries.filter(function(e){return e.batchId===q.id;});if(l.status!=='reserved'||l.activeBatchId!==q.id||!entries.length)fail('Unknown reserved batch');if(success&&(entries.some(function(e){return e.status!=='verified';})||l.lastVerifiedB!==entries[entries.length-1].targetB))fail('Every B stage and final B must verify');if(!success)entries.forEach(function(e){if(e.status==='reserved')e.status='faulted';});l.status=success?'verified':'faulted';delete l.activeBatchId;return l;}
function stopDecision(q,raw,stage,requested){if(!requested)return 'continue';if(raw.Z===q.xyClearanceRawZ)return 'stop-at-clearance';if(stage&&stage.axis==='Z'&&stage.startRaw.Z===raw.Z&&stage.targetRaw.Z===q.xyClearanceRawZ&&stage.speedFraction===1)return 'reviewed-clearance-lift';return 'stop-hold-position';}
var api={reconcileUnexecutedBatch:reconcileUnexecutedBatch,validate:validate,reserve:reserve,finish:finish,validatePreviousReport:validatePreviousReport,validateBudgetAmendment:validateBudgetAmendment,validateCycle:validateCycle,reserveCycle:reserveCycle,markCycleStep:markCycleStep,finishCycle:finishCycle,validateBatch:validateBatch,reserveBatch:reserveBatch,markBatchStep:markBatchStep,finishBatch:finishBatch,stopDecision:stopDecision,allowedSteps:steps.slice()};
if(typeof module!=='undefined'&&module.exports)module.exports=api;else root.CommissioningStroke=api;
})(this);
