'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const B=require('./commissioning-stroke.cjs');
const hash='a'.repeat(64),id='12345678-1234-1234-1234-123456789abc',sessionId='abcd1234-1234-1234-1234-123456789abc';
const ev=()=>({path:'/synthetic-only',sha256:hash});
const raw=()=>({X:100,Y:200,Z:50,A:720,B:-240});
function request(mode='wet',preview=false){
 const r=raw(),target={...r,[mode==='wet'?'B':'Z']:mode==='wet'?-246:45};
 return {schema:1,scope:preview?'contiguous-native-scrap-batch-preview':'contiguous-native-scrap-batch',enabled:false,mode,stopPath:'/synthetic-stop',id,sessionId,jvmStartMs:1,createdMs:1000,imageCapturedMs:900,reviewedImageMs:950,liveConfigurationSha256:hash,expectedRaw:r,expectedDriver:{...r},expectedNativePoses:{N1:{x:100,y:200,z:50},N2:{x:100,y:200,z:50},top:{},bottom:{}},rawBounds:{X:{min:95,max:105},Y:{min:195,max:205},Z:{min:45,max:55},B:{min:-260,max:-220}},headClearanceBounds:{N1:{minX:0,maxX:500,minY:0,maxY:500,minZ:0,maxZ:100},N2:{minX:0,maxX:500,minY:0,maxY:500,minZ:0,maxZ:100}},bothHeadsClearanceReview:true,clearanceReviewEvidence:ev(),xyClearanceRawZ:45,receivingProfile:{provenance:'commissioning-provisional',precisionCalibrated:false,flowCalibrated:false,sha256:hash,estimatedGapMm:.65,gapUncertaintyMm:.4,basis:'synthetic observed height interval',rawPose:{...r}},previewStages:[{axis:mode==='wet'?'B':'Z',speedFraction:mode==='wet'?.05:1,startRaw:r,targetRaw:target,...(mode==='wet'?{gapEvidence:ev(),estimatedGapMm:.65,gapUncertaintyMm:.4}:{}),...(preview?{}:{expandedCommands:['synthetic'],...ev()})}],finalTargetRaw:target,evidence:Array.from({length:7},ev),previousReportEvidence:ev(),nativePreviewEvidence:ev(),profileEvidence:ev(),barrierEvidence:ev(),reviewedImageEvidence:ev(),previousLedgerSha256:hash,syringeId:'synthetic',primeLedgerSha256:hash,carryoverSha256:hash,budgetAmendmentEvidence:null};
}
const clone=x=>JSON.parse(JSON.stringify(x));
const ledger=()=>({schema:1,scope:'signed-B-commissioning-strokes',sessionId,syringeId:'synthetic',primeLedgerSha256:hash,carryoverSha256:hash,startB:-240,lastVerifiedB:-240,totalAbsoluteDegrees:0,entries:[],status:'verified'});
const carry=()=>({schema:1,sessionId,syringeId:'synthetic',primeLedgerSha256:hash,priorGrossDegrees:10940,manualDisplacementUnknown:true,verifiedPrimeDegrees:960,startB:-240,maximumAbsoluteDegrees:120});
test('bounded wet batch reserves full gross and verifies each B stage',()=>{const q=request(),l=B.reserveBatch(ledger(),q,carry());assert.equal(l.totalAbsoluteDegrees,6);assert.equal(l.entries[0].batchId,id);assert.throws(()=>B.finishBatch(l,q,true));const done=B.finishBatch(B.markBatchStep(l,q,0,-246),q,true);assert.equal(done.status,'verified');assert.equal(done.lastVerifiedB,-246);assert.equal(done.totalAbsoluteDegrees,6);});
function sequenceRequest(){
 const q=request(),r={X:100,Y:200,Z:58.45,A:720,B:-3000};Object.assign(q,{scope:'contiguous-native-scrap-sequence-comparison-preview',targetSurface:'scrap-sequence-comparison',sequenceProtocol:'three-12-degree-sacrificial-then-three-6-degree-test-r2',expectedRaw:r,expectedDriver:{...r},xyClearanceRawZ:53.45,rawBounds:{X:{min:90,max:120},Y:{min:190,max:220},Z:{min:53.45,max:58.45},B:{min:-3400,max:-2900}},receivingProfile:{...q.receivingProfile,rawPose:{X:r.X,Y:r.Y,Z:r.Z,A:r.A}},previewStages:[]});
 q.expectedNativePoses={N1:{x:100,y:200,z:58.45},N2:{x:100,y:200,z:58.45},top:{},bottom:{}};
 let at={...r};function add(axis,value,extra={}){const target={...at,[axis]:value},d=value-at[axis];q.previewStages.push({axis,startRaw:at,targetRaw:target,speedFraction:axis==='B'?.05:1,...(axis==='B'?{gapEvidence:ev(),estimatedGapMm:.65,gapUncertaintyMm:.4}:{}),...extra});at=target;}
 function move(p){if(at.X!==p.X)add('X',p.X,at.Z===58.45?{wipeReview:true,wipeReviewEvidence:ev(),estimatedGapMm:.65,gapUncertaintyMm:.4}:{});if(at.Y!==p.Y)add('Y',p.Y,p.wipe?{wipeReview:true,wipeReviewEvidence:ev(),estimatedGapMm:.65,gapUncertaintyMm:.4}:{});}
 function stroke(d,dwell=0){add('B',at.B+d,dwell?{dwellMilliseconds:dwell}:{});}
 for(let i=0;i<3;i++)stroke(-20,i===2?2000:0);stroke(20,1000);move({X:101.5,Y:200});add('Z',53.45);move({X:102,Y:200});add('Z',58.45);stroke(-20,2000);stroke(2,500);add('Z',53.45);
 const deposits=(points,dose)=>points.forEach(p=>{if(at.X!==p.X)add('X',p.X);if(at.Y!==p.Y)add('Y',p.Y);add('Z',58.45);stroke(-2);if(dose===12){stroke(-6);stroke(-6,2000);}else stroke(-6,2000);stroke(2,500);add('Z',53.45);});
 deposits([{X:103,Y:201},{X:104,Y:201},{X:105,Y:201}],12);deposits([{X:103,Y:202},{X:104,Y:202},{X:105,Y:202}],6);stroke(20);stroke(20,2000);q.finalTargetRaw=at;return q;
}
test('dedicated scrap sequence scope admits exact 12 then 6 route and rejects altered order or >64 stages',()=>{
 const q=sequenceRequest();assert.equal(q.previewStages.length,54);B.validateBatch(q,1000,1,true);
 assert.equal(q.previewStages.filter(s=>s.axis==='B').reduce((n,s)=>n+Math.abs(s.targetRaw.B-s.startRaw.B),0),220);
 const wrong=clone(q),b=wrong.previewStages.filter(s=>s.axis==='B');const changed=b[8],shift=4;changed.targetRaw.B+=shift;let running={...wrong.expectedRaw};let bi=0;wrong.previewStages.forEach(s=>{const d=s.targetRaw[s.axis]-s.startRaw[s.axis];s.startRaw={...running};s.targetRaw={...running,[s.axis]:running[s.axis]+(s.axis==='B'&&bi++===8?d+shift:d)};running={...s.targetRaw};});wrong.finalTargetRaw=running;assert.throws(()=>B.validateBatch(wrong,1000,1,true),/12\/12\/12 then 6\/6\/6/);
 const tooLong=clone(q);while(tooLong.previewStages.length<=64)tooLong.previewStages.push(clone(tooLong.previewStages.at(-1)));assert.throws(()=>B.validateBatch(tooLong,1000,1,true),/scope limit/);
});
test('sequence-scope batch history accepts a verified stage index above the generic 40-stage cap',()=>{
 const old=ledger();old.lastVerifiedB=-242;old.totalAbsoluteDegrees=2;old.entries=[{requestId:'22345678-1234-1234-1234-123456789abc:53',batchId:'22345678-1234-1234-1234-123456789abc',batchScope:'contiguous-native-scrap-sequence-comparison',stageIndex:53,startB:-240,targetB:-242,deltaDegrees:-2,absoluteDegrees:2,status:'verified'}];
 const q=request();q.expectedRaw.B=-242;q.expectedDriver.B=-242;q.rawBounds.B={min:-260,max:-220};q.previousLedgerSha256=hash;q.previewStages[0].startRaw={...q.expectedRaw};q.previewStages[0].targetRaw={...q.expectedRaw,B:-244};q.finalTargetRaw={...q.previewStages[0].targetRaw};
 const next=B.reserveBatch(old,q,carry());assert.equal(next.totalAbsoluteDegrees,4);
});
test('fault consumes all reserved B budget and bars replay',()=>{const q=request(),l=B.reserveBatch(ledger(),q,carry()),fault=B.finishBatch(l,q,false);assert.equal(fault.totalAbsoluteDegrees,6);assert.equal(fault.entries[0].status,'faulted');assert.throws(()=>B.reserveBatch(fault,q,carry()));});
test('air batch has zero B stages and cannot reserve budget',()=>{const q=request('air');B.validateBatch(q,1000,1);assert.throws(()=>B.reserveBatch(ledger(),q,carry()));const bad=clone(q);bad.previewStages[0].axis='B';assert.throws(()=>B.validateBatch(bad,1000,1));});
test('contiguous single-axis, length, speed and clearance bounds fail closed',()=>{const q=request();for(const edit of [x=>x.previewStages[0].targetRaw.A++,x=>x.previewStages[0].speedFraction=1,x=>x.previewStages=Array.from({length:41},()=>x.previewStages[0]),x=>x.receivingProfile.gapUncertaintyMm=.6]){const v=clone(q);edit(v);assert.throws(()=>B.validateBatch(v,1000,1));}const a=request('air');a.previewStages[0].axis='X';a.previewStages[0].targetRaw={...a.expectedRaw,X:101};a.finalTargetRaw={...a.previewStages[0].targetRaw};assert.throws(()=>B.validateBatch(a,1000,1));a.previewStages[0].wipeReview=true;a.previewStages[0].wipeReviewEvidence=ev();a.previewStages[0].estimatedGapMm=.5;a.previewStages[0].gapUncertaintyMm=.2;B.validateBatch(a,1000,1);});
test('prior report accepts batch tail only with exact completed ledger hash',()=>{const q=request(),l=B.finishBatch(B.markBatchStep(B.reserveBatch(ledger(),q,carry()),q,0,-246),q,true),r={id,request:{id},status:'completed-contiguous-batch-awaiting-observation',uncertainCompletion:false,completedLedgerSha256:hash,finishedAt:'2026-09-30T00:00:00.000Z'};assert.equal(B.validatePreviousReport(r,l,hash,Date.parse(r.finishedAt)+1),true);r.completedLedgerSha256='b'.repeat(64);assert.throws(()=>B.validatePreviousReport(r,l,hash,Date.parse(r.finishedAt)+1));});
test('negative stage uncertainty and negative gap cannot bypass lower bound',()=>{const q=request();q.previewStages[0].estimatedGapMm=-1;q.previewStages[0].gapUncertaintyMm=-2;assert.throws(()=>B.validateBatch(q,1000,1));const a=request('air');a.previewStages[0].axis='X';a.previewStages[0].targetRaw={...a.expectedRaw,X:101};a.finalTargetRaw={...a.previewStages[0].targetRaw};a.previewStages[0].wipeReview=true;a.previewStages[0].wipeReviewEvidence=ev();a.previewStages[0].estimatedGapMm=-1;a.previewStages[0].gapUncertaintyMm=-2;assert.throws(()=>B.validateBatch(a,1000,1));});
test('batch ID replay rejected even with shifted B index; B verification is ordered',()=>{const q=request(),l=B.reserveBatch(ledger(),q,carry()),done=B.finishBatch(B.markBatchStep(l,q,0,-246),q,true);const q2=clone(q);q2.expectedRaw.B=-246;q2.expectedDriver.B=-246;const r=q2.expectedRaw,xy={...r,X:101};q2.previewStages.unshift({axis:'X',startRaw:r,targetRaw:xy,speedFraction:1,expandedCommands:['synthetic'],...ev()});q2.previewStages[1].startRaw=xy;q2.previewStages[1].targetRaw={...xy,B:-252};q2.finalTargetRaw={...xy,B:-252};q2.xyClearanceRawZ=50;assert.throws(()=>B.reserveBatch(done,q2,carry()),/batch replay/);const q3=request();const second={...q3.previewStages[0],startRaw:q3.finalTargetRaw,targetRaw:{...q3.finalTargetRaw,B:-252}};q3.previewStages.push(second);q3.finalTargetRaw=second.targetRaw;const two=B.reserveBatch(ledger(),q3,carry());assert.throws(()=>B.markBatchStep(two,q3,1,-252));assert.throws(()=>B.finishBatch(two,q3,true));});
test('cooperative stop allows only an already-reviewed clearance lift',()=>{const q=request('air'),at={...q.expectedRaw,Z:50},lift={axis:'Z',speedFraction:1,startRaw:at,targetRaw:{...at,Z:q.xyClearanceRawZ}};assert.equal(B.stopDecision(q,at,lift,false),'continue');assert.equal(B.stopDecision(q,at,lift,true),'reviewed-clearance-lift');assert.equal(B.stopDecision(q,at,{...lift,axis:'B'},true),'stop-hold-position');assert.equal(B.stopDecision(q,{...at,Z:q.xyClearanceRawZ},lift,true),'stop-at-clearance');});
test('optional post-B dwell accepts only integer 0..2000 and never linear stages',()=>{for(const preview of [false,true]){const q=request('wet',preview);B.validateBatch(q,1000,1,preview);for(const ms of [0,1,50,2000]){q.previewStages[0].dwellMilliseconds=ms;B.validateBatch(q,1000,1,preview);}for(const ms of [-1,2001,1.5,'50',null,NaN,Infinity]){q.previewStages[0].dwellMilliseconds=ms;assert.throws(()=>B.validateBatch(q,1000,1,preview));}}const a=request('air');a.previewStages[0].dwellMilliseconds=0;assert.throws(()=>B.validateBatch(a,1000,1));});

const FTP=require('./ftp-two-pad.cjs');
function ftpRequest(){
 const q=request(),start=raw();q.scope=FTP.scope(false);q.rawBounds.Z.max=50;q.previewStages=[];let at={...start};
 function add(axis,value){const target={...at,[axis]:value};q.previewStages.push({axis,startRaw:at,targetRaw:target,speedFraction:axis==='B'?.05:1,expandedCommands:['synthetic'],...ev(),...(axis==='B'?{gapEvidence:{path:'/ftp/surface.json',sha256:hash},estimatedGapMm:.65,gapUncertaintyMm:.4}:{})});at=target;}
 add('B',-246);add('Z',45);add('X',101);add('Z',50);add('B',-252);add('Z',45);q.finalTargetRaw=at;
 const e=name=>({path:'/ftp/'+name,sha256:hash});
 q.ftpTargetEvidence=e('targets.json');q.ftpTargetRecord={schema:1,scope:'ftp-two-pad-commissioning-targets',boardId:'synthetic-cleaned-demo',sessionId,jvmStartMs:1,liveConfigurationSha256:hash,reviewedBy:'synthetic-test',reviewedMs:950,boardCleaned:true,padsAvailable:true,boardUnmovedSinceRegistration:true,provenance:'commissioning-provisional',precisionCalibrated:false,flowCalibrated:false,cadEvidence:e('board.kicad_pcb'),registrationEvidence:e('registration.json'),tipOffsetEvidence:e('offset.json'),surfaceEvidence:e('surface.json'),padAvailabilityImage:e('available.png'),cameraMinusTipXYMm:[5,-3],quantizationMm:0.01,surface:{rawZ:50,estimatedGapMm:.65,gapUncertaintyMm:.4},pads:[{padId:'R1.1',doseStageIndex:0,rawPose:{X:100,Y:200,Z:50,A:720}},{padId:'R1.2',doseStageIndex:4,rawPose:{X:101,Y:200,Z:50,A:720}}],padChecks:['R1','R16','R40'].map(reference=>({reference,padId:reference+'.1',reviewedAligned:true,reportEvidence:e(reference+'/report.json'),imageEvidence:e(reference+'/top.png')}))};return q;
}
function ftpSources(q){
 const t=q.ftpTargetRecord,files={},e=name=>({path:'/ftp/'+name,sha256:hash});
 const cameraReport=xy=>({status:'completed-contiguous-air-batch-awaiting-observation',controllerPositionVerified:true,uncertainCompletion:false,finishedAt:new Date(900).toISOString(),request:{jvmStartMs:1,liveConfigurationSha256:hash},afterImages:{top:{path:'top.png'}},afterQuerySnapshot:{nativePoses:{top:{x:xy[0],y:xy[1]}}}});
 const targets=Array.from({length:40},(_,i)=>[1,2].map(n=>({padId:`R${i+1}.${n}`,machineXYMm:[104+n,197]}))).flat();
 const reg={scope:'offline-fresh-ftp-two-fiducial-transform-with-third-point-check',acceptance:{passed:true},board:t.cadEvidence,session:{jvmStartMs:1,liveConfigurationSha256:hash},independentFID3Check:{residualMm:.01},measurements:{},resistorPadMachineXYTargets:targets};
 for(const fid of ['FID1','FID2','FID3']){reg.measurements[fid]={imageCenterErrorPx:1,report:e(fid+'/report.json'),image:e(fid+'/top.png')};files['/ftp/'+fid+'/report.json']=cameraReport([0,0]);}
 for(const c of t.padChecks)files[c.reportEvidence.path]=cameraReport(targets.find(p=>p.padId===c.padId).machineXYMm);
 const base={boardId:t.boardId,provenance:'commissioning-provisional',precisionCalibrated:false,jvmStartMs:1,liveConfigurationSha256:hash,reviewedBy:'synthetic-test',basisEvidence:e('basis.json')};
 files[t.registrationEvidence.path]=reg;files[t.tipOffsetEvidence.path]={...base,cameraMinusTipXYMm:t.cameraMinusTipXYMm};files[t.surfaceEvidence.path]={...base,surface:t.surface};files[q.ftpTargetEvidence.path]=clone(t);
 return {files,read:(e,json)=>{assert.match(e.sha256,/^[a-f0-9]{64}$/);if(json){assert.ok(files[e.path],e.path);return files[e.path];}return null;}};
}
test('FTP two-pad wet branch preserves whole-budget reservation and ordered verification',()=>{const q=ftpRequest();B.validateBatch(q,1000,1);let l=B.reserveBatch(ledger(),q,carry());assert.equal(l.totalAbsoluteDegrees,12);l=B.markBatchStep(l,q,0,-246);l=B.markBatchStep(l,q,4,-252);assert.equal(B.finishBatch(l,q,true).lastVerifiedB,-252);const f=ftpSources(q);FTP.verifySources(q,f.read);});
test('FTP prevents duplicate/different-resistor targets, wrong dose pose and extra dose stage',()=>{for(const edit of [q=>q.ftpTargetRecord.pads[1].padId='R1.1',q=>q.ftpTargetRecord.pads[1].padId='R2.2',q=>q.ftpTargetRecord.pads[0].rawPose.X++,q=>q.ftpTargetRecord.pads[1].doseStageIndex=0,q=>q.ftpTargetRecord.surface.estimatedGapMm=.9,q=>q.ftpTargetRecord.pads[0].doseStageIndex=2]){const q=ftpRequest();edit(q);assert.throws(()=>B.validateBatch(q,1000,1));}});
test('FTP cannot downgrade to scrap, claim calibration, omit review or exceed board Z',()=>{for(const edit of [q=>q.scope='contiguous-native-scrap-batch',q=>q.ftpTargetRecord.precisionCalibrated=true,q=>q.ftpTargetRecord.boardUnmovedSinceRegistration=false,q=>q.ftpTargetRecord.reviewedMs=NaN,q=>q.ftpTargetRecord.reviewedMs=-400000,q=>q.rawBounds.Z.max=51,q=>delete q.ftpTargetEvidence]){const q=ftpRequest();edit(q);assert.throws(()=>B.validateBatch(q,1000,1));}});
test('FTP rejects low XY even with legacy noncontact wipe evidence',()=>{const q=ftpRequest();q.previewStages[2].wipeReview=true;q.previewStages[2].wipeReviewEvidence=ev();assert.throws(()=>B.validateBatch(q,1000,1));});
test('FTP air record permits no B and cannot map dose indices',()=>{const q=ftpRequest();q.mode='air';q.previewStages=q.previewStages.filter(s=>s.axis!=='B').map(s=>({...s,startRaw:{...s.startRaw,B:-240},targetRaw:{...s.targetRaw,B:-240}}));q.finalTargetRaw.B=-240;q.ftpTargetRecord.pads.forEach(p=>p.doseStageIndex=null);B.validateBatch(q,1000,1);assert.throws(()=>B.reserveBatch(ledger(),q,carry()));q.ftpTargetRecord.pads[0].doseStageIndex=0;assert.throws(()=>B.validateBatch(q,1000,1));});
test('FTP source verification rejects swapped record, offset, surface and camera evidence',()=>{for(const edit of [(q,f)=>f.files[q.ftpTargetEvidence.path].boardId='different',(q,f)=>f.files[q.ftpTargetRecord.tipOffsetEvidence.path].cameraMinusTipXYMm=[6,-3],(q,f)=>f.files[q.ftpTargetRecord.surfaceEvidence.path].surface={...q.ftpTargetRecord.surface,rawZ:51},(q,f)=>f.files['/ftp/R16/report.json'].afterQuerySnapshot.nativePoses.top.x=NaN,(q,f)=>f.files['/ftp/FID1/report.json'].uncertainCompletion=true]){const q=ftpRequest(),f=ftpSources(q);edit(q,f);assert.throws(()=>FTP.verifySources(q,f.read));}});
test('FTP registered coordinates must match selected tip offset; preview equality is order independent',()=>{const q=ftpRequest(),f=ftpSources(q);f.files[q.ftpTargetRecord.registrationEvidence.path].resistorPadMachineXYTargets[0].machineXYMm[0]+=.1;assert.throws(()=>FTP.verifySources(q,f.read));assert.equal(FTP.same({a:1,b:2},{b:2,a:1}),true);assert.equal(FTP.same({a:1},{a:2}),false);});

test('FTP rejects any added positive B stage, including relief at clearance',()=>{for(const placement of ['before','after']){const q=ftpRequest();if(placement==='after'){const at=q.finalTargetRaw,target={...at,B:at.B+2};q.previewStages.push({axis:'B',startRaw:at,targetRaw:target,speedFraction:.05,expandedCommands:['synthetic'],...ev(),gapEvidence:q.ftpTargetRecord.surfaceEvidence,estimatedGapMm:5.65,gapUncertaintyMm:.4});q.finalTargetRaw=target;}else{const at=q.expectedRaw,target={...at,B:at.B+2};q.previewStages.forEach(s=>{s.startRaw={...s.startRaw,B:s.startRaw.B+2};s.targetRaw={...s.targetRaw,B:s.targetRaw.B+2};});q.finalTargetRaw={...q.finalTargetRaw,B:q.finalTargetRaw.B+2};q.ftpTargetRecord.pads.forEach(p=>p.doseStageIndex++);q.previewStages.unshift({axis:'B',startRaw:at,targetRaw:target,speedFraction:.05,expandedCommands:['synthetic'],...ev(),gapEvidence:q.ftpTargetRecord.surfaceEvidence,estimatedGapMm:.65,gapUncertaintyMm:.4});}assert.throws(()=>B.validateBatch(q,1000,1),/only its two negative B/);}});


test('FTP explicitly quantizes registered-minus-offset targets onto M114 0.01 mm grid',()=>{const q=ftpRequest(),f=ftpSources(q);f.files[q.ftpTargetRecord.registrationEvidence.path].resistorPadMachineXYTargets[0].machineXYMm[0]=105.004;FTP.verifySources(q,f.read);q.ftpTargetRecord.pads[0].rawPose.X=100.004;assert.throws(()=>B.validateBatch(q,1000,1),/0.01 mm/);q.ftpTargetRecord.pads[0].rawPose.X=100;delete q.ftpTargetRecord.quantizationMm;assert.throws(()=>B.validateBatch(q,1000,1),/0.01 mm/);});

function stoppedBatchFixture(){const anchor=ledger();[-20,-20,-20,-20,-2,20,6,6,6].forEach(d=>{const startB=anchor.lastVerifiedB;anchor.entries.push({requestId:'fixture-anchor-'+anchor.entries.length,startB,targetB:startB+d,deltaDegrees:d,absoluteDegrees:Math.abs(d),status:'verified'});anchor.lastVerifiedB+=d;anchor.totalAbsoluteDegrees+=Math.abs(d);});return {anchor};}
test('11800-degree batch amendment preserves the immutable 120-degree anchor and requires matching review evidence',()=>{
 const anchor=ledger();let b=-240;for(const d of [-20,-20,-20,-20,-2,20,6,6,6]){const start=b;b+=d;anchor.entries.push({requestId:`anchor-${anchor.entries.length}`,startB:start,targetB:b,deltaDegrees:d,absoluteDegrees:Math.abs(d),status:'verified'});anchor.totalAbsoluteDegrees+=Math.abs(d);}anchor.lastVerifiedB=b;
 const anchorHash='b'.repeat(64),travel={path:'/11800-review.json',sha256:'9'.repeat(64)},ar={id:anchor.entries.at(-1).requestId,status:'completed-commissioning-stroke-awaiting-observation',uncertainCompletion:false,completedLedgerSha256:anchorHash,finishedAt:'1970-01-01T00:00:00.000Z',request:{id:anchor.entries.at(-1).requestId,sessionId,jvmStartMs:1,liveConfigurationSha256:hash}};
 const record={schema:1,sessionId,syringeId:'synthetic',originalCarryoverSha256:hash,anchorLedgerSha256:anchorHash,anchorGrossDegrees:120,anchorB:-284,newMaximumAbsoluteDegrees:11800,reviewedAt:new Date(500).toISOString(),reviewedBy:'synthetic',reason:'Fixed travel review for bounded commissioning.',anchorLedgerEvidence:{path:'/anchor-ledger.json',sha256:anchorHash},anchorReportEvidence:ev(),travelReviewEvidence:travel};
 const envelope={...record,...ev(),travelReviewEvidence:{...travel}},context={record,anchorLedger:anchor,anchorReport:ar};
 const q=request();q.expectedRaw.B=-284;q.expectedDriver.B=-284;q.rawBounds.B={min:-350,max:-250};q.previewStages[0].startRaw={...q.expectedRaw};q.previewStages[0].targetRaw={...q.expectedRaw,B:-290};q.finalTargetRaw={...q.previewStages[0].targetRaw};q.previousLedgerSha256=hash;q.budgetAmendmentEvidence=envelope;q.evidence.push(travel);
 const reserved=B.reserveBatch(anchor,q,carry(),context);assert.equal(reserved.totalAbsoluteDegrees,126);assert.deepEqual(reserved.entries.slice(0,anchor.entries.length),anchor.entries);assert.equal(carry().maximumAbsoluteDegrees,120);
 const missing=request();Object.assign(missing,q,{evidence:q.evidence.filter(x=>x.path!==travel.path)});assert.throws(()=>B.reserveBatch(anchor,missing,carry(),context),/travel review/);
 const changed=clone(anchor);changed.entries[0].targetB++;assert.throws(()=>B.reserveBatch(anchor,q,carry(),{...context,anchorLedger:changed}),/prefix/);
});

test('batch-only three-degree relief and restoration reserve gross, verify ordered positions, and cannot replay',()=>{
 const q=request();q.rawBounds.B={min:-300,max:-200};q.previewStages=[];let at={...q.expectedRaw};
 for(const delta of [-20,3,-3,-20,3]){const target={...at,B:at.B+delta};q.previewStages.push({axis:'B',speedFraction:.05,startRaw:at,targetRaw:target,gapEvidence:ev(),estimatedGapMm:.65,gapUncertaintyMm:.4,expandedCommands:['synthetic'],...ev()});at=target;}q.finalTargetRaw=at;
 B.validateBatch(q,1000,1);B.validateBatch({...q,scope:'contiguous-native-scrap-batch-preview'},1000,1,true);
 let l=B.reserveBatch(ledger(),q,carry());assert.equal(l.totalAbsoluteDegrees,49);assert.equal(B.finishBatch(l,q,false).totalAbsoluteDegrees,49);
 q.previewStages.forEach((s,i)=>{l=B.markBatchStep(l,q,i,s.targetRaw.B);});l=B.finishBatch(l,q,true);assert.equal(l.lastVerifiedB,-277);
 const next=request();next.id='22345678-1234-1234-1234-123456789abc';next.expectedRaw.B=-277;next.expectedDriver.B=-277;next.rawBounds.B={min:-300,max:-200};next.previewStages[0].startRaw={...next.expectedRaw};next.previewStages[0].targetRaw={...next.expectedRaw,B:-274};next.finalTargetRaw={...next.previewStages[0].targetRaw};assert.equal(B.reserveBatch(l,next,carry()).totalAbsoluteDegrees,52);
 assert.throws(()=>B.reserveBatch(l,{...next,id:q.id},carry()),/replay/);const forged=clone(l);delete forged.entries[1].batchId;assert.throws(()=>B.reserveBatch(forged,next,carry()),/Malformed/);const wrongKey=clone(l);wrongKey.entries[1].requestId='unrelated';assert.throws(()=>B.reserveBatch(wrongKey,next,carry()),/Malformed/);
 for(const delta of [-5,5,3.1]){const bad=clone(next);bad.previewStages[0].targetRaw.B=bad.expectedRaw.B+delta;bad.finalTargetRaw={...bad.previewStages[0].targetRaw};assert.throws(()=>B.validateBatch(bad,1000,1));}const faster=clone(next);faster.previewStages[0].speedFraction=.15;assert.throws(()=>B.validateBatch(faster,1000,1));
 assert.equal(B.allowedSteps.includes(3),false);assert.equal(B.allowedSteps.includes(-3),false);
});

function compensatedFixture(dose=4,retract=2,wait=0,idle=20){
 const q=ftpRequest(),t=q.ftpTargetRecord,e=name=>({path:'/ftp/'+name,sha256:hash});
 q.expectedRaw.Z=45;q.expectedDriver.Z=45;q.receivingProfile.rawPose.Z=45;q.rawBounds.B={min:-350,max:-150};q.previewStages=[];let at={...q.expectedRaw};
 function add(axis,value,dwell=0){const target={...at,[axis]:value};q.previewStages.push({axis,startRaw:at,targetRaw:target,speedFraction:axis==='B'?.05:1,expandedCommands:['synthetic'],...ev(),...(axis==='B'?{gapEvidence:t.surfaceEvidence,estimatedGapMm:.65+50-at.Z,gapUncertaintyMm:.4,dwellMilliseconds:dwell}:{})});at=target;return q.previewStages.length-1;}
 t.pads.forEach((p,n)=>{delete p.doseStageIndex;if(n)add('X',101);add('Z',50);p.restoreStageIndex=add('B',at.B-retract);p.doseStageIndices=dose===12?[add('B',at.B-6),add('B',at.B-6,200)]:[add('B',at.B-dose,200)];p.retractStageIndex=add('B',at.B+retract,wait);p.liftStageIndex=add('Z',45);});
 const idleIndices=[];for(let i=0;i<idle/20;i++)idleIndices.push(add('B',at.B+20,i===idle/20-1?2000:0));const finalIdleStageIndex=idleIndices[0];q.finalTargetRaw=at;
 const c=t.compensatedSequence={schema:1,protocol:'restore-dose-retract-lift-two-pad',doseDegrees:dose,retractDegrees:retract,dwellMilliseconds:200,maximumElapsedMilliseconds:1000,conditioningFinishedMs:800,finalIdleStageIndex,conditioningReportEvidence:e('conditioning.json'),conditioningLedgerEvidence:e('conditioning-ledger-copy.json'),preparationExperimentEvidence:e('preparation.json'),tipObservationEvidence:e('tip-review.json')};q.previousReportEvidence=c.conditioningReportEvidence;if(wait){c.retractDwellMilliseconds=wait;c.conditioningFinishedMs=200;}if(idle===40){c.idleReliefDegrees=40;c.finalIdleStageIndices=idleIndices;delete c.finalIdleStageIndex;}
 const f=ftpSources(q),rid='32345678-1234-1234-1234-123456789abc';
 let pos={...q.expectedRaw,Z:50,B:-240-retract+20};const ss=[];
 function prior(axis,target,dwell=0){const next={...pos,[axis]:target};ss.push({axis,startRaw:pos,targetRaw:next,dwellMilliseconds:dwell});pos=next;}
 prior('B',-240-retract,200);prior('B',-240,wait);prior('Z',45);
 const rq={id:rid,scope:'contiguous-native-scrap-batch',mode:'wet',sessionId,syringeId:q.syringeId,jvmStartMs:1,liveConfigurationSha256:hash,clearanceReviewEvidence:e('preparation-review.json'),previewStages:ss,finalTargetRaw:pos};
 f.files[c.conditioningReportEvidence.path]={id:rid,request:rq,status:'completed-contiguous-batch-awaiting-observation',controllerPositionVerified:true,uncertainCompletion:false,finishedAt:new Date(800).toISOString(),completedLedgerSha256:hash,afterQuerySnapshot:{raw:pos},stages:ss.map((s,i)=>({...s,index:i,verified:true,finishedAt:new Date(wait?(i===0?100:i===1?200:800):800).toISOString(),...(wait&&i===1?{dwell:{requestedMilliseconds:wait,actualElapsedMilliseconds:wait,stopObserved:false,endedAt:new Date(200+wait).toISOString()}}:{})}))};
 f.files[c.conditioningLedgerEvidence.path]={status:'verified',sessionId,syringeId:q.syringeId,lastVerifiedB:-240,entries:[{status:'verified',batchId:rid,stageIndex:1,targetB:-240,deltaDegrees:retract}]};
 f.files[c.preparationExperimentEvidence.path]={schema:1,scope:'reviewed-scrap-retraction-coupon',mode:'transfer-preparation',retractDegrees:retract,maximumTransferElapsedMilliseconds:1000,conditioningDoseDegrees:20,workRawZ:50,clearanceRawZ:45,dwellMilliseconds:200,...(wait?{retractDwellMilliseconds:wait}:{})};
 f.files[rq.clearanceReviewEvidence.path]={experimentEvidence:c.preparationExperimentEvidence};
 f.files[c.tipObservationEvidence.path]={reviewedBy:'synthetic',reviewedMs:900,capturedMs:850,noLongStrand:true,conditioningReportEvidence:c.conditioningReportEvidence,imageEvidence:e('tip.png')};
 return {q,t,c,f};
}
test('compensated FTP covers every B stage, reserves gross, and verifies ordered low doses',()=>{
 for(const dose of [2,3,4,6,12,20])for(const retract of [2,3,4,6]){const {q,f}=compensatedFixture(dose,retract);B.validateBatch(q,1000,1);FTP.verifySources(q,f.read);let l=B.reserveBatch(ledger(),q,carry());assert.equal(l.totalAbsoluteDegrees,2*dose+4*retract+20);q.previewStages.forEach((s,i)=>{if(s.axis==='B')l=B.markBatchStep(l,q,i,s.targetRaw.B);});assert.equal(B.finishBatch(l,q,true).lastVerifiedB,q.finalTargetRaw.B);}
});
test('compensated FTP rejects unknown protocol, expiry, uncovered B and shifted/mismatched groups',()=>{
 const edits=[x=>x.c.protocol='arbitrary',x=>x.c.doseDegrees=5,x=>x.c.retractDegrees=true,x=>x.c.maximumElapsedMilliseconds=300001,x=>x.c.conditioningFinishedMs=-5000,x=>x.c.conditioningFinishedMs=1001,x=>x.c.dwellMilliseconds=200.5,x=>x.t.pads[0].restoreStageIndex++,x=>x.t.pads[0].doseStageIndices=[0],x=>x.t.pads[1].restoreStageIndex=x.t.pads[0].restoreStageIndex,x=>x.t.pads[0].retractStageIndex++,x=>x.t.pads[0].liftStageIndex++,x=>x.c.finalIdleStageIndex--,x=>x.q.previousReportEvidence=ev(),x=>x.c.conditioningLedgerEvidence.sha256='b'.repeat(64),x=>x.t.pads[0].doseStageIndex=1,x=>x.q.previewStages[x.t.pads[0].restoreStageIndex].gapUncertaintyMm=.3];
 for(const edit of edits){const x=compensatedFixture();edit(x);assert.throws(()=>B.validateBatch(x.q,1000,1));}
 const x=compensatedFixture();assert.throws(()=>FTP.entryTime(x.q,1801),/expired/);
 const y=compensatedFixture();const extra={...y.q.previewStages.at(-1),startRaw:y.q.finalTargetRaw,targetRaw:{...y.q.finalTargetRaw,B:y.q.finalTargetRaw.B+2}};y.q.previewStages.push(extra);y.q.finalTargetRaw=extra.targetRaw;assert.throws(()=>B.validateBatch(y.q,1000,1));
});
test('compensated FTP rejects uncertain preparation, extra idle, stale B, unverified tail and unbound tip evidence',()=>{
 const edits=[x=>x.f.files[x.c.conditioningReportEvidence.path].uncertainCompletion=true,x=>x.f.files[x.c.conditioningReportEvidence.path].controllerPositionVerified=false,x=>x.f.files[x.c.conditioningReportEvidence.path].stages[1].verified=false,x=>x.f.files[x.c.conditioningReportEvidence.path].afterQuerySnapshot.raw.B++,x=>x.f.files[x.c.conditioningReportEvidence.path].finishedAt=new Date(799).toISOString(),x=>x.f.files[x.c.conditioningLedgerEvidence.path].entries[0].deltaDegrees=20,x=>x.f.files[x.c.preparationExperimentEvidence.path].mode='coupon',x=>x.f.files[x.c.preparationExperimentEvidence.path].maximumTransferElapsedMilliseconds=2000,x=>x.f.files['/ftp/preparation-review.json'].experimentEvidence=ev(),x=>x.f.files[x.c.tipObservationEvidence.path].noLongStrand=false,x=>x.f.files[x.c.tipObservationEvidence.path].reviewedMs=799,x=>x.f.files[x.c.tipObservationEvidence.path].capturedMs=799];
 for(const edit of edits){const x=compensatedFixture();edit(x);assert.throws(()=>FTP.verifySources(x.q,x.f.read));}
 const x=compensatedFixture(),r=x.f.files[x.c.conditioningReportEvidence.path],ss=r.request.previewStages,at=ss.at(-1).targetRaw,extra={axis:'B',startRaw:at,targetRaw:{...at,B:at.B+20}};ss.push(extra);r.stages.push({...extra,index:3,verified:true});assert.throws(()=>FTP.verifySources(x.q,x.f.read),/must end/);
});

test('compensated FTP binds retraction wait and double idle while conserving entry B and charging every stage',()=>{
 for(const wait of [0,200,500])for(const idle of [20,40]){
  const {q,t,c,f}=compensatedFixture(4,2,wait,idle);B.validateBatch(q,1000,1);FTP.verifySources(q,f.read);
  const bs=q.previewStages.filter(s=>s.axis==='B');assert.deepEqual(bs.map(s=>[s.targetRaw.B-s.startRaw.B,s.dwellMilliseconds]),[[-2,0],[-4,200],[2,wait],[-2,0],[-4,200],[2,wait],...(idle===40?[[20,0],[20,2000]]:[[20,2000]])]);
  assert.equal(q.finalTargetRaw.B,q.expectedRaw.B-8+idle);let l=B.reserveBatch(ledger(),q,carry());assert.equal(l.totalAbsoluteDegrees,16+idle);const failed=B.finishBatch(l,q,false);assert.equal(failed.totalAbsoluteDegrees,16+idle);assert.throws(()=>B.reserveBatch(failed,q,carry()));
  q.previewStages.forEach((s,i)=>{if(s.axis==='B')l=B.markBatchStep(l,q,i,s.targetRaw.B);});assert.equal(B.finishBatch(l,q,true).lastVerifiedB,q.finalTargetRaw.B);
 }
});
test('compensated FTP rejects undeclared waits, malformed idle groups and mismatched actual conditioning wait',()=>{
 const edits=[x=>x.c.retractDwellMilliseconds=1000,x=>x.c.retractDwellMilliseconds=true,x=>x.c.idleReliefDegrees=60,x=>x.c.finalIdleStageIndex=x.c.finalIdleStageIndices[0],x=>x.c.finalIdleStageIndices.pop(),x=>x.c.finalIdleStageIndices.reverse(),x=>x.q.previewStages[x.c.finalIdleStageIndices[0]].dwellMilliseconds=2000,x=>x.q.previewStages[x.c.finalIdleStageIndices[1]].dwellMilliseconds=0,x=>x.q.previewStages[x.t.pads[0].retractStageIndex].dwellMilliseconds=0,x=>x.q.previewStages[x.t.pads[0].restoreStageIndex].dwellMilliseconds=500];
 for(const edit of edits){const x=compensatedFixture(4,2,500,40);edit(x);assert.throws(()=>B.validateBatch(x.q,1000,1));}
 const sourceEdits=[x=>delete x.f.files[x.c.preparationExperimentEvidence.path].retractDwellMilliseconds,x=>x.f.files[x.c.conditioningReportEvidence.path].request.previewStages[1].dwellMilliseconds=200,x=>delete x.f.files[x.c.conditioningReportEvidence.path].stages[1].dwell,x=>x.f.files[x.c.conditioningReportEvidence.path].stages[1].dwell.actualElapsedMilliseconds=499,x=>x.f.files[x.c.conditioningReportEvidence.path].stages[1].dwell.stopObserved=true,x=>x.f.files[x.c.conditioningReportEvidence.path].stages[1].dwell.endedAt=new Date(699).toISOString(),x=>x.f.files[x.c.tipObservationEvidence.path].capturedMs=700];
 for(const edit of sourceEdits){const x=compensatedFixture(4,2,500,40);edit(x);assert.throws(()=>FTP.verifySources(x.q,x.f.read));}
});

function affineFixture(){
 const q=ftpRequest(),f=ftpSources(q),t=q.ftpTargetRecord,reg=f.files[t.registrationEvidence.path],e=name=>({path:'/ftp/'+name,sha256:hash});
 reg.scope='offline-fresh-ftp-three-fiducial-affine-with-held-out-pad-checks';delete reg.independentFID3Check;reg.fittedFiducials=['FID1','FID2','FID3'];reg.session.fixedRawZAB=[50,720,-240];reg.session.topCameraZRotation=[0,0];reg.transformFromThreeFiducials={model:'three-fiducial-affine',matrix:[[1,0],[0,1]],translationMm:[0,0]};
 function proof(name,xy){const report={id:name,status:'completed-contiguous-air-batch-awaiting-observation',controllerPositionVerified:true,uncertainCompletion:false,finishedAt:new Date(900).toISOString(),request:{id:name,jvmStartMs:1,liveConfigurationSha256:hash},afterImages:{top:{path:'top.png'}},afterQuerySnapshot:{raw:{X:xy[0],Y:xy[1],Z:50,A:720,B:-240},nativePoses:{top:{x:xy[0],y:xy[1],z:0,rotation:0}}}};f.files[e(name+'/report.json').path]=report;return {report:e(name+'/report.json'),image:e(name+'/top.png')};}
 reg.resistorPadMachineXYTargets.forEach(p=>p.designXYMm=p.machineXYMm.slice());
 ['FID1','FID2','FID3'].forEach((k,i)=>{const xy=[[0,0],[50,0],[0,50]][i];Object.assign(reg.measurements[k],proof(k,xy),{designXYMm:xy,measuredTopCameraXYMm:xy});});
 reg.imageJacobianEvidence=e('jacobian.json');const j={schema:1,scope:'measured-top-camera-image-jacobian',session:{jvmStartMs:1,liveConfigurationSha256:hash},fixedRawZAB:[50,720,-240],reviewedBy:'test',reviewedMs:925,pixelShiftPerCameraMm:[[100,0],[0,-100]],sourceMeasurements:[]};
 [[0,0],[1,0],[1,1]].forEach((xy,i)=>j.sourceMeasurements.push({...proof('J'+i,xy),rawXY:xy,centerPixels:[127.5+100*xy[0],127.5-100*xy[1]]}));f.files[reg.imageJacobianEvidence.path]=j;
 reg.independentHeldOutPadChecks=[];t.padChecks=[];
 ['R1.2','R16.1','R40.1'].forEach(padId=>{const xy=reg.resistorPadMachineXYTargets.find(p=>p.padId===padId).machineXYMm,p=proof(padId,xy);reg.independentHeldOutPadChecks.push({...p,padId,padIdentityReviewed:true,centerMeasurementReviewed:true,imageSizePixels:[256,256],observedCenterPixel:[127.5,127.5],imageCenterPixel:[127.5,127.5],cameraXYMm:xy,measuredPadXYMm:xy,predictedMachineXYMm:xy,imageCenterErrorPx:0,residualMm:0});t.padChecks.push({reference:padId.split('.')[0],padId,reviewedAligned:true,reportEvidence:p.report,imageEvidence:p.image});});f.files[q.ftpTargetEvidence.path]=clone(t);return {q,f,reg,j};
}
test('affine native admission recomputes fit, measured Jacobian and three held-out pads',()=>{const x=affineFixture();FTP.verifySources(x.q,x.f.read);});
test('affine native admission rejects candidate, fake independence, skew, changed J and held-out proof',()=>{
 for(const edit of [x=>x.reg.scope='offline-fresh-ftp-three-fiducial-affine-candidate',x=>x.reg.independentFID3Check={residualMm:0},x=>x.reg.transformFromThreeFiducials.matrix[0][1]=.008,x=>x.j.pixelShiftPerCameraMm[0][0]=99,x=>x.reg.independentHeldOutPadChecks.pop(),x=>x.reg.independentHeldOutPadChecks[0].observedCenterPixel[0]+=9,x=>x.reg.independentHeldOutPadChecks[0].centerMeasurementReviewed=false,x=>x.f.files['/ftp/R1.2/report.json'].id='FID1',x=>x.reg.resistorPadMachineXYTargets[0].designXYMm=[999,999]]){const x=affineFixture();edit(x);assert.throws(()=>FTP.verifySources(x.q,x.f.read));}
});
test('compensated decimal Z keeps authored gap and only tolerates derived floating arithmetic',()=>{
 const {q,t}=compensatedFixture(4,2,500,40),z=v=>v===50?58.3:v===45?53.4:v;
 t.surface={rawZ:58.3,estimatedGapMm:.4,gapUncertaintyMm:.3};t.pads.forEach(p=>p.rawPose.Z=58.3);q.xyClearanceRawZ=53.4;q.rawBounds.Z={min:53.4,max:58.3};q.expectedRaw.Z=q.expectedDriver.Z=53.4;q.finalTargetRaw.Z=53.4;
 q.previewStages.forEach(s=>{s.startRaw={...s.startRaw,Z:z(s.startRaw.Z)};s.targetRaw={...s.targetRaw,Z:z(s.targetRaw.Z)};if(s.axis==='B'){s.estimatedGapMm=.4+(58.3-s.startRaw.Z);s.gapUncertaintyMm=.3;}});
 FTP.validate(q,1000);q.previewStages[t.pads[0].doseStageIndices[0]].estimatedGapMm+=2e-9;assert.throws(()=>FTP.validate(q,1000),/gap differs/);
 t.surface.estimatedGapMm=.399;assert.throws(()=>FTP.validate(q,1000),/positive gap/);
});
const Inline=require('./ftp-inline-conditioning.cjs');
function inlineFixture(){
 const {q,t,c}=compensatedFixture(4,2,500,40);q.scope=Inline.scope(false);const suffix=clone(q.previewStages),initial={X:96,Y:200,Z:50,A:720,B:-240};q.expectedRaw=initial;q.expectedDriver=clone(initial);q.receivingProfile.rawPose=clone(initial);q.rawBounds.X.min=95;q.rawBounds.B.min=-400;
 const e={schema:1,scope:'reviewed-scrap-retraction-coupon',mode:'transfer-preparation',startRaw:clone(initial),workRawZ:50,clearanceRawZ:45,primeDegrees:40,preWipeReliefDegrees:2,conditioningDoseDegrees:20,doseDegrees:4,retractDegrees:2,dwellMilliseconds:200,conditioningDwellMilliseconds:2000,retractDwellMilliseconds:500,targetsXY:[{X:98,Y:200},{X:99,Y:200}]};
 ['conditioningReportEvidence','conditioningLedgerEvidence','preparationExperimentEvidence','tipObservationEvidence','conditioningFinishedMs','maximumElapsedMilliseconds'].forEach(k=>delete c[k]);
 let at=clone(initial);const pre=[];function add(axis,target,dwell,wipe){const next={...at,[axis]:target};pre.push({axis,startRaw:at,targetRaw:next,speedFraction:axis==='B'?.05:1,expandedCommands:['synthetic'],...ev(),...(axis==='B'?{gapEvidence:q.clearanceReviewEvidence,estimatedGapMm:.65,gapUncertaintyMm:.4,dwellMilliseconds:dwell}:{}),...(wipe?{wipeReview:true,wipeReviewEvidence:q.clearanceReviewEvidence,estimatedGapMm:.65,gapUncertaintyMm:.4}:{})});at=next;}
 add('B',-260,0);add('B',-280,2000);add('B',-278,1000);add('X',98,0,true);add('Z',45);add('X',99);add('Z',50);add('B',-298,2000);add('B',-296,500);add('Z',45);const count=pre.length;
 t.inlineConditioning={schema:1,protocol:'scrap-condition-transit-two-pad',experiment:e,experimentEvidence:ev(),maximumTransferMilliseconds:15000,prefixStageCount:count,retractionStageIndex:count-2,liftStageIndex:count-1};add('X',100);
 const shift=pre.length,delta=at.B+240;suffix.forEach(s=>{s.startRaw.B+=delta;s.targetRaw.B+=delta;});t.pads.forEach(p=>{p.restoreStageIndex+=shift;p.doseStageIndices=p.doseStageIndices.map(i=>i+shift);p.retractStageIndex+=shift;p.liftStageIndex+=shift;});c.finalIdleStageIndices=c.finalIdleStageIndices.map(i=>i+shift);q.previewStages=pre.concat(suffix);q.finalTargetRaw=clone(q.previewStages.at(-1).targetRaw);return {q,t,c};
}
test('inline conditioning shares one reservation and exact two-pad suffix',()=>{const {q}=inlineFixture();B.validateBatch(q,1000,1);let l=B.reserveBatch(ledger(),q,carry());assert.equal(l.totalAbsoluteDegrees,120);q.previewStages.forEach((s,i)=>{if(s.axis==='B')l=B.markBatchStep(l,q,i,s.targetRaw.B);});assert.equal(B.finishBatch(l,q,true).lastVerifiedB,q.finalTargetRaw.B);});
test('inline rejects changed prefix, scope downgrade, extra B and excessive stage count',()=>{for(const edit of [q=>q.previewStages[0].dwellMilliseconds=500,q=>q.ftpTargetRecord.inlineConditioning.maximumTransferMilliseconds=16000,q=>q.ftpTargetRecord.inlineConditioning.experiment.targetsXY[0].X=99,q=>q.scope=FTP.scope(false),q=>q.ftpTargetRecord.compensatedSequence.conditioningFinishedMs=800,q=>q.ftpTargetRecord.inlineConditioning.prefixStageCount++,q=>q.previewStages=Array(41).fill(q.previewStages[0])]){const {q}=inlineFixture();edit(q);assert.throws(()=>B.validateBatch(q,1000,1));}});
test('inline 15-second entry requires actual completed prefix and retract dwell',()=>{const {q}=inlineFixture(),x=q.ftpTargetRecord.inlineConditioning,records=q.previewStages.slice(0,x.prefixStageCount).map((s,i)=>({...clone(s),index:i,verified:true,finishedAt:new Date(1000).toISOString()}));records[x.retractionStageIndex].dwell={requestedMilliseconds:500,actualElapsedMilliseconds:501,stopObserved:false};assert.equal(Inline.entry(q,16000,records),15000);assert.throws(()=>Inline.entry(q,16001,records),/15 seconds/);assert.throws(()=>Inline.entry(q,999,records));records[0].verified=false;assert.throws(()=>Inline.entry(q,2000,records),/actually verified/);records[0].verified=true;records[x.retractionStageIndex].dwell.stopObserved=true;assert.throws(()=>Inline.entry(q,2000,records),/dwell/);});
function revalidatedFixture(){const x=affineFixture(),{q,f,reg}=x,t=q.ftpTargetRecord;t.reviewedMs=7200950;const e=name=>({path:'/ftp/'+name,sha256:hash});t.registrationRevalidationEvidence=e('revalidation.json');const v={schema:1,scope:'ftp-registration-revalidation',originalRegistrationEvidence:t.registrationEvidence,reviewedBy:'test',reviewedMs:7200940,boardUnmovedSinceRegistration:true,measurements:{}};['FID1','FID2','FID3'].forEach(k=>{const p=e('new-'+k+'/report.json'),im=e('new-'+k+'/top.png'),r=clone(f.files['/ftp/'+k+'/report.json']);r.id=r.request.id='new-'+k;r.status='completed-camera-survey-awaiting-image-review';r.finishedAt=new Date(7200900).toISOString();r.afterQuerySnapshot.raw.B=-999;f.files[p.path]=r;v.measurements[k]={report:p,image:im,fiducialIdentityReviewed:true,centeredInTopImageReviewed:true,observedCenterPixel:[127.5,127.5],imageSizePixels:[256,256]};});f.files[t.registrationRevalidationEvidence.path]=v;f.files[q.ftpTargetEvidence.path]=clone(t);return {...x,v};}
test('fresh three-fiducial no-refit revalidation retains old registration/J bytes and dates',()=>{const x=revalidatedFixture(),old=clone(x.reg);FTP.verifySources(x.q,x.f.read);assert.deepEqual(x.reg,old);delete x.q.ftpTargetRecord.registrationRevalidationEvidence;x.f.files[x.q.ftpTargetEvidence.path]=clone(x.q.ftpTargetRecord);assert.throws(()=>FTP.verifySources(x.q,x.f.read),/one hour/);});
test('registration revalidation rejects stale, shifted, uncentered or different-frame observations',()=>{for(const edit of [x=>{x.f.files['/ftp/new-FID1/report.json'].id=x.f.files['/ftp/new-FID1/report.json'].request.id='FID1';},x=>x.f.files['/ftp/new-FID1/report.json'].afterQuerySnapshot.nativePoses.top.x+=.081,x=>x.v.measurements.FID3.observedCenterPixel[0]+=2.01,x=>x.v.measurements.FID2.fiducialIdentityReviewed=false,x=>x.f.files['/ftp/new-FID2/report.json'].afterQuerySnapshot.raw.B++,x=>x.f.files['/ftp/new-FID1/report.json'].finishedAt=new Date(6000000).toISOString(),x=>x.v.originalRegistrationEvidence={path:'/wrong',sha256:hash},x=>x.v.boardUnmovedSinceRegistration=false]){const x=revalidatedFixture();edit(x);assert.throws(()=>FTP.verifySources(x.q,x.f.read));}});
test('inline source binding accepts XYZA profile while experiment and barrier retain exact B',()=>{const {q,t}=inlineFixture(),e=name=>({path:'/inline/'+name,sha256:hash});q.clearanceReviewEvidence=e('review.json');q.profileEvidence=e('profile.json');t.inlineConditioning.experimentEvidence=e('experiment.json');q.previewStages.slice(0,t.inlineConditioning.prefixStageCount).forEach(s=>{if(s.axis==='B')s.gapEvidence=q.clearanceReviewEvidence;if(s.wipeReview)s.wipeReviewEvidence=q.clearanceReviewEvidence;});const pose=clone(q.expectedRaw);delete pose.B;const profile={rawPose:pose,measurementEvidence:q.clearanceReviewEvidence,estimatedGapMm:.65,gapUncertaintyMm:.4,jvmStartMs:1,liveConfigurationSha256:hash,provenance:'commissioning-provisional',precisionCalibrated:false,flowCalibrated:false},files={'/inline/profile.json':profile,'/inline/review.json':{experimentEvidence:t.inlineConditioning.experimentEvidence},'/inline/experiment.json':clone(t.inlineConditioning.experiment)};Inline.sources(q,e=>files[e.path]);profile.rawPose.B=-999;assert.throws(()=>Inline.sources(q,e=>files[e.path]),/binding/);delete profile.rawPose.B;files['/inline/experiment.json'].startRaw.B--;assert.throws(()=>Inline.sources(q,e=>files[e.path]),/binding/);});
test('inline permits separately reviewed prefix clearance then only common FTP transit plane',()=>{const {q,t,c}=inlineFixture(),n=t.inlineConditioning.prefixStageCount,pre=q.previewStages.slice(0,n),rest=q.previewStages.slice(n);q.xyClearanceRawZ=44.95;q.rawBounds.Z.min=44.95;t.surface.rawZ=49.85;t.pads.forEach(p=>p.rawPose.Z=49.85);rest.forEach(s=>{s.startRaw={...s.startRaw,Z:s.startRaw.Z===45?44.95:49.85};s.targetRaw={...s.targetRaw,Z:s.targetRaw.Z===45?44.95:49.85};if(s.axis==='B')s.estimatedGapMm=.65+(49.85-s.startRaw.Z);});const from=clone(pre.at(-1).targetRaw),to={...from,Z:44.95};q.previewStages=pre.concat([{axis:'Z',startRaw:from,targetRaw:to,speedFraction:1,expandedCommands:['synthetic'],...ev()}],rest);t.pads.forEach(p=>{p.restoreStageIndex++;p.doseStageIndices=p.doseStageIndices.map(i=>i+1);p.retractStageIndex++;p.liftStageIndex++;});c.finalIdleStageIndices=c.finalIdleStageIndices.map(i=>i+1);q.finalTargetRaw=clone(q.previewStages.at(-1).targetRaw);B.validateBatch(q,1000,1);const lift=q.previewStages[n-1];assert.equal(B.stopDecision(q,lift.startRaw,lift,true),'reviewed-clearance-lift');assert.equal(B.stopDecision(q,lift.targetRaw,lift,true),'stop-at-clearance');assert.equal(B.stopDecision(q,q.previewStages[n-2].startRaw,q.previewStages[n-2],true),'stop-hold-position');q.previewStages[n+1].startRaw.Z=45;assert.throws(()=>B.validateBatch(q,1000,1));});

test('explicit revalidation lasts one hour while source age is measured at its original review',()=>{const x=revalidatedFixture(),t=x.q.ftpTargetRecord; t.reviewedMs=x.v.reviewedMs+3600000;x.f.files[x.q.ftpTargetEvidence.path]=clone(t);FTP.verifySources(x.q,x.f.read);t.reviewedMs++;x.f.files[x.q.ftpTargetEvidence.path]=clone(t);assert.throws(()=>FTP.verifySources(x.q,x.f.read),/revalidation required/);});
function groupFixture(dose=4,retract=2,conditioningDose=20){
 const base=inlineFixture(),q=clone(base.q),t=q.ftpTargetRecord,c=t.compensatedSequence,Group=require('./ftp-pad-group.cjs');q.scope=Group.scope(false);t.scope='ftp-eight-pad-commissioning-targets';t.inlineConditioning.protocol='scrap-condition-transit-eight-pad';c.protocol='restore-dose-retract-lift-eight-pad';c.doseDegrees=dose;t.pairReferences=['R1','R2','R3','R4'];t.pads=[];
 q.previewStages=q.previewStages.slice(0,t.inlineConditioning.prefixStageCount);if(conditioningDose!==20){t.inlineConditioning.experiment.conditioningDoseDegrees=conditioningDose;const i=t.inlineConditioning.retractionStageIndex-1,delta=20-conditioningDose;q.previewStages[i].targetRaw.B+=delta;for(let j=i+1;j<q.previewStages.length;j++){q.previewStages[j].startRaw.B+=delta;q.previewStages[j].targetRaw.B+=delta;}}if(retract!==2){c.retractDegrees=retract;t.inlineConditioning.experiment.retractDegrees=retract;const i=t.inlineConditioning.retractionStageIndex,delta=retract-2;q.previewStages[i].targetRaw.B+=delta;q.previewStages[i+1].startRaw.B+=delta;q.previewStages[i+1].targetRaw.B+=delta;}if(conditioningDose===12){const x=t.inlineConditioning,i=x.retractionStageIndex-1,old=q.previewStages[i],first=clone(old),second=clone(old);first.targetRaw.B=first.startRaw.B-6;first.dwellMilliseconds=0;second.startRaw=clone(first.targetRaw);q.previewStages.splice(i,1,first,second);x.prefixStageCount++;x.retractionStageIndex++;x.liftStageIndex++;}let at=clone(q.previewStages.at(-1).targetRaw);
 function add(axis,value,dwell){if(value===at[axis])return;const target={...at,[axis]:value};q.previewStages.push({axis,startRaw:at,targetRaw:target,speedFraction:axis==='B'?.05:1,expandedCommands:['synthetic'],...ev(),...(axis==='B'?{gapEvidence:t.surfaceEvidence,estimatedGapMm:t.surface.estimatedGapMm+(t.surface.rawZ-at.Z),gapUncertaintyMm:t.surface.gapUncertaintyMm,dwellMilliseconds:dwell}:{})});at=target;}
 for(let n=0;n<8;n++){const p={padId:t.pairReferences[Math.floor(n/2)]+'.'+(n%2+1),rawPose:{X:100+n*.5,Y:200+(n%2),Z:t.surface.rawZ,A:720},padAvailableReviewed:true,padIdentityReviewed:true,availabilityImageEvidence:ev(),availabilityReportEvidence:ev(),availabilityCapturedMs:900};add('X',p.rawPose.X);add('Y',p.rawPose.Y);add('Z',p.rawPose.Z);p.restoreStageIndex=q.previewStages.length;add('B',at.B-retract,0);p.doseStageIndices=[];const parts=dose===12?[6,6]:[dose];parts.forEach((v,i)=>{p.doseStageIndices.push(q.previewStages.length);add('B',at.B-v,i===parts.length-1?200:0);});p.retractStageIndex=q.previewStages.length;add('B',at.B+retract,500);p.liftStageIndex=q.previewStages.length;add('Z',q.xyClearanceRawZ);t.pads.push(p);}
 c.finalIdleStageIndices=[q.previewStages.length,q.previewStages.length+1];add('B',at.B+20,0);add('B',at.B+20,2000);q.finalTargetRaw=clone(at);
 // Anchor the fixture to the immutable original 120-degree history.
 q.expectedRaw.B-=44;q.expectedDriver.B-=44;q.receivingProfile.rawPose.B-=44;t.inlineConditioning.experiment.startRaw.B-=44;q.previewStages.forEach(s=>{s.startRaw={...s.startRaw,B:s.startRaw.B-44};s.targetRaw={...s.targetRaw,B:s.targetRaw.B-44};});q.finalTargetRaw.B-=44;q.rawBounds.B.min=-500;
 const anchor=stoppedBatchFixture().anchor,ar={id:anchor.entries.at(-1).requestId,request:{id:anchor.entries.at(-1).requestId,sessionId,jvmStartMs:1,liveConfigurationSha256:hash},status:'completed-commissioning-stroke-awaiting-observation',uncertainCompletion:false,completedLedgerSha256:hash,finishedAt:new Date(0).toISOString()},record={schema:1,sessionId,syringeId:'synthetic',originalCarryoverSha256:hash,anchorLedgerSha256:hash,anchorGrossDegrees:120,anchorB:-284,newMaximumAbsoluteDegrees:2400,reviewedAt:new Date(500).toISOString(),reviewedBy:'synthetic',reason:'Bounded synthetic eight-pad preservation test',anchorLedgerEvidence:ev(),anchorReportEvidence:ev()};q.budgetAmendmentEvidence={...record,...ev()};return {q,t,c,anchor,context:{record,anchorLedger:anchor,anchorReport:ar}};
}
test('eight-pad group reserves one charged history and verifies every B in order',()=>{
 for(const dose of [4,6]){const {q,anchor,context}=groupFixture(dose);B.validateBatch(q,1000,1);assert.ok(q.previewStages.length>40&&q.previewStages.length<=80);const gross=q.previewStages.filter(s=>s.axis==='B').reduce((v,s)=>v+Math.abs(s.targetRaw.B-s.startRaw.B),0);assert.equal(gross,dose===4?168:184);let l=B.reserveBatch(anchor,q,carry(),context);assert.equal(l.totalAbsoluteDegrees,120+gross);assert.deepEqual(l.entries.slice(0,anchor.entries.length),anchor.entries);assert.ok(l.entries.slice(anchor.entries.length).every(e=>e.batchScope===q.scope));const indices=q.previewStages.flatMap((s,i)=>s.axis==='B'?[i]:[]);assert.throws(()=>B.markBatchStep(l,q,indices[1],q.previewStages[indices[1]].targetRaw.B));const fault=B.finishBatch(l,q,false);assert.equal(fault.totalAbsoluteDegrees,120+gross);assert.throws(()=>B.reserveBatch(fault,q,carry(),context));q.previewStages.forEach((s,i)=>{if(s.axis==='B')l=B.markBatchStep(l,q,i,s.targetRaw.B);});l=B.finishBatch(l,q,true);assert.equal(l.lastVerifiedB,q.finalTargetRaw.B);
 const terminal={id:q.id,request:{id:q.id},status:'completed-contiguous-batch-awaiting-observation',uncertainCompletion:false,completedLedgerSha256:hash,finishedAt:new Date(1000).toISOString()};B.validatePreviousReport(terminal,l,hash,1001);
 const next=request();next.id='22345678-1234-1234-1234-123456789abc';next.expectedRaw.B=next.expectedDriver.B=l.lastVerifiedB;next.previewStages[0].startRaw=clone(next.expectedRaw);next.previewStages[0].targetRaw={...next.expectedRaw,B:l.lastVerifiedB-6};next.finalTargetRaw=clone(next.previewStages[0].targetRaw);next.rawBounds.B={min:-500,max:-200};next.budgetAmendmentEvidence=clone(q.budgetAmendmentEvidence);assert.equal(B.reserveBatch(l,next,carry(),context).totalAbsoluteDegrees,l.totalAbsoluteDegrees+6);assert.throws(()=>B.reserveBatch(l,{...next,id:q.id},carry(),context),/replay/);
 for(const edit of [e=>delete e.batchScope,e=>e.batchScope='unknown',e=>e.requestId='unrelated']){const bad=clone(l),e=bad.entries.find(e=>e.stageIndex>=40);assert.ok(e);edit(e);assert.throws(()=>B.reserveBatch(bad,next,carry(),context),/Malformed/);}
 }
});
test('application restart permits an explicitly listed amendment-anchor JVM only with same session and configuration',()=>{const {q,anchor,context}=groupFixture(4);q.jvmStartMs=2;context.anchorReport.request.jvmStartMs=1;q.applicationRestartEvidence={sessionId:q.sessionId,newJvmStartMs:2,liveConfigurationSha256:q.liveConfigurationSha256,allowedJvmStartMs:[1,2]};assert.doesNotThrow(()=>B.validateBudgetAmendment(q,context.record,anchor,context.anchorReport,anchor,carry()));for(const edit of [x=>x.applicationRestartEvidence.allowedJvmStartMs=[2],x=>x.applicationRestartEvidence.sessionId='other',x=>x.applicationRestartEvidence.liveConfigurationSha256='f'.repeat(64),x=>x.applicationRestartEvidence.newJvmStartMs=1]){const bad=clone(q);edit(bad);assert.throws(()=>B.validateBudgetAmendment(bad,context.record,anchor,context.anchorReport,anchor,carry()));}});
test('manual-home continuity permits only an exact historical ledger-prefix amendment anchor',()=>{const {q,anchor,context}=groupFixture(4),oldConfig='b'.repeat(64),anchorJvm=context.anchorReport.request.jvmStartMs;q.jvmStartMs=2;q.previousLedgerSha256='e'.repeat(64);context.anchorReport.request.liveConfigurationSha256=oldConfig;const proof={scope:'manual-home-ledger-anchor-continuity',sessionId:q.sessionId,syringeId:q.syringeId,currentLedgerSha256:q.previousLedgerSha256,currentJvmStartMs:q.jvmStartMs,currentConfigurationSha256:q.liveConfigurationSha256,oldConfigurationSha256:oldConfig,historicalAnchorReports:[{ledgerEvidence:context.record.anchorLedgerEvidence,reportEvidence:context.record.anchorReportEvidence,jvmStartMs:anchorJvm}]};assert.doesNotThrow(()=>B.validateBudgetAmendment(q,context.record,anchor,context.anchorReport,anchor,carry(),proof));const drift={...proof,currentLedgerSha256:'f'.repeat(64)};assert.throws(()=>B.validateBudgetAmendment(q,context.record,anchor,context.anchorReport,anchor,carry(),drift));const wrong={...proof,historicalAnchorReports:[]};assert.throws(()=>B.validateBudgetAmendment(q,context.record,anchor,context.anchorReport,anchor,carry(),wrong));});
test('eight-pad identity, all-B coverage, scope cap and cooperative stop stay bounded',()=>{
 for(const edit of [q=>q.ftpTargetRecord.pads[2].padId='R1.1',q=>q.ftpTargetRecord.pads[0].padAvailableReviewed=false,q=>q.ftpTargetRecord.compensatedSequence.doseDegrees=20,q=>q.previewStages[15].wipeReview=true,q=>q.scope=Inline.scope(false),q=>q.previewStages=Array(81).fill(q.previewStages[0]),q=>q.ftpTargetRecord.pads[7].doseStageIndices=[q.ftpTargetRecord.pads[6].doseStageIndices[0]]]){const {q}=groupFixture();edit(q);assert.throws(()=>B.validateBatch(q,1000,1));}
 const {q,t}=groupFixture(),p=t.pads[7],lift=q.previewStages[p.liftStageIndex],retract=q.previewStages[p.retractStageIndex];assert.equal(B.stopDecision(q,retract.startRaw,retract,true),'stop-hold-position');assert.equal(B.stopDecision(q,lift.startRaw,lift,true),'reviewed-clearance-lift');assert.equal(B.stopDecision(q,lift.targetRaw,q.previewStages[p.liftStageIndex+1],true),'stop-at-clearance');
});
function cleanupFixture(amount=6){const q=ftpRequest(),t=q.ftpTargetRecord,C=require('./ftp-one-pad-cleanup.cjs');q.scope=C.scope(false);t.scope='ftp-one-pad-cleanup-targets';t.boardCleaned=false;t.padsAvailable=false;delete t.padAvailabilityImage;t.pads=t.pads.slice(0,1);const p=t.pads[0];delete p.doseStageIndex;Object.assign(p,{aspirationStageIndex:0,liftStageIndex:1,padIdentityReviewed:true,defectReviewed:true,defectCapturedMs:900,defectReportEvidence:t.padChecks[0].reportEvidence,defectImageEvidence:t.padChecks[0].imageEvidence});t.cleanupSequence={schema:1,protocol:'positive-B-aspiration-lift-one-pad',retractDegrees:amount,dwellMilliseconds:2000};q.previewStages=q.previewStages.slice(0,2);q.previewStages[0].targetRaw={...q.expectedRaw,B:q.expectedRaw.B+amount};q.previewStages[0].dwellMilliseconds=2000;q.previewStages[1].startRaw=clone(q.previewStages[0].targetRaw);q.previewStages[1].targetRaw={...q.previewStages[1].startRaw,Z:q.xyClearanceRawZ};q.finalTargetRaw=clone(q.previewStages[1].targetRaw);return q;}
test('registered cleanup admits one positive B, preserves source guards, charges faults and ordered verification',()=>{for(const amount of [6,20]){const q=cleanupFixture(amount);B.validateBatch(q,1000,1);const f=ftpSources(q);FTP.verifySources(q,f.read);let l=B.reserveBatch(ledger(),q,carry());assert.equal(l.totalAbsoluteDegrees,amount);assert.equal(B.finishBatch(l,q,false).totalAbsoluteDegrees,amount);assert.throws(()=>B.finishBatch(l,q,true));l=B.finishBatch(B.markBatchStep(l,q,0,q.finalTargetRaw.B),q,true);assert.equal(l.lastVerifiedB,-240+amount);const shifted={...clone(q),expectedRaw:{...q.expectedRaw,B:l.lastVerifiedB}};assert.throws(()=>B.reserveBatch(l,shifted,carry()));f.files[q.ftpTargetRecord.surfaceEvidence.path].surface={...q.ftpTargetRecord.surface,rawZ:51};assert.throws(()=>FTP.verifySources(q,f.read));}});
test('cleanup cannot use scrap/dose scope, forward extrusion, deeper Z, extra B or low-XY wipe',()=>{
 for(const edit of [q=>q.scope='contiguous-native-scrap-batch',q=>q.scope=FTP.scope(false),q=>q.previewStages[0].targetRaw.B=-246,q=>q.previewStages[1].targetRaw.Z=44,q=>q.previewStages.push(clone(q.previewStages[0])),q=>q.ftpTargetRecord.pads[0].defectReviewed=false]){const q=cleanupFixture();edit(q);assert.throws(()=>B.validateBatch(q,1000,1));}
 const q=cleanupFixture(),a=clone(q.expectedRaw),b={...a,X:a.X+1},s=(start,target)=>({axis:'X',startRaw:start,targetRaw:target,speedFraction:1,expandedCommands:['synthetic'],...ev(),wipeReview:true,wipeReviewEvidence:ev(),estimatedGapMm:.65,gapUncertaintyMm:.4});q.previewStages.unshift(s(a,b),s(b,a));q.ftpTargetRecord.pads[0].aspirationStageIndex=2;q.ftpTargetRecord.pads[0].liftStageIndex=3;assert.throws(()=>B.validateBatch(q,1000,1),/forbids low XY/);
});

test('eight-pad1000ms dwell binds each exact forward stage without changing other waits or gross',()=>{const {q,t,c,anchor,context}=groupFixture(6);c.dwellMilliseconds=1000;t.pads.forEach(p=>q.previewStages[p.doseStageIndices[0]].dwellMilliseconds=1000);B.validateBatch(q,1000,1);assert.equal(B.reserveBatch(anchor,q,carry(),context).totalAbsoluteDegrees,304);assert.equal(q.previewStages[t.pads[0].retractStageIndex].dwellMilliseconds,500);assert.equal(q.previewStages[c.finalIdleStageIndices[1]].dwellMilliseconds,2000);q.previewStages[t.pads[3].doseStageIndices[0]].dwellMilliseconds=200;assert.throws(()=>B.validateBatch(q,1000,1),/amount\/dwell/);});

test('eight-pad20degree2000ms preserves one-stage coverage and full gross charge',()=>{const {q,t,c,anchor,context}=groupFixture(20);const n=q.previewStages.length;q.rawBounds.B.min=Math.min(q.expectedRaw.B,...q.previewStages.map(s=>s.targetRaw.B));c.dwellMilliseconds=2000;t.pads.forEach(p=>{assert.equal(p.doseStageIndices.length,1);q.previewStages[p.doseStageIndices[0]].dwellMilliseconds=2000;});B.validateBatch(q,1000,1);assert.equal(B.reserveBatch(anchor,q,carry(),context).totalAbsoluteDegrees,416);assert.equal(n,groupFixture(6).q.previewStages.length);q.previewStages[t.pads[0].doseStageIndices[0]].dwellMilliseconds=1000;assert.throws(()=>B.validateBatch(q,1000,1),/amount\/dwell/);});

test('group12 uses exactly two minus6 stages with last-part dwell and explicit96 cap',()=>{const {q,t,c,anchor,context}=groupFixture(12);c.dwellMilliseconds=2000;t.pads.forEach(p=>{assert.equal(p.doseStageIndices.length,2);const [a,b]=p.doseStageIndices;assert.equal(b,a+1);for(const i of [a,b])assert.equal(q.previewStages[i].targetRaw.B-q.previewStages[i].startRaw.B,-6);assert.equal(q.previewStages[a].dwellMilliseconds,0);q.previewStages[b].dwellMilliseconds=2000;});B.validateBatch(q,1000,1);assert.equal(B.reserveBatch(anchor,q,carry(),context).totalAbsoluteDegrees,352);const bad=clone(q);bad.ftpTargetRecord.pads[0].doseStageIndices.pop();assert.throws(()=>B.validateBatch(bad,1000,1),/dose/);const wait=clone(q);wait.previewStages[t.pads[0].doseStageIndices[0]].dwellMilliseconds=2000;assert.throws(()=>B.validateBatch(wait,1000,1),/amount\/dwell/);while(q.previewStages.length<=96)q.previewStages.push(clone(q.previewStages.at(-1)));assert.throws(()=>B.validateBatch(q,1000,1));});
test('distinct selected-pad up-to-40 scope is admitted only with unchanged reviewed per-pad guards',()=>{const {q,t}=groupFixture(4),Group=require('./ftp-pad-group.cjs');q.scope=Group.selected40Scope(false);t.scope='ftp-selected-pads-targets';delete t.pairReferences;t.inlineConditioning.protocol='scrap-condition-transit-selected-pads';t.compensatedSequence.protocol='restore-dose-retract-lift-selected-pads';t.pads.forEach(p=>{p.surface=clone(t.surface);p.surfaceEvidence=clone(t.surfaceEvidence);p.rawPose.Z=p.surface.rawZ;});B.validateBatch(q,1000,1);const oversized=clone(q);oversized.previewStages=Array(401).fill(clone(q.previewStages[0]));assert.throws(()=>B.validateBatch(oversized,1000,1),/stage count/);});

test('exact96-stage group preserves tagged history, gross fault charge and stop-at-lift',()=>{
 const {q,t,c,anchor,context}=groupFixture(12),oldLength=q.previewStages.length;
 const at=q.previewStages.findIndex((s,i)=>i>=t.inlineConditioning.prefixStageCount&&['X','Y'].includes(s.axis)),original=q.previewStages[at],pieces=97-oldLength,extra=pieces-1,split=[];let prior=clone(original.startRaw);
 for(let i=1;i<=pieces;i++){const target={...prior,[original.axis]:i===pieces?original.targetRaw[original.axis]:original.startRaw[original.axis]+(original.targetRaw[original.axis]-original.startRaw[original.axis])*i/pieces};split.push({...clone(original),startRaw:prior,targetRaw:target});prior=target;}
 q.previewStages.splice(at,1,...split);for(const p of t.pads){for(const k of ['restoreStageIndex','retractStageIndex','liftStageIndex'])if(p[k]>=at)p[k]+=extra;p.doseStageIndices=p.doseStageIndices.map(i=>i>=at?i+extra:i);}c.finalIdleStageIndices=c.finalIdleStageIndices.map(i=>i+extra);
 assert.equal(q.previewStages.length,96);B.validateBatch(q,1000,1);let l=B.reserveBatch(anchor,q,carry(),context);assert.equal(l.totalAbsoluteDegrees,352);assert.ok(l.entries.some(e=>e.stageIndex===95&&e.batchScope===q.scope));const fault=B.finishBatch(l,q,false);assert.equal(fault.totalAbsoluteDegrees,352);assert.throws(()=>B.reserveBatch(fault,q,carry(),context));
 q.previewStages.forEach((s,i)=>{if(s.axis==='B')l=B.markBatchStep(l,q,i,s.targetRaw.B);});l=B.finishBatch(l,q,true);
 const next=request();next.id='22345678-1234-1234-1234-123456789abc';next.expectedRaw.B=next.expectedDriver.B=l.lastVerifiedB;next.previewStages[0].startRaw=clone(next.expectedRaw);next.previewStages[0].targetRaw={...next.expectedRaw,B:l.lastVerifiedB-6};next.finalTargetRaw=clone(next.previewStages[0].targetRaw);next.rawBounds.B={min:-1000,max:-200};next.budgetAmendmentEvidence=clone(q.budgetAmendmentEvidence);assert.equal(B.reserveBatch(l,next,carry(),context).totalAbsoluteDegrees,358);
 const bad=clone(l);delete bad.entries.find(e=>e.stageIndex===95).batchScope;assert.throws(()=>B.reserveBatch(bad,next,carry(),context),/Malformed/);
 const lift=q.previewStages[t.pads[7].liftStageIndex];assert.equal(B.stopDecision(q,lift.startRaw,lift,true),'reviewed-clearance-lift');assert.equal(B.stopDecision(q,lift.targetRaw,q.previewStages.at(-1),true),'stop-at-clearance');q.previewStages.push(clone(q.previewStages.at(-1)));assert.throws(()=>B.validateBatch(q,1000,1),/stage count/);
});

test('group R3 binds conditioner and every restore/retract with full additional charge',()=>{const {q,t,anchor,context}=groupFixture(12,3);B.validateBatch(q,1000,1);assert.equal(B.reserveBatch(anchor,q,carry(),context).totalAbsoluteDegrees,369);for(const p of t.pads){assert.equal(q.previewStages[p.restoreStageIndex].targetRaw.B-q.previewStages[p.restoreStageIndex].startRaw.B,-3);assert.equal(q.previewStages[p.retractStageIndex].targetRaw.B-q.previewStages[p.retractStageIndex].startRaw.B,3);}const bad=clone(q);bad.ftpTargetRecord.inlineConditioning.experiment.retractDegrees=2;assert.throws(()=>B.validateBatch(bad,1000,1),/retraction differ/);const other=clone(q);other.ftpTargetRecord.compensatedSequence.retractDegrees=4;assert.throws(()=>B.validateBatch(other,1000,1));});

test('inline conditioner6 binds exact authored prefix without changing pad12/R3',()=>{const {q,t,anchor,context}=groupFixture(12,3,6);B.validateBatch(q,1000,1);assert.equal(B.reserveBatch(anchor,q,carry(),context).totalAbsoluteDegrees,355);const i=t.inlineConditioning.retractionStageIndex-1;assert.equal(q.previewStages[i].targetRaw.B-q.previewStages[i].startRaw.B,-6);assert.equal(q.previewStages[i].dwellMilliseconds,2000);assert.equal(q.previewStages.length,groupFixture(12,3,20).q.previewStages.length);for(const p of t.pads){assert.equal(p.doseStageIndices.length,2);for(const j of p.doseStageIndices)assert.equal(q.previewStages[j].targetRaw.B-q.previewStages[j].startRaw.B,-6);}const mismatch=clone(q);mismatch.ftpTargetRecord.inlineConditioning.experiment.conditioningDoseDegrees=20;assert.throws(()=>B.validateBatch(mismatch,1000,1),/prefix differs/);const bad=clone(q);bad.ftpTargetRecord.inlineConditioning.experiment.conditioningDoseDegrees=4;assert.throws(()=>B.validateBatch(bad,1000,1),/amounts/);});

test('explicit dummy finalwipe is only+X1.5 after R3 wait, within exact prefix and original clock',()=>{
 const {q,t,c,anchor,context}=groupFixture(12,3,6),x=t.inlineConditioning,i=x.retractionStageIndex+1,at=clone(q.previewStages[i].startRaw);x.experiment.conditioningFinalWipeMm=1.5;x.experiment.conditioningFinalWipeReviewed=true;
 const wipe={axis:'X',startRaw:at,targetRaw:{...at,X:at.X+1.5},speedFraction:1,expandedCommands:['synthetic'],...ev(),wipeReview:true,wipeReviewEvidence:q.clearanceReviewEvidence,estimatedGapMm:q.receivingProfile.estimatedGapMm,gapUncertaintyMm:q.receivingProfile.gapUncertaintyMm};q.previewStages[i].startRaw.X+=1.5;q.previewStages[i].targetRaw.X+=1.5;q.previewStages[i+1].startRaw.X+=1.5;q.previewStages.splice(i,0,wipe);x.prefixStageCount++;x.liftStageIndex++;for(const p of t.pads){p.restoreStageIndex++;p.retractStageIndex++;p.liftStageIndex++;p.doseStageIndices=p.doseStageIndices.map(v=>v+1);}c.finalIdleStageIndices=c.finalIdleStageIndices.map(v=>v+1);
 B.validateBatch(q,1000,1);assert.equal(B.reserveBatch(anchor,q,carry(),context).totalAbsoluteDegrees,355);assert.equal(B.stopDecision(q,wipe.startRaw,wipe,true),'stop-hold-position');assert.equal(B.stopDecision(q,wipe.targetRaw,q.previewStages[i+1],true),'reviewed-clearance-lift');
 const records=q.previewStages.slice(0,x.prefixStageCount).map((s,j)=>({...clone(s),index:j,verified:true,finishedAt:new Date(j===x.retractionStageIndex?1000:2000).toISOString()}));records[x.retractionStageIndex].dwell={requestedMilliseconds:500,actualElapsedMilliseconds:500,stopObserved:false};assert.equal(Inline.entry(q,16000,records),15000);assert.throws(()=>Inline.entry(q,16001,records),/15 seconds/);
 for(const edit of [v=>v.ftpTargetRecord.inlineConditioning.experiment.conditioningFinalWipeMm=-1.5,v=>v.ftpTargetRecord.inlineConditioning.experiment.conditioningFinalWipeReviewed=false,v=>v.previewStages[i].targetRaw.X+=.01,v=>v.previewStages[i].wipeReview=false]){const bad=clone(q);edit(bad);assert.throws(()=>B.validateBatch(bad,1000,1));}
});

test('conditioner12 is exactly two6 plus optional explicit restore3 with full charge',()=>{
 for(const restore of [0,3]){const {q,t,c,anchor,context}=groupFixture(12,3,12),x=t.inlineConditioning;
 if(restore){x.experiment.conditioningRestoreDegrees=3;const i=x.retractionStageIndex-2,old=q.previewStages[i],extra=clone(old);extra.targetRaw.B=extra.startRaw.B-3;extra.dwellMilliseconds=0;for(let j=i;j<q.previewStages.length;j++){q.previewStages[j].startRaw.B-=3;q.previewStages[j].targetRaw.B-=3;}q.previewStages.splice(i,0,extra);x.prefixStageCount++;x.retractionStageIndex++;x.liftStageIndex++;t.pads.forEach(p=>{p.restoreStageIndex++;p.doseStageIndices=p.doseStageIndices.map(v=>v+1);p.retractStageIndex++;p.liftStageIndex++;});c.finalIdleStageIndices=c.finalIdleStageIndices.map(v=>v+1);q.finalTargetRaw.B-=3;}
 B.validateBatch(q,1000,1);assert.equal(B.reserveBatch(anchor,q,carry(),context).totalAbsoluteDegrees,361+restore);
 const parts=q.previewStages.slice(x.retractionStageIndex-2,x.retractionStageIndex);assert.deepEqual(parts.map(s=>s.targetRaw.B-s.startRaw.B),[-6,-6]);assert.deepEqual(parts.map(s=>s.dwellMilliseconds),[0,2000]);
 for(const edit of [v=>v.previewStages[x.retractionStageIndex-2].dwellMilliseconds=2000,v=>v.ftpTargetRecord.inlineConditioning.experiment.conditioningDoseDegrees=6,v=>v.ftpTargetRecord.inlineConditioning.experiment.conditioningRestoreDegrees=2]){const bad=clone(q);edit(bad);assert.throws(()=>B.validateBatch(bad,1000,1));}
 }
});

test('cleanup100 reserves every+20 once, retains fault charge and verifies ordered completion',()=>{
 const q=cleanupFixture(20),t=q.ftpTargetRecord,p=t.pads[0],base=clone(q.previewStages[0]);t.cleanupSequence.protocol='positive-B-aspiration-series-lift-one-pad';t.cleanupSequence.retractDegrees=100;delete p.aspirationStageIndex;p.aspirationStageIndices=[0,1,2,3,4];p.liftStageIndex=5;let at=clone(q.expectedRaw);q.previewStages=[];for(let i=0;i<5;i++){const target={...at,B:at.B+20};q.previewStages.push({...clone(base),startRaw:at,targetRaw:target});at=target;}q.previewStages.push({axis:'Z',startRaw:at,targetRaw:{...at,Z:q.xyClearanceRawZ},speedFraction:1,expandedCommands:['synthetic'],...ev()});q.finalTargetRaw=clone(q.previewStages.at(-1).targetRaw);q.rawBounds.B.max=q.finalTargetRaw.B;
 B.validateBatch(q,1000,1);let l=B.reserveBatch(ledger(),q,carry());assert.equal(l.totalAbsoluteDegrees,100);assert.equal(B.finishBatch(l,q,false).totalAbsoluteDegrees,100);assert.throws(()=>B.markBatchStep(l,q,1,q.previewStages[1].targetRaw.B));assert.equal(B.stopDecision(q,q.previewStages[0].targetRaw,q.previewStages[1],true),'stop-hold-position');assert.equal(B.stopDecision(q,q.previewStages[4].targetRaw,q.previewStages[5],true),'reviewed-clearance-lift');for(let i=0;i<5;i++)l=B.markBatchStep(l,q,i,q.previewStages[i].targetRaw.B);l=B.finishBatch(l,q,true);assert.equal(l.lastVerifiedB,-140);assert.equal(l.entries.length,5);assert.throws(()=>B.reserveBatch(l,q,carry()));
});
