'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto'),P=require('./commissioning-stroke.cjs');
const ROOT='/home/lumen/lumenpnp', evidence=(p)=>({path:p,sha256:crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex')}),read=p=>JSON.parse(fs.readFileSync(p,'utf8'));
const batch='9d2592a4-0b68-41a7-ba1a-4fa1e7b40bc9',rid='c8113b57-6a31-4db9-8ccf-45c4d1138c66';
test('actual partial reconciliation report authorizes successive wet ledger reservations without replay/refund',t=>{
 const reportPath=path.join(ROOT,'automation/evidence/paste-batch-reconciliation-'+rid+'/report.json');if(!fs.existsSync(reportPath))return t.skip('requires the local actual partial-stop reconciliation evidence');
 const report=read(reportPath),ledgerPath=report.ledgerPath,currentLedger=read(ledgerPath),audit=read(path.join(ROOT,'automation/evidence/paste-batch-stop-audit-'+batch+'/report.json'));
 const preservedPath=path.join(path.dirname(reportPath),'faulted-ledger-preserved.json'),reconciled=P.reconcileStoppedPartialBatch(read(preservedPath),audit),reconciledBytes=Buffer.from(JSON.stringify(reconciled,null,2)+'\n'),reconciledSha=crypto.createHash('sha256').update(reconciledBytes).digest('hex');assert.equal(reconciledSha,report.completedLedgerSha256);assert.equal(reconciled.totalAbsoluteDegrees,8967);assert.equal(reconciled.lastVerifiedB,-3174);assert.equal(reconciled.entries.length,947);assert.equal(P.validatePreviousReport(report,reconciled,reconciledSha,Date.now()),true);
 const liveLedger=currentLedger,markerIndex=liveLedger.entries.findIndex(e=>e.kind==='partial-stopped-batch-reconciliation');assert.ok(markerIndex>=0);assert.ok(liveLedger.entries.slice(markerIndex+1).every(e=>e.status==='verified'));assert.ok(liveLedger.totalAbsoluteDegrees>=8967);assert.equal(liveLedger.status,'verified');assert.equal(P.partialReconciliationIndices(liveLedger)[markerIndex],'reconciliation');
 const ledger=reconciled,ledgerEv={path:ledgerPath,sha256:reconciledSha};
 const amendmentPath=path.join(ROOT,'automation/evidence/small-dot-commissioning-20260930/contiguous-coupon/travel-budget-review/cap-11800-reviewed-iso/budget-amendment.json'),record=read(amendmentPath),anchorPath=record.anchorLedgerEvidence.path,anchor=read(anchorPath),anchorReport=read(record.anchorReportEvidence.path),carry=read(path.join(ROOT,'automation/evidence/small-dot-commissioning-20260930/carryover.json'));
 carry.carryoverSha256=ledger.carryoverSha256;
 const amendment={...record,...evidence(amendmentPath)},ctx={record,anchorLedger:anchor,anchorReport};
 function request(id,previous,previousReport,before){const now=Date.now(),raw={X:321.04,Y:213.07,Z:53.25,A:720,B:before};const target={...raw,B:before-6},ev={path:'/integration/synthetic',sha256:'a'.repeat(64)},travel=record.travelReviewEvidence;
  return {schema:1,scope:'contiguous-native-scrap-batch',enabled:false,mode:'wet',stopPath:'/integration/stop.requested',id,sessionId:ledger.sessionId,jvmStartMs:audit.jvmStartMs,createdMs:now,imageCapturedMs:now-200,reviewedImageMs:now-100,liveConfigurationSha256:audit.liveConfigurationSha256,expectedRaw:raw,expectedDriver:{...raw},expectedNativePoses:{N1:{x:296.89552193427375,y:149.08304560455133,z:53.25},N2:{x:344.655,y:149.123,z:9.75},top:{x:321.04,y:213.07,z:0},bottom:{x:217.129,y:152.319,z:25.2}},rawBounds:{X:{min:300,max:330},Y:{min:200,max:230},Z:{min:48.25,max:58.25},B:{min:-4000,max:-3000}},headClearanceBounds:{N1:{minX:0,maxX:500,minY:0,maxY:500,minZ:0,maxZ:100},N2:{minX:0,maxX:500,minY:0,maxY:500,minZ:0,maxZ:100}},bothHeadsClearanceReview:true,clearanceReviewEvidence:ev,xyClearanceRawZ:48.25,receivingProfile:{provenance:'commissioning-provisional',precisionCalibrated:false,flowCalibrated:false,sha256:ev.sha256,estimatedGapMm:.6,gapUncertaintyMm:.3,basis:'Synthetic integration test only; no surface claim.',rawPose:{X:raw.X,Y:raw.Y,Z:raw.Z,A:raw.A}},previewStages:[{axis:'B',speedFraction:.05,startRaw:raw,targetRaw:target,gapEvidence:ev,estimatedGapMm:.6,gapUncertaintyMm:.3,expandedCommands:['synthetic'],path:'/integration/stage',sha256:ev.sha256}],finalTargetRaw:target,evidence:[ev,ev,ev,ev,ev,ev,ev,{path:travel.path,sha256:travel.sha256}],previousReportEvidence:previousReport,previousLedgerSha256:previous, nativePreviewEvidence:ev,profileEvidence:ev,barrierEvidence:ev,reviewedImageEvidence:ev,syringeId:ledger.syringeId,primeLedgerSha256:ledger.primeLedgerSha256,carryoverSha256:ledger.carryoverSha256,budgetAmendmentEvidence:amendment};
 }
 const firstId='01234567-89ab-4cde-8123-456789abcdef',q1=request(firstId,ledgerEv.sha256,evidence(reportPath),ledger.lastVerifiedB),reserved=P.reserveBatch(ledger,q1,carry,ctx);assert.equal(reserved.totalAbsoluteDegrees,ledger.totalAbsoluteDegrees+6);assert.equal(reserved.lastVerifiedB,ledger.lastVerifiedB);const firstTarget=ledger.lastVerifiedB-6;let done=P.markBatchStep(reserved,q1,0,firstTarget);done=P.finishBatch(done,q1,true);assert.equal(done.lastVerifiedB,firstTarget);assert.equal(done.totalAbsoluteDegrees,ledger.totalAbsoluteDegrees+6);
 const nextReport={id:firstId,request:{id:firstId},status:'completed-contiguous-batch-awaiting-observation',uncertainCompletion:false,completedLedgerSha256:'b'.repeat(64),finishedAt:new Date().toISOString()};const q2=request('11234567-89ab-4cde-8123-456789abcdef','b'.repeat(64),{path:'/synthetic/report.json',sha256:'b'.repeat(64)},done.lastVerifiedB);q2.previousReportEvidence={path:'/synthetic/report.json',sha256:'b'.repeat(64)};const reserved2=P.reserveBatch(done,q2,carry,ctx);assert.equal(reserved2.totalAbsoluteDegrees,ledger.totalAbsoluteDegrees+12);assert.equal(reserved2.entries.at(-1).startB,done.lastVerifiedB);assert.equal(P.partialReconciliationIndices(reserved2)[reserved2.entries.findIndex(e=>e.kind==='partial-stopped-batch-reconciliation')],'reconciliation');
});
