'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const B=require('./commissioning-stroke.cjs');
const hash='a'.repeat(64),id='12345678-1234-1234-1234-123456789abc',sessionId='abcd1234-1234-1234-1234-123456789abc';
const ev=()=>({path:'/synthetic-only',sha256:hash});
const raw=()=>({X:100,Y:200,Z:50,A:720,B:-240});
function request(mode='wet',preview=false){
 const r=raw(),target={...r,[mode==='wet'?'B':'Z']:mode==='wet'?-246:45};
 return {schema:1,scope:preview?'contiguous-native-scrap-batch-preview':'contiguous-native-scrap-batch',enabled:false,mode,stopPath:'/synthetic-stop',id,sessionId,jvmStartMs:1,createdMs:1000,imageCapturedMs:900,reviewedImageMs:950,liveConfigurationSha256:hash,expectedRaw:r,expectedDriver:{...r},expectedNativePoses:{N1:{x:100,y:200,z:50},N2:{x:100,y:200,z:50},top:{},bottom:{}},rawBounds:{X:{min:95,max:105},Y:{min:195,max:205},Z:{min:45,max:55},B:{min:-260,max:-220}},headClearanceBounds:{N1:{minX:0,maxX:500,minY:0,maxY:500,minZ:0,maxZ:100},N2:{minX:0,maxX:500,minY:0,maxY:500,minZ:0,maxZ:100}},bothHeadsClearanceReview:true,clearanceReviewEvidence:ev(),xyClearanceRawZ:45,receivingProfile:{provenance:'commissioning-provisional',precisionCalibrated:false,flowCalibrated:false,sha256:hash,estimatedGapMm:.65,gapUncertaintyMm:.4,basis:'synthetic observed height interval',rawPose:{...r}},previewStages:[{axis:mode==='wet'?'B':'Z',speedFraction:mode==='wet'?.05:1,startRaw:r,targetRaw:target,...(mode==='wet'?{gapEvidence:ev(),estimatedGapMm:.65,gapUncertaintyMm:.4}:{}),...(preview?{}:{expandedCommands:['synthetic'],...ev()})}],finalTargetRaw:target,evidence:Array.from({length:7},ev),previousReportEvidence:ev(),nativePreviewEvidence:ev(),profileEvidence:ev(),barrierEvidence:ev(),reviewedImageEvidence:ev(),previousLedgerSha256:hash,syringeId:'synthetic',primeLedgerSha256:hash,carryoverSha256:hash,budgetAmendmentEvidence:null};
}
const clone=x=>JSON.parse(JSON.stringify(x));
const ledger=()=>({schema:1,scope:'signed-B-commissioning-strokes',sessionId,syringeId:'synthetic',primeLedgerSha256:hash,carryoverSha256:hash,startB:-240,lastVerifiedB:-240,totalAbsoluteDegrees:0,entries:[],status:'verified'});
const carry=()=>({schema:1,sessionId,syringeId:'synthetic',primeLedgerSha256:hash,priorGrossDegrees:10940,manualDisplacementUnknown:true,verifiedPrimeDegrees:960,startB:-240,maximumAbsoluteDegrees:120});
test('bounded wet batch reserves full gross and verifies each B stage',()=>{const q=request(),l=B.reserveBatch(ledger(),q,carry());assert.equal(l.totalAbsoluteDegrees,6);assert.equal(l.entries[0].batchId,id);assert.throws(()=>B.finishBatch(l,q,true));const done=B.finishBatch(B.markBatchStep(l,q,0,-246),q,true);assert.equal(done.status,'verified');assert.equal(done.lastVerifiedB,-246);assert.equal(done.totalAbsoluteDegrees,6);});
test('fault consumes all reserved B budget and bars replay',()=>{const q=request(),l=B.reserveBatch(ledger(),q,carry()),fault=B.finishBatch(l,q,false);assert.equal(fault.totalAbsoluteDegrees,6);assert.equal(fault.entries[0].status,'faulted');assert.throws(()=>B.reserveBatch(fault,q,carry()));});
test('air batch has zero B stages and cannot reserve budget',()=>{const q=request('air');B.validateBatch(q,1000,1);assert.throws(()=>B.reserveBatch(ledger(),q,carry()));const bad=clone(q);bad.previewStages[0].axis='B';assert.throws(()=>B.validateBatch(bad,1000,1));});
test('contiguous single-axis, length, speed and clearance bounds fail closed',()=>{const q=request();for(const edit of [x=>x.previewStages[0].targetRaw.A++,x=>x.previewStages[0].speedFraction=1,x=>x.previewStages=Array.from({length:41},()=>x.previewStages[0]),x=>x.receivingProfile.gapUncertaintyMm=.6]){const v=clone(q);edit(v);assert.throws(()=>B.validateBatch(v,1000,1));}const a=request('air');a.previewStages[0].axis='X';a.previewStages[0].targetRaw={...a.expectedRaw,X:101};a.finalTargetRaw={...a.previewStages[0].targetRaw};assert.throws(()=>B.validateBatch(a,1000,1));a.previewStages[0].wipeReview=true;a.previewStages[0].wipeReviewEvidence=ev();a.previewStages[0].estimatedGapMm=.5;a.previewStages[0].gapUncertaintyMm=.2;B.validateBatch(a,1000,1);});
test('prior report accepts batch tail only with exact completed ledger hash',()=>{const q=request(),l=B.finishBatch(B.markBatchStep(B.reserveBatch(ledger(),q,carry()),q,0,-246),q,true),r={id,request:{id},status:'completed-contiguous-batch-awaiting-observation',uncertainCompletion:false,completedLedgerSha256:hash,finishedAt:'2026-09-30T00:00:00.000Z'};assert.equal(B.validatePreviousReport(r,l,hash,Date.parse(r.finishedAt)+1),true);r.completedLedgerSha256='b'.repeat(64);assert.throws(()=>B.validatePreviousReport(r,l,hash,Date.parse(r.finishedAt)+1));});
test('negative stage uncertainty and negative gap cannot bypass lower bound',()=>{const q=request();q.previewStages[0].estimatedGapMm=-1;q.previewStages[0].gapUncertaintyMm=-2;assert.throws(()=>B.validateBatch(q,1000,1));const a=request('air');a.previewStages[0].axis='X';a.previewStages[0].targetRaw={...a.expectedRaw,X:101};a.finalTargetRaw={...a.previewStages[0].targetRaw};a.previewStages[0].wipeReview=true;a.previewStages[0].wipeReviewEvidence=ev();a.previewStages[0].estimatedGapMm=-1;a.previewStages[0].gapUncertaintyMm=-2;assert.throws(()=>B.validateBatch(a,1000,1));});
test('batch ID replay rejected even with shifted B index; B verification is ordered',()=>{const q=request(),l=B.reserveBatch(ledger(),q,carry()),done=B.finishBatch(B.markBatchStep(l,q,0,-246),q,true);const q2=clone(q);q2.expectedRaw.B=-246;q2.expectedDriver.B=-246;const r=q2.expectedRaw,xy={...r,X:101};q2.previewStages.unshift({axis:'X',startRaw:r,targetRaw:xy,speedFraction:1,expandedCommands:['synthetic'],...ev()});q2.previewStages[1].startRaw=xy;q2.previewStages[1].targetRaw={...xy,B:-252};q2.finalTargetRaw={...xy,B:-252};q2.xyClearanceRawZ=50;assert.throws(()=>B.reserveBatch(done,q2,carry()),/batch replay/);const q3=request();const second={...q3.previewStages[0],startRaw:q3.finalTargetRaw,targetRaw:{...q3.finalTargetRaw,B:-252}};q3.previewStages.push(second);q3.finalTargetRaw=second.targetRaw;const two=B.reserveBatch(ledger(),q3,carry());assert.throws(()=>B.markBatchStep(two,q3,1,-252));assert.throws(()=>B.finishBatch(two,q3,true));});
test('cooperative stop allows only an already-reviewed clearance lift',()=>{const q=request('air'),at={...q.expectedRaw,Z:50},lift={axis:'Z',speedFraction:1,startRaw:at,targetRaw:{...at,Z:q.xyClearanceRawZ}};assert.equal(B.stopDecision(q,at,lift,false),'continue');assert.equal(B.stopDecision(q,at,lift,true),'reviewed-clearance-lift');assert.equal(B.stopDecision(q,at,{...lift,axis:'B'},true),'stop-hold-position');assert.equal(B.stopDecision(q,{...at,Z:q.xyClearanceRawZ},lift,true),'stop-at-clearance');});
test('optional post-B dwell accepts only integer 0..2000 and never linear stages',()=>{for(const preview of [false,true]){const q=request('wet',preview);B.validateBatch(q,1000,1,preview);for(const ms of [0,1,50,2000]){q.previewStages[0].dwellMilliseconds=ms;B.validateBatch(q,1000,1,preview);}for(const ms of [-1,2001,1.5,'50',null,NaN,Infinity]){q.previewStages[0].dwellMilliseconds=ms;assert.throws(()=>B.validateBatch(q,1000,1,preview));}}const a=request('air');a.previewStages[0].dwellMilliseconds=0;assert.throws(()=>B.validateBatch(a,1000,1));});

const FTP=require('./ftp-two-pad.cjs');
function ftpRequest(){
 const q=request(),start=raw();q.scope=FTP.scope(false);q.rawBounds.Z.max=50;q.previewStages=[];let at={...start};
 function add(axis,value){const target={...at,[axis]:value};q.previewStages.push({axis,startRaw:at,targetRaw:target,speedFraction:axis==='B'?.05:1,expandedCommands:['synthetic'],...ev(),...(axis==='B'?{gapEvidence:{path:'/ftp/surface.json',sha256:hash},estimatedGapMm:.65,gapUncertaintyMm:.4}:{})});at=target;}
 add('B',-246);add('Z',45);add('X',101);add('Z',50);add('B',-252);add('Z',45);q.finalTargetRaw=at;
 const e=name=>({path:'/ftp/'+name,sha256:hash});
 q.ftpTargetEvidence=e('targets.json');q.ftpTargetRecord={schema:1,scope:'ftp-two-pad-commissioning-targets',boardId:'synthetic-cleaned-demo',sessionId,jvmStartMs:1,liveConfigurationSha256:hash,reviewedBy:'synthetic-test',reviewedMs:950,boardCleaned:true,padsAvailable:true,boardUnmovedSinceRegistration:true,provenance:'commissioning-provisional',precisionCalibrated:false,flowCalibrated:false,cadEvidence:e('board.kicad_pcb'),registrationEvidence:e('registration.json'),tipOffsetEvidence:e('offset.json'),surfaceEvidence:e('surface.json'),padAvailabilityImage:e('available.png'),cameraMinusTipXYMm:[5,-3],surface:{rawZ:50,estimatedGapMm:.65,gapUncertaintyMm:.4},pads:[{padId:'R1.1',doseStageIndex:0,rawPose:{X:100,Y:200,Z:50,A:720}},{padId:'R1.2',doseStageIndex:4,rawPose:{X:101,Y:200,Z:50,A:720}}],padChecks:['R1','R16','R40'].map(reference=>({reference,padId:reference+'.1',reviewedAligned:true,reportEvidence:e(reference+'/report.json'),imageEvidence:e(reference+'/top.png')}))};return q;
}
function ftpSources(q){
 const t=q.ftpTargetRecord,files={},e=name=>({path:'/ftp/'+name,sha256:hash});
 const cameraReport=xy=>({status:'completed-contiguous-air-batch-awaiting-observation',controllerPositionVerified:true,uncertainCompletion:false,finishedAt:new Date(900).toISOString(),request:{jvmStartMs:1,liveConfigurationSha256:hash},afterImages:{top:{path:'top.png'}},afterQuerySnapshot:{nativePoses:{top:{x:xy[0],y:xy[1]}}}});
 const targets=Array.from({length:40},(_,i)=>[1,2].map(n=>({padId:`R${i+1}.${n}`,machineXYMm:[104+n,197]}))).flat();
 const reg={scope:'offline-fresh-ftp-two-fiducial-transform-with-third-point-check',acceptance:{passed:true},board:t.cadEvidence,session:{jvmStartMs:1,liveConfigurationSha256:hash},independentFID3Check:{residualMm:.01},measurements:{},resistorPadMachineXYTargets:targets};
 for(const fid of ['FID1','FID2','FID3']){reg.measurements[fid]={imageCenterErrorPx:1,report:e(fid+'/report.json'),image:e(fid+'/top.png')};files['/ftp/'+fid+'/report.json']=cameraReport([0,0]);}
 for(const c of t.padChecks)files[c.reportEvidence.path]=cameraReport(targets.find(p=>p.padId===c.padId).machineXYMm);
 const base={boardId:t.boardId,provenance:'commissioning-provisional',precisionCalibrated:false,jvmStartMs:1,liveConfigurationSha256:hash,reviewedBy:'synthetic-test',basisEvidence:e('basis.json')};
 files[t.registrationEvidence.path]=reg;files[t.tipOffsetEvidence.path]={...base,cameraMinusTipXYMm:t.cameraMinusTipXYMm};files[t.surfaceEvidence.path]={...base,surface:t.surface};files[q.ftpTargetEvidence.path]=clone(t);
 return {files,read:(e,json)=>{assert.match(e.sha256,/^[a-f0-9]{64}$/);if(json){assert.ok(files[e.path],e.path);return files[e.path];}return null;}};
}
test('FTP two-pad wet branch preserves whole-budget reservation and ordered verification',()=>{const q=ftpRequest();B.validateBatch(q,1000,1);let l=B.reserveBatch(ledger(),q,carry());assert.equal(l.totalAbsoluteDegrees,12);l=B.markBatchStep(l,q,0,-246);l=B.markBatchStep(l,q,4,-252);assert.equal(B.finishBatch(l,q,true).lastVerifiedB,-252);const f=ftpSources(q);FTP.verifySources(q,f.read);});
test('FTP prevents duplicate/different-resistor targets, wrong dose pose and extra dose stage',()=>{for(const edit of [q=>q.ftpTargetRecord.pads[1].padId='R1.1',q=>q.ftpTargetRecord.pads[1].padId='R2.2',q=>q.ftpTargetRecord.pads[0].rawPose.X++,q=>q.ftpTargetRecord.pads[1].doseStageIndex=0,q=>q.ftpTargetRecord.surface.estimatedGapMm=.9,q=>q.ftpTargetRecord.pads[0].doseStageIndex=2]){const q=ftpRequest();edit(q);assert.throws(()=>B.validateBatch(q,1000,1));}});
test('FTP cannot downgrade to scrap, claim calibration, omit review or exceed board Z',()=>{for(const edit of [q=>q.scope='contiguous-native-scrap-batch',q=>q.ftpTargetRecord.precisionCalibrated=true,q=>q.ftpTargetRecord.boardUnmovedSinceRegistration=false,q=>q.ftpTargetRecord.reviewedMs=NaN,q=>q.ftpTargetRecord.reviewedMs=-400000,q=>q.rawBounds.Z.max=51,q=>delete q.ftpTargetEvidence]){const q=ftpRequest();edit(q);assert.throws(()=>B.validateBatch(q,1000,1));}});
test('FTP rejects low XY even with legacy noncontact wipe evidence',()=>{const q=ftpRequest();q.previewStages[2].wipeReview=true;q.previewStages[2].wipeReviewEvidence=ev();assert.throws(()=>B.validateBatch(q,1000,1));});
test('FTP air record permits no B and cannot map dose indices',()=>{const q=ftpRequest();q.mode='air';q.previewStages=q.previewStages.filter(s=>s.axis!=='B').map(s=>({...s,startRaw:{...s.startRaw,B:-240},targetRaw:{...s.targetRaw,B:-240}}));q.finalTargetRaw.B=-240;q.ftpTargetRecord.pads.forEach(p=>p.doseStageIndex=null);B.validateBatch(q,1000,1);assert.throws(()=>B.reserveBatch(ledger(),q,carry()));q.ftpTargetRecord.pads[0].doseStageIndex=0;assert.throws(()=>B.validateBatch(q,1000,1));});
test('FTP source verification rejects swapped record, offset, surface and camera evidence',()=>{for(const edit of [(q,f)=>f.files[q.ftpTargetEvidence.path].boardId='different',(q,f)=>f.files[q.ftpTargetRecord.tipOffsetEvidence.path].cameraMinusTipXYMm=[6,-3],(q,f)=>f.files[q.ftpTargetRecord.surfaceEvidence.path].surface={...q.ftpTargetRecord.surface,rawZ:51},(q,f)=>f.files['/ftp/R16/report.json'].afterQuerySnapshot.nativePoses.top.x=NaN,(q,f)=>f.files['/ftp/FID1/report.json'].uncertainCompletion=true]){const q=ftpRequest(),f=ftpSources(q);edit(q,f);assert.throws(()=>FTP.verifySources(q,f.read));}});
test('FTP registered coordinates must match selected tip offset; preview equality is order independent',()=>{const q=ftpRequest(),f=ftpSources(q);f.files[q.ftpTargetRecord.registrationEvidence.path].resistorPadMachineXYTargets[0].machineXYMm[0]+=.1;assert.throws(()=>FTP.verifySources(q,f.read));assert.equal(FTP.same({a:1,b:2},{b:2,a:1}),true);assert.equal(FTP.same({a:1},{a:2}),false);});

test('FTP rejects any added positive B stage, including relief at clearance',()=>{for(const placement of ['before','after']){const q=ftpRequest();if(placement==='after'){const at=q.finalTargetRaw,target={...at,B:at.B+2};q.previewStages.push({axis:'B',startRaw:at,targetRaw:target,speedFraction:.05,expandedCommands:['synthetic'],...ev(),gapEvidence:q.ftpTargetRecord.surfaceEvidence,estimatedGapMm:5.65,gapUncertaintyMm:.4});q.finalTargetRaw=target;}else{const at=q.expectedRaw,target={...at,B:at.B+2};q.previewStages.forEach(s=>{s.startRaw={...s.startRaw,B:s.startRaw.B+2};s.targetRaw={...s.targetRaw,B:s.targetRaw.B+2};});q.finalTargetRaw={...q.finalTargetRaw,B:q.finalTargetRaw.B+2};q.ftpTargetRecord.pads.forEach(p=>p.doseStageIndex++);q.previewStages.unshift({axis:'B',startRaw:at,targetRaw:target,speedFraction:.05,expandedCommands:['synthetic'],...ev(),gapEvidence:q.ftpTargetRecord.surfaceEvidence,estimatedGapMm:.65,gapUncertaintyMm:.4});}assert.throws(()=>B.validateBatch(q,1000,1),/only its two negative B/);}});
