const {test}=require('node:test');const assert=require('node:assert/strict');const p=require('./connection-policy.cjs');
const connect='G21 ; mm\nG90 ; abs\nM260 A112 B1 S1\nM260 A109\nM260 B48\nM260 B27\nM260 S1\nM260 A112 B2 S1\nM260 A109\nM260 B48\nM260 B27\nM260 S1';
function state(){return {enabled:false,homed:false,busy:false,jobState:'Stopped',driverClass:'org.openpnp.machine.reference.driver.GcodeDriver',driverId:'DRV16982438146c1dd4',driverCount:1,connected:false,readerAlive:false,serialOpen:false,serialClass:'org.openpnp.machine.reference.driver.SerialPortCommunications',communicationsType:'serial',simulation:false,baud:115200,flowControl:'RtsCts',dataBits:'Eight',stopBits:'One',parity:'None',dtr:false,rts:false,lineEnding:'LF',quarantined:true,heldPart:false};}
test('audited startup policy accepts mode/sensor commands only',()=>p.checkCommands(connect,null,null));
test('home, motor release, rotation or altered sensor setup fails before connect',()=>{for(const extra of ['G28','M18','G1 B10','M260 B28'])assert.throws(()=>p.checkCommands(connect+'\n'+extra,null,null));assert.throws(()=>p.checkCommands(connect.replace('B27','B28'),null,null));});
test('unexpected enable or disable command is not silently exercised',()=>{assert.throws(()=>p.checkCommands(connect,'M17',null));assert.throws(()=>p.checkCommands(connect,null,'M18'));});
test('owner probe rejects browser owner, unknown error and timeout-style result',()=>{p.noOwner(1,'');for(const pair of [[0,'27176 zen'],[1,'permission denied'],[2,''],[0,'']])assert.throws(()=>p.noOwner(...pair));});
test('disconnected disabled quarantined state required',()=>{p.checkState(state());for(const [key,value] of [['enabled',true],['homed',true],['busy',true],['jobState','Paused'],['connected',true],['readerAlive',true],['serialOpen',true],['quarantined',false],['heldPart',true],['driverCount',2]]){const s=state();s[key]=value;assert.throws(()=>p.checkState(s),key);}});
test('unknown device settings and driver rejected',()=>{for(const [key,value] of [['driverId','other'],['driverClass','AsyncDriver'],['communicationsType','tcp'],['serialClass','other'],['baud',250000],['dtr',true],['rts',true],['simulation',true]]){const s=state();s[key]=value;assert.throws(()=>p.checkState(s),key);}});

test('reset, error and resend replies abort even if followed by ACK',()=>{p.responses(['FIRMWARE_NAME:Marlin MACHINE_TYPE:LumenPnP AXIS_COUNT:5','ok']);for(const line of ['Error: checksum','!! stop','start','echo: Last reset cause: EXTR','Resend: 2','rs N2','disconnected'])assert.throws(()=>p.responses([line,'ok']));});
