const {test}=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const os=require('node:os');const path=require('node:path');const cp=require('node:child_process');
const api=import('./coupon-trials.mjs');
// Synthetic geometry/process numbers solely for offline tests, never calibration.
function fixture(){const profile={calibrated:true,liveConfigurationSha256:'a'.repeat(64),nativeCoordinateFrame:'openpnp-N2-mm',measurementRecord:'test',registrationRecord:'test',jointClearanceRecord:'test',configurationBackup:'test',firmwareSettingsRecord:'test',nativeSpeedRecord:'test',leftNozzleId:'left',rightNozzleId:'right',leftHeadOffsets:'test',rightHeadOffsets:'test',xMin:0,xMax:50,yMin:0,yMax:50,zMin:0,zMax:20,safeZ:15,leftClearanceZ:5,clearanceDirection:'increasing',travelFeed:10,zFeed:10,dispenseFeed:10,speedFraction:0.01,rawBounds:{x:{min:0,max:50},y:{min:0,max:50}}};const req={schema:1,coordinateFrame:'openpnp-N2-mm',substrate:{id:'synthetic-scrap',kind:'scrap',support:'unplatformed',registrationRecord:'test',surfaceRecord:'test',tipAndMaterialRecord:'test',clearanceRecord:'test',bounds:{xMin:1,xMax:30,yMin:12,yMax:20}},demoBounds:{xMin:1,xMax:30,yMin:1,yMax:10},minDemoGapMm:1,minPadGapMm:1,tipEdgeMarginMm:0.2,pads:Array.from({length:6},(_,i)=>({id:'pad-'+i,unused:true,x:3+i*4,y:15,surfaceZ:2,extents:{xMin:2+i*4,xMax:4+i*4,yMin:14,yMax:16}})),process:{dosesDegrees:[1,2,3],retractionDegrees:0,dwellMilliseconds:0,standoffMm:0.5,verifiedDispenseSign:-1,directionRecord:'test',observedCurrentMa:420,dispenseDegreesPerMinute:120,retractionDegreesPerMinute:80,currentSettingsRecord:'synthetic current record'},limits:{maxDoseDegrees:4,maxTotalGrossDegrees:20,maxRetractionDegrees:0,maxDwellMilliseconds:0,doseLimitRecord:'test',remainingStrokeRecord:'test',maxMotorCurrentMa:500,maxDispenseDegreesPerMinute:200,maxRetractionDegreesPerMinute:100,currentRateLimitRecord:'synthetic limit record'}};return {req,profile,ref:{path:'/synthetic/profile.json',sha256:'b'.repeat(64)}};}
function observation(plan,i=0){const t=plan.trials[i];return {planSha256:plan.sha256,trialId:t.id,padId:t.padId,operator:'test operator',observedAt:'2026-09-30T10:00:00Z',notes:'synthetic observation',outcome:'deposited',assessment:'acceptable-by-operator',appliedDoseDegrees:t.doseDegrees,appliedMotorCurrentMa:t.motorCurrentMa,appliedDispenseDegreesPerMinute:t.dispenseDegreesPerMinute,appliedRetractionDegreesPerMinute:t.retractionDegreesPerMinute,settingsMatchedPlan:true,evidence:[{path:'/synthetic/image.png',sha256:'c'.repeat(64)}],settingsEvidence:[{path:'/synthetic/settings.txt',sha256:'d'.repeat(64)}],measurements:[]};}
function selection(plan){return {comparisonSha256:plan.sha256,selectedTrialId:'compare-2',fixtureUnchanged:true,registrationCurrent:true,operator:'test',reviewedAt:'2026-09-30T10:01:00Z',reason:'observed middle deposit',evidenceRecord:'synthetic review'};}
test('pending empty target template is intentionally non-runnable',async()=>{const {planComparison}=await api,{profile,ref}=fixture();const req=JSON.parse(fs.readFileSync(__dirname+'/coupon-request.pending.json'));assert.equal(req.pads.length,0);assert.throws(()=>planComparison(req,profile,ref));});
test('deterministic screening comparison binds current/rates and reserves three pads',async()=>{const {planComparison}=await api,{req,profile,ref}=fixture();const a=planComparison(req,profile,ref),b=planComparison(req,profile,ref);assert.deepEqual(a,b);assert.equal(a.stage,'screening-comparison');assert.deepEqual(a.trials.map(t=>t.doseDegrees),[1,2,3]);assert.ok(a.trials.every(t=>t.motorCurrentMa===420&&t.dispenseDegreesPerMinute===120&&t.retractionDegreesPerMinute===80));assert.equal(new Set(a.trials.map(t=>t.padId)).size,3);assert.equal(a.reservedRepeatPadIds.length,3);assert.equal(a.executionEnabled,false);assert.equal(a.demoAuthorized,false);});
test('unmeasured profile and unregistered/empty target inputs fail closed',async()=>{const {planComparison}=await api;for(const change of [f=>f.profile.calibrated=false,f=>f.req.pads=[],f=>f.req.coordinateFrame='board',f=>f.req.substrate.surfaceRecord=null]){const f=fixture();change(f);assert.throws(()=>planComparison(f.req,f.profile,f.ref));}});
test('duplicate, previously-used or differently-sized pads rejected',async()=>{const {planComparison}=await api;for(const change of [r=>r.pads[1].id=r.pads[0].id,r=>r.pads[1].unused=false,r=>r.pads[1].extents.xMax+=0.2]){const f=fixture();change(f.req);assert.throws(()=>planComparison(f.req,f.profile,f.ref));}});
test('geometry enforces scrap bounds, +Y demo separation, pad spacing and tip margin',async()=>{const {planComparison}=await api;for(const change of [r=>r.demoBounds.yMax=13,r=>r.minPadGapMm=3,r=>r.pads[0].x=2,r=>r.substrate.bounds.xMax=20]){const f=fixture();change(f.req);assert.throws(()=>planComparison(f.req,f.profile,f.ref));}});
test('dose order, per-dose cap, gross stroke and current/rate bounds enforced',async()=>{const {planComparison}=await api;for(const change of [r=>r.process.dosesDegrees=[2,1,3],r=>r.process.dosesDegrees=[1,2,5],r=>r.limits.maxTotalGrossDegrees=5,r=>r.process.verifiedDispenseSign=0,r=>r.process.observedCurrentMa=501,r=>r.process.dispenseDegreesPerMinute=201,r=>r.process.retractionDegreesPerMinute=101,r=>r.process.currentSettingsRecord=null,r=>r.limits.currentRateLimitRecord=null]){const f=fixture();change(f.req);assert.throws(()=>planComparison(f.req,f.profile,f.ref));}});
test('scrap Z and standoff must stay inside bounds with clearance',async()=>{const {planComparison}=await api;for(const change of [r=>r.pads[0].surfaceZ=25,r=>r.process.standoffMm=14,r=>r.pads[0].surfaceZ=NaN]){const f=fixture();change(f.req);assert.throws(()=>planComparison(f.req,f.profile,f.ref));}});
test('observation records actual evidence without software acceptance',async()=>{const {planComparison,recordObservation}=await api,f=fixture(),p=planComparison(f.req,f.profile,f.ref),o=observation(p);const r=recordObservation(p,o);assert.equal(r.physicalAcceptanceEstablished,false);assert.equal(r.demoAuthorized,false);assert.equal(r.observation.assessment,'acceptable-by-operator');o.evidence=[];assert.throws(()=>recordObservation(p,o),/evidence/);o.evidence=[{path:'/synthetic/image.png',sha256:'c'.repeat(64)}];o.settingsEvidence=[];assert.throws(()=>recordObservation(p,o),/settings/);});
test('observation bound to exact plan, pad and explicit actual outcome',async()=>{const {planComparison,recordObservation}=await api,f=fixture(),p=planComparison(f.req,f.profile,f.ref);for(const change of [o=>o.planSha256='wrong',o=>o.padId='other',o=>o.outcome='software-success',o=>o.appliedDoseDegrees=null]){const o=observation(p);change(o);assert.throws(()=>recordObservation(p,o));}p.trials[0].doseDegrees=99;assert.throws(()=>recordObservation(p,observation(p)),/digest/);});
test('actual current/rates are recorded and cannot be falsely claimed as matching plan',async()=>{const {planComparison,recordObservation}=await api,f=fixture(),p=planComparison(f.req,f.profile,f.ref);for(const key of ['appliedMotorCurrentMa','appliedDispenseDegreesPerMinute','appliedRetractionDegreesPerMinute']){const o=observation(p);o[key]++;assert.throws(()=>recordObservation(p,o),/conflicts with actual current\/rates/);o.settingsMatchedPlan=false;const r=recordObservation(p,o);assert.equal(r.observation.settingsMatchedPlan,false);}const o=observation(p);o.appliedMotorCurrentMa=null;assert.throws(()=>recordObservation(p,o),/required/);});
test('repeat stage requires three real reviews and uses only reserved pads',async()=>{const {planComparison,recordObservation,planRepeats}=await api,f=fixture(),p=planComparison(f.req,f.profile,f.ref),records=p.trials.map((_,i)=>recordObservation(p,observation(p,i))),r=planRepeats(p,records,selection(p));assert.deepEqual(r.trials.map(t=>t.padId),p.reservedRepeatPadIds);assert.deepEqual(r.trials.map(t=>t.doseDegrees),[2,2,2]);assert.equal(r.cumulativeGrossDegrees,12);assert.equal(r.demoAuthorized,false);assert.throws(()=>planRepeats(p,records.slice(1),selection(p)));});
test('uncertainty, altered applied dose and duplicate reviews block repeats',async()=>{const {planComparison,recordObservation,planRepeats}=await api;for(const kind of ['uncertain','altered','duplicate']){const f=fixture(),p=planComparison(f.req,f.profile,f.ref),obs=p.trials.map((_,i)=>observation(p,i));if(kind==='uncertain'){obs[0].outcome='uncertain';obs[0].assessment='unassessed';obs[0].appliedDoseDegrees=null;}if(kind==='altered')obs[0].appliedDoseDegrees=1.2;const records=obs.map(o=>recordObservation(p,o));if(kind==='duplicate')records[1]=records[0];assert.throws(()=>planRepeats(p,records,selection(p)));}});
test('different actual current or rate blocks repeat-stage qualification',async()=>{const {planComparison,recordObservation,planRepeats}=await api,f=fixture(),p=planComparison(f.req,f.profile,f.ref),obs=p.trials.map((_,i)=>observation(p,i));obs[0].appliedDispenseDegreesPerMinute=119;obs[0].settingsMatchedPlan=false;const records=obs.map(o=>recordObservation(p,o));assert.throws(()=>planRepeats(p,records,selection(p)),/dose\/current\/rates differ/);});
test('repeats cannot exceed remaining total or use stale registration',async()=>{const {planComparison,recordObservation,planRepeats}=await api,f=fixture();f.req.limits.maxTotalGrossDegrees=10;const p=planComparison(f.req,f.profile,f.ref),records=p.trials.map((_,i)=>recordObservation(p,observation(p,i)));assert.throws(()=>planRepeats(p,records,selection(p)),/stroke/);const s=selection(p);s.registrationCurrent=false;assert.throws(()=>planRepeats(p,records,s),/attestation/);});
test('CLI output is exclusive and actual evidence hashes are verified',async()=>{const {sha256}=await api,f=fixture(),dir=fs.mkdtempSync(path.join(os.tmpdir(),'coupon-offline-'));try{const req=path.join(dir,'request.json'),profile=path.join(dir,'profile.json'),out=path.join(dir,'plan.json'),obs=path.join(dir,'obs.json'),record=path.join(dir,'record.json'),image=path.join(dir,'image.txt'),settings=path.join(dir,'settings.txt'),cli=path.join(__dirname,'coupon-trials.mjs');fs.writeFileSync(req,JSON.stringify(f.req));fs.writeFileSync(profile,JSON.stringify(f.profile));const run=(...args)=>cp.spawnSync(process.execPath,[cli,...args],{encoding:'utf8'});assert.equal(run('compare',req,profile,out).status,0);assert.notEqual(run('compare',req,profile,out).status,0);const p=JSON.parse(fs.readFileSync(out)),o=observation(p);fs.writeFileSync(image,'synthetic only');fs.writeFileSync(settings,'synthetic current/rate settings');o.evidence=[{path:image,sha256:sha256(fs.readFileSync(image))}];o.settingsEvidence=[{path:settings,sha256:sha256(fs.readFileSync(settings))}];fs.writeFileSync(obs,JSON.stringify(o));assert.equal(run('record',out,obs,record).status,0);fs.writeFileSync(settings,'changed');assert.notEqual(run('record',out,obs,path.join(dir,'bad.json')).status,0);}finally{fs.rmSync(dir,{recursive:true,force:true});}});
