'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),G=require('./ftp-pad-group.cjs');
function fixture(){const pads=['R3.1','R2.2'].map((padId,i)=>{const surface={rawZ:58.4-i*.01,estimatedGapMm:.4,gapUncertaintyMm:.3};return {padId,rawPose:{X:10+i,Y:20,Z:surface.rawZ,A:720},padIdentityReviewed:true,padAvailableReviewed:true,availabilityCapturedMs:900,availabilityReportEvidence:{path:'/reviewed/'+padId+'/report.json',sha256:'a'.repeat(64)},availabilityImageEvidence:{path:'/reviewed/'+padId+'/top.png',sha256:'b'.repeat(64)},surface,surfaceEvidence:{path:'/reviewed/'+padId+'/surface.json',sha256:'c'.repeat(64)}};});return {createdMs:1000,jvmStartMs:1,liveConfigurationSha256:'d'.repeat(64),scope:G.selectedScope(false),mode:'wet',ftpTargetRecord:{reviewedMs:950,scope:'ftp-selected-pads-targets',inlineConditioning:{protocol:'scrap-condition-transit-selected-pads'},compensatedSequence:{protocol:'restore-dose-retract-lift-selected-pads',doseDegrees:4,retractDegrees:3,dwellMilliseconds:200,retractDwellMilliseconds:500,idleReliefDegrees:40},pads}};}
function report(q,p,path){return {status:'completed-contiguous-air-batch-awaiting-observation',controllerPositionVerified:true,uncertainCompletion:false,request:{jvmStartMs:q.jvmStartMs,liveConfigurationSha256:q.liveConfigurationSha256},finishedAt:new Date(p.availabilityCapturedMs).toISOString(),afterImages:{top:{path:'top.png'}}};}
test('selected pad policy admits individually reviewed registered identities and one-to-eight bounded surfaces',()=>{const q=fixture();G.validateSelected(q);q.scope=G.selectedScope(true);G.validateSelected(q);});
test('selected pad policy rejects duplicates, future/stale reports, missing surface proof and lower-gap failures',()=>{for(const edit of [q=>q.ftpTargetRecord.pads[1].padId='R3.1',q=>q.ftpTargetRecord.pads[0].padAvailableReviewed=false,q=>q.ftpTargetRecord.pads[0].availabilityCapturedMs=951,q=>q.ftpTargetRecord.pads[0].surface.estimatedGapMm=.39,q=>q.ftpTargetRecord.pads[0].surfaceEvidence=null,q=>q.ftpTargetRecord.pads.push(...Array(7).fill(q.ftpTargetRecord.pads[0]))]){const q=fixture();edit(q);assert.throws(()=>G.validateSelected(q));}const q=fixture();assert.throws(()=>G.validateSelected(q,300901),/Fresh/);});
test('selected availability report binds its own image, timestamp, JVM and config; surface binds report data',()=>{const q=fixture();G.verifySelectedImages(q,(e,json)=>{const p=q.ftpTargetRecord.pads.find(x=>x.availabilityReportEvidence.path===e.path||x.surfaceEvidence.path===e.path);if(!json)return null;if(e.path.endsWith('surface.json'))return {surface:p.surface};return report(q,p);});for(const edit of [r=>r.request.jvmStartMs++,r=>r.uncertainCompletion=true,r=>r.afterImages.top.path='other.png',r=>r.finishedAt=new Date(899).toISOString()]){const q2=fixture();assert.throws(()=>G.verifySelectedImages(q2,(e,json)=>{const p=q2.ftpTargetRecord.pads.find(x=>x.availabilityReportEvidence.path===e.path||x.surfaceEvidence.path===e.path);if(e.path.endsWith('surface.json'))return {surface:p.surface};const r=report(q2,p);edit(r);return r;}));}});
test('selected batch history receives its own explicit 96-stage scope',()=>{assert.equal(G.stageIndex(39),true);assert.equal(G.stageIndex(40),false);assert.equal(G.stageIndex(95,G.selectedScope(false)),true);assert.equal(G.stageIndex(96,G.selectedScope(false)),false);assert.equal(G.stageIndex(95,G.scope(false)),true);assert.equal(G.stageIndex(96,G.scope(false)),false);});
test('separate forty-pad scope retains individual evidence gates and has a bounded 400-stage cap',()=>{const q=fixture();q.scope=G.selected40Scope(false);q.ftpTargetRecord.pads=Array.from({length:40},(_,i)=>{const ref=Math.floor(i/2)+1,pad=i%2+1;return {...q.ftpTargetRecord.pads[i%2],padId:`R${ref}.${pad}`,rawPose:{X:10+i,Y:20,Z:58.4,A:720},surface:{rawZ:58.4,estimatedGapMm:.404,gapUncertaintyMm:.3}};});q.ftpTargetRecord.pads.forEach(p=>p.rawPose.Z=p.surface.rawZ);G.validateSelected(q);assert.equal(G.stageIndex(399,G.selected40Scope(false)),true);assert.equal(G.stageIndex(400,G.selected40Scope(false)),false);q.ftpTargetRecord.pads.push({...q.ftpTargetRecord.pads[0],padId:'R21.1'});assert.throws(()=>G.validateSelected(q),/forty/);});
