'use strict';
// Pure, narrowly scoped FTP demo target policy. readEvidence is supplied by the
// caller and MUST verify file SHA-256 before returning JSON or image bytes.
(function(root){
var fail=function(s){throw Error(s);},hash=/^[a-f0-9]{64}$/;
var Cleanup=typeof module!=='undefined'&&module.exports?require('./ftp-one-pad-cleanup.cjs'):root.PasteFtpOnePadCleanup;
var Group=typeof module!=='undefined'&&module.exports?require('./ftp-pad-group.cjs'):root.PasteFtpPadGroup;
var Revalidation=typeof module!=='undefined'&&module.exports?require('./ftp-registration-revalidation.cjs'):root.PasteFtpRegistrationRevalidation;
var FastCamera=typeof module!=='undefined'&&module.exports?require('./fast-camera-inspection.cjs'):root.PasteFastCameraInspection;
var Inline=typeof module!=='undefined'&&module.exports?require('./ftp-inline-conditioning.cjs'):root.PasteFtpInlineConditioning;
function stroke(){return typeof module!=='undefined'&&module.exports?require('./commissioning-stroke.cjs'):root.CommissioningStroke;}
function number(v,label){if(typeof v!=='number'||!isFinite(v))fail(label+' must be finite');return v;}
function evidence(e){if(!e||typeof e.path!=='string'||e.path.charAt(0)!=='/'||!hash.test(e.sha256))fail('FTP evidence path/hash required');return e;}
function allowedHeldoutIds(ids){var k=ids.slice().sort().join(',');return k==='R1.2,R16.1,R40.1'||k==='R1.2,R16.1,R24.1';}
function allowedHeldoutRefs(refs){var k=refs.slice().sort().join(',');return k==='R1,R16,R40'||k==='R1,R16,R24';}
function heldoutSpread(ids,registered){var pts=ids.map(function(id){var p=registered[id];if(!p||!Array.isArray(p.machineXYMm)||p.machineXYMm.length!==2)fail('Held-out registered pad target missing');return [number(p.machineXYMm[0],'held-out X'),number(p.machineXYMm[1],'held-out Y')];});var xs=pts.map(function(p){return p[0];}),ys=pts.map(function(p){return p[1];});if(Math.max.apply(null,xs)-Math.min.apply(null,xs)<25||Math.max.apply(null,ys)-Math.min.apply(null,ys)<25)fail('Held-out pads must remain at least 25 mm apart on both XY axes');}
function same(a,b){if(a===b)return true;if(!a||!b||typeof a!=='object'||typeof b!=='object'||Array.isArray(a)!==Array.isArray(b))return false;var ak=Object.keys(a).sort(),bk=Object.keys(b).sort();return JSON.stringify(ak)===JSON.stringify(bk)&&ak.every(function(k){return same(a[k],b[k]);});}
function close(a,b,label){if(Math.abs(number(a,label)-Math.round(number(b,label)*100)/100)>1e-9)fail(label+' differs from registered target');}
function scope(preview,q){if(Cleanup&&Cleanup.isCleanup(q))return Cleanup.scope(preview);if(Group&&Group.isMinimumTravelTrial(q))return Group.minimumTravelTrialScope(preview);if(Group&&Group.isRetractionComparison(q))return Group.retractionComparisonScope(preview);if(Group&&Group.isSelected40(q))return Group.selected40Scope(preview);if(Group&&Group.isSelected(q))return Group.selectedScope(preview);if(Group&&Group.isGroup(q))return Group.scope(preview);return Inline&&Inline.isInline(q)?Inline.scope(preview):'contiguous-native-ftp-two-pad'+(preview?'-preview':'');}
function isFtp(q){return q&&(q.scope===scope(false)||q.scope===scope(true)||Cleanup&&Cleanup.isCleanup(q)||Group&&Group.isSelected40(q)||Group&&Group.isRetractionComparison(q)||Group&&Group.isMinimumTravelTrial(q)||Inline&&Inline.isInline(q));}
function integer(v,lo,hi,label){if(Math.floor(number(v,label))!==v||v<lo||v>hi)fail(label+' outside reviewed integer range');return v;}
function entryTime(q,now){if(Inline&&Inline.isInline(q))return;var c=q.ftpTargetRecord&&q.ftpTargetRecord.compensatedSequence;if(!c)return;var elapsed=number(now,'entry time')-number(c.conditioningFinishedMs,'conditioning finish');if(elapsed<0||elapsed>integer(c.maximumElapsedMilliseconds,1,300000,'conditioning elapsed limit'))fail('FTP conditioning entry state expired');}
function retractWait(c){var v=c.retractDwellMilliseconds===undefined?0:c.retractDwellMilliseconds;if([0,200,500].indexOf(v)<0)fail('FTP retraction wait must be 0, 200 or 500 ms');return v;}
function minimumTravel(q,t,now){
 Group.validateMinimumTravelTrial(q,now);var c=t.compensatedSequence,covered=Inline.prefix(q),Stroke=stroke();
 function at(i,axis){integer(i,0,q.previewStages.length-1,'minimum-travel stage');var st=q.previewStages[i];if(st.axis!==axis||covered[i])fail('Minimum-travel stage axis/duplicate index');covered[i]=true;return st;}
 function b(i,delta,p,dwell,surface,evidenceRef,actual){var st=at(i,'B'),s=surface||p.surface,se=evidenceRef||p.surfaceEvidence,observed=st.targetRaw.B-st.startRaw.B;if(actual===undefined?observed!==delta:Math.abs(observed-actual)>1e-9)fail('Minimum-travel B amount differs');if((st.dwellMilliseconds||0)!==dwell)fail('Minimum-travel dwell differs');['X','Y','Z','A'].forEach(function(k){if(st.startRaw[k]!==p.rawPose[k]||st.targetRaw[k]!==p.rawPose[k])fail('Minimum-travel B pose differs');});var gap=s.estimatedGapMm+(s.rawZ-p.rawPose.Z);if(!same(st.gapEvidence,se)||Math.abs(number(st.estimatedGapMm,'derived gap')-gap)>1e-9||st.gapUncertaintyMm!==s.gapUncertaintyMm)fail('Minimum-travel B gap/source differs');return st;}
 t.pads.forEach(function(p,i){var pair=p.pairOrder,ds=p.doseStageIndices;if(!Array.isArray(ds)||ds.length!==1)fail('Minimum-travel pad needs exactly one six-degree dose');
  if(pair===1){if(p.doseStageIndices[0]!==p.restoreStageIndex+1)fail('Pair-start restore must precede its dose with no intervening B stage');var source=q.previewStages[p.restoreSourceStageIndex],rs=at(p.restoreStageIndex,'B');Stroke.validateMinimumTrialRestore(p,rs,source);if((rs.dwellMilliseconds||0)!==0||!same(rs.gapEvidence,p.surfaceEvidence)||rs.gapUncertaintyMm!==p.surface.gapUncertaintyMm||Math.abs(rs.estimatedGapMm-(p.surface.estimatedGapMm+(p.surface.rawZ-p.rawPose.Z)))>1e-9)fail('Pair-start restore gap/dwell differs');['X','Y','Z','A'].forEach(function(k){if(rs.startRaw[k]!==p.rawPose[k]||rs.targetRaw[k]!==p.rawPose[k])fail('Pair-start restore pose differs');});}
  else if(pair!==2||p.restoreStageIndex!==null||p.restoreSourceStageIndex!==null)fail('Only pair-start pads may restore');
  b(ds[0],-6,p,c.dwellMilliseconds,p.surface,p.surfaceEvidence);
  var liftIndex;if(pair===1){if(p.retractStageIndex!==null||p.liftStageIndex!==ds[0]+1)fail('First pad must lift directly without an interim retract');liftIndex=p.liftStageIndex;}
  else{if(p.retractStageIndex!==ds[0]+1||p.liftStageIndex!==p.retractStageIndex+1)fail('Second pad must retract only after its paired dose, then lift');var rs2=b(p.retractStageIndex,p.actualRetractRawDelta,p,c.retractDwellMilliseconds,p.surface,p.surfaceEvidence,p.actualRetractRawDelta);Stroke.validateMinimumTrialRetraction(q,p,rs2);liftIndex=p.liftStageIndex;}
  var lift=at(liftIndex,'Z');if(lift.startRaw.Z!==p.surface.rawZ||lift.targetRaw.Z!==q.xyClearanceRawZ)fail('Every paired pad must preserve the reviewed clearance lift');
 });
 if(c.finalIdleStageIndices===undefined||!Array.isArray(c.finalIdleStageIndices)||c.finalIdleStageIndices.length!==2)fail('Minimum-travel route needs two clearance relief stages');var lastPad=t.pads[t.pads.length-1],idle=c.finalIdleStageIndices;
 idle.forEach(function(i,n){if(i!==lastPad.liftStageIndex+1+n||n===1&&i!==q.previewStages.length-1)fail('Final clearance relief must immediately follow the last lift');var st=at(i,'B'),pose=st.startRaw;if(st.targetRaw.B-st.startRaw.B!==20||pose.Z!==q.xyClearanceRawZ||st.targetRaw.Z!==q.xyClearanceRawZ||st.dwellMilliseconds!==(n===1?2000:0)||!same(st.gapEvidence,lastPad.surfaceEvidence))fail('Final 40-degree relief must be two +20 stages at clearance with last dwell');});
 q.previewStages.forEach(function(st,i){if(st.axis==='B'&&!covered[i])fail('Unaccounted minimum-travel B stage');});return covered;
}
function compensated(q,t,now){
 if(Group&&Group.isMinimumTravelTrial(q))return minimumTravel(q,t,now);
 var comparison=Group&&Group.isRetractionComparison(q),selected=Group&&(Group.isSelected(q)||Group.isSelected40(q));
 var c=t.compensatedSequence;if(c===undefined)return null;if(!c)fail('Explicit compensated FTP object required');
 if(q.mode!=='wet'||c.schema!==1||c.protocol!==(comparison?'restore-dose-retract-lift-retraction-comparison':selected?'restore-dose-retract-lift-selected-pads':Group&&Group.isGroup(q)?'restore-dose-retract-lift-eight-pad':'restore-dose-retract-lift-two-pad')||[2,3,4,6,12,20].indexOf(c.doseDegrees)<0||(!comparison&&[2,3,4,6].indexOf(c.retractDegrees)<0)||(comparison&&(c.doseDegrees!==6||c.conditioningRetractDegrees!==3)))fail('Unknown compensated FTP protocol/amount');
 integer(c.dwellMilliseconds,0,2000,'FTP dose dwell');entryTime(q,now);var wait=retractWait(c),idle=c.idleReliefDegrees===undefined?20:c.idleReliefDegrees;if([20,40].indexOf(idle)<0)fail('FTP idle relief must be 20 or 40 degrees');
 if(!Inline.isInline(q))['conditioningReportEvidence','conditioningLedgerEvidence','preparationExperimentEvidence','tipObservationEvidence'].forEach(function(k){evidence(c[k]);});
 if(!Inline.isInline(q)&&(!same(c.conditioningReportEvidence,q.previousReportEvidence)||c.conditioningLedgerEvidence.sha256!==q.previousLedgerSha256))fail('FTP conditioning must be exact preceding charged report/ledger');
 var covered=Inline.isInline(q)?Inline.prefix(q):{},last=Inline.isInline(q)?t.inlineConditioning.prefixStageCount-1:-1;
 function at(i,axis){integer(i,0,q.previewStages.length-1,'FTP stage index');var st=q.previewStages[i];if(st.axis!==axis||covered[i])fail('FTP stage axis/duplicate index');covered[i]=true;return st;}
 function b(i,delta,p,dwell,surface,surfaceEvidence,actualDelta){var st=at(i,'B'),s=surface||t.surface,se=surfaceEvidence||t.surfaceEvidence;if((actualDelta===undefined?st.targetRaw.B-st.startRaw.B!==delta:Math.abs((st.targetRaw.B-st.startRaw.B)-actualDelta)>1e-9)||(st.dwellMilliseconds||0)!==dwell)fail('FTP compensated amount/dwell differs');['X','Y','Z','A'].forEach(function(k){if(st.startRaw[k]!==p[k]||st.targetRaw[k]!==p[k])fail('FTP compensated pose differs');});var gap=s.estimatedGapMm+(s.rawZ-p.Z);if(!same(st.gapEvidence,se)||Math.abs(number(st.estimatedGapMm,'derived gap')-gap)>1e-9||st.gapUncertaintyMm!==s.gapUncertaintyMm)fail('FTP compensated gap differs');}
 t.pads.forEach(function(p){
  if(p.doseStageIndex!==undefined)fail('Compensated FTP uses explicit doseStageIndices only');
  var ds=p.doseStageIndices,count=c.doseDegrees===12?2:1;
  if(!Array.isArray(ds)||ds.length!==count||p.restoreStageIndex<=last)fail('FTP ordered dose group required');
  var ps=(selected||comparison)?p.surface:t.surface,pe=(selected||comparison)?p.surfaceEvidence:t.surfaceEvidence;
  var restoreDelta=comparison?p.restoreRawDelta:-c.retractDegrees;
  b(p.restoreStageIndex,comparison?0:-c.retractDegrees,p.rawPose,0,ps,pe,comparison?restoreDelta:undefined);
  ds.forEach(function(i,n){if(i!==p.restoreStageIndex+1+n)fail('FTP dose stages must immediately follow restore');b(i,c.doseDegrees===12?-6:-c.doseDegrees,p.rawPose,n===count-1?c.dwellMilliseconds:0,ps,pe);});
  if(p.retractStageIndex!==ds[count-1]+1||p.liftStageIndex!==p.retractStageIndex+1)fail('FTP immediate retract and lift required');
  if(comparison){var strokePolicy=stroke(),priorRetract,group=t.retractionComparison.groups[p.group-1],padOrder=group&&group.padIds;if(!group||!padOrder||[1,2,3,4].indexOf(p.group)<0)fail('Comparison pad lacks an exact group mapping');if(p.padId===padOrder[0])priorRetract=q.previewStages[group.prefixStartStageIndex+t.inlineConditioning.retractionStageIndex];else{var orderedIndex=t.pads.indexOf(p);if(orderedIndex<=0||t.pads[orderedIndex-1].group!==p.group)fail('Comparison restore must follow a same-group preceding pad');priorRetract=q.previewStages[t.pads[orderedIndex-1].retractStageIndex];}if(strokePolicy&&strokePolicy.validateFractionalComparisonRestore)strokePolicy.validateFractionalComparisonRestore(t.retractionComparison,p,q.previewStages[p.restoreStageIndex],priorRetract);if(strokePolicy&&strokePolicy.validateFractionalRetractionComparison)strokePolicy.validateFractionalRetractionComparison(t.retractionComparison,p,q.previewStages[p.retractStageIndex],4.44);}
  b(p.retractStageIndex,comparison?0:c.retractDegrees,p.rawPose,wait,ps,pe,comparison?p.actualRetractRawDelta:undefined);var lift=at(p.liftStageIndex,'Z');if(lift.startRaw.Z!==ps.rawZ||lift.targetRaw.Z!==q.xyClearanceRawZ)fail('FTP lift must reach common clearance');last=p.liftStageIndex;
 });
 var finalPad=t.pads[t.pads.length-1],idleSurface=(selected||comparison)?finalPad.surface:t.surface,idleEvidence=(selected||comparison)?finalPad.surfaceEvidence:t.surfaceEvidence;
 if(comparison){
  if(idle!==40||c.finalIdleStageIndex!==undefined||c.finalIdleStageIndices!==undefined)fail('Comparison uses per-group 40-degree finishing relief only');
  t.retractionComparison.groups.forEach(function(g,gi){var block=t.pads.slice(gi*8,gi*8+8),pad=block[block.length-1],ids=g.groupIdleReliefStageIndices,ps=pad.surface,pe=pad.surfaceEvidence;if(!Array.isArray(ids)||ids.length!==2||ids[0]!==pad.liftStageIndex+1||ids[1]!==ids[0]+1||g.groupEndStageIndex!==ids[1])fail('Each comparison group requires a bound two-stage 40-degree relief after its final lift');b(ids[0],20,{X:q.previewStages[ids[0]].startRaw.X,Y:q.previewStages[ids[0]].startRaw.Y,Z:q.xyClearanceRawZ,A:q.expectedRaw.A},0,ps,pe);b(ids[1],20,{X:q.previewStages[ids[1]].startRaw.X,Y:q.previewStages[ids[1]].startRaw.Y,Z:q.xyClearanceRawZ,A:q.expectedRaw.A},2000,ps,pe);if(gi<t.retractionComparison.groups.length-1&&ids[1]+1!==t.retractionComparison.groups[gi+1].resetStartStageIndex||gi===t.retractionComparison.groups.length-1&&ids[1]!==q.previewStages.length-1)fail('Comparison group relief/reset boundaries differ');});
 }else{
  var idleIndices;if(idle===20){if(c.finalIdleStageIndices!==undefined)fail('Single idle uses finalIdleStageIndex');idleIndices=[c.finalIdleStageIndex];}else{if(c.finalIdleStageIndex!==undefined||!Array.isArray(c.finalIdleStageIndices)||c.finalIdleStageIndices.length!==2)fail('Double idle needs exactly two finalIdleStageIndices');idleIndices=c.finalIdleStageIndices;}
  idleIndices.forEach(function(i,n){if(i!==last+1+n||n===idleIndices.length-1&&i!==q.previewStages.length-1)fail('FTP final idle must immediately follow final pad lift and end route');var final=q.previewStages[i];if(!final)fail('FTP final idle stage missing');b(i,20,{X:final.startRaw.X,Y:final.startRaw.Y,Z:q.xyClearanceRawZ,A:q.expectedRaw.A},n===idleIndices.length-1?2000:0,idleSurface,idleEvidence);});
 }
 q.previewStages.forEach(function(st,i){if(st.axis==='B'&&!covered[i])fail('FTP unaccounted B stage');});return covered;
}
function verifyConditioning(q,read){if(Inline.isInline(q)){Inline.sources(q,read);return;}
 var t=q.ftpTargetRecord,c=t.compensatedSequence;if(!c)return;
 var wait=retractWait(c),r=read(c.conditioningReportEvidence,true),l=read(c.conditioningLedgerEvidence,true),e=read(c.preparationExperimentEvidence,true),o=read(c.tipObservationEvidence,true),rq=r&&r.request;
 var priorJvmAllowed=r&&r.request&&q.applicationRestartEvidence&&q.applicationRestartEvidence.sessionId===q.sessionId&&q.applicationRestartEvidence.newJvmStartMs===q.jvmStartMs&&q.applicationRestartEvidence.liveConfigurationSha256===q.liveConfigurationSha256&&Array.isArray(q.applicationRestartEvidence.allowedJvmStartMs)&&q.applicationRestartEvidence.allowedJvmStartMs.indexOf(r.request.jvmStartMs)>=0;
 if(!rq||r.status!=='completed-contiguous-batch-awaiting-observation'||r.controllerPositionVerified!==true||r.uncertainCompletion!==false||r.id!==rq.id||rq.scope!=='contiguous-native-scrap-batch'||rq.mode!=='wet'||rq.sessionId!==q.sessionId||rq.syringeId!==q.syringeId||!(rq.jvmStartMs===q.jvmStartMs||priorJvmAllowed)||rq.liveConfigurationSha256!==q.liveConfigurationSha256||r.completedLedgerSha256!==q.previousLedgerSha256)fail('Verified same-session scrap conditioning report required');
 if(!isFinite(Date.parse(r.finishedAt))||Date.parse(r.finishedAt)<c.conditioningFinishedMs||!l||l.status!=='verified'||l.sessionId!==q.sessionId||l.syringeId!==q.syringeId||l.lastVerifiedB!==q.expectedRaw.B||!r.afterQuerySnapshot||r.afterQuerySnapshot.raw.B!==q.expectedRaw.B)fail('FTP conditioning terminal B/ledger/time differs');
 if(!e||e.schema!==1||e.scope!=='reviewed-scrap-retraction-coupon'||e.mode!=='transfer-preparation'||e.retractDegrees!==c.retractDegrees||e.maximumTransferElapsedMilliseconds!==c.maximumElapsedMilliseconds||e.conditioningDoseDegrees!==20||(e.retractDwellMilliseconds===undefined?0:e.retractDwellMilliseconds)!==wait)fail('Explicit transfer-preparation experiment required');
 var review=read(evidence(rq.clearanceReviewEvidence),true);if(!same(review.experimentEvidence,c.preparationExperimentEvidence))fail('Conditioning review does not bind preparation experiment');
 var stages=rq.previewStages,done=r.stages;if(!Array.isArray(stages)||stages.length<3||!Array.isArray(done)||done.length!==stages.length)fail('Complete conditioning stage history required');
 stages.forEach(function(s,i){var d=done[i];if(!d||d.index!==i||d.verified!==true||d.axis!==s.axis||!same(d.startRaw,s.startRaw)||!same(d.targetRaw,s.targetRaw))fail('Unverified conditioning stage');});
 var n=stages.length;if(Date.parse(done[n-2].finishedAt)!==c.conditioningFinishedMs)fail('Conditioning clock must start at verified retraction');var dose=stages[n-3],retract=stages[n-2],lift=stages[n-1];
 if(dose.axis!=='B'||dose.targetRaw.B-dose.startRaw.B!==-20||dose.startRaw.Z!==e.workRawZ||(dose.dwellMilliseconds||0)!==(e.conditioningDwellMilliseconds===undefined?(e.dwellMilliseconds===undefined?2000:e.dwellMilliseconds):e.conditioningDwellMilliseconds)||retract.axis!=='B'||retract.targetRaw.B-retract.startRaw.B!==c.retractDegrees||(retract.dwellMilliseconds||0)!==wait||lift.axis!=='Z'||lift.targetRaw.Z!==e.clearanceRawZ||!same(dose.targetRaw,retract.startRaw)||!same(retract.targetRaw,lift.startRaw)||!same(lift.targetRaw,rq.finalTargetRaw)||!same(lift.targetRaw,r.afterQuerySnapshot.raw)||lift.targetRaw.B!==q.expectedRaw.B)fail('Conditioning must end with dose, selected retract, lift and no idle relief');
 if(wait){var w=done[n-2].dwell;if(!w||w.requestedMilliseconds!==wait||w.stopObserved!==false||number(w.actualElapsedMilliseconds,'actual conditioning retract wait')<wait||!isFinite(Date.parse(w.endedAt))||Date.parse(w.endedAt)<c.conditioningFinishedMs+wait||Date.parse(w.endedAt)>Date.parse(r.finishedAt)||!o||number(o.capturedMs,'post-wait tip capture')<Date.parse(r.finishedAt))fail('Verified conditioning retract dwell and subsequent tip observation required');}
 var tail=l.entries&&l.entries[l.entries.length-1];if(!tail||tail.status!=='verified'||tail.batchId!==r.id||tail.stageIndex!==n-2||tail.targetB!==q.expectedRaw.B||tail.deltaDegrees!==c.retractDegrees)fail('Conditioning is not the current charged ledger tail');
 if(!o||o.noLongStrand!==true||typeof o.reviewedBy!=='string'||!o.reviewedBy.trim()||!same(o.conditioningReportEvidence,c.conditioningReportEvidence)||integer(o.reviewedMs,c.conditioningFinishedMs,t.reviewedMs,'tip observation time')!==o.reviewedMs||integer(o.capturedMs,c.conditioningFinishedMs,o.reviewedMs,'tip capture time')!==o.capturedMs)fail('Fresh authored tip observation required');read(evidence(o.imageEvidence),false);
}
function validate(q,now){
 var cleanup=Cleanup&&Cleanup.isCleanup(q),group=Group&&Group.isGroup(q),comparison=Group&&Group.isRetractionComparison(q),minimum=Group&&Group.isMinimumTravelTrial(q),selected=Group&&(Group.isSelected(q)||Group.isSelected40(q));if(cleanup)Cleanup.validate(q,now);if(group)Group.validate(q,now);if(minimum)Group.validateMinimumTravelTrial(q,now);if(selected||comparison)Group.validateSelected(q,now);var t=q.ftpTargetRecord;if(!Inline.isInline(q)&&t&&t.inlineConditioning!==undefined)fail('Inline conditioning requires its separate scope');if(!t||t.schema!==1||t.scope!==(cleanup?'ftp-one-pad-cleanup-targets':(selected||comparison||minimum)?'ftp-selected-pads-targets':group?'ftp-eight-pad-commissioning-targets':'ftp-two-pad-commissioning-targets')||typeof t.boardId!=='string'||!t.boardId.trim())fail('Explicit FTP board identity/target record required');
 evidence(q.ftpTargetEvidence);if(t.quantizationMm!==0.01)fail('FTP targets must explicitly use the 0.01 mm report grid');
 if(t.sessionId!==q.sessionId||t.jvmStartMs!==q.jvmStartMs||t.liveConfigurationSha256!==q.liveConfigurationSha256)fail('FTP session/configuration mismatch');
 if(typeof t.reviewedBy!=='string'||!t.reviewedBy.trim()||Math.floor(number(t.reviewedMs,'FTP review time'))!==t.reviewedMs||t.reviewedMs>now||now-t.reviewedMs>300000)fail('Fresh explicitly authored FTP review required');
 if(!cleanup&&(t.boardCleaned!==true||t.padsAvailable!==true)||t.boardUnmovedSinceRegistration!==true||t.provenance!=='commissioning-provisional'||t.precisionCalibrated!==false||t.flowCalibrated!==false)fail('Explicit cleaned/unmoved/available FTP attestations and provisional status required');
 evidence(t.cadEvidence);evidence(t.registrationEvidence);evidence(t.tipOffsetEvidence);evidence(t.surfaceEvidence);evidence(cleanup?t.pads[0].defectImageEvidence:t.padAvailabilityImage);
 if(!Array.isArray(t.cameraMinusTipXYMm)||t.cameraMinusTipXYMm.length!==2)fail('Explicit parent-chosen provisional tip offset required');t.cameraMinusTipXYMm.forEach(function(x){number(x,'tip offset');});
 var s=t.surface;if(!s||number(s.rawZ,'FTP dispense Z')<=q.xyClearanceRawZ||number(s.estimatedGapMm,'FTP gap')<=0||number(s.gapUncertaintyMm,'FTP uncertainty')<0||s.estimatedGapMm-s.gapUncertaintyMm<0.1)fail('FTP board-specific positive gap required');
 if(!Array.isArray(t.padChecks)||t.padChecks.length!==3||!allowedHeldoutRefs(t.padChecks.map(function(c){return c.reference;})))fail('Three distinct supported distant FTP pad checks required');
 t.padChecks.forEach(function(c){if(c.reviewedAligned!==true||!new RegExp('^'+c.reference+'\\.[12]$').test(c.padId))fail('Explicit reviewed distant-pad identity required');evidence(c.reportEvidence);evidence(c.imageEvidence);});
 if(!Array.isArray(t.pads)||t.pads.length!==(cleanup?1:group?8:(selected||comparison||minimum)?t.pads.length:2)||(selected||comparison||minimum)&&(t.pads.length<1||t.pads.length>(comparison?32:minimum?8:Group.isSelected40(q)?40:8)))fail('FTP selected/pair/group pad count required');
 var minimum=Group&&Group.isMinimumTravelTrial(q),ids={},ref=null,indices={},maxSurfaceZ=s.rawZ;t.pads.forEach(function(p){var m=/^(R(?:[1-9]|[1-3][0-9]|40))\.([12])$/.exec(p.padId);if(!m||ids[p.padId]||!group&&!selected&&!comparison&&!minimum&&ref&&m[1]!==ref)fail('Two unique pads of the same resistor required');ids[p.padId]=true;ref=m[1];var ps=(selected||comparison||minimum)?p.surface:s;if(selected||comparison||minimum){number(ps.rawZ,'selected pad surface Z');number(ps.estimatedGapMm,'selected pad gap');number(ps.gapUncertaintyMm,'selected pad uncertainty');if(ps.estimatedGapMm-ps.gapUncertaintyMm<0.1||ps.rawZ<=q.xyClearanceRawZ)fail('Selected pad surface needs positive lower gap above clearance');if(ps.rawZ>maxSurfaceZ)maxSurfaceZ=ps.rawZ;}
  if(!p.rawPose)fail('FTP pad pose required');['X','Y','Z','A'].forEach(function(k){number(p.rawPose[k],'pad '+k);});
  if(['X','Y','Z'].some(function(k){return Math.abs(p.rawPose[k]-Math.round(p.rawPose[k]*100)/100)>1e-9;}))fail('FTP raw target must be on the 0.01 mm report grid');
  if(p.rawPose.Z!==ps.rawZ||p.rawPose.A!==q.expectedRaw.A)fail('FTP target Z/A differs');
  if(q.mode==='wet'&&!cleanup&&!t.compensatedSequence){var i=number(p.doseStageIndex,'dose stage');if(Math.floor(i)!==i||i<0||i>=q.previewStages.length||indices[i])fail('Unique FTP dose stage indices required');indices[i]=p;}
  else if(q.mode==='air'&&p.doseStageIndex!==null)fail('Air FTP record must not map a B dose stage');
 });
 if(q.rawBounds.Z.max>(Inline.isInline(q)?Math.max(maxSurfaceZ,t.inlineConditioning.experiment.workRawZ):maxSurfaceZ))fail('FTP route exceeds reviewed board dispense Z');
 var coverage=cleanup?Cleanup.coverage(q,t):compensated(q,t,now);
 var doses=0;q.previewStages.forEach(function(st,i){if(Inline.isInline(q)&&Inline.isPrefixStage(q,i))return;if(st.wipeReview===true||((st.axis==='X'||st.axis==='Y')&&st.startRaw.Z!==q.xyClearanceRawZ))fail('FTP branch forbids low XY/wipe');
  if(coverage)return;
  if(st.axis==='B'&&st.targetRaw.B>=st.startRaw.B)fail('FTP permits only its two negative B dose stages');
  if(st.axis==='B'&&st.targetRaw.B<st.startRaw.B){var p=indices[i];if(!p)fail('Negative B outside the two FTP dose stages');['X','Y','Z','A'].forEach(function(k){if(st.startRaw[k]!==p.rawPose[k]||st.targetRaw[k]!==p.rawPose[k])fail('FTP dose pose differs from target record');});if(!same(st.gapEvidence,t.surfaceEvidence)||st.estimatedGapMm!==s.estimatedGapMm||st.gapUncertaintyMm!==s.gapUncertaintyMm)fail('FTP dose gap differs from board evidence');doses++;}
 });
 if(q.mode==='wet'&&!coverage&&doses!==2)fail('Exactly one negative B dose per FTP pad required');
 return t;
}
function affineSources(q,reg,registered,read,observe,fidReports,revalidated){
 if(!same(reg.fittedFiducials,['FID1','FID2','FID3'])||reg.independentFID3Check!==undefined)fail('Affine must identify three fitted fiducials and independent pads, not an independent FID3');
 function pair(v,label){if(!Array.isArray(v)||v.length!==2)fail(label+' pair required');return [number(v[0],label),number(v[1],label)];}
 function inverse(m){if(!Array.isArray(m)||m.length!==2)fail('2x2 matrix required');var a=pair(m[0],'matrix'),b=pair(m[1],'matrix'),d=a[0]*b[1]-a[1]*b[0];if(!isFinite(d)||Math.abs(d)<1e-9)fail('Degenerate matrix');return [[b[1]/d,-a[1]/d],[-b[0]/d,a[0]/d]];}
 function multiply(a,b){return [[a[0][0]*b[0][0]+a[0][1]*b[1][0],a[0][0]*b[0][1]+a[0][1]*b[1][1]],[a[1][0]*b[0][0]+a[1][1]*b[1][0],a[1][0]*b[0][1]+a[1][1]*b[1][1]]];}
 function distance(a,b){a=pair(a,'point');b=pair(b,'point');return Math.sqrt(Math.pow(a[0]-b[0],2)+Math.pow(a[1]-b[1],2));}
 function equalPair(a,b,label){if(distance(a,b)>1e-7)fail(label+' differs');}
 function frame(report){var snap=report.afterQuerySnapshot,raw=snap&&snap.raw,top=snap&&snap.nativePoses&&snap.nativePoses.top;if(!raw||!top||!same([raw.Z,raw.A,raw.B],reg.session.fixedRawZAB)||!same([top.z,top.rotation],reg.session.topCameraZRotation))fail('Affine camera proof Z/A/B or imaging plane differs');return pair([top.x,top.y],'camera center');}
 var tr=reg.transformFromThreeFiducials,m=tr&&tr.matrix,t=tr&&tr.translationMm;inverse(m);t=pair(t,'affine translation');var a=m[0][0],b=m[0][1],c=m[1][0],d=m[1][1],det=a*d-b*c,aa=a*a+c*c,bb=b*b+d*d,ab=a*b+c*d,disc=Math.sqrt(Math.pow(aa-bb,2)+4*ab*ab),lo=Math.sqrt(Math.max(0,(aa+bb-disc)/2)),hi=Math.sqrt(Math.max(0,(aa+bb+disc)/2)),skew=Math.abs(Math.acos(Math.max(-1,Math.min(1,ab/Math.sqrt(aa*bb))))*180/Math.PI-90);
 if(det<=0||number(lo,'affine minimum scale')<.99-1e-12||number(hi,'affine maximum scale')>1.01+1e-12||number(skew,'affine skew')>.3+1e-12)fail('Affine orientation/scale/skew gate failed');
 function apply(p){p=pair(p,'design point');return [a*p[0]+b*p[1]+t[0],c*p[0]+d*p[1]+t[1]];}
 var used={};['FID1','FID2','FID3'].forEach(function(k){var v=reg.measurements[k],report=fidReports[k];if(report&&report.request&&report.request.scope==='camera-only-registered-fast-inspection'){FastCamera.verifyCalibrationReport(report,k);}var xy=frame(report);equalPair(v.measuredTopCameraXYMm,xy,'Fitted camera source');equalPair(apply(v.designXYMm),xy,'Affine fiducial fit');used[report.id]=true;});
 Object.keys(registered).forEach(function(k){equalPair(apply(registered[k].designXYMm),registered[k].machineXYMm,'Affine pad prediction');});
 var je=evidence(reg.imageJacobianEvidence),j=read(je,true),samples=j&&j.sourceMeasurements;
 if(!j||j.schema!==1||j.scope!=='measured-top-camera-image-jacobian'||!same(j.session,{jvmStartMs:q.jvmStartMs,liveConfigurationSha256:q.liveConfigurationSha256})||!same(j.fixedRawZAB,reg.session.fixedRawZAB)||typeof j.reviewedBy!=='string'||!j.reviewedBy.trim()||!isFinite(j.reviewedMs)||Math.floor(j.reviewedMs)!==j.reviewedMs||j.reviewedMs>q.ftpTargetRecord.reviewedMs||!revalidated&&q.ftpTargetRecord.reviewedMs-j.reviewedMs>3600000||!Array.isArray(samples)||samples.length!==3)fail('Reviewed measured same-session Jacobian required');
 var centers=[],positions=[],jids={};samples.forEach(function(v){var report=read(evidence(v.report),true);observe(report,v.report,evidence(v.image));if(jids[report.id]||Date.parse(report.finishedAt)>j.reviewedMs)fail('Jacobian source identity/review time differs');jids[report.id]=true;var xy=frame(report);equalPair(v.rawXY,[report.afterQuerySnapshot.raw.X,report.afterQuerySnapshot.raw.Y],'Jacobian raw pose');positions.push(xy);centers.push(pair(v.centerPixels,'Jacobian center'));});
 function displacement(ps){return [[ps[1][0]-ps[0][0],ps[2][0]-ps[0][0]],[ps[1][1]-ps[0][1],ps[2][1]-ps[0][1]]];}
 var derived=multiply(displacement(centers),inverse(displacement(positions))),jm=j.pixelShiftPerCameraMm,inv=inverse(jm);equalPair(derived[0],jm[0],'Measured Jacobian');equalPair(derived[1],jm[1],'Measured Jacobian');
 var checks=reg.independentHeldOutPadChecks;if(!Array.isArray(checks)||checks.length!==3||!allowedHeldoutIds(checks.map(function(v){return v.padId;})))fail('Affine checks must be R1.2/R16.1 plus R24.1 or R40.1');heldoutSpread(checks.map(function(v){return v.padId;}),registered);
 checks.forEach(function(v){if(v.padIdentityReviewed!==true||v.centerMeasurementReviewed!==true)fail('Explicit independent pad image review required');var report=read(evidence(v.report),true);observe(report,v.report,evidence(v.image));if(report&&report.request&&report.request.scope==='camera-only-registered-fast-inspection'){FastCamera.verifyCalibrationReport(report,v.padId.split('.')[0]);}if(used[report.id])fail('Pad checks must be independent of fitted fiducials and each other');used[report.id]=true;var xy=frame(report),size=pair(v.imageSizePixels,'image size'),p=pair(v.observedCenterPixel,'observed pad center');if(size.some(function(n){return n<2||Math.floor(n)!==n;})||p.some(function(n,i){return n<0||n>=size[i];}))fail('Pad image bounds invalid');var center=[(size[0]-1)/2,(size[1]-1)/2],delta=[p[0]-center[0],p[1]-center[1]],measured=[xy[0]-inv[0][0]*delta[0]-inv[0][1]*delta[1],xy[1]-inv[1][0]*delta[0]-inv[1][1]*delta[1]],px=distance(p,center),mm=distance(measured,registered[v.padId].machineXYMm);if(px>8||mm>.08)fail('Independent affine pad exceeds 8 pixels or 0.08 mm');equalPair(v.cameraXYMm,xy,'Pad camera source');equalPair(v.imageCenterPixel,center,'Pad image center');equalPair(v.measuredPadXYMm,measured,'Measured pad point');equalPair(v.predictedMachineXYMm,registered[v.padId].machineXYMm,'Pad prediction');if(Math.abs(number(v.imageCenterErrorPx,'pad pixels')-px)>1e-7||Math.abs(number(v.residualMm,'pad residual')-mm)>1e-7)fail('Independent pad residual metadata differs');var current=q.ftpTargetRecord.padChecks.filter(function(p){return p.padId===v.padId;})[0];if(!current||!same(current.reportEvidence,v.report)||!same(current.imageEvidence,v.image))fail('FTP target pad checks must bind the accepted affine held-out images');});
}
function nativeSources(q,reg,registered,read,revalidated){
 var refs=['FID1','FID2','FID3'],src=reg.nativeSource,reviewedMs=q.ftpTargetRecord&&q.ftpTargetRecord.reviewedMs,maxAgeMs=revalidated?3600000:1800000;
 if(typeof reviewedMs!=='number'||!isFinite(reviewedMs)||Math.floor(reviewedMs)!==reviewedMs)fail('Native report review timestamp required');
 function pair(v,label){if(!Array.isArray(v)||v.length!==2)fail(label+' pair required');return [number(v[0],label),number(v[1],label)];}
 function distance(a,b){var x=pair(a,'point'),y=pair(b,'point'),dx=x[0]-y[0],dy=x[1]-y[1];return Math.sqrt(dx*dx+dy*dy);}
 function equalPair(a,b,label){if(distance(a,b)>1e-7)fail(label+' differs');}
 function axes(a,b,label){if(!a||!b||!same(a,b)||Object.keys(a).sort().join(',')!=='A,B,X,Y,Z')fail(label+' exact same five-axis model pose required');}
 if(!src||!Array.isArray(src.reports)||src.reports.length!==3||src.reports.map(function(v){return v.reference;}).join(',')!==refs.join(','))fail('Native registration must bind ordered FID1/FID2/FID3 reports');
 var tr=reg.transformFromFID1FID2;if(!tr||!Array.isArray(tr.matrix)||tr.matrix.length!==2||!Array.isArray(tr.translationMm))fail('Native similarity transform required');
 var a=number(tr.matrix[0][0],'similarity a'),minusB=number(tr.matrix[0][1],'similarity -b'),b=number(tr.matrix[1][0],'similarity b'),a2=number(tr.matrix[1][1],'similarity a'),tx=number(tr.translationMm[0],'similarity tx'),ty=number(tr.translationMm[1],'similarity ty');
 if(Math.abs(a-a2)>1e-9||Math.abs(minusB+b)>1e-9)fail('Native similarity matrix must preserve orientation');
 var scale=Math.sqrt(a*a+b*b);if(scale<.99||scale>1.01||Math.abs(number(tr.scale,'similarity scale')-scale)>1e-9)fail('Native similarity scale outside 0.99–1.01');
 function apply(p){p=pair(p,'native design coordinate');return [a*p[0]+minusB*p[1]+tx,b*p[0]+a2*p[1]+ty];}
 var reports={},boards={};
 refs.forEach(function(ref,i){
  var m=reg.measurements&&reg.measurements[ref],rref=m&&evidence(m.report),report=rref&&read(rref,true),det=report&&report.nativeFiducialDetection;
  if(!m||!report||report.schema!==1||report.scope!=='native-current-pose-fiducial-vision'||report.status!=='completed-native-fiducial-detection-awaiting-review'||report.error||report.physicalRegistrationEstablished!==false||report.noMotion!==true||report.noActuation!==true||report.noVacuum!==true||report.jobSaved!==false||report.configurationSaved!==false||report.modelPoseUnchanged!==true||report.configurationRestored!==true)fail('Completed no-motion native fiducial report required');
  var reportSource=src.reports[i],finishedMs=Date.parse(report.finishedAt);if(!reportSource||reportSource.reference!==ref||reportSource.path!==rref.path||reportSource.sha256!==rref.sha256||report.requestId!==m.reportId||report.finishedAt!==m.finishedAt||!report.requestId||reports[report.requestId]||!isFinite(finishedMs)||finishedMs>reviewedMs||reviewedMs-finishedMs>maxAgeMs)fail('Native fiducial report identity/time differs, is stale, or replays');reports[report.requestId]=true;
  if(report.jvmStartMs!==q.jvmStartMs||report.liveConfigurationBeforeSha256!==q.liveConfigurationSha256||report.liveConfigurationAfterSha256!==q.liveConfigurationSha256)fail('Native report must bind the exact current session/configuration');
  var be=evidence(report.sourceBarrier),barrier=read(be,true),snap=barrier&&barrier.afterQuerySnapshot;if(!barrier||!same(src.sourceBarriers[i],be)||barrier.schema!==1||barrier.status!=='completed-read-only-position-barrier'||barrier.controllerPositionVerified!==true||barrier.uncertainCompletion!==false||barrier.noMotionCommandSubmitted!==true||barrier.request.scope!=='read-only-native-position-barrier'||barrier.request.jvmStartMs!==q.jvmStartMs||barrier.request.liveConfigurationSha256!==q.liveConfigurationSha256||barrier.liveConfigurationSha256!==q.liveConfigurationSha256||report.sourceBarrierId!==barrier.request.id||!same(report.sourceBarrierSnapshot,snap))fail('Native report must bind its hash-verified same-session position barrier');
  if(!same(snap, {raw:{X:report.nativePose.rawAxes.X.model,Y:report.nativePose.rawAxes.Y.model,Z:report.nativePose.rawAxes.Z.model,A:report.nativePose.rawAxes.A.model,B:report.nativePose.rawAxes.B.model},driver:{X:report.nativePose.rawAxes.X.driver,Y:report.nativePose.rawAxes.Y.driver,Z:report.nativePose.rawAxes.Z.driver,A:report.nativePose.rawAxes.A.driver,B:report.nativePose.rawAxes.B.driver},nativePoses:snap.nativePoses}))fail('Native raw/driver axes differ from source barrier');
  axes(report.modelPoseBefore,report.modelPoseAfter,'Native detector');axes(report.modelPoseBefore,report.nativePose&&report.nativePose.rawAxes,'Native snapshot');
  var raw=report.modelPoseBefore;if(!same([raw.Z.model,raw.A.model,raw.B.model],reg.session.fixedRawZAB))fail('Native registration fixed Z/A/B differs from its reports');
  var board=report.board||{},cam=report.camera||{},nativePose=report.nativePose||{};
  if(board.boardId!==src.boardId||board.side!==src.boardSide||report.jobPath!==src.jobPath||!same(board.localToGlobalMatrix,src.localToGlobalMatrix)||cam.id!==src.cameraId)fail('Native registration board/job/camera identity differs');
  if(!cam.locationMm||!cam.locationAfterMm||!same(cam.locationMm,cam.locationAfterMm)||!same(cam.locationMm,nativePose.cameraLocationMm)||cam.exposureRestored!==true||cam.exposureUsed!==36)fail('Native report must bind and restore exact camera pose/exposure');
  if(!Array.isArray(board.fiducials)||board.fiducials.length!==3)fail('Native report must bind all saved board fiducials');
  var fids={};board.fiducials.forEach(function(f){if(!f||refs.indexOf(f.reference)<0||fids[f.reference])fail('Native report fiducial identities must be exact and unique');fids[f.reference]=f;});
  if(Object.keys(fids).sort().join(',')!==refs.slice().sort().join(','))fail('Native report must include exactly FID1/FID2/FID3');
  refs.forEach(function(k){var f=fids[k],expected=reg.measurements[k]&&reg.measurements[k].nativeFiducialDetection&&reg.measurements[k].nativeFiducialDetection.expectedMachineXYMm;if(!f.partId||!Array.isArray(f.localXYMm)||!Array.isArray(f.savedJobExpectedMachineXYMm))fail('Native report board fiducial source differs');});
  if(!det||det.reference!==ref||!det.visionSettingsId||!det.visionSettingsName)fail('Native fiducial detector result/identity missing');
  equalPair(det.detectedMachineXYMm,m.measuredTopCameraXYMm,'Native detected machine location');
  var fitXY=apply(m.designXYMm);if(ref!=='FID3')equalPair(fitXY,m.measuredTopCameraXYMm,'Native fitted fiducial');
  var fid=fids[ref],barrierTop=snap.nativePoses&&snap.nativePoses.top;equalPair(m.designXYMm,[Number(ref==='FID2'?12.5:62.5),Number(ref==='FID1'?5:70)],'Canonical CAD fiducial coordinate');
  if(!barrierTop)fail('Native source barrier top-camera pose missing');equalPair(det.expectedMachineXYMm,[barrierTop.x,barrierTop.y],'Native expected current camera position');
  var detResidual=distance(det.detectedMachineXYMm,det.expectedMachineXYMm);if(detResidual>2.0)fail('Native fiducial detection exceeds 2.0 mm expected-location limit');
  if(Math.abs(number(det.cameraCenterResidualMm,'native detector residual')-detResidual)>1e-6)fail('Native detector reported camera-center residual differs');
  if(!Array.isArray(det.keypoints)||!det.keypoints.length||!det.keypoints.some(function(k){if(!k)return false;var p=pair(k.machineXYMm,'native keypoint');return distance(p,m.measuredTopCameraXYMm)<=1e-7&&Math.abs(number(k.cameraCenterResidualMm,'keypoint residual')-detResidual)<=1e-6;}))fail('Native point must match one returned native keypoint');
  ['raw','nativeInput'].forEach(function(name){var v=report.images&&report.images[name],ev=v&&evidence(v);if(!ev||ev.path.slice(0,ev.path.lastIndexOf('/'))!==rref.path.slice(0,rref.path.lastIndexOf('/')))fail('Native source image must be beside its report');read(ev,false);});
  if(m.designXYMm.length!==2||!m.report||m.report.path!==rref.path||m.report.sha256!==rref.sha256)fail('Native registration measurement provenance mismatch');
 });
 var fitted=reg.measurements.FID3,pred3=apply(fitted.designXYMm),measured3=pair(fitted.measuredTopCameraXYMm,'native FID3 observation'),residual=distance(pred3,measured3),check=reg.independentFID3Check;
 if(!check||!same(check.predictedMachineXYMm,pred3)||!same(check.measuredTopCameraXYMm,measured3)||Math.abs(number(check.residualMm,'native FID3 residual')-residual)>1e-7||residual>.08||number(check.maximumAllowedMm,'native FID3 limit')!==.08)fail('Independent native FID3 residual exceeds 0.08 mm or is inconsistent');
 refs.slice(0,2).forEach(function(ref){var m=reg.measurements[ref];equalPair(apply(m.designXYMm),m.measuredTopCameraXYMm,'Native fitted FID point');});
 if(!Array.isArray(reg.resistorPadMachineXYTargets)||reg.resistorPadMachineXYTargets.length!==80)fail('Native registration must contain exactly 80 CAD pad targets');
 Object.keys(registered).forEach(function(k){equalPair(apply(registered[k].designXYMm),registered[k].machineXYMm,'Native registered pad prediction');});
}
function verifySources(q,readEvidence){
 if(Cleanup&&Cleanup.isCleanup(q))Cleanup.verifyImage(q,readEvidence);
 if(Group&&Group.isGroup(q))Group.verifyImages(q,readEvidence);
 if(Group&&(Group.isSelected(q)||Group.isSelected40(q)||Group.isMinimumTravelTrial(q)))Group.verifySelectedImages(q,readEvidence);
 var t=q.ftpTargetRecord,actual=readEvidence(evidence(q.ftpTargetEvidence),true);if(!same(actual,t))fail('FTP target record bytes/content differ');
 var reg=readEvidence(t.registrationEvidence,true);readEvidence(t.cadEvidence,false);readEvidence(Cleanup&&Cleanup.isCleanup(q)?t.pads[0].defectImageEvidence:t.padAvailabilityImage,false);
 var affine=reg&&reg.scope==='offline-fresh-ftp-three-fiducial-affine-with-held-out-pad-checks',native=reg&&reg.scope==='offline-native-fresh-ftp-two-fiducial-transform-with-third-point-check';if(!reg||!native&&!affine&&reg.scope!=='offline-fresh-ftp-two-fiducial-transform-with-third-point-check'||!reg.acceptance||reg.acceptance.passed!==true||!same(reg.board,t.cadEvidence)||!reg.session||reg.session.jvmStartMs!==q.jvmStartMs||reg.session.liveConfigurationSha256!==q.liveConfigurationSha256||!native&&!affine&&(!reg.independentFID3Check||number(reg.independentFID3Check.residualMm,'FID3 residual')<0||reg.independentFID3Check.residualMm>0.08))fail('Accepted same-session three-fiducial registration required');
 var revalidated=Revalidation.verify(q,reg,readEvidence);
 function observation(report,ev,image){
  if(!report||report.controllerPositionVerified!==true||report.uncertainCompletion!==false||['completed-camera-survey-awaiting-image-review','completed-contiguous-air-batch-awaiting-observation'].indexOf(report.status)<0||!report.request||report.request.jvmStartMs!==q.jvmStartMs||report.request.liveConfigurationSha256!==q.liveConfigurationSha256)fail('FTP camera evidence session/completion mismatch');
  var finished=Date.parse(report.finishedAt);if(!isFinite(finished)||finished>t.reviewedMs||!revalidated&&t.reviewedMs-finished>3600000)fail('FTP registration/pad checks must be reviewed within one hour');
  if(report.request.scope==='camera-only-registered-fast-inspection')FastCamera.verifyCalibrationReport(report);
  var top=report.afterImages&&report.afterImages.top;if(!top||image.path!==ev.path.slice(0,ev.path.lastIndexOf('/')+1)+top.path)fail('FTP image must belong to its camera report');readEvidence(image,false);
 }
 var fidReports={};if(native){if(reg.acceptance.nativeFiducialResidualMmMaximum!==2.0||reg.acceptance.fiducial3ResidualMmMaximum!==.08||reg.executionReady!==false||reg.physicalRegistrationEstablished!==false)fail('Native registration acceptance/provisional status fields required');}
 else ['FID1','FID2','FID3'].forEach(function(k){var m=reg.measurements&&reg.measurements[k];if(!m||number(m.imageCenterErrorPx,'fiducial centering')<0||m.imageCenterErrorPx>2)fail('Reviewed three centered fiducials required');var report=readEvidence(evidence(m.report),true);observation(report,m.report,evidence(m.image));fidReports[k]=report;});
 var registered={};if(!Array.isArray(reg.resistorPadMachineXYTargets)||reg.resistorPadMachineXYTargets.length!==80)fail('FTP registration must contain 80 pad targets');reg.resistorPadMachineXYTargets.forEach(function(p){if(registered[p.padId])fail('Duplicate registered pad');registered[p.padId]=p;});if(affine)heldoutSpread(t.padChecks.map(function(c){return c.padId;}),registered);
 t.padChecks.forEach(function(c){var report=readEvidence(c.reportEvidence,true);observation(report,c.reportEvidence,c.imageEvidence);var p=registered[c.padId],cam=report.afterQuerySnapshot&&report.afterQuerySnapshot.nativePoses&&report.afterQuerySnapshot.nativePoses.top;if(!p||!cam||Math.sqrt(Math.pow(number(cam.x,'check camera X')-number(p.machineXYMm[0],'registered X'),2)+Math.pow(number(cam.y,'check camera Y')-number(p.machineXYMm[1],'registered Y'),2))>0.1)fail('Distant-pad camera location differs from registration');});
 if(affine)affineSources(q,reg,registered,readEvidence,observation,fidReports,revalidated);if(native)nativeSources(q,reg,registered,readEvidence,revalidated);
 var off=readEvidence(t.tipOffsetEvidence,true),surf=readEvidence(t.surfaceEvidence,true);
 [off,surf].forEach(function(v){if(!v||v.boardId!==t.boardId||v.provenance!=='commissioning-provisional'||v.precisionCalibrated!==false||v.jvmStartMs!==q.jvmStartMs||v.liveConfigurationSha256!==q.liveConfigurationSha256||typeof v.reviewedBy!=='string'||!v.reviewedBy.trim())fail('Explicit provisional board/tip evidence required');});
 readEvidence(evidence(off.basisEvidence),false);readEvidence(evidence(surf.basisEvidence),false);
 if(!same(off.cameraMinusTipXYMm,t.cameraMinusTipXYMm)||!same(surf.surface,t.surface))fail('Selected tip offset or Z/gap differs from authored evidence');
 t.pads.forEach(function(p){var rp=registered[p.padId];if(!rp)fail('FTP pad missing from registration');close(p.rawPose.X,rp.machineXYMm[0]-t.cameraMinusTipXYMm[0],'registered head X');close(p.rawPose.Y,rp.machineXYMm[1]-t.cameraMinusTipXYMm[1],'registered head Y');if(Group&&(Group.isSelected(q)||Group.isSelected40(q)||Group.isMinimumTravelTrial(q))){var ps=readEvidence(evidence(p.surfaceEvidence),true);if(!ps||ps.boardId!==t.boardId||ps.provenance!=='commissioning-provisional'||ps.precisionCalibrated!==false||ps.jvmStartMs!==q.jvmStartMs||ps.liveConfigurationSha256!==q.liveConfigurationSha256||typeof ps.reviewedBy!=='string'||!ps.reviewedBy.trim()||!same(ps.surface,p.surface))fail('Per-pad surface review must be same-board/current and bind exact target surface');readEvidence(evidence(ps.basisEvidence),false);}});
 verifyConditioning(q,readEvidence);
 return t;
}
var api={entryTime:entryTime,scope:scope,isFtp:isFtp,validate:validate,verifySources:verifySources,verifyNativeSources:nativeSources,same:same};if(typeof module!=='undefined'&&module.exports)module.exports=api;else root.PasteFtpTwoPad=api;
})(this);
