'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),G=require('./ftp-pad-group.cjs');
function fixture(){return {createdMs:1000,jvmStartMs:1,liveConfigurationSha256:'a'.repeat(64),scope:G.scope(false),mode:'wet',ftpTargetRecord:{reviewedMs:950,scope:'ftp-eight-pad-commissioning-targets',inlineConditioning:{protocol:'scrap-condition-transit-eight-pad'},compensatedSequence:{protocol:'restore-dose-retract-lift-eight-pad',doseDegrees:4,retractDegrees:2,dwellMilliseconds:200,retractDwellMilliseconds:500,idleReliefDegrees:40},pairReferences:['R33','R34','R35','R36'],pads:['R33','R34','R35','R36'].flatMap(r=>[1,2].map(n=>({padId:r+'.'+n,padAvailableReviewed:true,padIdentityReviewed:true,availabilityCapturedMs:900,availabilityReportEvidence:{path:'/reviewed/'+r+'/report.json',sha256:'a'.repeat(64)},availabilityImageEvidence:{path:'/reviewed/'+r+'/top.png',sha256:'a'.repeat(64)}})))}};}
test('separate eight-pad scope requires four complete individually reviewed pairs',()=>{const q=fixture();G.validate(q);q.ftpTargetRecord.compensatedSequence.doseDegrees=6;G.validate(q);const paths=[];G.verifyImages(q,(e,json)=>{paths.push(e.path);return json?camera(q):null;});assert.equal(paths.length,16);});
test('eight-pad scope rejects duplicates, partial pairs, missing image review and recipe changes',()=>{for(const edit of [q=>q.scope='contiguous-native-ftp-conditioned-two-pad',q=>q.ftpTargetRecord.pads.pop(),q=>q.ftpTargetRecord.pads[1].padId='R33.1',q=>q.ftpTargetRecord.pairReferences[1]='R33',q=>q.ftpTargetRecord.pads[0].padAvailableReviewed=false,q=>q.ftpTargetRecord.pads[0].availabilityImageEvidence.sha256='bad',q=>q.ftpTargetRecord.compensatedSequence.doseDegrees=12,q=>q.ftpTargetRecord.compensatedSequence.idleReliefDegrees=20]){const q=fixture();edit(q);assert.throws(()=>G.validate(q));}});
test('only explicitly tagged group history permits indices40..79',()=>{assert.equal(G.stageIndex(39),true);assert.equal(G.stageIndex(40),false);assert.equal(G.stageIndex(79,G.scope(false)),true);assert.equal(G.stageIndex(80,G.scope(false)),false);assert.equal(G.stageIndex(1,'unknown'),false);assert.equal(G.stageIndex(1.5,G.scope(false)),false);});

function camera(q){return {status:'completed-camera-survey-awaiting-image-review',controllerPositionVerified:true,uncertainCompletion:false,request:{jvmStartMs:q.jvmStartMs,liveConfigurationSha256:q.liveConfigurationSha256},finishedAt:new Date(900).toISOString(),afterImages:{top:{path:'top.png'}}};}
test('pad availability binds exact fresh image/report timestamp and session',()=>{const q=fixture();G.validate(q,300900);assert.throws(()=>G.validate(q,300901),/Fresh/);for(const edit of [r=>r.request.jvmStartMs++,r=>r.uncertainCompletion=true,r=>r.finishedAt=new Date(899).toISOString(),r=>r.afterImages.top.path='other.png']){const r=camera(q);edit(r);assert.throws(()=>G.verifyImages(q,(e,json)=>json?r:null),/camera report/);}delete q.ftpTargetRecord.pads[0].availabilityCapturedMs;assert.throws(()=>G.validate(q),/Fresh/);});

test('eight-pad forward dwell admits only200,1000 or2000',()=>{for(const wait of [200,1000,2000]){const q=fixture();q.ftpTargetRecord.compensatedSequence.dwellMilliseconds=wait;G.validate(q);}for(const wait of [0,500,2001,true,200.5,NaN]){const q=fixture();q.ftpTargetRecord.compensatedSequence.dwellMilliseconds=wait;assert.throws(()=>G.validate(q));}});

test('group dose20 is explicit and dose12 remains rejected',()=>{const q=fixture();q.ftpTargetRecord.compensatedSequence.doseDegrees=20;G.validate(q);q.ftpTargetRecord.compensatedSequence.doseDegrees=12;assert.throws(()=>G.validate(q));});
