'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),C=require('./ftp-one-pad-cleanup.cjs');
const ev=p=>({path:p,sha256:'a'.repeat(64)}),clone=q=>JSON.parse(JSON.stringify(q));
function fixture(){const raw={X:100,Y:200,Z:58.3,A:720,B:-2000},s={rawZ:58.3,estimatedGapMm:.4,gapUncertaintyMm:.3},pad={padId:'R40.1',rawPose:{X:100,Y:200,Z:58.3,A:720},padIdentityReviewed:true,defectReviewed:true,defectCapturedMs:900,defectReportEvidence:ev('/camera/report.json'),defectImageEvidence:ev('/camera/top.png'),aspirationStageIndex:0,liftStageIndex:1};return {scope:C.scope(false),mode:'wet',createdMs:1000,jvmStartMs:1,liveConfigurationSha256:'a'.repeat(64),xyClearanceRawZ:53.4,ftpTargetRecord:{scope:'ftp-one-pad-cleanup-targets',reviewedMs:950,surface:s,surfaceEvidence:ev('/surface.json'),pads:[pad],cleanupSequence:{schema:1,protocol:'positive-B-aspiration-lift-one-pad',retractDegrees:6,dwellMilliseconds:2000}},previewStages:[{axis:'B',startRaw:raw,targetRaw:{...raw,B:-1994},dwellMilliseconds:2000,gapEvidence:ev('/surface.json'),estimatedGapMm:.4,gapUncertaintyMm:.3},{axis:'Z',startRaw:{...raw,B:-1994},targetRaw:{...raw,B:-1994,Z:53.4}}]};}
test('one registered known defect admits +6 or+20 then immediate lift only',()=>{for(const amount of [6,20]){const q=fixture();q.ftpTargetRecord.cleanupSequence.retractDegrees=amount;q.previewStages[0].targetRaw.B=q.previewStages[1].startRaw.B=q.previewStages[1].targetRaw.B=-2000+amount;C.validate(q,1000);assert.deepEqual(C.coverage(q,q.ftpTargetRecord),{0:true});}});
test('cleanup rejects forward B, additional B, unreviewed pad, stale image and dwell changes',()=>{for(const edit of [q=>q.previewStages[0].targetRaw.B=-2006,q=>q.previewStages.push(clone(q.previewStages[0])),q=>q.ftpTargetRecord.pads[0].padId='R2.1',q=>q.ftpTargetRecord.pads[0].defectReviewed=false,q=>q.ftpTargetRecord.compensatedSequence={},q=>q.ftpTargetRecord.pads[0].defectCapturedMs=-400000,q=>q.ftpTargetRecord.cleanupSequence.dwellMilliseconds=2001,q=>q.previewStages[0].targetRaw.X++,q=>q.previewStages[1].targetRaw.Z=53.3]){const q=fixture();edit(q);assert.throws(()=>{C.validate(q,1000);C.coverage(q,q.ftpTargetRecord);});}});
test('cleanup binds the actual defect report/image/time/session',()=>{const q=fixture(),r={status:'completed-camera-survey-awaiting-image-review',controllerPositionVerified:true,uncertainCompletion:false,request:{jvmStartMs:1,liveConfigurationSha256:q.liveConfigurationSha256},finishedAt:new Date(900).toISOString(),afterImages:{top:{path:'top.png'}}};C.verifyImage(q,(e,json)=>json?r:null);for(const edit of [r=>r.request.jvmStartMs++,r=>r.finishedAt=new Date(899).toISOString(),r=>r.afterImages.top.path='other.png']){const v=clone(r);edit(v);assert.throws(()=>C.verifyImage(q,(e,json)=>json?v:null));}});

test('observed R16.2 defect remains gated by fresh explicit review',()=>{const q=fixture();q.ftpTargetRecord.pads[0].padId='R16.2';C.validate(q,1000);C.coverage(q,q.ftpTargetRecord);q.ftpTargetRecord.pads[0].defectReviewed=false;assert.throws(()=>C.validate(q,1000));q.ftpTargetRecord.pads[0].defectReviewed=true;assert.throws(()=>C.validate(q,301001),/Fresh/);q.ftpTargetRecord.pads[0].padId='R16.1';assert.throws(()=>C.validate(q,1000));});

test('explicit100 is exactly five consecutive+20 stages with bounded dwell and final lift',()=>{
 function hundred(){const q=fixture(),t=q.ftpTargetRecord,p=t.pads[0],base=q.previewStages[0];t.cleanupSequence.protocol='positive-B-aspiration-series-lift-one-pad';t.cleanupSequence.retractDegrees=100;delete p.aspirationStageIndex;p.aspirationStageIndices=[0,1,2,3,4];p.liftStageIndex=5;let at=clone(base.startRaw);q.previewStages=[];for(let i=0;i<5;i++){const target={...at,B:at.B+20};q.previewStages.push({...clone(base),startRaw:at,targetRaw:target});at=target;}q.previewStages.push({axis:'Z',startRaw:at,targetRaw:{...at,Z:q.xyClearanceRawZ}});return q;}
 const q=hundred();C.validate(q,1000);assert.deepEqual(C.coverage(q,q.ftpTargetRecord),{0:true,1:true,2:true,3:true,4:true});
 for(const edit of [q=>q.ftpTargetRecord.cleanupSequence.protocol='positive-B-aspiration-lift-one-pad',q=>q.ftpTargetRecord.cleanupSequence.retractDegrees=80,q=>q.ftpTargetRecord.pads[0].aspirationStageIndices.pop(),q=>q.ftpTargetRecord.pads[0].aspirationStageIndices=[0,1,3,4,5],q=>q.ftpTargetRecord.pads[0].aspirationStageIndex=0,q=>q.previewStages[2].axis='X',q=>q.previewStages[2].targetRaw.B-=40,q=>q.previewStages[1].dwellMilliseconds=2001,q=>q.previewStages[1].startRaw.B++,q=>q.previewStages[3].targetRaw.X++,q=>q.previewStages[5].targetRaw.Z-=.01]){const bad=hundred();edit(bad);assert.throws(()=>{C.validate(bad,1000);C.coverage(bad,bad.ftpTargetRecord);});}
});
