'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),G=require('./ftp-pad-group.cjs');
function fixture(){return {createdMs:1000,jvmStartMs:1,liveConfigurationSha256:'a'.repeat(64),scope:G.scope(false),mode:'wet',ftpTargetRecord:{reviewedMs:950,scope:'ftp-eight-pad-commissioning-targets',inlineConditioning:{protocol:'scrap-condition-transit-eight-pad'},compensatedSequence:{protocol:'restore-dose-retract-lift-eight-pad',doseDegrees:4,retractDegrees:2,dwellMilliseconds:200,retractDwellMilliseconds:500,idleReliefDegrees:40},pairReferences:['R33','R34','R35','R36'],pads:['R33','R34','R35','R36'].flatMap(r=>[1,2].map(n=>({padId:r+'.'+n,padAvailableReviewed:true,padIdentityReviewed:true,availabilityCapturedMs:900,availabilityReportEvidence:{path:'/reviewed/'+r+'/report.json',sha256:'a'.repeat(64)},availabilityImageEvidence:{path:'/reviewed/'+r+'/top.png',sha256:'a'.repeat(64)}})))}};}
test('separate eight-pad scope requires four complete individually reviewed pairs',()=>{const q=fixture();G.validate(q);q.ftpTargetRecord.compensatedSequence.doseDegrees=6;G.validate(q);const paths=[];G.verifyImages(q,(e,json)=>{paths.push(e.path);return json?camera(q):null;});assert.equal(paths.length,16);});
test('eight-pad scope rejects duplicates, partial pairs, missing image review and recipe changes',()=>{for(const edit of [q=>q.scope='contiguous-native-ftp-conditioned-two-pad',q=>q.ftpTargetRecord.pads.pop(),q=>q.ftpTargetRecord.pads[1].padId='R33.1',q=>q.ftpTargetRecord.pairReferences[1]='R33',q=>q.ftpTargetRecord.pads[0].padAvailableReviewed=false,q=>q.ftpTargetRecord.pads[0].availabilityImageEvidence.sha256='bad',q=>q.ftpTargetRecord.compensatedSequence.doseDegrees=8,q=>q.ftpTargetRecord.compensatedSequence.idleReliefDegrees=20]){const q=fixture();edit(q);assert.throws(()=>G.validate(q));}});
test('only explicitly tagged group history permits indices40..95',()=>{assert.equal(G.stageIndex(39),true);assert.equal(G.stageIndex(40),false);assert.equal(G.stageIndex(79,G.scope(false)),true);assert.equal(G.stageIndex(95,G.scope(false)),true);assert.equal(G.stageIndex(96,G.scope(false)),false);assert.equal(G.stageIndex(1,'unknown'),false);assert.equal(G.stageIndex(1.5,G.scope(false)),false);});

function camera(q){return {status:'completed-camera-survey-awaiting-image-review',controllerPositionVerified:true,uncertainCompletion:false,request:{jvmStartMs:q.jvmStartMs,liveConfigurationSha256:q.liveConfigurationSha256},finishedAt:new Date(900).toISOString(),afterImages:{top:{path:'top.png'}}};}
test('pad availability binds exact fresh image/report timestamp and session',()=>{const q=fixture();G.validate(q,300900);assert.throws(()=>G.validate(q,300901),/Fresh/);for(const edit of [r=>r.request.jvmStartMs++,r=>r.uncertainCompletion=true,r=>r.finishedAt=new Date(899).toISOString(),r=>r.afterImages.top.path='other.png']){const r=camera(q);edit(r);assert.throws(()=>G.verifyImages(q,(e,json)=>json?r:null),/camera report/);}delete q.ftpTargetRecord.pads[0].availabilityCapturedMs;assert.throws(()=>G.validate(q),/Fresh/);});

test('eight-pad forward dwell admits only200,1000 or2000',()=>{for(const wait of [200,1000,2000]){const q=fixture();q.ftpTargetRecord.compensatedSequence.dwellMilliseconds=wait;G.validate(q);}for(const wait of [0,500,2001,true,200.5,NaN]){const q=fixture();q.ftpTargetRecord.compensatedSequence.dwellMilliseconds=wait;assert.throws(()=>G.validate(q));}});

test('group doses12 and20 are explicit and dose8 remains rejected',()=>{const q=fixture();q.ftpTargetRecord.compensatedSequence.doseDegrees=20;G.validate(q);q.ftpTargetRecord.compensatedSequence.doseDegrees=12;G.validate(q);q.ftpTargetRecord.compensatedSequence.doseDegrees=8;assert.throws(()=>G.validate(q));});

test('fractional comparison requires four exact ordered groups, bounded indices and wider prebatch freshness',()=>{
 const groups=[],pads=[];for(let g=1;g<=4;g++){const ids=[];for(let r=(g-1)*4+1;r<=g*4;r++)for(let side=1;side<=2;side++){const padId='R'+r+'.'+side;ids.push(padId);pads.push({padId,group:g,retractPercent:[15,20,25,30][g-1],padIdentityReviewed:true,padAvailableReviewed:true,availabilityCapturedMs:900,availabilityReportEvidence:{path:'/r/'+padId+'/report.json',sha256:'a'.repeat(64)},availabilityImageEvidence:{path:'/r/'+padId+'/top.png',sha256:'a'.repeat(64)},surface:{rawZ:58.4,estimatedGapMm:.4,gapUncertaintyMm:.3},surfaceEvidence:{path:'/r/'+padId+'/surface.json',sha256:'a'.repeat(64)},rawPose:{X:r,Y:side,Z:58.4,A:720}});}
 const ranges=[[null,null,0,11,79],[80,94,95,106,174],[175,187,188,199,264],[265,276,277,288,352]][g-1],resetStart=ranges[0],resetEnd=ranges[1],prefixStart=ranges[2],groupStart=ranges[3],groupEnd=ranges[4];
 groups.push({group:g,retractPercent:[15,20,25,30][g-1],padIds:ids,resetStartStageIndex:resetStart,resetEndStageIndex:resetEnd,prefixStartStageIndex:prefixStart,prefixStageCount:11,groupStartStageIndex:groupStart,groupEndStageIndex:groupEnd});}
 const q={createdMs:1000,jvmStartMs:1,liveConfigurationSha256:'a'.repeat(64),scope:G.retractionComparisonScope(false),mode:'wet',ftpTargetRecord:{reviewedMs:950,scope:'ftp-selected-pads-targets',inlineConditioning:{protocol:'scrap-condition-transit-retraction-comparison'},compensatedSequence:{protocol:'restore-dose-retract-lift-retraction-comparison',doseDegrees:6,retractDegrees:3,conditioningRetractDegrees:3,dwellMilliseconds:2000,retractDwellMilliseconds:500,idleReliefDegrees:40},retractionComparison:{schema:1,protocol:'four-group-fractional-retraction-comparison',doseDegrees:6,stepsPerDegree:4.44,groups},pads}};
 assert.equal(G.validateSelected(q,900000).pads.length,32);
 const bad=JSON.parse(JSON.stringify(q));bad.ftpTargetRecord.retractionComparison.groups[1].groupStartStageIndex='106';assert.throws(()=>G.validateSelected(bad,900000),/stage boundaries/);
 const stale=JSON.parse(JSON.stringify(q));assert.throws(()=>G.validateSelected(stale,900951),/Fresh/);
});
