const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path'),crypto=require('node:crypto'),P=require('./manual-home-ledger-anchor.cjs');
const hash=b=>crypto.createHash('sha256').update(b).digest('hex');
test('raw B comparison tolerates report decimal rounding only within 1e-7',()=>{assert.doesNotThrow(()=>P.close(-4081.90,-4081.8999999999996,'B'));assert.throws(()=>P.close(-4081.899,-4081.9,'B'),/mismatch/);});
function fixture(){const dir=fs.mkdtempSync(path.join(os.tmpdir(),'manual-home-ledger-'));function write(name,value,raw){const b=Buffer.from(raw===undefined?JSON.stringify(value):raw),file=path.join(dir,name);fs.writeFileSync(file,b);return {path:file,sha256:hash(b)};}function read(e,json){const b=fs.readFileSync(e.path);if(hash(b)!==e.sha256)throw Error('evidence hash mismatch');return json?JSON.parse(b):b.toString('utf8');}
 const oldXml='<configuration><entry><string>N1</string><runout-compensation class="org.openpnp.machine.reference.ReferenceNozzleTipCalibration$ModelBasedRunoutCameraOffsetCompensation" units="Millimeters" center-x="0" center-y="0" peak-error="0.1" phase-shift="0.2" radius="1" rms-error="0.05"/></entry></configuration>',newXml=oldXml.replace('center-x="0"','center-x="1.25"');
 const pose={X:358.37,Y:118.71,Z:32.25,A:720,B:-3526},current={...pose,A:200};const ledger={schema:1,status:'verified',scope:'signed-B-commissioning-strokes',sessionId:'session-1',syringeId:'syringe-1',carryoverSha256:'c'.repeat(64),primeLedgerSha256:'p'.repeat(64),lastVerifiedB:-3526,entries:[{requestId:'tail-1',status:'verified',startB:-3520,targetB:-3526,deltaDegrees:-6,absoluteDegrees:6}]};const le=write('ledger.json',ledger),report={id:'tail-1',status:'completed-contiguous-batch-awaiting-observation',uncertainCompletion:false,completedLedgerSha256:le.sha256,request:{id:'tail-1',sessionId:ledger.sessionId,liveConfigurationSha256:hash(oldXml),jvmStartMs:1790886238424}};const re=write('latest.json',report),model={scope:'pure-model-state-no-controller-access',jvmStartMs:1790898122720,liveConfigurationSha256:hash(newXml),enabled:true,homed:true,busy:false,controllerPoseTrusted:false,motionQueue:0,executor:{shutdown:false,terminated:false,active:0,queued:0},taskOwner:null,drivers:[{connected:true,readerAlive:true,error:null,motionPending:false}],nozzles:[{name:'N2',tip:null,compatible:0,changer:false,part:null,manualNozzleTipChangeLocation:{initialized:false}}]},me=write('model.json',model),oldXmlEv=write('old.xml',null,oldXml),newXmlEv=write('new.xml',null,newXml);
 function m114(p,c){return `X:${p.X.toFixed(2)} Y:${p.Y.toFixed(2)} Z:${p.Z.toFixed(2)} A:${p.A.toFixed(2)} B:${p.B.toFixed(2)} Count X:114678 Y:37987 Z:1290 A:${c.A} B:${c.B}`;}
 const old={status:'completed-read-only-position-barrier',noMotionCommandSubmitted:true,controllerPositionVerified:true,uncertainCompletion:false,request:{scope:'read-only-native-position-barrier',jvmStartMs:1790886238424,liveConfigurationSha256:hash(oldXml)},liveConfigurationSha256:hash(oldXml),privateConfigurationSnapshot:oldXmlEv,afterQuerySnapshot:{raw:pose},position:{responses:[m114(pose,{A:3197,B:-15655}),'ok']}};const oldRef=write('old-barrier.json',old),fresh={status:'completed-read-only-position-barrier',noMotionCommandSubmitted:true,controllerPositionVerified:true,uncertainCompletion:false,request:{scope:'read-only-native-position-barrier',jvmStartMs:model.jvmStartMs,liveConfigurationSha256:model.liveConfigurationSha256,manualHomeAcknowledgement:true,installerEvidence:me},liveConfigurationSha256:model.liveConfigurationSha256,privateConfigurationSnapshot:newXmlEv,afterQuerySnapshot:{raw:current},position:{responses:[m114(current,{A:888,B:-15655}),'ok']}};const currentRef=write('current-barrier.json',fresh);
 const continuityImage=write('same-syringe.png',null,'synthetic reviewed image bytes');const q={scope:'contiguous-native-scrap-batch-preview',sessionId:ledger.sessionId,syringeId:ledger.syringeId,jvmStartMs:model.jvmStartMs,liveConfigurationSha256:model.liveConfigurationSha256,expectedRaw:current,previousLedgerSha256:le.sha256,previousReportEvidence:re,barrierEvidence:currentRef};const record={schema:1,scope:'manual-home-ledger-anchor-continuity',sessionId:q.sessionId,syringeId:q.syringeId,currentJvmStartMs:q.jvmStartMs,currentConfigurationSha256:q.liveConfigurationSha256,reviewedBy:'reviewer',reviewedMs:1000,operatorAcknowledgement:{manualHomeConfirmed:true,quote:'kk i just homed it.'},physicalContinuityReview:{samePhysicalSyringeObserved:true,noReportedChange:true,syringeId:q.syringeId,reviewedBy:'reviewer',reviewedMs:1000,evidence:continuityImage},currentLedgerEvidence:le,latestTerminalReportEvidence:re,oldBarrierEvidence:oldRef,currentBarrierEvidence:currentRef,historicalAnchorReports:[]};return {dir,q,record,read,le,ledger,report,old,fresh,oldXml,newXml,currentRef};}
test('manual home authorizes exact selected-pad batch ledger continuity with B raw/count continuity and N1-only XML change',()=>{const f=fixture();try{f.q.scope='contiguous-native-ftp-selected-pads-preview';assert.equal(P.validate(f.record,f.q,f.read,2000).currentLedgerSha256,f.le.sha256);assert.throws(()=>P.validate(f.record,{...f.q,scope:'contiguous-native-ftp-two-pad-preview'},f.read,2000),/scope/);}finally{fs.rmSync(f.dir,{recursive:true,force:true});}});
test('rejects B count mismatch, changed evidence hashes, altered config, and current ledger drift',()=>{const f=fixture();try{let r=JSON.parse(JSON.stringify(f.record));let q=JSON.parse(JSON.stringify(f.q));r.oldBarrierEvidence={...r.oldBarrierEvidence,sha256:'f'.repeat(64)};assert.throws(()=>P.validate(r,q,f.read,2000),/hash/);r=JSON.parse(JSON.stringify(f.record));const old=JSON.parse(JSON.stringify(f.old));old.position.responses[0]=old.position.responses[0].replace('B:-15655','B:-15654');fs.writeFileSync(r.oldBarrierEvidence.path,JSON.stringify(old));r.oldBarrierEvidence.sha256=hash(fs.readFileSync(r.oldBarrierEvidence.path));assert.throws(()=>P.validate(r,q,f.read,2000),/count mismatch/);fs.rmSync(r.oldBarrierEvidence.path);fs.writeFileSync(r.oldBarrierEvidence.path,JSON.stringify(f.old));r.oldBarrierEvidence.sha256=hash(fs.readFileSync(r.oldBarrierEvidence.path));const altered=f.newXml.replace('center-x="1.25"','center-x="9.25"');fs.writeFileSync(f.fresh.privateConfigurationSnapshot.path,altered);const freshBytes=fs.readFileSync(f.fresh.privateConfigurationSnapshot.path);f.fresh.privateConfigurationSnapshot.sha256=hash(freshBytes);fs.writeFileSync(f.currentRef.path,JSON.stringify(f.fresh));f.currentRef.sha256=hash(fs.readFileSync(f.currentRef.path));r.currentBarrierEvidence=f.currentRef;q.barrierEvidence=f.currentRef;assert.throws(()=>P.validate(r,q,f.read,2000),/Configuration XML evidence/);fs.writeFileSync(f.fresh.privateConfigurationSnapshot.path,f.newXml);f.fresh.privateConfigurationSnapshot.sha256=hash(fs.readFileSync(f.fresh.privateConfigurationSnapshot.path));fs.writeFileSync(f.currentRef.path,JSON.stringify(f.fresh));f.currentRef.sha256=hash(fs.readFileSync(f.currentRef.path));const drift=JSON.parse(JSON.stringify(f.ledger));drift.lastVerifiedB=-3525;fs.writeFileSync(f.le.path,JSON.stringify(drift));f.le.sha256=hash(fs.readFileSync(f.le.path));r=JSON.parse(JSON.stringify(f.record));r.currentLedgerEvidence=f.le;q=JSON.parse(JSON.stringify(f.q));q.previousLedgerSha256=f.le.sha256;assert.throws(()=>P.validate(r,q,f.read,2000),/ledger|terminal/i);}finally{fs.rmSync(f.dir,{recursive:true,force:true});}});

test('manual-home cache is invocation-scoped and keyed by request and reader identity',()=>{const f=fixture();try{f.q.scope='contiguous-native-ftp-selected-pads-preview';assert.doesNotThrow(()=>P.validate(f.record,f.q,f.read,2000));const changed={...f.q,expectedRaw:{...f.q.expectedRaw,B:f.q.expectedRaw.B+0.01}};assert.throws(()=>P.validate(f.record,changed,f.read,2000),/B|ledger|barrier|report/i);const rejectingReader=(e,json)=>{throw Error('distinct reader must be consulted');};assert.throws(()=>P.validate(f.record,f.q,rejectingReader,2000),/distinct reader/);assert.doesNotThrow(()=>P.validate(f.record,f.q,f.read,2000));}finally{fs.rmSync(f.dir,{recursive:true,force:true});}});

test('continuation preserves original same-B home anchor through a verified wet B ledger extension',()=>{const f=fixture();try{
 const baseLedger={...f.ledger,startB:-240,totalAbsoluteDegrees:6};const baseBytes=Buffer.from(JSON.stringify(baseLedger,null,2)+'\n'),basePath=path.join(f.dir,'baseline-ledger.json');fs.writeFileSync(basePath,baseBytes);const baseLedgerRef={path:basePath,sha256:hash(baseBytes)};
 const baseReport=JSON.parse(JSON.stringify(f.report));baseReport.completedLedgerSha256=baseLedgerRef.sha256;const baseReportBytes=Buffer.from(JSON.stringify(baseReport)),baseReportPath=path.join(f.dir,'baseline-report.json');fs.writeFileSync(baseReportPath,baseReportBytes);const baseReportRef={path:baseReportPath,sha256:hash(baseReportBytes)};
 const baseProof=JSON.parse(JSON.stringify(f.record));baseProof.currentLedgerEvidence=baseLedgerRef;baseProof.latestTerminalReportEvidence=baseReportRef;
 const baseProofBytes=Buffer.from(JSON.stringify(baseProof)),baseProofPath=path.join(f.dir,'baseline-proof.json');fs.writeFileSync(baseProofPath,baseProofBytes);const baseProofRef={path:baseProofPath,sha256:hash(baseProofBytes)};
 const baseQ={...f.q,previousLedgerSha256:baseLedgerRef.sha256,previousReportEvidence:baseReportRef,manualHomeLedgerAnchorEvidence:baseProofRef};
 const batchId='11111111-1111-4111-8111-111111111111',target=-3529;
 const m114=(b,c)=>`X:10.00 Y:20.00 Z:30.00 A:200.00 B:${b.toFixed(2)} Count X:100 Y:200 Z:300 A:888 B:${c}`;
 const nextLedger=JSON.parse(JSON.stringify(baseLedger));nextLedger.entries.push({requestId:batchId+':0',batchId,stageIndex:0,startB:-3526,targetB:target,deltaDegrees:-3,absoluteDegrees:3,status:'verified',batchScope:'contiguous-native-ftp-selected-pads'});nextLedger.lastVerifiedB=target;nextLedger.totalAbsoluteDegrees=9;
 const ledgerBytes=Buffer.from(JSON.stringify(nextLedger,null,2)+'\n'),ledgerPath=path.join(f.dir,'continued-ledger.json');fs.writeFileSync(ledgerPath,ledgerBytes);const ledgerRef={path:ledgerPath,sha256:hash(ledgerBytes)};
 const previewStages=[{axis:'B',startRaw:{B:-3526},targetRaw:{B:target}}];const request={...baseQ,id:batchId,scope:'contiguous-native-ftp-selected-pads',mode:'wet',enabled:false,previewStages,expectedRaw:{...baseQ.expectedRaw,B:-3526},previousLedgerSha256:baseLedgerRef.sha256,previousReportEvidence:baseReportRef};
 const wet={id:batchId,status:'completed-contiguous-batch-awaiting-observation',uncertainCompletion:false,controllerPositionVerified:true,countsVerified:true,motionSubmitted:true,completedLedgerSha256:ledgerRef.sha256,ledgerPath,request,beforeQuerySnapshot:{raw:request.expectedRaw},before:{responses:[m114(-3526,-15655),'ok']},stage0:{responses:[m114(target,-15668),'ok']},after:{responses:[m114(target,-15668),'ok']},afterQuerySnapshot:{raw:{...request.expectedRaw,B:target}}};
 const wetBytes=Buffer.from(JSON.stringify(wet)),wetPath=path.join(f.dir,'wet-report.json');fs.writeFileSync(wetPath,wetBytes);const wetRef={path:wetPath,sha256:hash(wetBytes)};
 const fresh=JSON.parse(JSON.stringify(f.fresh));fresh.afterQuerySnapshot.raw.B=target;fresh.position.responses[0]=m114(target,-15668);const freshBytes=Buffer.from(JSON.stringify(fresh)),freshPath=path.join(f.dir,'continued-barrier.json');fs.writeFileSync(freshPath,freshBytes);const freshRef={path:freshPath,sha256:hash(freshBytes)};
 const cont={schema:1,scope:'manual-home-ledger-anchor-continuation',continuationEvidence:{baselineManualHomeProofEvidence:baseProofRef,verifiedBMotionReports:[{reportEvidence:wetRef,ledgerEvidence:ledgerRef}],reconstructedBaseLedger:{sourceLedgerEvidence:ledgerRef,prefixEntryCount:1,sha256:baseLedgerRef.sha256}},currentLedgerEvidence:ledgerRef,currentBarrierEvidence:freshRef,latestTerminalReportEvidence:wetRef};
 const contBytes=Buffer.from(JSON.stringify(cont)),contPath=path.join(f.dir,'continuation-proof.json');fs.writeFileSync(contPath,contBytes);const contRef={path:contPath,sha256:hash(contBytes)};
 const q={...baseQ,manualHomeLedgerAnchorEvidence:contRef,expectedRaw:{...request.expectedRaw,B:target},previousLedgerSha256:ledgerRef.sha256,previousReportEvidence:wetRef,barrierEvidence:freshRef};
 assert.equal(P.validate(cont,q,f.read,2000).currentLedgerSha256,ledgerRef.sha256);
 const priorLedgerBytes=fs.readFileSync(ledgerPath);fs.writeFileSync(ledgerPath,Buffer.concat([priorLedgerBytes,Buffer.from('corrupt')]));assert.throws(()=>P.validate(cont,q,f.read,2000),/hash/);fs.writeFileSync(ledgerPath,priorLedgerBytes);
 const airId='22222222-2222-4222-8222-222222222222',airRequest={...q,id:airId,scope:'contiguous-native-ftp-selected-pads',mode:'air',enabled:false,previousReportEvidence:wetRef};
 const air={id:airId,status:'completed-contiguous-air-batch-awaiting-observation',uncertainCompletion:false,controllerPositionVerified:true,request:airRequest,before:{responses:[m114(target,-15668),'ok']},after:{responses:[m114(target,-15668),'ok']}};
 const airBytes=Buffer.from(JSON.stringify(air)),airPath=path.join(f.dir,'air-report.json');fs.writeFileSync(airPath,airBytes);const airRef={path:airPath,sha256:hash(airBytes)};
 cont.latestTerminalReportEvidence=airRef;const cont2Bytes=Buffer.from(JSON.stringify(cont));fs.writeFileSync(contPath,cont2Bytes);contRef.sha256=hash(cont2Bytes);q.manualHomeLedgerAnchorEvidence=contRef;q.previousReportEvidence=airRef;
 assert.equal(P.validate(cont,q,f.read,2000).currentLedgerSha256,ledgerRef.sha256);
 air.after.responses[0]=m114(target,-15669);const badAirBytes=Buffer.from(JSON.stringify(air));fs.writeFileSync(airPath,badAirBytes);airRef.sha256=hash(badAirBytes);cont.latestTerminalReportEvidence=airRef;const cont3Bytes=Buffer.from(JSON.stringify(cont));fs.writeFileSync(contPath,cont3Bytes);contRef.sha256=hash(cont3Bytes);q.manualHomeLedgerAnchorEvidence=contRef;q.previousReportEvidence=airRef;
 assert.throws(()=>P.validate(cont,q,f.read,2000),/AIR report changed terminal B controller count/);
 }finally{fs.rmSync(f.dir,{recursive:true,force:true});}});
