const {test}=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const guard=require('./measurement-request.cjs');
function q(){return {schema:1,id:'12345678-1234-1234-1234-123456789abc',createdMs:1000,jvmStartMs:42,operator:'test only',sampleRole:'setup',target:{id:'test-target',description:'Synthetic fixed marker',fixture:'Synthetic fixture'},operatorObservedTarget:false,evidencePaths:[],firmwareQueryRecord:null,physicalMeasurements:[]};}
test('pending request cannot be treated as measurement',()=>assert.throws(()=>guard.validate(JSON.parse(fs.readFileSync(__dirname+'/measurement-request.pending.json')),1001,42)));
test('unhomed setup requests require no physical calibration claims',()=>{const a=q();assert.equal(guard.validate(a,1001,42),a);assert.equal(a.operatorObservedTarget,false);});
test('fresh request bound to exact session',()=>{assert.throws(()=>guard.validate(q(),301001,42),/expired/);assert.throws(()=>guard.validate(q(),999,42),/expired/);assert.throws(()=>guard.validate(q(),1001,43),/session/);const a=q();a.createdMs=NaN;assert.throws(()=>guard.validate(a,1001,42),/finite/);});
test('paired samples require identified fixed target and operator observation',()=>{const a=q();a.sampleRole='right-tip-centered';assert.throws(()=>guard.validate(a,1001,42),/observation/);a.operatorObservedTarget=true;guard.validate(a,1001,42);a.target.id='';assert.throws(()=>guard.validate(a,1001,42),/target id/);});
test('existing evidence paths explicit and absolute',()=>{const a=q();a.evidencePaths=['relative.png'];assert.throws(()=>guard.validate(a,1001,42),/absolute/);a.evidencePaths=[];a.firmwareQueryRecord='relative.json';assert.throws(()=>guard.validate(a,1001,42),/absolute/);});
test('physical values require units and measurement method, retain zero',()=>{const a=q();a.physicalMeasurements=[{name:'synthetic',value:0,unit:'mm',method:'test only'}];guard.validate(a,1001,42);a.physicalMeasurements[0].value=Infinity;assert.throws(()=>guard.validate(a,1001,42),/finite/);a.physicalMeasurements[0].value=0;a.physicalMeasurements[0].unit='';assert.throws(()=>guard.validate(a,1001,42),/unit/);});
test('unknown sample roles and reused measurement labels rejected',()=>{const a=q();a.sampleRole='autocalibrate';assert.throws(()=>guard.validate(a,1001,42),/sampleRole/);a.sampleRole='surface';a.operatorObservedTarget=true;a.physicalMeasurements=[{name:'same',value:1,unit:'mm',method:'test'},{name:'same',value:2,unit:'mm',method:'test'}];assert.throws(()=>guard.validate(a,1001,42),/Duplicate/);});
