const test=require('node:test'),assert=require('node:assert/strict'),p=require('./position-barrier.cjs');
function request(){const raw={X:1,Y:2,Z:3,A:4,B:720},pose={x:1,y:2,z:3,rotation:720};return {schema:1,scope:'read-only-native-position-barrier',id:'12345678-1234-1234-1234-123456789abc',createdMs:100,jvmStartMs:1,operator:'offline test',liveConfigurationSha256:'a'.repeat(64),installerEvidence:{path:'/synthetic/installer.json',sha256:'b'.repeat(64)},reviewedReadOnlyQuery:true,expectedRaw:{...raw},expectedDriver:{...raw},expectedNativePoses:{N1:{...pose},N2:{...pose},top:{...pose},bottom:{...pose}}};}
function installer(){return {status:'installed-in-memory-awaiting-read-only-barrier-and-review',diskUnchanged:true,coordinatesUnchanged:true,noControllerCommands:true,configurationSaved:false,previousCommand:null,request:{jvmStartMs:1},liveConfigurationAfterSha256:'a'.repeat(64)};}
test('fresh full-state query with same-JVM successful installation allowed',()=>{p.validate(request(),100,1);p.installer(installer(),request());});
test('reject missing/stale/mismatched state and motion-shaped input',()=>{for(const key of ['expectedRaw','expectedDriver','expectedNativePoses','installerEvidence'])assert.throws(()=>p.validate({...request(),[key]:null},100,1));for(const key of ['command','target','deltaMm','axis','speedFraction'])assert.throws(()=>p.validate({...request(),[key]:1},100,1));assert.throws(()=>p.validate(request(),300101,1));assert.throws(()=>p.validate(request(),100,2));const q=request();q.expectedRaw.B=NaN;assert.throws(()=>p.validate(q,100,1));});
test('failure or different installer cannot authorize query',()=>{for(const change of [{status:'failed-no-controller-commands'},{diskUnchanged:false},{coordinatesUnchanged:false},{previousCommand:'other'},{request:{jvmStartMs:2}},{liveConfigurationAfterSha256:'c'.repeat(64)}])assert.throws(()=>p.installer({...installer(),...change},request()));});
test('pending template cannot authorize',()=>assert.throws(()=>p.validate(require('./position-barrier.pending.json'),100,1)));
test('reviewed exact B prerequisite edit can authorize new-hash read-only barrier',()=>{const r={...installer(),status:'configured-B-prerequisites-in-memory-awaiting-fresh-barrier',exactTwoFieldChangeVerified:true,previousLimitRotation:true,requestedLimitRotation:false,previousFeedratePerSecond:50000,requestedFeedratePerSecond:100,extrusionAuthorized:false};p.installer(r,request());for(const change of [{requestedFeedratePerSecond:200},{exactTwoFieldChangeVerified:false},{extrusionAuthorized:true}])assert.throws(()=>p.installer({...r,...change},request()));});
test('completed same-JVM native home may anchor configuration hash without further installer action',()=>{const q=request(),home={status:'completed-native-home-enabled-awaiting-image-review',request:{jvmStartMs:q.jvmStartMs,liveConfigurationSha256:q.liveConfigurationSha256},liveConfigurationSha256:q.liveConfigurationSha256,controllerPositionVerified:true,rotationUnchangedVerified:true,nativeMotionCompletionReported:true,uncertainCompletion:false,diskUnchanged:true,machineEnabled:true,machineHomed:true};p.installer(home,q);for(const change of [{request:{jvmStartMs:2,liveConfigurationSha256:q.liveConfigurationSha256}},{liveConfigurationSha256:'c'.repeat(64)},{controllerPositionVerified:false},{rotationUnchangedVerified:false},{nativeMotionCompletionReported:false},{uncertainCompletion:true},{diskUnchanged:false},{machineEnabled:false},{machineHomed:false}])assert.throws(()=>p.installer({...home,...change},q));});

function calibrationXml(centerX='0') { return '<configuration><entry><string>N1</string><runout-compensation class="org.openpnp.machine.reference.ReferenceNozzleTipCalibration$ModelBasedRunoutCameraOffsetCompensation" units="Millimeters" center-x="'+centerX+'" center-y="0" peak-error="0.1" phase-shift="0.2" radius="1" rms-error="0.05"/></entry><entry><string>N2</string><value>unchanged</value></entry></configuration>'; }
test('calibration lineage permits numeric N1 runout updates only',()=>{assert.equal(p.calibrationXml(calibrationXml('0'),calibrationXml('1.25')),true);assert.throws(()=>p.calibrationXml(calibrationXml(),calibrationXml().replace('unchanged','changed')));assert.throws(()=>p.calibrationXml(calibrationXml(),'<configuration><entry><string>N2</string><value>unchanged</value></entry></configuration>'));});
