const {test}=require('node:test'),assert=require('node:assert/strict');
const H=require('./reset-home.cjs'),Z=require('./z-observation.cjs');
function fixture(){const now=2000000,raw={X:0,Y:0,Z:25,A:720,B:720},poses={};for(const k of ['N1','N2','top','bottom'])poses[k]={x:0,y:0,z:25,rotation:720};const q={schema:1,scope:'reviewed-post-reset-native-home',id:'12345678-1234-1234-1234-123456789abc',jvmStartMs:42,createdMs:now,operator:'offline',reviewedEntireHomingEnvelope:true,bothHeadsClearForXYAndZHome:true,noHeldPartsObserved:true,reviewedFirmwareNoABHoming:true,enableAfterVerifiedHome:true,liveConfigurationSha256:'a'.repeat(64),expectedRaw:raw,expectedDriver:{...raw},expectedNativePoses:poses,sourceEvidence:{path:'/offline/source',sha256:'b'.repeat(64)},corridorEvidence:{path:'/offline/image',sha256:'c'.repeat(64),capturedMs:now-1000}};const s={status:'completed-unhomed-positive-Z-clearance-awaiting-image-review',controllerPositionVerified:true,independentFirmwareStepVerified:true,uncertainCompletion:false,machineRemainsDisabledUnhomed:true,request:{jvmStartMs:42},liveConfigurationSha256:q.liveConfigurationSha256,finishedAt:new Date(now-600000).toISOString(),afterQuerySnapshot:{raw,driver:{...raw},nativePoses:poses}};return {q,s,now};}
test('stationary clearance source may be30min old while request/image remain5min',()=>{const {q,s,now}=fixture();H.validate(q,now,42,Z);H.source(s,q,now,Z);assert.throws(()=>H.source({...s,finishedAt:new Date(now-1800001).toISOString()},q,now,Z));assert.throws(()=>H.validate({...q,createdMs:now-300001},now,42,Z));assert.throws(()=>H.validate({...q,corridorEvidence:{...q.corridorEvidence,capturedMs:now-300001}},now,42,Z));});
test('source mismatch, uncertainty and absent full physical review refuse home',()=>{const {q,s,now}=fixture();for(const patch of [{uncertainCompletion:true},{controllerPositionVerified:false},{request:{jvmStartMs:43}},{afterQuerySnapshot:{...s.afterQuerySnapshot,raw:{...q.expectedRaw,Z:20}}}])assert.throws(()=>H.source({...s,...patch},q,now,Z));assert.throws(()=>H.validate({...q,bothHeadsClearForXYAndZHome:false},now,42,Z));});
test('new home XYZ established by report while rotations must remain720',()=>{H.reported({X:0,Y:0,Z:31.5,A:720,B:720},{A:720,B:720},Z);for(const patch of [{X:1},{Z:25},{A:0},{B:0}])assert.throws(()=>H.reported({X:0,Y:0,Z:31.5,A:720,B:720,...patch},{A:720,B:720},Z));});

const homeLine='X:0.00 Y:0.00 Z:31.50 A:720.00 B:720.00 Count X:0 Y:0 Z:1260 A:3197 B:3197';
const homePosition={X:0,Y:0,Z:31.5,A:720,B:720};
test('G28 report is valid prior evidence while fresh M114 requires its own full report and following ACK',()=>{assert.equal(H.priorHomeResponses(['ok','echo:busy: processing',homeLine,'ok','ok'],homePosition,Z),1);H.freshHomeResponses([homeLine,'ok'],homePosition,homePosition,Z);assert.throws(()=>H.freshHomeResponses(['ok',homeLine],homePosition,homePosition,Z));assert.throws(()=>H.freshHomeResponses(['ok'],homePosition,homePosition,Z));assert.throws(()=>H.freshHomeResponses([homeLine,'ok',homeLine,'ok'],homePosition,homePosition,Z));assert.throws(()=>H.freshHomeResponses([homeLine,'ok'],{...homePosition,B:0},homePosition,Z));assert.throws(()=>H.priorHomeResponses([homeLine.replace('B:720.00','B:0.00')],homePosition,Z));assert.throws(()=>H.priorHomeResponses(['X:0.00 Y:0.00 Z:31.50'],homePosition,Z));});

test('idle finalization supplies only cache identity for a separately reviewed new home',()=>{const {q,s,now}=fixture();const finalized={...s,status:'completed-home-cache-finalization-disabled-unhomed',scope:'exact-home-audit-finalization-no-motion',jvmStartMs:q.jvmStartMs,noHome:true,noMotion:true,noEnable:true,machineEnabled:false,machineHomed:false,absolutePhysicalPositionUnknown:true,physicalRegistrationInvalidated:true,rotationUnchangedVerified:true,diskUnchanged:true};delete finalized.request;delete finalized.independentFirmwareStepVerified;const request={...q,homeReason:'deliberate-rehome-after-prolonged-idle'};H.validate(request,now,42,Z);H.source(finalized,request,now,Z);assert.throws(()=>H.source(finalized,q,now,Z));for(const patch of [{noMotion:false},{noEnable:false},{machineHomed:true},{absolutePhysicalPositionUnknown:false},{jvmStartMs:43},{uncertainCompletion:true}])assert.throws(()=>H.source({...finalized,...patch},request,now,Z));assert.throws(()=>H.validate({...request,reviewedEntireHomingEnvelope:false},now,42,Z));assert.throws(()=>H.validate({...request,corridorEvidence:{...q.corridorEvidence,capturedMs:now-300001}},now,42,Z));});
test('explicit enabled homed rehome accepts completed prime at arbitrary finiteB without resettingrotation',()=>{const {q,s,now}=fixture();q.mode='enabled-homed-rehome';q.homeReason='user-requested-rehome-after-cleaning';q.expectedRaw.B=-10220;q.expectedDriver.B=-10220;q.expectedNativePoses.N2.rotation=-10220;const prime={...s,status:'completed-waste-prime-awaiting-observation',countsVerified:true,request:{jvmStartMs:42,liveConfigurationSha256:q.liveConfigurationSha256},afterQuerySnapshot:{raw:q.expectedRaw,driver:q.expectedDriver,nativePoses:q.expectedNativePoses}};delete prime.machineRemainsDisabledUnhomed;delete prime.liveConfigurationSha256;H.validate(q,now,42,Z);H.source(prime,q,now,Z);H.reported({X:0,Y:0,Z:31.5,A:720,B:-10220},q.expectedRaw,Z);assert.throws(()=>H.validate({...q,mode:undefined},now,42,Z));assert.throws(()=>H.validate({...q,homeReason:'other'},now,42,Z));for(const patch of [{countsVerified:false},{uncertainCompletion:true},{request:{jvmStartMs:43,liveConfigurationSha256:q.liveConfigurationSha256}}])assert.throws(()=>H.source({...prime,...patch},q,now,Z));assert.throws(()=>H.reported({X:0,Y:0,Z:31.5,A:720,B:720},q.expectedRaw,Z));});
test('explicit deliberate rehome may use verified completed home but never assumes physical clearance',()=>{const {q,s,now}=fixture();q.mode='enabled-homed-rehome';q.homeReason='user-requested-rehome-after-cleaning';const home={...s,status:'completed-native-home-enabled-awaiting-image-review',request:{jvmStartMs:42,liveConfigurationSha256:q.liveConfigurationSha256},rotationUnchangedVerified:true,nativeMotionCompletionReported:true,machineEnabled:true,machineHomed:true,diskUnchanged:true};delete home.machineRemainsDisabledUnhomed;H.validate(q,now,42,Z);H.source(home,q,now,Z);for(const key of ['controllerPositionVerified','rotationUnchangedVerified','nativeMotionCompletionReported','machineEnabled','machineHomed','diskUnchanged'])assert.throws(()=>H.source({...home,[key]:false},q,now,Z));for(const patch of [{uncertainCompletion:true},{request:{jvmStartMs:43,liveConfigurationSha256:q.liveConfigurationSha256}},{request:{jvmStartMs:42,liveConfigurationSha256:'f'.repeat(64)}},{finishedAt:new Date(now-1800001).toISOString()}])assert.throws(()=>H.source({...home,...patch},q,now,Z));assert.throws(()=>H.source(home,{...q,mode:undefined},now,Z));assert.throws(()=>H.validate({...q,bothHeadsClearForXYAndZHome:false},now,42,Z));assert.throws(()=>H.validate({...q,corridorEvidence:{...q.corridorEvidence,capturedMs:now-300001}},now,42,Z));});

test('fresh power-cycle startup home accepts only matching idle model cache identity',()=>{const {q,s,now}=fixture();const request={...q,mode:'fresh-startup-home',homeReason:'user-requested-home-after-power-cycle'};const startup={scope:'pure-model-state-no-controller-access',time:new Date(now-1000).toISOString(),jvmStartMs:42,enabled:true,homed:false,busy:false,taskOwner:null,motionQueue:0,preRotate:false,executor:{shutdown:false,terminated:false,active:0,queued:0},drivers:[{id:'DRV16982438146c1dd4',connected:true,readerAlive:true,error:null,motionPending:false}],axes:Object.keys(q.expectedRaw).map(letter=>({letter,raw:q.expectedRaw[letter],driver:q.expectedDriver[letter]})),nativePoses:q.expectedNativePoses,liveConfigurationSha256:q.liveConfigurationSha256};H.validate(request,now,42,Z);H.source(startup,request,now,Z);for(const patch of [{enabled:false},{homed:true},{busy:true},{jvmStartMs:43},{liveConfigurationSha256:'f'.repeat(64)},{drivers:[{...startup.drivers[0],readerAlive:false}]},{axes:startup.axes.map(a=>a.letter==='Z'?{...a,raw:1}:a)}])assert.throws(()=>H.source({...startup,...patch},request,now,Z));assert.throws(()=>H.validate({...request,homeReason:'other'},now,42,Z));});
